/*
 * Decompiled with CFR 0.152.
 */
public final class APa {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final float Ha;
    public static final String Ga;
    public static final String fa;
    public static final float Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final float O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final int F;
    public static final double g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        Q = "sides";
        D = -7.5F /* ZKM Deobf */;
        u = "\\*";
        q = "MinecartRideable";
        Z = "potatoBaked";
        S = "power";
        v = "createWorld.customize.custom.useVillages";
        fa = "ON";
        ca = "options.framerateLimit.max";
        b = "vertical_slab";
        a = 33873 /* ZKM Deobf Int */;
        y = "TileZ";
        C = "options.gamma.max";
        g = -0.36D /* ZKM Deobf */;
        J = 121 /* ZKM Deobf Int */;
        ga = "tooltipDrawVanillaBackground_";
        w = "party/crown.png";
        X = "END_COMBAT";
        e = 638 /* ZKM Deobf Int */;
        T = "IN YOU FACE";
        f = "rightHands";
        K = "composite2";
        d = "wither/wither_armor";
        i = "decoration";
        N = "COPYTOCLIPBOARD";
        A = "GL11.GL_PIXEL_MAP_G_TO_G";
        Ga = "renderClouds:false";
        Aa = 4194304 /* ZKM Deobf Int */;
        Y = "head.main";
        o = 0.0027000000700354576F /* ZKM Deobf */;
        k = "survival";
        la = "of.options.shaders.SPECULAR_MAP";
        Ka = -0.29980000853538513F /* ZKM Deobf */;
        I = "gbuffers_terrain_cutout_mip";
        x = "/usr/bin/open";
        O = 3000.0F /* ZKM Deobf */;
        s = "stat.useItem";
        P = "GL11.GL_NORMAL_ARRAY_POINTER";
        h = "mob.guardian.land.hit";
        W = "BlockModel requires either elements or parent, found neither";
        z = "ms";
        n = "rotateExpr_";
        r = "5CD17E52-A79A-43D3-A529-90FDE04B181E";
        E = "VC: Player connected '{}'";
        Ja = "TOP";
        c = "GL12.GL_TEXTURE_MIN_LOD";
        l = "Audio recived ";
        m = "minecraft";
        B = "\n#define MC_GLSL_VERSION ";
        j = "mob.zombiepig.zpigdeath";
        G = "{\"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":512.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":1000.0, \"mainNoiseScaleY\":3000.0, \"mainNoiseScaleZ\":1000.0, \"baseSize\":8.5, \"stretchY\":10.0, \"biomeDepthWeight\":1.0, \"biomeDepthOffset\":0.0, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":0.0, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":20 }";
        p = "Tail1";
        t = " instead of ";
        F = 4259712 /* ZKM Deobf Int */;
        R = "GL11.GL_DIFFUSE";
        Da = "achievement.blazeRod";
        V = " Drop: ";
        M = "\u0000\u0019\u0000\u0001\u0001\u0019\u0019\u0000\u0000\u0000\u0001\u100f\u0000\u0002\u100f\u0001\u0003\u1004\u0002\u0004\u1006\u0003\u0005\u1001\u0004\u0006\u100c\u0005\u0007\u1001\u0007\b\u1001\b\t\u1009\t\n\u1007\n\u000b\u1208\u0006\f\u1004\u000b\r\u1001\f\u000e\u1001\r\u000f\u1001\u000e\u0010\u1001\u000f\u0011\u1001\u0010\u0012\u1001\u0011\u0013\u1001\u0012\u0014\u1208\u0013\u0015\u1208\u0014\u0016\u1208\u0015\u0017\u1208\u0016\u0018\u1208\u0017\u0019\u1208\u0018";
        ja = -62.0F /* ZKM Deobf */;
        U = "iii";
        L = 32840 /* ZKM Deobf Int */;
        H = "Server Connector #";
        Ha = 0.00800000037997961F /* ZKM Deobf */;
    }

    public APa() {
        APa a2;
    }
}

