/*
 * Decompiled with CFR 0.152.
 */
public final class AQa {
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final double ca;
    public static final String Ja;
    public static final int ja;
    public static final int Ha;
    public static final String Ga;
    public static final int fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final double K;
    public static final String H;
    public static final double c;
    public static final int B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final String D;
    public static final float f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final int j;
    public static final float J;
    public static final String A;
    public static final double I;

    public AQa() {
        AQa a2;
    }

    static {
        e = "Duplicate language->'";
        j = 0x9D4A2A78 ^ 0x9D4AAE93;
        h = "animate_";
        H = "Everything's going to plan. No, really, that was supposed to happen.";
        v = "antiAlias_";
        b = "application/json; charset=utf-8";
        F = "GL15.GL_DYNAMIC_COPY";
        Ma = "assets/minecraft/textures/block";
        I = Double.longBitsToDouble(0xD4E0AA65734C3EF4L ^ 0xEB0B1C20D286FE77L);
        Da = "shaders/post/desaturate.json";
        q = "[ \t]*const[ \t]*float[ \t]*shadowDistance[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        Fa = "ID #";
        Ja = "ofOcclusionFancy";
        ja = 0x12C4427E ^ 0x12C440B6;
        i = "D:/vstest";
        G = Float.intBitsToFloat(0x97004A76 ^ 0xA8354E85);
        l = "zombie_pigman";
        p = "ghast/ghast";
        ha = "No source texture: ";
        k = 0xF53AB813 ^ 0xF53D41A1;
        L = "NeBEF";
        D = "rotation_acceleration";
        A = "fence";
        Aa = "SpawnZ";
        P = 0xF8E83B6D ^ 0xF8E83B69;
        n = "flower_tulip_red";
        w = "gl_caps[ARB_geometry_shader4]";
        la = "selectWorld.newWorld.copyOf";
        Ha = 0xD215881F ^ 0xD21588F2;
        B = 0xC7E6E58D ^ 0xC7E6E699;
        K = Double.longBitsToDouble(0xF4C0258A50164E80L ^ 0x3496A58A50164E80L);
        Z = "Emote action '{}' not found in bobj for {}";
        U = "GL11.GL_TEXTURE_1D";
        N = "tId";
        Ka = 0xFDA0E083 ^ 0xFDA0E10E;
        J = Float.intBitsToFloat(0x4CAEC5C5 ^ 0xA8C3C46);
        W = Float.intBitsToFloat(0x19BC6455 ^ 0x588C6455);
        u = "fade_";
        d = Float.intBitsToFloat(0x7A9B6E9A ^ 0xC5685DA9);
        Y = "hoverColor_";
        a = "ofCloudsHeight:";
        t = "normal";
        r = "string";
        C = "Removed channel {} because it's not playing anymore";
        O = "Behavior '";
        Ia = "location";
        V = " vsync";
        ba = 0x7A493235 ^ 0x7A493222;
        z = "dripWater";
        x = "commands.achievement.unknownAchievement";
        Q = "cryingObsidian";
        o = "reverse_subtract";
        E = "Teroser";
        m = "F2";
        ca = Double.longBitsToDouble(0x2BDD92FECEA75160L ^ 0x140E98C3BE04866AL);
        s = "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0002\u0000\u0001\n\u0002'\u0003\n\u0004'";
        g = "category";
        ga = "menu.generatingTerrain";
        R = "BURNING_SKULL";
        Ga = "RIGHT_SLEEVE";
        c = Double.longBitsToDouble(0xAF198C87B7D1787EL ^ 0xEE6510BFB7D1787EL);
        T = "Downloading file (%.2f MB)...";
        X = "horn_coral_block";
        fa = 0xBA6AD09C ^ 0xBA5EFDBB;
        S = "rabbit_stew";
        y = "CUT_COPPER";
        M = "porkchop";
        f = Float.intBitsToFloat(0xA63AAC ^ 0x3AA528C3);
    }
}

