/*
 * Decompiled with CFR 0.152.
 */
public final class Asa {
    public static final int Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final float P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final float p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final double W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final long o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Asa() {
        Asa a2;
    }

    static {
        O = "Unexpected key packet";
        n = 4614 /* ZKM Deobf Int */;
        x = "VERTEX";
        N = "effectTextAnimation";
        T = "time_";
        m = "minecraft:blocks/planks_oak";
        Ga = "item.charcoal";
        ga = ", texid: ";
        M = "Height";
        Q = "zombie";
        a = "Can't serialize unregistered packet";
        ca = "hoveredBlockY_";
        e = "gl_caps[ARB_occlusion_query2]";
        Ia = 301 /* ZKM Deobf Int */;
        f = "o_arm";
        F = "amd";
        l = 0.7685D /* ZKM Deobf */;
        H = "bootsDiamond";
        Ka = "Fleeing speed bonus";
        Aa = "waxed_exposed_cut_copper_stairs";
        Ha = "DARK_BLUE";
        z = "polished_blackstone_brick_slab_double";
        X = "Name cannot be null!";
        G = "sp";
        D = "waxed_weathered_cut_copper";
        i = "GL error 0x%04x: %s at %s %s\n";
        B = "GL11.GL_TEXTURE_MIN_FILTER";
        c = "assets/minecraft/blockstates/granite.json";
        I = "Intruders!!!!";
        b = "Duplicate enchantment id!";
        P = -3.4779000282287598F /* ZKM Deobf */;
        v = "emotes/emote/";
        S = "strikethrough";
        U = "GL11.GL_MAP_COLOR";
        C = 12345 /* ZKM Deobf Int */;
        R = "Included file not found: ";
        k = ", tallocated: ";
        L = "textures/body/garlands4.png";
        Y = "controls.title";
        r = "right.Shape32";
        K = "\u0432\u0441\u0451";
        A = "bow3";
        h = 0.9399999976158142F /* ZKM Deobf */;
        V = 2932 /* ZKM Deobf Int */;
        W = 0.015625D /* ZKM Deobf */;
        s = "GL11.GL_ALPHA16";
        la = 3475 /* ZKM Deobf Int */;
        y = 52.0D /* ZKM Deobf */;
        o = 0xCA20FA2BE651E224L ^ 0xCA20FA2BE651FF68L;
        J = "overlay";
        q = "No method: ";
        E = "/shaders/shaders.properties";
        g = "ELEMENTID";
        Da = "smooth_red_sandstone";
        Ja = "https://shaderserver.vimeworld.com/verify/upload?";
        j = "g";
        u = -0.00570000009611249F /* ZKM Deobf */;
        p = 1.325700044631958F /* ZKM Deobf */;
        Z = "North Carolina";
        ja = "overrideHeight:";
        w = "MC_";
        fa = 61457 /* ZKM Deobf Int */;
        t = "Level Requirement: ";
        d = "SHIMMER";
    }
}

