/*
 * Decompiled with CFR 0.152.
 */
public final class aSa_2 {
    public static final int ha;
    public static final int Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final float Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final int S;
    public static final double Z;
    public static final String Y;
    public static final double r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final double p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        M = "Shaders can not be loaded, Fast Render is enabled.";
        v = "hide-hud-network-info";
        y = "east=false,north=true,south=false,up=true,west=false";
        Aa = 7.449999809265137F /* ZKM Deobf */;
        H = -1.4766000509262085F /* ZKM Deobf */;
        P = "dirt";
        la = 608 /* ZKM Deobf Int */;
        a = "MUL";
        Fa = 3331 /* ZKM Deobf Int */;
        O = "commands.seed.success";
        Ia = "destroy";
        m = "light_blue_stained_glass_pane";
        q = "pre-renderCompositeFinal";
        K = " points";
        V = 0.0D /* ZKM Deobf */;
        N = "spectator";
        S = 5390 /* ZKM Deobf Int */;
        U = 9154376 /* ZKM Deobf Int */;
        X = "textures/gui/title/background/panorama_2.png";
        h = "wall_ns_above";
        k = 2000 /* ZKM Deobf Int */;
        z = "\u0422\u043e\u043b\u044c\u043a\u043e \u0431\u0440\u043e\u043d\u044f";
        F = "dark";
        Ga = "[]";
        Y = "stairsStone";
        W = "Invalid handler";
        Q = "OPTIONSET";
        G = "mob.zombie.infect";
        n = "attribute";
        c = "remove";
        ga = "frontleg.main";
        t = ", addedParent: ";
        e = ", texture='";
        B = "Right.Right49";
        ha = 2824 /* ZKM Deobf Int */;
        I = "24";
        w = "Wrong location! (";
        fa = "' (";
        T = "foodTickTimer";
        i = "GL13.GL_TEXTURE31";
        ca = "Right.Right2";
        ja = "brown_stained_hardened_clay";
        l = " is an invalid choice";
        Da = 8237 /* ZKM Deobf Int */;
        Z = 0.27D /* ZKM Deobf */;
        b = 0.004000000189989805F /* ZKM Deobf */;
        C = "UP_X";
        Ha = 0.53125F /* ZKM Deobf */;
        u = "kind_";
        D = "The received encoded string buffer length is less than zero! Weird string!";
        p = -0.8040816326530612D /* ZKM Deobf */;
        r = 0.001953125D /* ZKM Deobf */;
        Ka = "chestplateNetherite";
        E = "Spawn Reinforcements Chance";
        R = "COD";
        s = "Body.Shape33";
        d = "waxed_weathered_cut_copper_stairs";
        Ja = "[/MOTD]";
        g = "MAGMA_CUBE";
        j = "texture_";
        x = "Player Count";
        o = -9.960000038146973F /* ZKM Deobf */;
        f = "Texture";
        A = "mossy_cobblestone";
        L = "icons/icon_32x32.png";
        J = "fragment";
    }

    public aSa_2() {
        aSa_2 a2;
    }
}

