/*
 * Decompiled with CFR 0.152.
 */
public final class aSa_2 {
    public static final int ha;
    public static final int Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final float Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final int S;
    public static final double Z;
    public static final String Y;
    public static final double r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final double p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        M = "Shaders can not be loaded, Fast Render is enabled.";
        v = "hide-hud-network-info";
        y = "east=false,north=true,south=false,up=true,west=false";
        Aa = Float.intBitsToFloat(0x8D9DAB3A ^ 0xCD73CD5C);
        H = Float.intBitsToFloat(0xCBDCFC13 ^ 0x7461FD28);
        P = "dirt";
        la = 0xF82A99A4 ^ 0xF82A9BC4;
        a = "MUL";
        Fa = 0xFED516 ^ 0xFED815;
        O = "commands.seed.success";
        Ia = "destroy";
        m = "light_blue_stained_glass_pane";
        q = "pre-renderCompositeFinal";
        K = " points";
        V = Double.longBitsToDouble(0x82A8E03D7E097686L ^ 0x82A8E03D7E097686L);
        N = "spectator";
        S = 0xE337EC61 ^ 0xE337F96F;
        U = 0x85EA4841 ^ 0x8561E709;
        X = "textures/gui/title/background/panorama_2.png";
        h = "wall_ns_above";
        k = 0x3DA83796 ^ 0x3DA83046;
        z = "\u0422\u043e\u043b\u044c\u043a\u043e \u0431\u0440\u043e\u043d\u044f";
        F = "dark";
        Ga = "[]";
        Y = "stairsStone";
        W = "Invalid handler";
        Q = "OPTIONSET";
        G = "mob.zombie.infect";
        n = "attribute";
        c = "remove";
        ga = "frontleg.main";
        t = ", addedParent: ";
        e = ", texture='";
        B = "Right.Right49";
        ha = 0x26A6E9CA ^ 0x26A6E2C2;
        I = "24";
        w = "Wrong location! (";
        fa = "' (";
        T = "foodTickTimer";
        i = "GL13.GL_TEXTURE31";
        ca = "Right.Right2";
        ja = "brown_stained_hardened_clay";
        l = " is an invalid choice";
        Da = 0x35103892 ^ 0x351018BF;
        Z = Double.longBitsToDouble(0x28F13270F195D8E6L ^ 0x172075DEE5EF39AEL);
        b = Float.intBitsToFloat(0x9ABC8460 ^ 0xA13F960F);
        C = "UP_X";
        Ha = Float.intBitsToFloat(0x3C268A9F ^ 0x32E8A9F);
        u = "kind_";
        D = "The received encoded string buffer length is less than zero! Weird string!";
        p = Double.longBitsToDouble(0xB6300F0DAAEB9EL ^ 0xBF5F8B066ADB0F4BL);
        r = Double.longBitsToDouble(0x50FB005982BDEA32L ^ 0x6F9B005982BDEA32L);
        Ka = "chestplateNetherite";
        E = "Spawn Reinforcements Chance";
        R = "COD";
        s = "Body.Shape33";
        d = "waxed_weathered_cut_copper_stairs";
        Ja = "[/MOTD]";
        g = "MAGMA_CUBE";
        j = "texture_";
        x = "Player Count";
        o = Float.intBitsToFloat(0xB8318110 ^ 0x792EDD39);
        f = "Texture";
        A = "mossy_cobblestone";
        L = "icons/icon_32x32.png";
        J = "fragment";
    }

    public aSa_2() {
        aSa_2 a2;
    }
}

