/*
 * Decompiled with CFR 0.152.
 */
public final class ATa {
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final double Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final float Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final long y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final float q;
    public static final float x;
    public static final float v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final int M;
    public static final String k;
    public static final double j;
    public static final String J;
    public static final String A;
    public static final String I;

    public ATa() {
        ATa a2;
    }

    static {
        t = "GL11.GL_CLIP_PLANE0";
        s = ",;";
        F = "concrete_powder";
        G = "RGB5_A1";
        o = 7680 /* ZKM Deobf Int */;
        g = "model_helmet";
        J = "ARMOR_LEGS";
        r = 0.8999999761581421F /* ZKM Deobf */;
        d = "assets/minecraft/models/block/podzol.json";
        K = "tools";
        v = -6.133299827575684F /* ZKM Deobf */;
        N = "brain_coral_block";
        x = -0.20000000298023224F /* ZKM Deobf */;
        ia = "potion.prefix.bulky";
        X = 3072 /* ZKM Deobf Int */;
        T = "Right.Right0";
        Z = 0.84375F /* ZKM Deobf */;
        n = "fire_layer_[0-1]";
        w = "TOUCHSCREEN";
        e = "data:urlencoded,";
        la = 40057 /* ZKM Deobf Int */;
        a = "Piece1.Shape8";
        m = "ofPotionParticles:";
        Y = "props";
        ga = "cobblestone";
        l = "GL14.GL_BLEND_SRC_RGB";
        y = 0x72A91974CDBD2A5L ^ 0x72A91974CDBD2B9L;
        R = "Fade";
        Ha = "rainStrength";
        Fa = "culling_";
        i = 322 /* ZKM Deobf Int */;
        q = 0.05250000208616257F /* ZKM Deobf */;
        fa = "CX";
        Da = ", max: ";
        O = 30003 /* ZKM Deobf Int */;
        ba = "Error linking with the LibraryJavaSound plug-in";
        Ga = "bounciness_randomness";
        M = 272 /* ZKM Deobf Int */;
        P = "assets/minecraft/models/block/cube_mirrored.json";
        b = "Piece2.Shape7";
        C = "MinecartFurnace";
        z = 40049 /* ZKM Deobf Int */;
        A = "shadow terrain solid";
        Aa = "HOLD";
        U = "redstone";
        f = "gbufferProjectionInverse";
        ha = "resourcepacks/";
        k = "potion.prefix.thick";
        H = "A team with the name '";
        Ja = 34852 /* ZKM Deobf Int */;
        L = 137 /* ZKM Deobf Int */;
        V = "achievement.onARail";
        W = "Invalid index %d requested for %s";
        p = "Exception in server tick loop";
        ca = "test";
        h = "leaves2";
        E = ", tex: ";
        Ka = "Shape26";
        S = 40040 /* ZKM Deobf Int */;
        u = "ofVoidParticles:";
        ja = "unsupported filtering method";
        Ma = 414 /* ZKM Deobf Int */;
        j = 0.55D /* ZKM Deobf */;
        B = "Camera path resource not found: ";
        Q = "BOTTOM_RIGHT";
        c = "stat.swimOneCm";
        Ia = 57.29577951308232D /* ZKM Deobf */;
        D = ", face: ";
        I = "glass_pane_top_white";
    }
}

