/*
 * Decompiled with CFR 0.152.
 */
public final class ATa {
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final double Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final float Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final long y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final float q;
    public static final float x;
    public static final float v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final int M;
    public static final String k;
    public static final double j;
    public static final String J;
    public static final String A;
    public static final String I;

    public ATa() {
        ATa a2;
    }

    static {
        t = "GL11.GL_CLIP_PLANE0";
        s = ",;";
        F = "concrete_powder";
        G = "RGB5_A1";
        o = 0x73EF257F ^ 0x73EF3B7F;
        g = "model_helmet";
        J = "ARMOR_LEGS";
        r = Float.intBitsToFloat(0x75AF366E ^ 0x4AC95008);
        d = "assets/minecraft/models/block/podzol.json";
        K = "tools";
        v = Float.intBitsToFloat(0x70FF7B34 ^ 0xB03B38CA);
        N = "brain_coral_block";
        x = Float.intBitsToFloat(0x94D1279E ^ 0x2A9DEB53);
        ia = "potion.prefix.bulky";
        X = 0x5A2461DA ^ 0x5A246DDA;
        T = "Right.Right0";
        Z = Float.intBitsToFloat(0xDA484053 ^ 0xE5104053);
        n = "fire_layer_[0-1]";
        w = "TOUCHSCREEN";
        e = "data:urlencoded,";
        la = 0x8B8583FD ^ 0x8B851F84;
        a = "Piece1.Shape8";
        m = "ofPotionParticles:";
        Y = "props";
        ga = "cobblestone";
        l = "GL14.GL_BLEND_SRC_RGB";
        y = 0x72A91974CDBD2A5L ^ 0x72A91974CDBD2B9L;
        R = "Fade";
        Ha = "rainStrength";
        Fa = "culling_";
        i = 0x2BFCF745 ^ 0x2BFCF607;
        q = Float.intBitsToFloat(0x8A48FDDC ^ 0xB71FF7E2);
        fa = "CX";
        Da = ", max: ";
        O = 0x87A2F3DC ^ 0x87A286EF;
        ba = "Error linking with the LibraryJavaSound plug-in";
        Ga = "bounciness_randomness";
        M = 0x99F1A ^ 0x99E0A;
        P = "assets/minecraft/models/block/cube_mirrored.json";
        b = "Piece2.Shape7";
        C = "MinecartFurnace";
        z = 0x8594708 ^ 0x859DB79;
        A = "shadow terrain solid";
        Aa = "HOLD";
        U = "redstone";
        f = "gbufferProjectionInverse";
        ha = "resourcepacks/";
        k = "potion.prefix.thick";
        H = "A team with the name '";
        Ja = 0xB3355037 ^ 0xB335D813;
        L = 0xD06E3401 ^ 0xD06E3488;
        V = "achievement.onARail";
        W = "Invalid index %d requested for %s";
        p = "Exception in server tick loop";
        ca = "test";
        h = "leaves2";
        E = ", tex: ";
        Ka = "Shape26";
        S = 0x6524B239 ^ 0x65242E51;
        u = "ofVoidParticles:";
        ja = "unsupported filtering method";
        Ma = 0x117D46CF ^ 0x117D4751;
        j = Double.longBitsToDouble(0x69F7D8ACA554ABAAL ^ 0x561641353CCD3230L);
        B = "Camera path resource not found: ";
        Q = "BOTTOM_RIGHT";
        c = "stat.swimOneCm";
        Ia = Double.longBitsToDouble(0xE94C902E69A9E785L ^ 0xA90035F273CA267DL);
        D = ", face: ";
        I = "glass_pane_top_white";
    }
}

