/*
 * Decompiled with CFR 0.152.
 */
public final class Ata_1 {
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final long p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final String e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final double I;

    static {
        q = "Shape7";
        V = "ENCHANTMENT";
        C = "textures/pet/triggerteddy.png";
        W = "fireball";
        Da = "lapis";
        B = "GL11.GL_VERSION";
        D = Float.intBitsToFloat(0xEE785216 ^ 0xD0693A65);
        fa = " size ";
        K = "EASE_IN_QUART";
        s = "seaLevel";
        f = "pinecolor.png";
        g = "CPM";
        t = "CB";
        la = 0x950A020D ^ 0x6AF5FDE5;
        T = "ThrownExpBottle";
        A = "lapis_ore";
        U = "options.viewBobbing";
        O = "spruce_planks";
        o = "Your IP address is banned from this server!\nReason: ";
        P = 0x72244415 ^ 0x7224C0F4;
        Ia = "of.options.save.30min";
        h = "shaders/";
        d = "of.options.WATER_PARTICLES";
        ca = 0xBAC88107 ^ 0x45B77EF8;
        M = 0xD0A906EC ^ 0x2F5B9D13;
        b = "attack";
        ja = "VoicePlayerState{microExists=";
        J = "scrollOffsetVal_";
        v = 0x26C9085B ^ 0x26C980C8;
        Ha = "ofClearWater:";
        p = 0xFF18FDEDADD8BA57L ^ 0xFF18FDEDADD7F817L;
        k = "strawberry";
        c = 0x1297C142 ^ 0x12975D05;
        w = "targets";
        z = 0xBCA5B472 ^ 0xBCA5A17A;
        X = 0xE8CBEABF ^ 0xE8CB8963;
        H = "Illegal color";
        Ja = "Left.Shape30123";
        n = 0xEBACCF8 ^ 0xEBAC1A0;
        I = Double.longBitsToDouble(0xB2C8FF6B8F6112A0L ^ 0x8C58399C4F6112A0L);
        R = 0xCE05116E ^ 0xCE05138E;
        l = Float.intBitsToFloat(0x78EA12C2 ^ 0xC3E9070B);
        u = "Airportal";
        m = "options.guiScale.x9";
        F = "spruce_slab";
        a = "kenny";
        j = "createWorld.customize.custom.mainNoiseScaleX";
        ga = "blocks/lava_flow";
        r = "Already decorating";
        G = "game.neutral.hurt.fall.small";
        Ga = "furnace";
        Q = "SmartLeaves: Model is not cube, general quads: ";
        y = "Spawn egg shell";
        Fa = "EASE_IN_QUAD";
        x = 0x6D1AB6C8 ^ 0x6D1A36FC;
        E = "leave";
        i = "player-collision-velocity";
        Z = "\u0438 \u043f\u0440\u0438\u0433\u043b\u0430\u0448\u0435\u043d\u0438\u044f";
        L = "yellow_concrete";
        e = "GL11.GL_T2F_N3F_V3F";
        Aa = "chest_texture";
        N = "\u00a7a\u0412\u0435\u0441\u0435\u043d\u043d\u044f\u044f \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044f";
        S = "Exception while adding particle";
        Y = "textures/pet/spinner_fl2.png";
        Ka = "Invalid rotation ";
    }

    public Ata_1() {
        Ata_1 a2;
    }
}

