/*
 * Decompiled with CFR 0.152.
 */
public final class aua {
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final int fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final float X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final float q;
    public static final long x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final float a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final double L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        l = "textures/pet/xmas_gift_green.png";
        ha = "waxed_cut_copper_slab_double";
        C = 0x765C6DC1 ^ 0x765C6053;
        ba = "assets/minecraft/blockstates/andesite.json";
        y = "textures/pet/christmas_chest2.png";
        n = "Right.Right43";
        d = 0xD5E17A3A ^ 0xD5E17169;
        f = 0xD05C43C0 ^ 0xD05C41A8;
        Ma = "RGBA32I";
        j = "ENTITYBLOCK_ANIMATED";
        O = "lightningBolt";
        g = "at_tangent";
        ca = "LIGHT_PURPLE";
        X = Float.intBitsToFloat(0xE34B20B8 ^ 0xA398138B);
        D = "WIDTHEXPRANIM";
        i = "glass.properties";
        P = "ALL_STEM";
        v = 0xDE88DC3C ^ 0xDE88D068;
        L = Double.longBitsToDouble(0x30B41709A36548B3L ^ 0x8F306DE8E36548B3L);
        k = "commands.spreadplayers.usage";
        G = "_model_";
        Q = "hide-hud-armor";
        la = "of.options.RAIN_SPLASH";
        Ha = "Block{";
        Da = "bites";
        ja = "Broken attribute value";
        ga = "LOW";
        W = "fireworks.";
        e = "texteria/voicechat.json";
        Aa = 0xABD89534 ^ 0xABD86539;
        H = "deepslateBrickStairs";
        r = "position";
        s = "container.brewing";
        M = "outtarget";
        Ga = 0x8ECE1278 ^ 0x8ECE1144;
        A = "speed_";
        q = Float.intBitsToFloat(0xC6D48E21 ^ 0x6A48E21);
        a = Float.intBitsToFloat(0x9CA18271 ^ 0xDF818271);
        B = "\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c \u043f\u0440\u0438\u0433\u043b\u0430\u0448\u0435\u043d\u0438\u0435";
        x = 0x2B9E91F1DE78B2F0L ^ 0x2B9E91F1DE3BB557L;
        w = "birch_trapdoor";
        S = "waxedExposedCutCopperSlab";
        R = "pre shadow";
        u = "options.stream.chat.userFilter.all";
        I = "RENDER_DISTANCE";
        F = "VISIBLE";
        m = 0x8427AE6E ^ 0x8427AF69;
        U = "CATMULLROM";
        Ka = "ViPH";
        J = "textures/gui/container/stats_icons.png";
        h = "startFade_";
        E = "NORTH";
        Ia = "entityCollision";
        N = 0x94D171E6 ^ 0x94D1F281;
        c = "MUSHROOM_COW";
        V = Float.intBitsToFloat(0xFF550970 ^ 0xCAD33ECD);
        Fa = "shaders/post/fxaa_of_";
        Ja = "math.atan";
        K = "0.34, 1.56, 0.64, 1";
        z = "\u0418\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u044d\u043c\u043e\u0446\u0438\u0438";
        p = "of.options.shaders.HAND_DEPTH_MUL";
        o = "IsVillager";
        b = Float.intBitsToFloat(0x85DADAFD ^ 0xC4C1E9CE);
        Z = 0x17B15EC ^ 0x17BE5E4;
        Y = "stat.entityKilledBy";
        T = Float.intBitsToFloat(0x2DC8933D ^ 0x907A5965);
        fa = 0x73298E92 ^ 0x73298F8F;
        t = "options.chat.height.unfocused";
    }

    public aua() {
        aua a2;
    }
}

