/*
 * Decompiled with CFR 0.152.
 */
public final class Bpa_2 {
    public static final float Ea;
    public static final String Ca;
    public static final double ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final double Ja;
    public static final int ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final float i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final float A;
    public static final String I;

    public Bpa_2() {
        Bpa_2 a2;
    }

    static {
        Y = "uvlock";
        C = "of.options.TREES";
        F = "textures/pet/deerpet.png";
        D = "notGate";
        U = "GL11.GL_TEXTURE_STACK_DEPTH";
        b = 16.100000381469727F /* ZKM Deobf */;
        j = "textures/entity/rabbit/black.png";
        k = "animationTicks_";
        L = "goalSetup";
        z = "purpurBlock";
        Ia = "dstalpha";
        w = 3.5F /* ZKM Deobf */;
        v = 1027 /* ZKM Deobf Int */;
        Ea = 3.799999952316284F /* ZKM Deobf */;
        Aa = "BLL3";
        P = "Could not load animation ";
        ja = 5386 /* ZKM Deobf Int */;
        d = "%(\\d+\\$)?[\\d\\.]*[df]";
        H = "key.mouseButton";
        ha = "assets/minecraft/models/block/sandstone_all.json";
        a = 197 /* ZKM Deobf Int */;
        E = "Front.8a";
        Da = "low_left_arm";
        ga = 412 /* ZKM Deobf Int */;
        s = 190 /* ZKM Deobf Int */;
        x = 357 /* ZKM Deobf Int */;
        e = "Shader info log: ";
        W = "\u4eca";
        B = "&c\u0422\u043e\u0447\u043a\u0438 \u0441 \u0442\u0430\u043a\u0438\u043c \u043d\u043e\u043c\u0435\u0440\u043e\u043c \u0435\u0449\u0435 \u043d\u0435\u0442";
        I = "RUN_COMMAND";
        Ja = 1.41D /* ZKM Deobf */;
        m = 656 /* ZKM Deobf Int */;
        Q = "chirp";
        Ga = "). Deleting it.";
        Ma = "shaders/post/invert.json";
        X = "ANIMATED_FIRE";
        ca = "lodestone";
        o = "failed";
        g = 4286019447 /* ZKM Deobf Int */;
        p = "TEXTCOLORANIM";
        Ca = "ghast";
        i = 0.22500000894069672F /* ZKM Deobf */;
        A = 0.1745329052209854F /* ZKM Deobf */;
        Fa = "stripe_middle";
        q = "Noise texture enabled";
        Ha = 46 /* ZKM Deobf Int */;
        la = "GL11.GL_FRONT_AND_BACK";
        R = "texture_chest";
        r = "shadowcolor1Nearest";
        N = "commands.gamerule.usage";
        y = "coarse";
        J = "motionXExpr_";
        n = "random.chestopen";
        t = "\u00a7e%d fps\u00a7r (%d chunk update%s) T: %s%s%s%s%s";
        Ka = "armorItemAmount";
        T = "HEIGHTANIM";
        O = "Not found: ";
        Z = 53 /* ZKM Deobf Int */;
        G = 659 /* ZKM Deobf Int */;
        c = "GL11.GL_SET";
        fa = "VarInt too big";
        f = "options.ao";
        u = "textures/blocks/sandstone_normal.png";
        ia = -0.03125D /* ZKM Deobf */;
        K = 2415919104 /* ZKM Deobf Int */;
        V = "Back-face Cutout Mipped";
        M = 2097152 /* ZKM Deobf Int */;
        l = "HurtTime";
        h = "modelPart_";
        ba = "EMOTES";
        S = 6839882 /* ZKM Deobf Int */;
    }
}

