/*
 * Decompiled with CFR 0.152.
 */
public final class Bpa_2 {
    public static final float Ea;
    public static final String Ca;
    public static final double ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final double Ja;
    public static final int ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final float i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final float A;
    public static final String I;

    public Bpa_2() {
        Bpa_2 a2;
    }

    static {
        Y = "uvlock";
        C = "of.options.TREES";
        F = "textures/pet/deerpet.png";
        D = "notGate";
        U = "GL11.GL_TEXTURE_STACK_DEPTH";
        b = Float.intBitsToFloat(0xE717DC6D ^ 0xA69710A0);
        j = "textures/entity/rabbit/black.png";
        k = "animationTicks_";
        L = "goalSetup";
        z = "purpurBlock";
        Ia = "dstalpha";
        w = Float.intBitsToFloat(0x53965074 ^ 0x13F65074);
        v = 0x9A36E4C0 ^ 0x9A36E0C3;
        Ea = Float.intBitsToFloat(0x7C34067E ^ 0x3C47354D);
        Aa = "BLL3";
        P = "Could not load animation ";
        ja = 0xCC3B28FD ^ 0xCC3B3DF7;
        d = "%(\\d+\\$)?[\\d\\.]*[df]";
        H = "key.mouseButton";
        ha = "assets/minecraft/models/block/sandstone_all.json";
        a = 0xA6CE0D1B ^ 0xA6CE0DDE;
        E = "Front.8a";
        Da = "low_left_arm";
        ga = 0xC86E7C1C ^ 0xC86E7D80;
        s = 0x1CA080BB ^ 0x1CA08005;
        x = 0x90F7C98B ^ 0x90F7C8EE;
        e = "Shader info log: ";
        W = "\u4eca";
        B = "&c\u0422\u043e\u0447\u043a\u0438 \u0441 \u0442\u0430\u043a\u0438\u043c \u043d\u043e\u043c\u0435\u0440\u043e\u043c \u0435\u0449\u0435 \u043d\u0435\u0442";
        I = "RUN_COMMAND";
        Ja = Double.longBitsToDouble(0xFE6C688789846671L ^ 0xC19AE7DBA171A4FEL);
        m = 0xDB604A19 ^ 0xDB604889;
        Q = "chirp";
        Ga = "). Deleting it.";
        Ma = "shaders/post/invert.json";
        X = "ANIMATED_FIRE";
        ca = "lodestone";
        o = "failed";
        g = 0xC35F2A30 ^ 0x3C285D47;
        p = "TEXTCOLORANIM";
        Ca = "ghast";
        i = Float.intBitsToFloat(0x7CAE6F55 ^ 0x42C80932);
        A = Float.intBitsToFloat(0x133675CC ^ 0x2D04CD0D);
        Fa = "stripe_middle";
        q = "Noise texture enabled";
        Ha = 0x3B2E3241 ^ 0x3B2E326F;
        la = "GL11.GL_FRONT_AND_BACK";
        R = "texture_chest";
        r = "shadowcolor1Nearest";
        N = "commands.gamerule.usage";
        y = "coarse";
        J = "motionXExpr_";
        n = "random.chestopen";
        t = "\u00a7e%d fps\u00a7r (%d chunk update%s) T: %s%s%s%s%s";
        Ka = "armorItemAmount";
        T = "HEIGHTANIM";
        O = "Not found: ";
        Z = 0x4F2CF7D1 ^ 0x4F2CF7E4;
        G = 0x5C8EEF25 ^ 0x5C8EEDB6;
        c = "GL11.GL_SET";
        fa = "VarInt too big";
        f = "options.ao";
        u = "textures/blocks/sandstone_normal.png";
        ia = Double.longBitsToDouble(0x5415090BC673F787L ^ 0xEBB5090BC673F787L);
        K = 0xCD6DAEAE ^ 0x5D6DAEAE;
        V = "Back-face Cutout Mipped";
        M = 0xF27A566B ^ 0xF25A566B;
        l = "HurtTime";
        h = "modelPart_";
        ba = "EMOTES";
        S = 0xDBDBB02D ^ 0xDBB3EE67;
    }
}

