/*
 * Decompiled with CFR 0.152.
 */
public final class bpa_1 {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final float Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final float O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final double J;
    public static final String A;
    public static final int I;

    public bpa_1() {
        bpa_1 a2;
    }

    static {
        c = "largeBlast";
        J = Double.longBitsToDouble(0x174D657F051AF301L ^ 0x174D657F051AF300L);
        h = "whiteStone";
        Y = "Invalid TagEnd added to ListTag";
        x = "\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435";
        U = 0xCB7E2921 ^ 0xCB7E2864;
        g = 0xC3659B6 ^ 0xF3C21A80;
        y = "IRON";
        q = "nearest";
        G = 0x4E300FBA ^ 0x4E94A702;
        k = "right.Shape30";
        i = Float.intBitsToFloat(0x93FB2CD8 ^ 0xACF8B0D7);
        t = "thirdperson";
        Fa = "ip";
        fa = 0xF8F599D0 ^ 0xF8F5997D;
        f = "pulling_0";
        T = "ironMaxHeight";
        W = Float.intBitsToFloat(0xE22C4677 ^ 0xDC921CC8);
        P = "Text";
        L = "commands.save.flushEnd";
        Z = "commands.effect.failure.notActive.all";
        m = "Fetching addPacket for removed entity";
        r = "' took aprox ";
        R = "NBT Tag";
        e = 0xBF4BDF56 ^ 0xBF4BD884;
        n = "crimson_door";
        I = 0xB1C255B9 ^ 0xB1C255E7;
        Ja = "GL error 0x%04x: %s at %s %s %s\n";
        ja = Float.intBitsToFloat(0xFF3E9135 ^ 0xC0B490F8);
        z = "children";
        Aa = Float.intBitsToFloat(0x7C0C6304 ^ 0xBDEC6304);
        O = Float.intBitsToFloat(0x861AA24B ^ 0xBAC0D644);
        la = "TABLE";
        d = "fov_";
        D = ", value: ";
        E = "hide-looking-at-debug";
        F = "impelXZOnSides_";
        M = "Back.7a";
        H = "jumpBar";
        v = "commands.spreadplayers.success.";
        Ia = "Once per ";
        V = "duration";
        A = "hash is broken";
        s = Float.intBitsToFloat(0x19D3B456 ^ 0x22F0635D);
        N = "airFriction_";
        a = "ROSE";
        X = "bobView";
        p = "village";
        w = "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u1004\u0000\u0002\u1004\u0001\u0003\u1004\u0002\u0004\u1004\u0003\u0005\u1001\u0004";
        ga = "ofSunMoon:";
        Ga = " in model ";
        b = "GL11.GL_EYE_LINEAR";
        l = "GL14.GL_GENERATE_MIPMAP_HINT";
        K = Float.intBitsToFloat(0x8F97D104 ^ 0xB10E489E);
        o = "\": \"";
        Ha = Float.intBitsToFloat(0xA7293497 ^ 0xE6153497);
        C = "of.options.shaders.TEX_MAG_FIL_B";
        B = "Applying mipmap";
        Da = "doFireTick";
        Ka = "NORTH_EAST";
        ca = "[Shaders] Error saving configuration for ";
        j = "syringa";
        Q = "X180_Y270";
        S = "Random zombie-spawn bonus";
        u = "chestplate_";
    }
}

