/*
 * Decompiled with CFR 0.152.
 */
public final class bpa_1 {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final float Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final float O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final double J;
    public static final String A;
    public static final int I;

    public bpa_1() {
        bpa_1 a2;
    }

    static {
        c = "largeBlast";
        J = 5e-324D /* ZKM Deobf */;
        h = "whiteStone";
        Y = "Invalid TagEnd added to ListTag";
        x = "\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435";
        U = 325 /* ZKM Deobf Int */;
        g = 4294198070 /* ZKM Deobf Int */;
        y = "IRON";
        q = "nearest";
        G = 10791096 /* ZKM Deobf Int */;
        k = "right.Shape30";
        i = 0.5141000151634216F /* ZKM Deobf */;
        t = "thirdperson";
        Fa = "ip";
        fa = 173 /* ZKM Deobf Int */;
        f = "pulling_0";
        T = "ironMaxHeight";
        W = 0.37178608775138855F /* ZKM Deobf */;
        P = "Text";
        L = "commands.save.flushEnd";
        Z = "commands.effect.failure.notActive.all";
        m = "Fetching addPacket for removed entity";
        r = "' took aprox ";
        R = "NBT Tag";
        e = 2002 /* ZKM Deobf Int */;
        n = "crimson_door";
        I = 94 /* ZKM Deobf Int */;
        Ja = "GL error 0x%04x: %s at %s %s %s\n";
        ja = 1.078179955482483F /* ZKM Deobf */;
        z = "children";
        Aa = -28.0F /* ZKM Deobf */;
        O = 0.0266666691750288F /* ZKM Deobf */;
        la = "TABLE";
        d = "fov_";
        D = ", value: ";
        E = "hide-looking-at-debug";
        F = "impelXZOnSides_";
        M = "Back.7a";
        H = "jumpBar";
        v = "commands.spreadplayers.success.";
        Ia = "Once per ";
        V = "duration";
        A = "hash is broken";
        s = 0.002500000176951289F /* ZKM Deobf */;
        N = "airFriction_";
        a = "ROSE";
        X = "bobView";
        p = "village";
        w = "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u1004\u0000\u0002\u1004\u0001\u0003\u1004\u0002\u0004\u1004\u0003\u0005\u1001\u0004";
        ga = "ofSunMoon:";
        Ga = " in model ";
        b = "GL11.GL_EYE_LINEAR";
        l = "GL14.GL_GENERATE_MIPMAP_HINT";
        K = 0.30000001192092896F /* ZKM Deobf */;
        o = "\": \"";
        Ha = 11.75F /* ZKM Deobf */;
        C = "of.options.shaders.TEX_MAG_FIL_B";
        B = "Applying mipmap";
        Da = "doFireTick";
        Ka = "NORTH_EAST";
        ca = "[Shaders] Error saving configuration for ";
        j = "syringa";
        Q = "X180_Y270";
        S = "Random zombie-spawn bonus";
        u = "chestplate_";
    }
}

