/*
 * Decompiled with CFR 0.152.
 */
public final class BQa {
    public static final float ea;
    public static final String Ea;
    public static final float Ca;
    public static final double ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final double R;
    public static final int Q;
    public static final double N;
    public static final String T;
    public static final float p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final float M;
    public static final String k;
    public static final int j;
    public static final int J;
    public static final int A;
    public static final float I;

    static {
        Ga = "key.right";
        S = "hosting_lan";
        e = "hat";
        B = "glass_blue";
        la = "default";
        U = "value_";
        Ca = Float.intBitsToFloat(0x967AD11F ^ 0xDFD5191F);
        Ea = "FLIP_NORTH";
        d = Float.intBitsToFloat(0xB42C2C8B ^ 0xF43509CD);
        X = "purpur_double_slab";
        x = "colortex4";
        v = "ofPortalParticles:";
        T = "GL11.GL_LUMINANCE8_ALPHA8";
        O = "commands.defaultgamemode.usage";
        M = Float.intBitsToFloat(0x9E4B641D ^ 0x21C0D6E2);
        Q = 0xDEC5400 ^ 0xDEC549B;
        o = "exposedChiseledCopper";
        D = "zombie.spawnReinforcements";
        Ka = ".mcr";
        L = "Uniform.upload called, but count value (";
        E = "record.nowPlaying";
        ga = "unsupported interlace method ";
        I = Float.intBitsToFloat(0xBF422AC4 ^ 0x7ECB6D6A);
        H = Float.intBitsToFloat(0xBEFF0639 ^ 0x7E170639);
        q = "changeCallback_";
        P = Float.intBitsToFloat(0xFC77DF3D ^ 0x4307DF3D);
        Ma = "hash";
        K = "Unknown blend: ";
        C = "floor";
        u = "\u0410\u0440\u0445\u0438\u0432\u043d\u0430\u044f";
        c = "st";
        ea = Float.intBitsToFloat(0x490BC1A2 ^ 0x7680735D);
        Da = "%1$d / 0x%1$X / 0b%2$s";
        R = Double.longBitsToDouble(0x1F28A1AA680AD84CL ^ 0x2098A1AA680AD84CL);
        Ia = "STOPANIMATION";
        A = 0xBD2D17C7 ^ 0xBD2D92BF;
        n = 0x199BD6E9 ^ 0x19DE99D7;
        Fa = 0xA5758089 ^ 0xA57582E5;
        J = 0x3211A278 ^ 0x3211A191;
        a = "Could not build element in tooltip";
        h = 0xF71BC0D3 ^ 0xF71BBF2C;
        w = "ofFogType:";
        g = "cooked_porkchop";
        s = "q.skin.jacket";
        Aa = "block.";
        t = 0xE6027309 ^ 0xE60271B5;
        k = "commands.banlist.ips";
        G = "Delay";
        ca = "Integrated singleplayer server";
        j = 0x471883ED ^ 0x4718A484;
        Ha = "assets/minecraft/models/block/redstone_block.json";
        ia = Double.longBitsToDouble(0x942AEB99E886BDB3L ^ 0xABF62755244A717EL);
        p = Float.intBitsToFloat(0x23B865CD ^ 0x60D965CD);
        N = Double.longBitsToDouble(0xE77A4CB456CF248BL ^ 0xD9009B46F6CF248BL);
        F = "execute-dance";
        ja = "-0-1+2-3&4-4+13";
        z = "easeInOutQuad";
        V = "GL11.GL_TEXTURE_COORD_ARRAY_TYPE";
        r = Float.intBitsToFloat(0xB5F7283 ^ 0x34FFABF8);
        b = "commands.scoreboard.objectives.add.usage";
        W = 0x636921EF ^ 0x636920A8;
        y = "noiseTextureResolution";
        fa = "creeper/creeper";
        i = "ambient.weather.thunder";
        Z = 0x27327E99 ^ 0x27327378;
        f = "gui/emotes/";
        m = "GSG";
        ba = "meta:missing_sound";
        l = "\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0430\u0435\u0442 \u043f\u0430\u0442\u0438";
        Ja = "\u25b6";
        ha = "twinkle_far";
        Y = "opposite";
    }

    public BQa() {
        BQa a2;
    }
}

