/*
 * Decompiled with CFR 0.152.
 */
public final class BQa {
    public static final float ea;
    public static final String Ea;
    public static final float Ca;
    public static final double ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final double R;
    public static final int Q;
    public static final double N;
    public static final String T;
    public static final float p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final float M;
    public static final String k;
    public static final int j;
    public static final int J;
    public static final int A;
    public static final float I;

    static {
        Ga = "key.right";
        S = "hosting_lan";
        e = "hat";
        B = "glass_blue";
        la = "default";
        U = "value_";
        Ca = 1440000.0F /* ZKM Deobf */;
        Ea = "FLIP_NORTH";
        d = 2.392899990081787F /* ZKM Deobf */;
        X = "purpur_double_slab";
        x = "colortex4";
        v = "ofPortalParticles:";
        T = "GL11.GL_LUMINANCE8_ALPHA8";
        O = "commands.defaultgamemode.usage";
        M = -1.0914000272750854F /* ZKM Deobf */;
        Q = 155 /* ZKM Deobf Int */;
        o = "exposedChiseledCopper";
        D = "zombie.spawnReinforcements";
        Ka = ".mcr";
        L = "Uniform.upload called, but count value (";
        E = "record.nowPlaying";
        ga = "unsupported interlace method ";
        I = -17.15999984741211F /* ZKM Deobf */;
        H = -7.25F /* ZKM Deobf */;
        q = "changeCallback_";
        P = -0.9375F /* ZKM Deobf */;
        Ma = "hash";
        K = "Unknown blend: ";
        C = "floor";
        u = "\u0410\u0440\u0445\u0438\u0432\u043d\u0430\u044f";
        c = "st";
        ea = 1.0914000272750854F /* ZKM Deobf */;
        Da = "%1$d / 0x%1$X / 0b%2$s";
        R = 0.0625D /* ZKM Deobf */;
        Ia = "STOPANIMATION";
        A = 34168 /* ZKM Deobf Int */;
        n = 4542270 /* ZKM Deobf Int */;
        Fa = 620 /* ZKM Deobf Int */;
        J = 1001 /* ZKM Deobf Int */;
        a = "Could not build element in tooltip";
        h = 32767 /* ZKM Deobf Int */;
        w = "ofFogType:";
        g = "cooked_porkchop";
        s = "q.skin.jacket";
        Aa = "block.";
        t = 700 /* ZKM Deobf Int */;
        k = "commands.banlist.ips";
        G = "Delay";
        ca = "Integrated singleplayer server";
        j = 10089 /* ZKM Deobf Int */;
        Ha = "assets/minecraft/models/block/redstone_block.json";
        ia = 0.45D /* ZKM Deobf */;
        p = 225.0F /* ZKM Deobf */;
        N = 1.0000000116860974e-07D /* ZKM Deobf */;
        F = "execute-dance";
        ja = "-0-1+2-3&4-4+13";
        z = "easeInOutQuad";
        V = "GL11.GL_TEXTURE_COORD_ARRAY_TYPE";
        r = 1.2566369771957397F /* ZKM Deobf */;
        b = "commands.scoreboard.objectives.add.usage";
        W = 327 /* ZKM Deobf Int */;
        y = "noiseTextureResolution";
        fa = "creeper/creeper";
        i = "ambient.weather.thunder";
        Z = 3553 /* ZKM Deobf Int */;
        f = "gui/emotes/";
        m = "GSG";
        ba = "meta:missing_sound";
        l = "\u041f\u0435\u0440\u0435\u043c\u0435\u0449\u0430\u0435\u0442 \u043f\u0430\u0442\u0438";
        Ja = "\u25b6";
        ha = "twinkle_far";
        Y = "opposite";
    }

    public BQa() {
        BQa a2;
    }
}

