/*
 * Decompiled with CFR 0.152.
 */
public final class bqa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final long S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final float v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final double H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final double E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Q = "%s/mipmaps/%s.%d%s";
        Ka = "VERTICAL";
        b = "generation";
        g = "The given array is NULL";
        G = "ORANGE_TULIP";
        m = "Server brand";
        F = "createWorld.customize.custom.mainNoiseScaleZ";
        c = "Item name";
        D = "start_at";
        Z = "AAA";
        u = "RABBIT";
        p = 32819 /* ZKM Deobf Int */;
        P = 202 /* ZKM Deobf Int */;
        N = -1.7999999523162842F /* ZKM Deobf */;
        ja = -1.5078125F /* ZKM Deobf */;
        C = "builtin/generated";
        l = "Piece1.Shape28";
        t = "mob.villager.idle";
        k = "CUSTOM_ITEMS";
        Ha = "GL11.GL_PIXEL_MAP_I_TO_I";
        B = "container.enderchest";
        o = 4226832 /* ZKM Deobf Int */;
        V = "invalid frameindex ";
        O = 262144 /* ZKM Deobf Int */;
        Y = "ViDF";
        h = "golden_leggings";
        Da = "Block data value";
        Ga = 74 /* ZKM Deobf Int */;
        w = "copper_grate";
        E = 27.0D /* ZKM Deobf */;
        y = "math.pow";
        i = "body_y_rotation";
        Fa = "worlds";
        ha = "bamboo_door";
        J = "textures/pet/ghast.png";
        a = "DRIP_LAVA";
        ga = "No particle_effect.description was found...";
        I = "gdepthtex";
        n = "Block coordinates";
        q = "\u0412 \u043c\u043e\u0434\u0435\u043b\u0438 \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0430 \u0441\u043b\u043e\u043c\u0430\u043d\u043d\u0430\u044f \u0442\u0435\u043a\u0441\u0442\u0443\u0440\u0430 '";
        j = "OLD_CLIENT";
        f = "\u5002";
        x = 2979 /* ZKM Deobf Int */;
        X = "Alban";
        fa = "potion.effects.whenDrank";
        S = 0x4E6A5D8FE1357856L ^ 0x4E6A5D8FE1356F26L;
        z = 822 /* ZKM Deobf Int */;
        e = "commands.effect.failure.notActive";
        R = "SY";
        Aa = 4.96999979019165F /* ZKM Deobf */;
        s = "armorTags";
        W = "lerp";
        d = "ls";
        Ia = "multiplayer.player.joined.renamed";
        la = "gbuffers_damagedblock";
        Ja = "oxidizedCutCopperStairs";
        r = 12289 /* ZKM Deobf Int */;
        K = "filtered";
        A = "end_stone_brick_wall";
        v = 2.299999952316284F /* ZKM Deobf */;
        U = "Unable to find method '";
        ca = "commands.blockdata.tagError";
        T = "slot.enderchest.";
        M = "ofAnimatedLava";
        H = -180.0D /* ZKM Deobf */;
        L = 4294961979 /* ZKM Deobf Int */;
    }

    public bqa_1() {
        bqa_1 a2;
    }
}

