/*
 * Decompiled with CFR 0.152.
 */
public final class bqa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final long S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final float v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final double H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final double E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Q = "%s/mipmaps/%s.%d%s";
        Ka = "VERTICAL";
        b = "generation";
        g = "The given array is NULL";
        G = "ORANGE_TULIP";
        m = "Server brand";
        F = "createWorld.customize.custom.mainNoiseScaleZ";
        c = "Item name";
        D = "start_at";
        Z = "AAA";
        u = "RABBIT";
        p = 0xB4B1A7D2 ^ 0xB4B127E1;
        P = 0xB9BB5049 ^ 0xB9BB5083;
        N = Float.intBitsToFloat(0xC7BF3CD3 ^ 0x78595AB5);
        ja = Float.intBitsToFloat(0xDE8350F1 ^ 0x614250F1);
        C = "builtin/generated";
        l = "Piece1.Shape28";
        t = "mob.villager.idle";
        k = "CUSTOM_ITEMS";
        Ha = "GL11.GL_PIXEL_MAP_I_TO_I";
        B = "container.enderchest";
        o = 0x341F6E4A ^ 0x345F115A;
        V = "invalid frameindex ";
        O = 0xF3A1A3F0 ^ 0xF3A5A3F0;
        Y = "ViDF";
        h = "golden_leggings";
        Da = "Block data value";
        Ga = 0xD0D1ED97 ^ 0xD0D1EDDD;
        w = "copper_grate";
        E = Double.longBitsToDouble(0xCBD3C9E57F949FF1L ^ 0x8BE8C9E57F949FF1L);
        y = "math.pow";
        i = "body_y_rotation";
        Fa = "worlds";
        ha = "bamboo_door";
        J = "textures/pet/ghast.png";
        a = "DRIP_LAVA";
        ga = "No particle_effect.description was found...";
        I = "gdepthtex";
        n = "Block coordinates";
        q = "\u0412 \u043c\u043e\u0434\u0435\u043b\u0438 \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0430 \u0441\u043b\u043e\u043c\u0430\u043d\u043d\u0430\u044f \u0442\u0435\u043a\u0441\u0442\u0443\u0440\u0430 '";
        j = "OLD_CLIENT";
        f = "\u5002";
        x = 0x823E54E1 ^ 0x823E5F42;
        X = "Alban";
        fa = "potion.effects.whenDrank";
        S = 0x4E6A5D8FE1357856L ^ 0x4E6A5D8FE1356F26L;
        z = 0x393FC4B9 ^ 0x393FC78F;
        e = "commands.effect.failure.notActive";
        R = "SY";
        Aa = Float.intBitsToFloat(0x9B39ADDB ^ 0xDBA6A7E6);
        s = "armorTags";
        W = "lerp";
        d = "ls";
        Ia = "multiplayer.player.joined.renamed";
        la = "gbuffers_damagedblock";
        Ja = "oxidizedCutCopperStairs";
        r = 0x43EA6462 ^ 0x43EA5463;
        K = "filtered";
        A = "end_stone_brick_wall";
        v = Float.intBitsToFloat(0xDB9B6119 ^ 0x9B88522A);
        U = "Unable to find method '";
        ca = "commands.blockdata.tagError";
        T = "slot.enderchest.";
        M = "ofAnimatedLava";
        H = Double.longBitsToDouble(0x1CC458A47561BF83L ^ 0xDCA2D8A47561BF83L);
        L = 0x92B74F2F ^ 0x6D48A414;
    }

    public bqa_1() {
        bqa_1 a2;
    }
}

