/*
 * Decompiled with CFR 0.152.
 */
public final class BRa_2 {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final double Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final double D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public BRa_2() {
        BRa_2 a2;
    }

    static {
        i = "\nYour ban will be removed on ";
        p = "Banned by an operator.";
        K = "hide-crosshair";
        v = 2005 /* ZKM Deobf Int */;
        u = 424 /* ZKM Deobf Int */;
        Da = 1.4779000282287598F /* ZKM Deobf */;
        G = "\u0000\u0006\u0001\u0000\u0001\u0007\u0006\u0000\u0000\u0000\u0001\u0208\u0003C\u0000\u0004:\u0000\u0005\u023b\u0000\u00064\u0000\u0007:\u0000";
        n = "\u041a\u0443\u043f\u0438\u0442\u044c";
        B = -0.017453299835324287F /* ZKM Deobf */;
        f = 33063 /* ZKM Deobf Int */;
        R = "orange_stained_glass";
        k = 7.0F /* ZKM Deobf */;
        z = 32856 /* ZKM Deobf Int */;
        O = "MTick";
        Ia = "Head.32";
        s = "str_starts";
        Z = "QUARTZ";
        a = "mob";
        I = "sticky_piston";
        Y = 0.12D /* ZKM Deobf */;
        Ja = "4b";
        fa = "translucent_sort";
        N = "smooth_sandstone";
        ja = 405 /* ZKM Deobf Int */;
        F = "Expected 3 ";
        la = "Level time";
        E = 112 /* ZKM Deobf Int */;
        L = 34972 /* ZKM Deobf Int */;
        j = "commands.banip.success";
        J = "smooth_basalt";
        Ha = "black_stained_hardened_clay";
        o = "dead_bush";
        x = "gl_caps[EXT_texture_3d]";
        r = "textures/pet/walrus.png";
        H = "font";
        b = 32776 /* ZKM Deobf Int */;
        q = "^[a-zA-Z0-9_]+$";
        M = "player_";
        T = "Could not upload shaderpack";
        c = "[ \t]*const[ \t]*bool[ \t]*(shadowcolor1Mipmap|shadowColor1Mipmap)[ \t]*=[ \t]*true[ \t]*;.*";
        g = "textures/entity/sheep/sheep_fur.png";
        d = "buildSword";
        e = "VERDANT";
        P = "SMOOTH_WORLD";
        w = "0x%05X - %s";
        S = "activatorRail";
        Aa = 378 /* ZKM Deobf Int */;
        Ga = "\ufffd";
        W = "selectServer.deleteQuestion";
        V = "of.options.shaders.SHADOW_CLIP_FRUSTRUM";
        t = "mangrove_log";
        Q = "touchscreen";
        A = ", variants: ";
        U = "half_horizontal_bottom";
        l = ", step: ";
        ca = "stem_(?:bent|straight)";
        m = "[ \t]*const[ \t]*int[ \t]*noiseTextureResolution[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        D = 1.382D /* ZKM Deobf */;
        C = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1208\u0000\u0002\u1004\u0001\u0003\u1002\u0002";
        Fa = "record_mellohi";
        y = ", should be: ";
        h = 342 /* ZKM Deobf Int */;
        X = " doesn't have an extra id for double slab";
        ga = "Definitely; Server brand changed to '";
        Ka = "light_blue_wool";
    }
}

