/*
 * Decompiled with CFR 0.152.
 */
public final class BRa_2 {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final double Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final double D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public BRa_2() {
        BRa_2 a2;
    }

    static {
        i = "\nYour ban will be removed on ";
        p = "Banned by an operator.";
        K = "hide-crosshair";
        v = 0xD64B7D0E ^ 0xD64B7ADB;
        u = 0x50A5CEC7 ^ 0x50A5CF6F;
        Da = Float.intBitsToFloat(0x23CE7254 ^ 0x1C735980);
        G = "\u0000\u0006\u0001\u0000\u0001\u0007\u0006\u0000\u0000\u0000\u0001\u0208\u0003C\u0000\u0004:\u0000\u0005\u023b\u0000\u00064\u0000\u0007:\u0000";
        n = "\u041a\u0443\u043f\u0438\u0442\u044c";
        B = Float.intBitsToFloat(0x63C3C009 ^ 0xDF4D3A30);
        f = 0xCBFE5FE2 ^ 0xCBFEDEC5;
        R = "orange_stained_glass";
        k = Float.intBitsToFloat(0x40751D34 ^ 0x951D34);
        z = 0x393A2DE7 ^ 0x393AADBF;
        O = "MTick";
        Ia = "Head.32";
        s = "str_starts";
        Z = "QUARTZ";
        a = "mob";
        I = "sticky_piston";
        Y = Double.longBitsToDouble(0x2FBF266AEBE6C4D2L ^ 0x10019E3B0063DA6AL);
        Ja = "4b";
        fa = "translucent_sort";
        N = "smooth_sandstone";
        ja = 0x90526291 ^ 0x90526304;
        F = "Expected 3 ";
        la = "Level time";
        E = 0x3B64615F ^ 0x3B64612F;
        L = 0xB1269416 ^ 0xB1261C8A;
        j = "commands.banip.success";
        J = "smooth_basalt";
        Ha = "black_stained_hardened_clay";
        o = "dead_bush";
        x = "gl_caps[EXT_texture_3d]";
        r = "textures/pet/walrus.png";
        H = "font";
        b = 0xFB07DA83 ^ 0xFB075A8B;
        q = "^[a-zA-Z0-9_]+$";
        M = "player_";
        T = "Could not upload shaderpack";
        c = "[ \t]*const[ \t]*bool[ \t]*(shadowcolor1Mipmap|shadowColor1Mipmap)[ \t]*=[ \t]*true[ \t]*;.*";
        g = "textures/entity/sheep/sheep_fur.png";
        d = "buildSword";
        e = "VERDANT";
        P = "SMOOTH_WORLD";
        w = "0x%05X - %s";
        S = "activatorRail";
        Aa = 0x2E0AD33E ^ 0x2E0AD244;
        Ga = "\ufffd";
        W = "selectServer.deleteQuestion";
        V = "of.options.shaders.SHADOW_CLIP_FRUSTRUM";
        t = "mangrove_log";
        Q = "touchscreen";
        A = ", variants: ";
        U = "half_horizontal_bottom";
        l = ", step: ";
        ca = "stem_(?:bent|straight)";
        m = "[ \t]*const[ \t]*int[ \t]*noiseTextureResolution[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        D = Double.longBitsToDouble(0xE5F4BE914BB8522AL ^ 0xDA02A23D438974C3L);
        C = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1208\u0000\u0002\u1004\u0001\u0003\u1002\u0002";
        Fa = "record_mellohi";
        y = ", should be: ";
        h = 0x26703AF3 ^ 0x26703BA5;
        X = " doesn't have an extra id for double slab";
        ga = "Definitely; Server brand changed to '";
        Ka = "light_blue_wool";
    }
}

