/*
 * Decompiled with CFR 0.152.
 */
public final class bRa_1 {
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final long z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final long w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public bRa_1() {
        bRa_1 a2;
    }

    static {
        X = "enchantmenttable";
        K = "RG32I";
        i = "mossy_stone_brick_slab";
        c = "I feel sad now :(";
        e = "mob.bat.takeoff";
        D = "leggingsCloth";
        r = "invalide filter type in scanline: ";
        P = "Invalid symmetry in: ";
        B = "Renderer: ";
        ja = "particles_add";
        p = "op";
        O = "nether_gold_ore";
        N = "biomes";
        I = "body5";
        Ka = "\u0000\u0004\u0001\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0004\u0002\u1208\u0000\u0003\f\u0004<\u0000";
        y = "_pulling_2";
        E = "Failed compress push voice data";
        F = "Shape24123";
        H = "stat.leaveGame";
        l = "Custom block slab ";
        T = "random.fizz";
        fa = -0.2602503001689911F /* ZKM Deobf */;
        L = 4294967246 /* ZKM Deobf Int */;
        Ga = "gaux4 format : RGB32F";
        J = "dstcolor";
        w = 0x3C3593C66267D67EL ^ 0x3C3593C670C01821L;
        Aa = "record";
        Q = "tuff_slab_double";
        U = 33997 /* ZKM Deobf Int */;
        m = "GL13.GL_SOURCE2_RGB";
        Ha = "GL13.GL_COMPRESSED_TEXTURE_FORMATS";
        o = "clownfish";
        C = "Flicker";
        j = "\u0410\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438";
        s = 1282 /* ZKM Deobf Int */;
        t = 377 /* ZKM Deobf Int */;
        f = "INVENTORY";
        Y = "fisherman";
        a = "createWorld.customize.custom.randomize";
        n = "COARSE_DIRT";
        S = "upperlip";
        z = 0x58A2941435C4E756L ^ 0x58A2941434384703L;
        h = "fireworksSpark";
        R = 406 /* ZKM Deobf Int */;
        M = "tp";
        k = "Dryness halflife: ";
        V = "shadowColor1Nearest";
        G = "assets/minecraft/models/block/lapis_block.json";
        d = "hide_with_leggings";
        W = "GL13.GL_TEXTURE19";
        v = "tile.bed.notValid";
        A = 789 /* ZKM Deobf Int */;
        x = "Unknown failed to connect reason";
        b = "screen";
        u = "helmetCloth";
        Ja = "commands.whitelist.enabled";
        Z = "buildHoe";
        q = "melon_stem";
        g = "VertexFormat error: Trying to add a position VertexFormatElement when one already exists, ignoring.";
    }
}

