/*
 * Decompiled with CFR 0.152.
 */
public final class bsa {
    public static final int Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final float p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final float A;
    public static final int I;

    public bsa() {
        bsa a2;
    }

    static {
        l = "forever";
        m = 0x19F297F8 ^ 0x190B6E01;
        ga = "math.asin";
        k = "WITHER";
        w = "entityBaseTick";
        C = "nether_wart";
        Y = "gunpowder";
        a = "spruceFenceGate";
        Ia = 0xF646AD1C ^ 0xF6462D55;
        q = "cauldron";
        H = "collision_radius";
        p = Float.intBitsToFloat(0x40932E50 ^ 0x805AB7CA);
        o = "Back.3b";
        f = "0 & !1 & !2 & 3 & 3+6";
        X = 0x127BE4FD ^ 0x127BE432;
        g = "visibility_";
        c = "nametagVisibility";
        la = Float.intBitsToFloat(0x1C67031C ^ 0x5D07031C);
        Z = 0xAA6AE3BE ^ 0xAA6AE15F;
        D = "GL13.GL_TEXTURE26";
        n = "deadHornCoralBlock";
        Aa = "math.max";
        A = Float.intBitsToFloat(0xA85F6F0C ^ 0x971FAB90);
        G = "VarLong too big";
        i = "BLLeg.BLL2";
        R = "block/half_slab";
        E = "mushroom";
        F = "Solid";
        ca = 0xCBB21A2 ^ 0xCEA819C;
        r = "\u041e\u0448\u0438\u0431\u043a\u0430 \u0430\u0432\u0442\u043e\u0440\u0438\u0437\u0430\u0446\u0438\u0438";
        M = "WHITE_TULIP";
        W = 0x365C177F ^ 0x365C16E0;
        Ja = "of.options.shaders.SHADOW_RES_MUL";
        L = "Body.Shape23";
        V = "advMode.notEnabled";
        v = "CanDestroy";
        N = "textures/gui/title/minecraft.png";
        e = "villages";
        Ha = 0x841367F3 ^ 0x841364FF;
        B = "skull_char";
        Q = "CHICKEN";
        K = "options.video";
        b = "has_record";
        Ga = "white_carpet";
        y = "Cannot modify read-only score";
        d = "end_stone_brick_slab_double";
        P = "command_block_minecart";
        S = "brown_mushroom";
        x = "minidot.unlock";
        u = Float.intBitsToFloat(0x663AA620 ^ 0x2376C620);
        fa = "10b";
        s = "achievement.fullBeacon";
        Ka = Float.intBitsToFloat(0x425F231E ^ 0x7CF7D6DD);
        z = "fenceGate";
        I = 0x5C4F4C50 ^ 0x5C4F5353;
        h = "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
        J = ".ttf";
        Da = "granite_smooth";
        t = "\n\nA detailed walkthrough of the error, its code path and all known details is as follows:\n";
        O = " args to ";
        T = "TEXTUREPATH";
        j = 0x45413FED ^ 0x4541345C;
        U = "textures/body/mercy_wings_yellow.png";
        ja = "right.Shape31";
    }
}

