/*
 * Decompiled with CFR 0.152.
 */
public final class Bta {
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final double ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final int T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final float C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Y = "MC|StopUsing";
        S = "mob.irongolem.throw";
        P = "Particle being added";
        k = "depthtex1";
        O = 0xD0A1711E ^ 0xD0A17A17;
        V = "mushroom_(?:brown|red)";
        m = "createWorld.customize.custom.depthNoiseScaleExponent";
        N = 0xA72FC25 ^ 0xA727924;
        U = "MyWeighedRandomItem{weight=";
        ga = "BestLongSideFit";
        f = "right.Shape47";
        Ia = "\u042d\u043b\u0435\u043c\u0435\u043d\u0442\u044b \u0432 \u0434\u0435\u0440\u0435\u0432\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0441\u0442\u0430\u0432\u0430\u0442\u044c\u0441\u044f \u043e\u0442\u043a\u0440\u044b\u0442\u044b\u043c\u0438";
        Ha = "SHSSD";
        ca = "commands.scoreboard.players.list.usage";
        H = "texteria-sound";
        r = "EMITTER_XZ";
        q = "GL11.GL_INDEX_LOGIC_OP";
        X = "hayBlock";
        la = 0xF9CA7016 ^ 0xF9CA70DD;
        w = "mob.horse.leather";
        fa = "GL11.GL_MAX_CLIENT_ATTRIB_STACK_DEPTH";
        Ka = "VCount";
        c = Double.longBitsToDouble(0x6A4D7C2DA8C5D3BCL ^ 0x55B57C2DA8C5D3BCL);
        g = "reversesubtract";
        B = ", color=";
        K = "ENTITY";
        F = "12";
        v = 0x99580AF ^ 0x9280BDD;
        n = "hugeexplosion";
        y = "graniteMinHeight";
        Aa = "Failed to parse option '";
        T = 0xD3AF2F7B ^ 0xD3AF5A4C;
        j = "GL11.GL_VERTEX_ARRAY";
        h = "Noise texture resolution: ";
        e = "commands.xp.failure.widthdrawXp";
        M = "stretchY";
        A = "Unable to get X-rotated facing of ";
        J = " lim ";
        d = "beginRender";
        b = "Chunk-relative: %d %d %d";
        Z = "GL11.GL_EXP";
        a = "of.general.id";
        u = 0x8D25AFAF ^ 0x72DA50D0;
        s = "east=false,north=true,south=true,west=true";
        t = "mob.zombie.woodbreak";
        Ga = "CAPS";
        ja = Double.longBitsToDouble(0xD060C705C42869C3L ^ 0xEF8782D4B0757E85L);
        o = "tile.oreCoal.name";
        D = Float.intBitsToFloat(0xD5F2971B ^ 0xEACA971B);
        i = Float.intBitsToFloat(0xC1329D17 ^ 0xFEB2A979);
        Ja = "\u0411\u0430\u0440 \u043f\u0440\u043e\u0447\u043d\u043e\u0441\u0442\u0438";
        R = "helmet";
        Q = "book";
        x = "nether";
        z = "xPos";
        W = "TEXTURE_NOT_SET";
        C = Float.intBitsToFloat(0x5D620746 ^ 0xE2FDA7BF);
        p = 0x26717A43 ^ 0x267178A8;
        G = Float.intBitsToFloat(0x5DBCABB6 ^ 0x609F7CBC);
        E = "deepslate_coal_ore";
        L = Float.intBitsToFloat(0x3241307D ^ 0xD524275);
        l = " must have 'model' field";
        Da = "always";
        I = "Allocating texture {}x{} in {} ms";
    }

    public Bta() {
        Bta a2;
    }
}

