/*
 * Decompiled with CFR 0.152.
 */
public final class Bta {
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final double ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final int T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final float C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Y = "MC|StopUsing";
        S = "mob.irongolem.throw";
        P = "Particle being added";
        k = "depthtex1";
        O = 2825 /* ZKM Deobf Int */;
        V = "mushroom_(?:brown|red)";
        m = "createWorld.customize.custom.depthNoiseScaleExponent";
        N = 34049 /* ZKM Deobf Int */;
        U = "MyWeighedRandomItem{weight=";
        ga = "BestLongSideFit";
        f = "right.Shape47";
        Ia = "\u042d\u043b\u0435\u043c\u0435\u043d\u0442\u044b \u0432 \u0434\u0435\u0440\u0435\u0432\u0435 \u0431\u0443\u0434\u0443\u0442 \u043e\u0441\u0442\u0430\u0432\u0430\u0442\u044c\u0441\u044f \u043e\u0442\u043a\u0440\u044b\u0442\u044b\u043c\u0438";
        Ha = "SHSSD";
        ca = "commands.scoreboard.players.list.usage";
        H = "texteria-sound";
        r = "EMITTER_XZ";
        q = "GL11.GL_INDEX_LOGIC_OP";
        X = "hayBlock";
        la = 203 /* ZKM Deobf Int */;
        w = "mob.horse.leather";
        fa = "GL11.GL_MAX_CLIENT_ATTRIB_STACK_DEPTH";
        Ka = "VCount";
        c = 1.5D /* ZKM Deobf */;
        g = "reversesubtract";
        B = ", color=";
        K = "ENTITY";
        F = "12";
        v = 12422002 /* ZKM Deobf Int */;
        n = "hugeexplosion";
        y = "graniteMinHeight";
        Aa = "Failed to parse option '";
        T = 30007 /* ZKM Deobf Int */;
        j = "GL11.GL_VERTEX_ARRAY";
        h = "Noise texture resolution: ";
        e = "commands.xp.failure.widthdrawXp";
        M = "stretchY";
        A = "Unable to get X-rotated facing of ";
        J = " lim ";
        d = "beginRender";
        b = "Chunk-relative: %d %d %d";
        Z = "GL11.GL_EXP";
        a = "of.general.id";
        u = 4294967167 /* ZKM Deobf Int */;
        s = "east=false,north=true,south=true,west=true";
        t = "mob.zombie.woodbreak";
        Ga = "CAPS";
        ja = 0.7272727272727273D /* ZKM Deobf */;
        o = "tile.oreCoal.name";
        D = 0.71875F /* ZKM Deobf */;
        i = 1.0016000270843506F /* ZKM Deobf */;
        Ja = "\u0411\u0430\u0440 \u043f\u0440\u043e\u0447\u043d\u043e\u0441\u0442\u0438";
        R = "helmet";
        Q = "book";
        x = "nether";
        z = "xPos";
        W = "TEXTURE_NOT_SET";
        C = -1.2470999956130981F /* ZKM Deobf */;
        p = 747 /* ZKM Deobf Int */;
        G = 0.03999999910593033F /* ZKM Deobf */;
        E = "deepslate_coal_ore";
        L = 0.5759587287902832F /* ZKM Deobf */;
        l = " must have 'model' field";
        Da = "always";
        I = "Allocating texture {}x{} in {} ms";
    }

    public Bta() {
        Bta a2;
    }
}

