/*
 * Decompiled with CFR 0.152.
 */
public final class bua_1 {
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final double o;
    public static final float h;
    public static final double K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final double g;
    public static final long L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final long k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        D = "createWorld.customize.custom.useDungeons";
        n = "displayId_";
        U = "blockRedstone";
        e = "dark_oak_slab";
        E = 0x849E4F16 ^ 0x842ED873;
        Aa = "hardness";
        Ka = "interpolant";
        V = "GL11.GL_COLOR_CLEAR_VALUE";
        p = "container.hopper";
        u = 0xC8EA1A03 ^ 0xC8734543;
        Y = "buy-request";
        t = "ofAnimatedExplosion:";
        M = " X ";
        I = "Post render";
        v = "FPS";
        Q = "textures/font/ascii_sga.png";
        la = 0x4DC8F26 ^ 0x4DC0F5C;
        R = "BRLeg.Shape44";
        q = "item.banner.white.name";
        x = "ForcedAge";
        j = "[Shaders] Invalid screen: ";
        H = "GL11.GL_TEXTURE_GEN_S";
        fa = "mob.chicken.hurt";
        F = " (NYI)";
        m = "][difficulty]";
        B = "rearlegtip";
        ca = "body6";
        i = "pumpkin_pie";
        k = 0x9E35C15ACD98B4C7L ^ 0x9E35C15AC86D55C7L;
        S = "Bottomless Pit";
        s = "HurtBy";
        ga = "bamboo_slab_double";
        Ja = "spawnpoint";
        P = "JACKET";
        b = 0x2D17C458 ^ 0x2D17CF9A;
        X = "options.difficulty.normal";
        l = "facing=east";
        O = "commands.xp.success.levels";
        K = Double.longBitsToDouble(0x460F227FDB90EA63L ^ 0xF9CC114C9B90EA63L);
        w = "ROTATE_XYZ";
        z = 0xED295F82 ^ 0xED295216;
        J = "' does not exist";
        W = "BorderSizeLerpTime";
        L = 0xD5DFC23B3582493AL ^ 0xD5DFC23B3582493DL;
        o = Double.longBitsToDouble(0xB81CBE4D309087DAL ^ 0x7C527D4909087DAL);
        C = "GL11.GL_T2F_C3F_V3F";
        y = "potion.prefix.mundane";
        r = 0xB99EF336 ^ 0xB99E6F7D;
        f = "glGenLists returned an ID of 0 for a count of ";
        G = "slot.horse.chest";
        Ha = "arrowDamage";
        c = "ancientDebris";
        g = Double.longBitsToDouble(0x71A938AC91463D9DL ^ 0xB12678AC91463D9DL);
        Da = "commands.trigger.disabled";
        ja = "ofAnimatedFlame";
        h = Float.intBitsToFloat(0xB4906F5A ^ 0xB99DC8A);
        a = "File IO Thread";
        Ga = "\u0412\u042b\u041a\u041b";
        T = Float.intBitsToFloat(0x4D2427F3 ^ 0x7151E57C);
        d = "useMineShafts";
        N = "TranslatableComponent{key='";
        A = "facing=east,half=bottom,shape=inner_right";
        Z = "FRL2";
    }

    public bua_1() {
        bua_1 a2;
    }
}

