/*
 * Decompiled with CFR 0.152.
 */
public final class cPa {
    public static final int Ea;
    public static final String Ca;
    public static final String ia;
    public static final int Ma;
    public static final float ba;
    public static final float ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final double x;
    public static final int v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final int d;
    public static final int a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public cPa() {
        cPa a2;
    }

    static {
        w = "textures/gui/container/generic_54.png";
        Ha = "item.dyed";
        ga = "BlockModel requires either elements or parent, found both";
        X = 0xDA1594B8 ^ 0xDA159F48;
        L = Double.longBitsToDouble(0xFDC1656A7ABCCE0AL ^ 0x3DDD656A7ABCCE0AL);
        U = "' not resolved";
        G = "\u4efa ";
        c = "warped_log";
        i = "clear";
        t = " items";
        N = "chiseled_sandstone";
        P = "cutCopperSlab";
        Ma = 0xE58E65A3 ^ 0xE58E6557;
        m = "SPHERE";
        O = "hide-food";
        ha = Float.intBitsToFloat(0x9D9AE7C0 ^ 0xDF50E7C0);
        C = "potion.harm";
        h = "gl_caps[EXT_blend_subtract]";
        s = "IMAGEPATH";
        A = 0xB0314BDD ^ 0xB1EBDFE4;
        ia = " program: ";
        B = 0x6B802268 ^ 0x6BD35961;
        f = "STREAM_CHAT_USER_FILTER";
        Z = "plane_normal";
        W = "minecraft:furnace";
        F = "creators";
        I = "Ice Mountains";
        J = "material";
        l = "dioriteCount";
        Ea = 0xA2A55747 ^ 0xA2A5573B;
        E = "porkchopRaw";
        k = "lake";
        Aa = "centerDepthHalflife";
        d = 0xFE9F2BF4 ^ 0x8B60D40B;
        o = 0xA9FDE3BA ^ 0xA9FD7FD7;
        n = "textures/body/fierywings_green.png";
        j = "ofCustomFonts:";
        Ja = "commands.blockdata.notValid";
        la = "chatLinks";
        Ca = "\u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432";
        D = 0x3684349D ^ 0x36843094;
        Da = "endUpdateChunks1";
        K = "paleOakStairs";
        S = "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u1001\u0000\u0002\u1001\u0001\u0003\u1004\u0004\u0004\u1208\u0002\u0005\u1208\u0003\u0006)";
        x = Double.longBitsToDouble(0xF3532171ABD518CEL ^ 0xB3356171ABD518CEL);
        fa = "renderClouds";
        Y = "block/vertical_slab";
        Ga = Float.intBitsToFloat(0x91FD111B ^ 0xD2D2111B);
        p = "mycel";
        q = "wing.bone";
        Ia = "  \u00a7r";
        M = "lang";
        ba = Float.intBitsToFloat(0xDA85CF60 ^ 0x9BC456FA);
        u = "[ \t]*const[ \t]*bool[ \t]*\\w+MipmapEnabled[ \t]*=[ \t]*true[ \t]*;.*";
        ca = "Piece1.Shape15";
        e = "randomTickSpeed";
        b = 0x40CCAB6C ^ 0x406700C7;
        R = "gl_caps[ARB_shader_texture_lod]";
        g = "textures/pet/skullpet.png";
        r = "Back.11b";
        Fa = 0x7DFE9352 ^ 0x7DFEE60F;
        v = 0x7578B184 ^ 0x75782DDA;
        z = 0x1B8E4D95 ^ 0x1B8E41B4;
        V = "), ";
        H = ".mca";
        T = "compress";
        a = 0xF4BCA45E ^ 0xF4BCA77B;
        ja = 0x187592BB ^ 0x1875131C;
        Ka = Float.intBitsToFloat(0x93AAC6AB ^ 0x5232C6AB);
        y = "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u100c\u0000";
        Q = 0x2B4EC001 ^ 0x2B4EC032;
    }
}

