/*
 * Decompiled with CFR 0.152.
 */
public final class cPa {
    public static final int Ea;
    public static final String Ca;
    public static final String ia;
    public static final int Ma;
    public static final float ba;
    public static final float ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final double x;
    public static final int v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final int d;
    public static final int a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public cPa() {
        cPa a2;
    }

    static {
        w = "textures/gui/container/generic_54.png";
        Ha = "item.dyed";
        ga = "BlockModel requires either elements or parent, found both";
        X = 3056 /* ZKM Deobf Int */;
        L = -7.0D /* ZKM Deobf */;
        U = "' not resolved";
        G = "\u4efa ";
        c = "warped_log";
        i = "clear";
        t = " items";
        N = "chiseled_sandstone";
        P = "cutCopperSlab";
        Ma = 244 /* ZKM Deobf Int */;
        m = "SPHERE";
        O = "hide-food";
        ha = 101.0F /* ZKM Deobf */;
        C = "potion.harm";
        h = "gl_caps[EXT_blend_subtract]";
        s = "IMAGEPATH";
        A = 31102009 /* ZKM Deobf Int */;
        ia = " program: ";
        B = 5470985 /* ZKM Deobf Int */;
        f = "STREAM_CHAT_USER_FILTER";
        Z = "plane_normal";
        W = "minecraft:furnace";
        F = "creators";
        I = "Ice Mountains";
        J = "material";
        l = "dioriteCount";
        Ea = 124 /* ZKM Deobf Int */;
        E = "porkchopRaw";
        k = "lake";
        Aa = "centerDepthHalflife";
        d = 1979711487 /* ZKM Deobf Int */;
        o = 40045 /* ZKM Deobf Int */;
        n = "textures/body/fierywings_green.png";
        j = "ofCustomFonts:";
        Ja = "commands.blockdata.notValid";
        la = "chatLinks";
        Ca = "\u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432";
        D = 1033 /* ZKM Deobf Int */;
        Da = "endUpdateChunks1";
        K = "paleOakStairs";
        S = "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u1001\u0000\u0002\u1001\u0001\u0003\u1004\u0004\u0004\u1208\u0002\u0005\u1208\u0003\u0006)";
        x = 178.0D /* ZKM Deobf */;
        fa = "renderClouds";
        Y = "block/vertical_slab";
        Ga = 175.0F /* ZKM Deobf */;
        p = "mycel";
        q = "wing.bone";
        Ia = "  \u00a7r";
        M = "lang";
        ba = 12.100000381469727F /* ZKM Deobf */;
        u = "[ \t]*const[ \t]*bool[ \t]*\\w+MipmapEnabled[ \t]*=[ \t]*true[ \t]*;.*";
        ca = "Piece1.Shape15";
        e = "randomTickSpeed";
        b = 11250603 /* ZKM Deobf Int */;
        R = "gl_caps[ARB_shader_texture_lod]";
        g = "textures/pet/skullpet.png";
        r = "Back.11b";
        Fa = 30045 /* ZKM Deobf Int */;
        v = 40030 /* ZKM Deobf Int */;
        z = 3105 /* ZKM Deobf Int */;
        V = "), ";
        H = ".mca";
        T = "compress";
        a = 805 /* ZKM Deobf Int */;
        ja = 33191 /* ZKM Deobf Int */;
        Ka = -19.0F /* ZKM Deobf */;
        y = "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u100c\u0000";
        Q = 51 /* ZKM Deobf Int */;
    }
}

