/*
 * Decompiled with CFR 0.152.
 */
public final class CRa {
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final int Y;
    public static final int r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final double N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final float M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        k = "waxed_cut_copper_slab";
        t = "q.mouse_local_x";
        N = Double.longBitsToDouble(0xF668F9BDE95D9093L ^ 0xB620F9BDE95D9093L);
        z = "textures/gui/presets/chaos.png";
        r = 0x8528F43F ^ 0x8528F7D2;
        Y = 0x50958453 ^ 0x50950453;
        b = "GL11.GL_REPEAT";
        R = ": error serializing progress";
        F = "UPDATE_MICRO";
        u = 0x467C8D96 ^ 0x467CCDA9;
        Z = 0x6D576835 ^ 0x6D57ED6F;
        c = "Saving worlds";
        ca = "MoreCarrotTicks";
        Ja = "yyyy-MM-dd HH:mm:ss";
        e = "Piece1.Shape82";
        I = "mob.cow.say";
        C = 0xAAC606F ^ 0xAAC7F2F;
        j = "keySneakButton:";
        o = "Shape47123";
        G = 0xE3D272B4 ^ 0xE3D279D7;
        d = Float.intBitsToFloat(0x136C11D7 ^ 0x51FA11D7);
        X = "polished_blackstone";
        Aa = "random.levelup";
        Da = "textures/particle/footprint.png";
        f = "streamMicToggleBehavior";
        Ka = "commands.clone.noOverlap";
        B = "S Z";
        V = Float.intBitsToFloat(0x39F85386 ^ 0x39F85387);
        M = Float.intBitsToFloat(0x88F4E155 ^ 0x4854E155);
        p = "ward";
        ga = "mesh";
        g = "enchantment.level.4";
        K = "blue_carpet";
        i = "->";
        Ga = "Left.Shape6123";
        E = "Failed to load shader: ";
        A = "File not found: ";
        J = "0.25, 1, 0.5, 1";
        D = "^";
        q = Float.intBitsToFloat(0xEFB4ECA4 ^ 0xAD9CECA4);
        L = 0x5AEAD96E ^ 0x5AEAD949;
        P = "generatorName";
        fa = "textures/entity/spider/cave_spider.png";
        s = "GL11.GL_DONT_CARE";
        w = Float.intBitsToFloat(0x3484CC13 ^ 0x741FFF20);
        Q = "Wrong array length: ";
        H = "Unable to load variant: ";
        a = "Skipped playing soundEvent: {}, master volume was zero";
        ja = Float.intBitsToFloat(0x2B182CC ^ 0x410582CC);
        v = "wither/wither_invulnerable";
        Ha = "#line 1 ";
        U = "[L";
        n = "(Level ";
        h = "gbuffers_skytextured";
        O = "Potion not found for image: ";
        m = "OOO";
        x = "Not all rows in the given aisle are the correct width (expected ";
        W = " elements: ";
        ha = "gilded_blackstone";
        la = Float.intBitsToFloat(0x56405022 ^ 0x16463644);
        S = "force_";
        Fa = "Invalid volume";
        l = ").";
        y = "data:base64,";
        Ia = 0x6228C8AB ^ 0x62284036;
        T = "textures/body/exowings_white.png";
    }

    public CRa() {
        CRa a2;
    }
}

