/*
 * Decompiled with CFR 0.152.
 */
public final class cRa_3 {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final float Fa;
    public static final int Ia;
    public static final int la;
    public static final double ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final float z;
    public static final float X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final float d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Q = "ICI";
        E = "ofTranslucentBlocks";
        Ja = "WATER_PARTICLES";
        Y = "Native call failed (";
        ba = "XRX";
        l = "eText_";
        q = "textures/entity/bat.png";
        T = "hops";
        y = "SERVER_MAINTENANCE";
        V = "redstone_block";
        L = 2500.0F /* ZKM Deobf */;
        ja = "generic.movementSpeed";
        Ha = "GL11.GL_ALWAYS";
        J = "redstoneMaxHeight";
        Ka = "demo.remainingTime";
        U = "textures/entity/chest/trapped_double.png";
        n = 180 /* ZKM Deobf Int */;
        B = "party/checkbox/active_hover.png";
        G = "mobSpell";
        p = "low_body";
        X = 0.707099974155426F /* ZKM Deobf */;
        d = 3.4028234663852886e+37F /* ZKM Deobf */;
        c = "oOoooo";
        Ga = "JSON";
        K = "of.options.SHOW_CAPES";
        N = "MrHald";
        fa = 6656 /* ZKM Deobf Int */;
        R = 33321 /* ZKM Deobf Int */;
        h = 127 /* ZKM Deobf Int */;
        O = "offsetTop_";
        m = "deadBrainCoralBlock";
        I = "of.options.VIGNETTE";
        Ia = 2978 /* ZKM Deobf Int */;
        v = "cyan";
        ha = "gametime";
        z = -0.6540337204933167F /* ZKM Deobf */;
        f = "Underwater Overlay";
        S = "Skeleton";
        D = 719 /* ZKM Deobf Int */;
        C = "Body.Shape6";
        Z = "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u023b\u0000\u00027\u0000";
        ca = "textures/effect/";
        la = 33001 /* ZKM Deobf Int */;
        A = "./";
        ia = "weathered_copper_grate";
        g = "GL11.GL_3D_COLOR_TEXTURE";
        M = "glitchy";
        Fa = 173.0F /* ZKM Deobf */;
        Da = "textures/pet/unlucky_cat.png";
        ga = 0.17499999701976776D /* ZKM Deobf */;
        s = "Lp";
        W = "waxed_cut_copper_stairs";
        o = 2.5306999683380127F /* ZKM Deobf */;
        j = 762 /* ZKM Deobf Int */;
        i = "postCelestialRotate";
        r = 872415231 /* ZKM Deobf Int */;
        t = "iron_boots";
        k = "CustomName";
        a = 32773 /* ZKM Deobf Int */;
        w = "radiusval_";
        x = "/\\* SHADOWFOV:[0-9\\.]+ \\*/.*";
        u = "gui.button.press";
        F = "selectWorld.bonusItems";
        Aa = 4294902015 /* ZKM Deobf Int */;
        H = 2243405 /* ZKM Deobf Int */;
        e = "of.options.ANIMATED_TEXTURES";
        Ma = "east=true,north=true,south=false,up=true,west=true";
        b = "aesCipherDecrypt";
        P = "GL11.GL_ALPHA";
    }

    public cRa_3() {
        cRa_3 a2;
    }
}

