/*
 * Decompiled with CFR 0.152.
 */
public final class cRa_3 {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final float Fa;
    public static final int Ia;
    public static final int la;
    public static final double ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final float z;
    public static final float X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final float d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Q = "ICI";
        E = "ofTranslucentBlocks";
        Ja = "WATER_PARTICLES";
        Y = "Native call failed (";
        ba = "XRX";
        l = "eText_";
        q = "textures/entity/bat.png";
        T = "hops";
        y = "SERVER_MAINTENANCE";
        V = "redstone_block";
        L = Float.intBitsToFloat(0x624CB0CB ^ 0x2750F0CB);
        ja = "generic.movementSpeed";
        Ha = "GL11.GL_ALWAYS";
        J = "redstoneMaxHeight";
        Ka = "demo.remainingTime";
        U = "textures/entity/chest/trapped_double.png";
        n = 0xA1D55299 ^ 0xA1D5522D;
        B = "party/checkbox/active_hover.png";
        G = "mobSpell";
        p = "low_body";
        X = Float.intBitsToFloat(0x9FEDF500 ^ 0xA0D8F181);
        d = Float.intBitsToFloat(0x374A3C87 ^ 0x4A86F04B);
        c = "oOoooo";
        Ga = "JSON";
        K = "of.options.SHOW_CAPES";
        N = "MrHald";
        fa = 0xADF899E0 ^ 0xADF883E0;
        R = 0xCA65E481 ^ 0xCA6566A8;
        h = 0xFA110D0C ^ 0xFA110D73;
        O = "offsetTop_";
        m = "deadBrainCoralBlock";
        I = "of.options.VIGNETTE";
        Ia = 0x5DEBA15 ^ 0x5DEB1B7;
        v = "cyan";
        ha = "gametime";
        z = Float.intBitsToFloat(0x9DB376C6 ^ 0x22941807);
        f = "Underwater Overlay";
        S = "Skeleton";
        D = 0x563685F2 ^ 0x5636873D;
        C = "Body.Shape6";
        Z = "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u023b\u0000\u00027\u0000";
        ca = "textures/effect/";
        la = 0xD062A92C ^ 0xD06229C5;
        A = "./";
        ia = "weathered_copper_grate";
        g = "GL11.GL_3D_COLOR_TEXTURE";
        M = "glitchy";
        Fa = Float.intBitsToFloat(0x81E35EDB ^ 0xC2CE5EDB);
        Da = "textures/pet/unlucky_cat.png";
        ga = Double.longBitsToDouble(0x639855BB59924323L ^ 0x5C5E33DD39924323L);
        s = "Lp";
        W = "waxed_cut_copper_stairs";
        o = Float.intBitsToFloat(0xAF4E5AD ^ 0x4AD51350);
        j = 0x3631647B ^ 0x36316681;
        i = "postCelestialRotate";
        r = 0x700B2EA8 ^ 0x43F4D157;
        t = "iron_boots";
        k = "CustomName";
        a = 0x470DC85 ^ 0x4705C80;
        w = "radiusval_";
        x = "/\\* SHADOWFOV:[0-9\\.]+ \\*/.*";
        u = "gui.button.press";
        F = "selectWorld.bonusItems";
        Aa = 0xB4696D8E ^ 0x4B966D71;
        H = 0xA7696473 ^ 0xA74B5F3E;
        e = "of.options.ANIMATED_TEXTURES";
        Ma = "east=true,north=true,south=false,up=true,west=true";
        b = "aesCipherDecrypt";
        P = "GL11.GL_ALPHA";
    }

    public cRa_3() {
        cRa_3 a2;
    }
}

