/*
 * Decompiled with CFR 0.152.
 */
public final class DPa {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final double Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final int ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final double Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final double r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final long o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        ha = "textures/entity/horse/horse_chestnut.png";
        n = "8a";
        x = "key.attack";
        Q = "double_grass";
        R = 0x9F3232D5 ^ 0x9F3222CD;
        b = "Right54";
        Z = "\u5143";
        G = "Saving chunks";
        T = "HANDSHAKING";
        X = " at ";
        C = "TOP_LEFT";
        e = 0x9F988AA4 ^ 0x9F988EA3;
        q = 0x90E57A89 ^ 0x90E56E80;
        U = "stat.mobsButton";
        fa = "prismarineWall";
        B = "diagonal_left";
        S = "Invalid axis: ";
        v = "OMB";
        H = "Something wrong with native library";
        p = "_fur";
        Ha = "\u0000\u000e\u0000\u0001\u0001\u000e\u000e\u0000\u0001\u0000\u0001\u1001\u0000\u0002\u1001\u0001\u0003\u1001\u0002\u0004\u1001\u0003\u0005\u1208\u0004\u0006\u1001\u0005\u0007\u1208\u0006\b\u1001\u0007\t\u1006\b\n\u1001\t\u000b\u1006\n\f\u100a\u000b\r\u001b\u000e\u1208\f";
        F = "saveTextureMap";
        ca = "generation marker";
        f = "menu.returnToMenu";
        Fa = "Invalid integer: ";
        m = Float.intBitsToFloat(0xD20C03FA ^ 0x137C03FA);
        Ga = 0x117ED96F ^ 0x117ED25C;
        K = "potion.prefix.debonair";
        J = 0x999DD131 ^ 0x999DD183;
        ja = 0xEDDE2171 ^ 0xEDDE2AE0;
        t = "dye_green";
        N = "Left.Shape48123";
        h = "slot.hotbar.";
        ga = 0x11F7264E ^ 0x71F7264E;
        a = "commands.achievement.give.success.one";
        i = 0xB7B7BF13 ^ 0xB7B737F2;
        P = Double.longBitsToDouble(0x845CF2004D1DB271L ^ 0xC4C3B2004D1DB271L);
        Ja = Float.intBitsToFloat(0x68603C89 ^ 0xA9330FBA);
        j = 0xD8DF261 ^ 0xD8D7775;
        I = "slime";
        W = "vines";
        l = "commands.scoreboard.objectives.setdisplay.successCleared";
        A = "Right.Right28";
        M = "Left.Shape46123";
        y = "OMSimpleT";
        c = "ofSmoothFps";
        V = "EASE_IN_OUT_QUINT";
        Ka = "+0-1-2+3&4-4+13";
        d = "targetSelector";
        la = "right_sleeve";
        Aa = Double.longBitsToDouble(0xB154DA31EC1129C8L ^ 0xF166DA31EC1129C8L);
        o = 0xF65DE54686E4E4D3L ^ 0xF65DE54686E4E429L;
        O = "check_decay";
        g = ",zoom:";
        s = Float.intBitsToFloat(0xD1FC6C16 ^ 0xEF7A6684);
        u = "underwatercolor.png";
        r = Double.longBitsToDouble(0xA5ED4316FCCA0577L ^ 0x9A03FB471CCA0577L);
        w = "texture_layer_1";
        Da = "tell";
        Ia = Double.longBitsToDouble(0xDB4D0ED0B1320437L ^ 0xE41D6C9D63C3ADCBL);
        ba = "X";
        k = "# ";
        L = "\u041f\u0440\u043e\u0447\u0435\u0435";
        D = "resourcePack.incompatible.confirm.";
        E = "16";
        z = "MISC_TEXTURE";
        Y = "BRLeg.BRL3";
    }

    public DPa() {
        DPa a2;
    }
}

