/*
 * Decompiled with CFR 0.152.
 */
public final class dpa_1 {
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final double X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        s = "cache: ";
        Ha = "&&";
        M = ", expected to find a Boolean";
        G = "d.items";
        d = "stat.breakItem.";
        k = "renderResMul";
        w = "lanServer.title";
        j = 0xAF3503C8 ^ 0xAF351DC9;
        K = "geometry.";
        v = "textures/entity/wither/wither_invulnerable.png";
        N = "instant_health";
        U = "\u0412\u0441\u0435";
        L = "biomeScaleWeight";
        g = "sunflower";
        e = 0xAEAD438A ^ 0xAEADCB12;
        p = "supported.\n";
        O = "gl_caps[ARB_draw_indirect]";
        o = Float.intBitsToFloat(0x4BC6C5E0 ^ 0xA235C7A);
        B = "X_ROT";
        Q = "Shadow map half-plane: ";
        y = "options.fov.max";
        Aa = 0xB213A130 ^ 0xB213B931;
        ca = ") is  not in the range of 1 to 4. Ignoring.";
        F = "{ \"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":512.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":5000.0, \"mainNoiseScaleY\":1000.0, \"mainNoiseScaleZ\":5000.0, \"baseSize\":8.5, \"stretchY\":8.0, \"biomeDepthWeight\":2.0, \"biomeDepthOffset\":0.5, \"biomeScaleWeight\":2.0, \"biomeScaleOffset\":0.375, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":255 }";
        V = "Spawn egg spot";
        Ga = 0xEF5631A2 ^ 0xEF563136;
        T = 0x4BC5A0FB ^ 0x4BC5D5B7;
        Z = "ASCENDING_NORTH";
        fa = "clouds";
        l = "MC|TrList";
        ja = "sheep/sheep_fur";
        H = "commands.scoreboard.teams.usage";
        i = "ANDESITE_SMOOTH";
        a = "prismarine_slab";
        S = "minecraft:blocks/mycelium_top";
        n = "GL11.GL_UNPACK_SKIP_ROWS";
        A = 0xEE0B2A53 ^ 0xEE0B2A31;
        Ka = "fire_coral_block";
        ga = "D";
        f = "mob.horse.angry";
        c = "createWorld.customize.custom.center";
        D = "SIZE";
        r = "brown_concrete_powder";
        Da = 0x8FEFBFDF ^ 0x8FEF3308;
        I = "createWorld.customize.custom.confirm1";
        la = "flipbook";
        m = "chatWidth";
        q = 0x553B92C2 ^ 0x553B120A;
        W = "Chunk location";
        b = "jungle_leaves";
        C = "MOB_APPEARANCE";
        u = Float.intBitsToFloat(0x27AA45DD ^ 0x6710EF76);
        P = "commands.unban.usage";
        E = 0x495588F ^ 0x40C1DB5;
        X = Double.longBitsToDouble(0xB323BCA697AE00CAL ^ 0x8CC5DAC0F7AE00CAL);
        t = "textures/entity/blaze.png";
        h = "FRL1";
        R = "commands.weather.usage";
        z = "PLANT";
        Y = "Unbalanced brackets: ";
        Ja = 0xD9045CE1 ^ 0xD90458E3;
        J = "[ \t]*const[ \t]*bool[ \t]*(\\w+)MipmapEnabled[ \t]*=[ \t]*true[ \t]*;.*";
        x = "GL11.GL_STENCIL_WRITEMASK";
    }

    public dpa_1() {
        dpa_1 a2;
    }
}

