/*
 * Decompiled with CFR 0.152.
 */
public final class dqa {
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final long fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final float p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final float B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final double m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public dqa() {
        dqa a2;
    }

    static {
        U = "stainedGlass";
        d = 34466 /* ZKM Deobf Int */;
        i = "legacy_query";
        L = 1664525 /* ZKM Deobf Int */;
        Da = "commands.scoreboard.players.remove.usage";
        K = "SizeOnDisk";
        O = "!";
        r = 33638 /* ZKM Deobf Int */;
        o = "'->name: empty value";
        e = "Piece3";
        u = "AUDIO_END";
        Ja = "Pigscene";
        x = "CLOCK$";
        G = 2834 /* ZKM Deobf Int */;
        t = "uniform [ _a-zA-Z0-9]+ shadowcolor0;.*";
        p = -0.6998000144958496F /* ZKM Deobf */;
        w = " to be a Int, was ";
        a = "Server";
        P = "block/";
        l = "648D7064-6A60-4F59-8ABE-C2C23A6DD7A9";
        b = "models/";
        X = "[";
        Y = "Trap";
        Z = "options.stream.compression.low";
        A = 34031 /* ZKM Deobf Int */;
        Q = "shadowtex1Mipmap";
        R = "\u041a\u0435\u043d\u043d\u0438";
        B = 0.09000000357627869F /* ZKM Deobf */;
        y = "url_";
        C = "OMDZR";
        W = "of.options.ANIMATED_FLAME";
        ja = "gameRenderer";
        Ka = "VCR: disconnected {}";
        I = "OpenGL Mipmap levels: Not available (GL12.GL_TEXTURE_MAX_LEVEL)";
        D = "shadow_";
        H = 3251 /* ZKM Deobf Int */;
        S = "party info, leader: ";
        fa = 0x652F1381B7AC8279L ^ 0x652F1381B6AC8279L;
        g = "Right5";
        J = "Shape33123";
        ga = 5653556 /* ZKM Deobf Int */;
        E = "Molang expression cannot be blank!";
        f = "offsetY_";
        ca = "ActiveEffects";
        z = "Invalid Biome id";
        Ha = "BOOLVAL";
        k = "step";
        n = "DARK_OAK";
        h = "mob.horse.donkey.idle";
        Ga = 5382 /* ZKM Deobf Int */;
        T = "vertexFormat_";
        N = "DSS";
        Aa = "&e2w&c3d&b4h&a5m&d6s&f7q - &e2 \u043d\u0435\u0434\u0435\u043b\u0438&f, &c3 \u0434\u043d\u044f&f, &b4 \u0447\u0430\u0441\u0430&f, &a5 \u043c\u0438\u043d\u0443\u0442&f, &d6 \u0441\u0435\u043a\u0443\u043d\u0434&f, 7 \u043c\u0438\u043b\u043b\u0438\u0441\u0435\u043a\u0443\u043d\u0434";
        V = "enchantments";
        q = "commands.ban.success";
        j = ", strikethrough=";
        F = " ticks per second\n\n";
        m = 0.81D /* ZKM Deobf */;
        la = "sand";
        M = 820 /* ZKM Deobf Int */;
        s = "\n#define MC_GL_VERSION ";
        v = "Response out of order: ";
        c = "del dfbTextures";
    }
}

