/*
 * Decompiled with CFR 0.152.
 */
public final class dQa_2 {
    public static final int ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final long Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final int z;
    public static final float X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final long c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final String J;
    public static final String A;
    public static final String I;

    public dQa_2() {
        dQa_2 a2;
    }

    static {
        v = "minecraft:particle_appearance_lighting";
        A = "MODELPATH";
        m = "adobe";
        ba = 16307 /* ZKM Deobf Int */;
        i = "commands.scoreboard.players.enable.noTrigger";
        Y = "commands.generic.snytax";
        Ja = "GL13.GL_SAMPLE_BUFFERS";
        l = "Owner";
        I = "diamond_block";
        M = "texteria/cache/resource/";
        L = "LeftArm";
        w = "SYSTEM";
        Z = "Couldn't parse statistics file ";
        q = "stat.craftItem";
        C = "ABORT_DESTROY_BLOCK";
        u = 31287121 /* ZKM Deobf Int */;
        h = "banned-ips.txt";
        f = "HEIGHTVAL_NOT_SET";
        E = 32857 /* ZKM Deobf Int */;
        K = "dark_oak_fence";
        S = ".txt";
        ja = 4321 /* ZKM Deobf Int */;
        s = "\u0422\u0435\u043a\u0441\u0442: ";
        T = "GL11.GL_TEXTURE_INTENSITY_SIZE";
        e = ":model=";
        fa = "REGISTER";
        U = 332 /* ZKM Deobf Int */;
        j = -2.9000000953674316F /* ZKM Deobf */;
        la = "7107DE5E-7CE8-4030-940E-514C1F160890";
        W = "Will I ever be good enough for you? :(";
        Da = "WINDOWS";
        Ha = "game.neutral.die";
        F = 711 /* ZKM Deobf Int */;
        d = 36209 /* ZKM Deobf Int */;
        N = "shadow terrain cutoutmipped";
        G = "Left.Shape57123";
        c = 0xB561EF9A0662CAA6L ^ 0xB561EF9A0662CD76L;
        Ia = "mob.horse.idle";
        R = 4352 /* ZKM Deobf Int */;
        b = "difficulty:";
        Fa = "dark_oak_trapdoor";
        g = 40044 /* ZKM Deobf Int */;
        r = 0.4176750183105469F /* ZKM Deobf */;
        P = "X0_Y0";
        ia = 32888 /* ZKM Deobf Int */;
        V = "Zombie reinforcement caller charge";
        z = 2966 /* ZKM Deobf Int */;
        H = "GL11.GL_SPOT_CUTOFF";
        Ga = 0x52291D9AF515ED1BL ^ 0x52291D9AF515ED1AL;
        y = "side";
        D = "drag_on_hover";
        p = "record_stal";
        ha = "P";
        x = "GL11.GL_COLOR_ARRAY_POINTER";
        ca = "Don't know how to handle metadata section '";
        ga = "angle_";
        B = "killEnemy";
        Q = "spawn_rate";
        k = "q.gui_y";
        o = -2000.0F /* ZKM Deobf */;
        Ka = "model_boots";
        X = -0.5235987901687622F /* ZKM Deobf */;
        J = "magenta_concrete";
        O = "maxRows_";
        n = 34964 /* ZKM Deobf Int */;
        Aa = "Left.Shape53123";
        a = "/party kick ";
        Ma = "Sheep";
        t = 3024 /* ZKM Deobf Int */;
    }
}

