/*
 * Decompiled with CFR 0.152.
 */
public final class dQa_2 {
    public static final int ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final long Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final int z;
    public static final float X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final long c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final String J;
    public static final String A;
    public static final String I;

    public dQa_2() {
        dQa_2 a2;
    }

    static {
        v = "minecraft:particle_appearance_lighting";
        A = "MODELPATH";
        m = "adobe";
        ba = 0xA91A325 ^ 0xA919C96;
        i = "commands.scoreboard.players.enable.noTrigger";
        Y = "commands.generic.snytax";
        Ja = "GL13.GL_SAMPLE_BUFFERS";
        l = "Owner";
        I = "diamond_block";
        M = "texteria/cache/resource/";
        L = "LeftArm";
        w = "SYSTEM";
        Z = "Couldn't parse statistics file ";
        q = "stat.craftItem";
        C = "ABORT_DESTROY_BLOCK";
        u = 0xAC14D9F9 ^ 0xADC9BEA8;
        h = "banned-ips.txt";
        f = "HEIGHTVAL_NOT_SET";
        E = 0x80D6279A ^ 0x80D6A7C3;
        K = "dark_oak_fence";
        S = ".txt";
        ja = 0xB9434801 ^ 0xB94358E0;
        s = "\u0422\u0435\u043a\u0441\u0442: ";
        T = "GL11.GL_TEXTURE_INTENSITY_SIZE";
        e = ":model=";
        fa = "REGISTER";
        U = 0x69972B18 ^ 0x69972A54;
        j = Float.intBitsToFloat(0xE15307C2 ^ 0x216A9E58);
        la = "7107DE5E-7CE8-4030-940E-514C1F160890";
        W = "Will I ever be good enough for you? :(";
        Da = "WINDOWS";
        Ha = "game.neutral.die";
        F = 0x78E595F3 ^ 0x78E59734;
        d = 0x58571AE3 ^ 0x58579792;
        N = "shadow terrain cutoutmipped";
        G = "Left.Shape57123";
        c = 0xB561EF9A0662CAA6L ^ 0xB561EF9A0662CD76L;
        Ia = "mob.horse.idle";
        R = 0xC55A06C0 ^ 0xC55A17C0;
        b = "difficulty:";
        Fa = "dark_oak_trapdoor";
        g = 0x18F67D85 ^ 0x18F6E1E9;
        r = Float.intBitsToFloat(0xEB7250AB ^ 0xD5A7892B);
        P = "X0_Y0";
        ia = 0xDBDA9243 ^ 0xDBDA123B;
        V = "Zombie reinforcement caller charge";
        z = 0x73C087F3 ^ 0x73C08C65;
        H = "GL11.GL_SPOT_CUTOFF";
        Ga = 0x52291D9AF515ED1BL ^ 0x52291D9AF515ED1AL;
        y = "side";
        D = "drag_on_hover";
        p = "record_stal";
        ha = "P";
        x = "GL11.GL_COLOR_ARRAY_POINTER";
        ca = "Don't know how to handle metadata section '";
        ga = "angle_";
        B = "killEnemy";
        Q = "spawn_rate";
        k = "q.gui_y";
        o = Float.intBitsToFloat(0x15A639F3 ^ 0xD15C39F3);
        Ka = "model_boots";
        X = Float.intBitsToFloat(0xE3712C60 ^ 0x5C7726F2);
        J = "magenta_concrete";
        O = "maxRows_";
        n = 0x525C8344 ^ 0x525C0BD0;
        Aa = "Left.Shape53123";
        a = "/party kick ";
        Ma = "Sheep";
        t = 0xB8B52D70 ^ 0xB8B526A0;
    }
}

