/*
 * Decompiled with CFR 0.152.
 */
public final class dsa {
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final double Ja;
    public static final long ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final double Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final long p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final float o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public dsa() {
        dsa a2;
    }

    static {
        Ha = "gui.yes";
        G = "GL11.GL_POLYGON_STIPPLE";
        e = "NOT_POSSIBLE_NOW";
        D = "leftLeg.leftLeg1";
        I = "Shape64123";
        Ga = "hide-hud";
        ha = 1052704 /* ZKM Deobf Int */;
        A = "RightLeg.Shape9";
        ca = "golden_sword";
        S = "GL11.GL_STACK_UNDERFLOW";
        c = ") is not in the range of 1 to 4. Ignoring.";
        la = "bone2";
        b = "netherquartz";
        n = "options.sounds.title";
        K = -0.125F /* ZKM Deobf */;
        l = 32831 /* ZKM Deobf Int */;
        p = 0xF53D9599491F838L ^ 0xF731DC23172ABCFL;
        Fa = " in the specified shader program.";
        w = "e";
        g = "|tex=";
        Ia = "stat.flyOneCm";
        q = "/mob/zombie";
        N = "options.sensitivity.min";
        Z = "huggywuggy";
        x = "PERFORM_RESPAWN";
        t = " for key '";
        P = "_wool";
        Ka = -10.0D /* ZKM Deobf */;
        z = "MATCH";
        H = "mob.horse.hit";
        o = 0.6108651757240295F /* ZKM Deobf */;
        M = 34075 /* ZKM Deobf Int */;
        m = "base_UV";
        Da = 34202 /* ZKM Deobf Int */;
        fa = "_double";
        Y = -2.440000057220459F /* ZKM Deobf */;
        j = "\u0000\f\u0003\u0000\u0001\f\f\u0000\u0002\u0000\u00014\u0000\u00024\u0000\u00034\u0001\u00044\u0001\u00057\u0002\u00067\u0002\u0007\u023b\u0000\b\u023b\u0001\t)\n)\u000b\u023b\u0000\f\u023b\u0001";
        v = 3600.0F /* ZKM Deobf */;
        r = "commands.message.usage";
        R = "east=false,north=true,south=false,up=true,west=true";
        Q = "Unexpected error in VoiceChatClient execute";
        Ja = -198.0D /* ZKM Deobf */;
        y = "mossy_brick_monster_egg";
        k = "createWorld.customize.custom.minHeight";
        a = "up";
        U = 32832 /* ZKM Deobf Int */;
        J = "deepslateTiles";
        C = "VM: ";
        ja = 0xEE89AE3F744867B5L ^ 0xEE89AE3F744867AAL;
        s = "Boat";
        ga = "shadow translucent";
        B = 1.4142135381698608F /* ZKM Deobf */;
        O = "textures/entity/cat/black.png";
        L = "shaders/post/sobel.json";
        F = "100%";
        d = "S X";
        i = "ANAGLYPH";
        T = "mob.slime.";
        f = 500 /* ZKM Deobf Int */;
        Aa = -1.326449990272522F /* ZKM Deobf */;
        h = "GL13.GL_TEXTURE11";
        u = "TEX_MIN_FIL_N";
        W = "][chunks_loaded]";
        E = "GL11.GL_POINTS";
        X = "oxidizedCopperTrapdoor";
        V = "SQUID";
    }
}

