/*
 * Decompiled with CFR 0.152.
 */
public final class dsa {
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final double Ja;
    public static final long ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final double Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final long p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final float o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public dsa() {
        dsa a2;
    }

    static {
        Ha = "gui.yes";
        G = "GL11.GL_POLYGON_STIPPLE";
        e = "NOT_POSSIBLE_NOW";
        D = "leftLeg.leftLeg1";
        I = "Shape64123";
        Ga = "hide-hud";
        ha = 0xB8BC976E ^ 0xB8AC874E;
        A = "RightLeg.Shape9";
        ca = "golden_sword";
        S = "GL11.GL_STACK_UNDERFLOW";
        c = ") is not in the range of 1 to 4. Ignoring.";
        la = "bone2";
        b = "netherquartz";
        n = "options.sounds.title";
        K = Float.intBitsToFloat(0x1F7070A7 ^ 0xA17070A7);
        l = 0x4FAC1815 ^ 0x4FAC982A;
        p = 0xF53D9599491F838L ^ 0xF731DC23172ABCFL;
        Fa = " in the specified shader program.";
        w = "e";
        g = "|tex=";
        Ia = "stat.flyOneCm";
        q = "/mob/zombie";
        N = "options.sensitivity.min";
        Z = "huggywuggy";
        x = "PERFORM_RESPAWN";
        t = " for key '";
        P = "_wool";
        Ka = Double.longBitsToDouble(0xC6B4C609BD1F8BCCL ^ 0x690C609BD1F8BCCL);
        z = "MATCH";
        H = "mob.horse.hit";
        o = Float.intBitsToFloat(0x1EE4D42C ^ 0x21F8B585);
        M = 0x51C349E8 ^ 0x51C3CCF3;
        m = "base_UV";
        Da = 0xFB234208 ^ 0xFB23C792;
        fa = "_double";
        Y = Float.intBitsToFloat(0x70C2113F ^ 0xB0DE39C9);
        j = "\u0000\f\u0003\u0000\u0001\f\f\u0000\u0002\u0000\u00014\u0000\u00024\u0000\u00034\u0001\u00044\u0001\u00057\u0002\u00067\u0002\u0007\u023b\u0000\b\u023b\u0001\t)\n)\u000b\u023b\u0000\f\u023b\u0001";
        v = Float.intBitsToFloat(0xBF0CA8F3 ^ 0xFA6DA8F3);
        r = "commands.message.usage";
        R = "east=false,north=true,south=false,up=true,west=true";
        Q = "Unexpected error in VoiceChatClient execute";
        Ja = Double.longBitsToDouble(0xFDA2A3244D812EC1L ^ 0x3DCA63244D812EC1L);
        y = "mossy_brick_monster_egg";
        k = "createWorld.customize.custom.minHeight";
        a = "up";
        U = 0x490B2110 ^ 0x490BA150;
        J = "deepslateTiles";
        C = "VM: ";
        ja = 0xEE89AE3F744867B5L ^ 0xEE89AE3F744867AAL;
        s = "Boat";
        ga = "shadow translucent";
        B = Float.intBitsToFloat(0x1C2F235A ^ 0x239A27A9);
        O = "textures/entity/cat/black.png";
        L = "shaders/post/sobel.json";
        F = "100%";
        d = "S X";
        i = "ANAGLYPH";
        T = "mob.slime.";
        f = 0x3AF546B ^ 0x3AF559F;
        Aa = Float.intBitsToFloat(0x856FCF6F ^ 0x3AC60672);
        h = "GL13.GL_TEXTURE11";
        u = "TEX_MIN_FIL_N";
        W = "][chunks_loaded]";
        E = "GL11.GL_POINTS";
        X = "oxidizedCopperTrapdoor";
        V = "SQUID";
    }
}

