/*
 * Decompiled with CFR 0.152.
 */
public final class dua {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final float ca;
    public static final float Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final long Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final float O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final float p;
    public static final String n;
    public static final float s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final float B;
    public static final double d;
    public static final float a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public dua() {
        dua a2;
    }

    static {
        Q = "READY_TO_ACCEPT";
        z = "glowstone";
        Ha = 0xEBC2F3E4 ^ 0xEBC2FF10;
        I = 0x726D6813 ^ 0x8D8A0742;
        Aa = 0x798948543B4BB408L ^ 0x798948543B4BE9C8L;
        W = "#iterator() cannot be used nested.";
        l = "Sea";
        Ja = Float.intBitsToFloat(0xB552392D ^ 0xD838E3A);
        C = "GL11.GL_TEXTURE_RED_SIZE";
        f = "'/";
        i = "dark_prismarine_slab_double";
        r = "isEyeInWater";
        K = "Head.18";
        Z = "Tex Min: ";
        e = "HERMITE";
        u = "u";
        h = "fogcolor0.png";
        Fa = ", requests: ";
        X = "Error whilst disconnecting player";
        g = "LEGS";
        T = "name";
        A = "iron_trapdoor";
        ha = "DropChances";
        ja = "UNBIND";
        v = "Failed to load texture ";
        k = 0x2056CBCE ^ 0x2056CAED;
        y = "GL11.GL_RGBA2";
        a = Float.intBitsToFloat(0x60274A25 ^ 0x5DE5C579);
        F = "sequenceNumber_";
        U = 0x7749414B ^ 0x77494585;
        ca = Float.intBitsToFloat(0x92783B63 ^ 0x52783B63);
        O = Float.intBitsToFloat(0xA8FDB19D ^ 0x68DD124A);
        V = "swordWood";
        M = "##0.00";
        t = "facing=east,half=bottom,shape=outer_right";
        n = "SETTINGS";
        H = "Accessed Blocks before Bootstrap!";
        w = Double.longBitsToDouble(0x2B586FD47D5C8274L ^ 0x1420FCA0CE6FB147L);
        Y = "Right46";
        N = Float.intBitsToFloat(0x91B6DE90 ^ 0xD18E9017);
        G = "//";
        P = "mob.horse.skeleton.idle";
        L = "menu.singleplayer";
        ba = "Could not add element to group '";
        Ka = "LPT3";
        fa = Float.intBitsToFloat(0xF405F192 ^ 0xB609F192);
        Da = "XS_X2";
        Ga = "Updating screen events";
        b = "item.fireCharge.use";
        j = "Multiple geometries in ";
        Ia = "stairsRedSandStone";
        q = "GL11.GL_PROJECTION_MATRIX";
        B = Float.intBitsToFloat(0xCB8F53A3 ^ 0xAB753A3);
        R = "variant=default";
        o = "31";
        E = "lootBonusDigger";
        s = Float.intBitsToFloat(0x93F5E71B ^ 0x2D802594);
        c = 0x31C23345 ^ 0x31C231D4;
        d = Double.longBitsToDouble(0xD1BCE2326E7E12C9L ^ 0x91CE22326E7E12C9L);
        p = Float.intBitsToFloat(0x62B7D7BC ^ 0x5C469187);
        ga = "InLove";
        S = "potion.prefix.artless";
        J = "Ping: (<1.3.x) from {}:{}";
        D = "placeholder_";
        m = "[ \t]*const[ \t]*bool[ \t]*shadowHardwareFiltering1[ \t]*=[ \t]*true[ \t]*;.*";
        x = "\u00a71\u0000%d\u0000%s\u0000%s\u0000%d\u0000%d";
        la = "GL11.GL_LINEAR_MIPMAP_NEAREST";
    }
}

