/*
 * Decompiled with CFR 0.152.
 */
public final class dua {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final float ca;
    public static final float Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final long Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final float O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final float p;
    public static final String n;
    public static final float s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final float B;
    public static final double d;
    public static final float a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public dua() {
        dua a2;
    }

    static {
        Q = "READY_TO_ACCEPT";
        z = "glowstone";
        Ha = 3316 /* ZKM Deobf Int */;
        I = 4293357393 /* ZKM Deobf Int */;
        Aa = 0x798948543B4BB408L ^ 0x798948543B4BE9C8L;
        W = "#iterator() cannot be used nested.";
        l = "Sea";
        Ja = -9.999999747378752e-05F /* ZKM Deobf */;
        C = "GL11.GL_TEXTURE_RED_SIZE";
        f = "'/";
        i = "dark_prismarine_slab_double";
        r = "isEyeInWater";
        K = "Head.18";
        Z = "Tex Min: ";
        e = "HERMITE";
        u = "u";
        h = "fogcolor0.png";
        Fa = ", requests: ";
        X = "Error whilst disconnecting player";
        g = "LEGS";
        T = "name";
        A = "iron_trapdoor";
        ha = "DropChances";
        ja = "UNBIND";
        v = "Failed to load texture ";
        k = 291 /* ZKM Deobf Int */;
        y = "GL11.GL_RGBA2";
        a = 0.0949999988079071F /* ZKM Deobf */;
        F = "sequenceNumber_";
        U = 1230 /* ZKM Deobf Int */;
        ca = -2.0F /* ZKM Deobf */;
        O = -2.509999990463257F /* ZKM Deobf */;
        V = "swordWood";
        M = "##0.00";
        t = "facing=east,half=bottom,shape=outer_right";
        n = "SETTINGS";
        H = "Accessed Blocks before Bootstrap!";
        w = 0.005999999865889549D /* ZKM Deobf */;
        Y = "Right46";
        N = 2.8797929286956787F /* ZKM Deobf */;
        G = "//";
        P = "mob.horse.skeleton.idle";
        L = "menu.singleplayer";
        ba = "Could not add element to group '";
        Ka = "LPT3";
        fa = 35.0F /* ZKM Deobf */;
        Da = "XS_X2";
        Ga = "Updating screen events";
        b = "item.fireCharge.use";
        j = "Multiple geometries in ";
        Ia = "stairsRedSandStone";
        q = "GL11.GL_PROJECTION_MATRIX";
        B = -11.5F /* ZKM Deobf */;
        R = "variant=default";
        o = "31";
        E = "lootBonusDigger";
        s = -0.23999999463558197F /* ZKM Deobf */;
        c = 657 /* ZKM Deobf Int */;
        d = 300.0D /* ZKM Deobf */;
        p = 0.4712389409542084F /* ZKM Deobf */;
        ga = "InLove";
        S = "potion.prefix.artless";
        J = "Ping: (<1.3.x) from {}:{}";
        D = "placeholder_";
        m = "[ \t]*const[ \t]*bool[ \t]*shadowHardwareFiltering1[ \t]*=[ \t]*true[ \t]*;.*";
        x = "\u00a71\u0000%d\u0000%s\u0000%s\u0000%d\u0000%d";
        la = "GL11.GL_LINEAR_MIPMAP_NEAREST";
    }
}

