/*
 * Decompiled with CFR 0.152.
 */
public final class Epa_1 {
    public static final int Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final double Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final float Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        G = ",pitch:";
        i = "double_plant_sunflower_front";
        I = "GL11.GL_Q";
        c = "backFace.translucent";
        n = "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0007\u0003\u0007";
        B = "tuffBrickWall";
        d = "\u041f\u041a\u041c";
        Aa = "map";
        Y = 0x2905F122 ^ 0x2905BE8F;
        Ga = "INTERACT";
        g = Float.intBitsToFloat(0xA16FC8DE ^ 0xE0E6FBED);
        j = "pig/pig";
        S = "charcoal";
        ga = "EMOJI";
        C = 0xAAAC284A ^ 0xAAAC29EA;
        F = "lavaLakeChance";
        x = Float.intBitsToFloat(0xB2F40FC8 ^ 0xC6852AC);
        J = "RG8";
        la = "minY_";
        N = "save-all";
        D = 0x697DDCEB ^ 0x697D5973;
        Ia = 0x855EDB68 ^ 0x85A22768;
        l = 0x89F8706 ^ 0x89F9204;
        Ka = Double.longBitsToDouble(0x7765E4698CE207E5L ^ 0x4897E4698CE207E5L);
        z = "\u0000\n\u0001\u0000\u0001\n\n\u0000\u0000\u0000\u0001<\u0000\u0002<\u0000\u0003<\u0000\u0004<\u0000\u0005<\u0000\u0006<\u0000\u0007<\u0000\b<\u0000\t<\u0000\n<\u0000";
        o = "/\\* DRYNESSHL:[0-9\\.]+ \\*/.*";
        ca = "PARTY";
        H = 0xAEA213E7 ^ 0xAEA296FE;
        e = "Invalid/missing description!";
        P = "east=false,north=true,south=false,west=true";
        r = "PEACEFUL";
        M = "enchantment.";
        Ja = "Right43";
        Q = Float.intBitsToFloat(0xBC481ACF ^ 0x325EBBF);
        V = 0x2138EDB1 ^ 0x2138EE89;
        u = 0x4F7234C7 ^ 0x4F72345D;
        m = "LuckyFirst";
        t = "appleGold";
        w = ", quads: ";
        y = "achievement.theEnd";
        k = ".json";
        f = "PET";
        O = 0xD1B965AF ^ 0xD1B9668C;
        p = "\u5141";
        W = "gen_";
        K = "death.fell.assist.item";
        Ha = "\u041d\u0430\u043a\u043b\u043e\u043d \u0432\u043b\u0435\u0432\u043e";
        E = "alex";
        a = "/reconnect ";
        Z = "Lighting";
        fa = "COM4";
        U = "facing=west,half=bottom,shape=outer_right";
        A = "dark_oak_door";
        q = "ThrownEnderpearl";
        v = "purple_concrete";
        L = "cobble";
        ja = 0x17CF04B1 ^ 0x17CF042C;
        b = "mud_brick_wall";
        X = "birchTrapdoor";
        T = "Don't be sad, have a hug! <3";
        Da = "GL11.GL_MAP1_TEXTURE_COORD_1";
        s = "GL11.GL_PIXEL_MAP_I_TO_A";
        h = "seed";
        R = ", but was given one with a height of ";
    }

    public Epa_1() {
        Epa_1 a2;
    }
}

