/*
 * Decompiled with CFR 0.152.
 */
public final class Eqa {
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final int Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final double O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final float m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final double I;

    static {
        z = "/mob/pigzombie";
        n = "GL11.GL_BLUE_BIAS";
        m = Float.intBitsToFloat(0x5A93EF2C ^ 0x67706115);
        Z = "body";
        U = "minecartCommandBlock";
        t = "createWorld.customize.custom.useTemples";
        D = "jungleTrapdoor";
        i = 0xD47C96C1 ^ 0xD47C0AB1;
        S = 0xB6129E5F ^ 0xB6129EEA;
        o = "mob.bat.death";
        y = "screenshots";
        Ha = 0x73A933CF ^ 0x73A93191;
        l = "polished_blackstone_brick_slab";
        k = "hasPlacedChest3";
        r = "attributes[";
        T = "thumbId";
        C = "potion.prefix.fancy";
        Ga = "dye_pink";
        ja = "crops";
        E = 0xF8DBB4D8 ^ 0xF8DBB96F;
        p = "stoneBrickWall";
        e = "waxedExposedCopperGrate";
        h = "enterCallback_";
        L = "Result";
        b = "options.chat.width";
        I = Double.longBitsToDouble(0xE1F8C323FBF9F085L ^ 0x5E6CB9C2BC57E4FEL);
        O = Double.longBitsToDouble(0x98C9F3420AC74C1CL ^ 0xA7306ADB935ED586L);
        Ka = 0x6E0FF242 ^ 0x6E0FF20A;
        G = "potion.prefix.foul";
        Da = "\u041f\u0440\u0438\u043d\u044f\u0442\u0438\u0435 \u0438\u043d\u0432\u0430\u0439\u0442\u043e\u0432";
        B = "\u0000\n\u0001\u0001\u0001\n\n\u0000\u0000\u0000\u0001\f\u0002\u0007\u0003?\u0000\u0004\u023b\u0000\u00057\u0000\u0006\u023b\u0000\u0007\u1009\u0000\b\u1009\u0001\t\u023b\u0000\n?\u0000";
        q = "hoveredBlockZ_";
        Q = "x:";
        Aa = 0x59F2D235 ^ 0x59F2D10F;
        R = " bytes encoded, max ";
        g = "textures/pet/mushroom_nether_red.png";
        A = "GL11.GL_RED_BIAS";
        V = "textures/gui/achievement/achievement_background.png";
        J = "\u5046";
        K = "stats";
        W = "lever";
        fa = "Shape35";
        ca = "Back.1a";
        H = "granite_stairs";
        j = "resourcePack.title";
        u = 0x85B793E0 ^ 0x85B792C9;
        d = "commands.save.flushStart";
        f = "GL11.GL_POLYGON_OFFSET_FACTOR";
        M = "minecraft:blocks/glass_pane_top";
        N = "Press a key to select a command, and again to use it.";
        w = Double.longBitsToDouble(0x43C712D1BE3DB99FL ^ 0x3049AD1BE3DB99FL);
        Y = "of.options.shaders.TEX_MAG_FIL_N";
        a = 0xA769C76B ^ 0xA769B224;
        Ja = "half_vertical";
        v = "filled_map";
        s = "textures/entity/zombie/zombie_villager.png";
        P = " IN: [{}:{}] {}";
        c = " (Owned)";
        ga = 0x28179BC7 ^ 0x28179E8F;
        F = "No such direction: ";
        X = "Left.Shape39123";
        Ia = "LONG";
        x = Float.intBitsToFloat(0xBC14806C ^ 0x7D9D45BA);
        la = "SIZEEXPR";
    }

    public Eqa() {
        Eqa a2;
    }
}

