/*
 * Decompiled with CFR 0.152.
 */
public final class Era {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final float D;
    public static final float f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Era() {
        Era a2;
    }

    static {
        Q = "CustomColors";
        la = "Could not read json resource ";
        ga = "ARMOR_STAND";
        G = 0x37A51129 ^ 0x37A5072B;
        e = "# X";
        j = "file.encoding.system";
        V = "event";
        X = "prismarine";
        M = "dandelion";
        A = "AUDIO_DATA_BATCH";
        Ja = 0x6D0F43BD ^ 0x6D0FC33E;
        h = Float.intBitsToFloat(0x80122A93 ^ 0xC3152A93);
        a = "tickables";
        d = " when I expected it to be compiling; aborting task";
        f = Float.intBitsToFloat(0xC6020305 ^ 0x798566FB);
        N = "slot:";
        O = "gbuffers_basic";
        K = "textures/entity/horse/horse_zombie.png";
        w = "Maybe if you treated it better then it'll have more motivation to work faster! Poor server.";
        Y = "EMOTE";
        U = "Right.Right20";
        g = "mob.irongolem.hit";
        t = Float.intBitsToFloat(0x170ECDEF ^ 0x2D8ECDEF);
        Ha = "quartz_slab";
        J = "red_stained_glass";
        Ia = "oreIron";
        T = "GL13.GL_SOURCE1_ALPHA";
        n = "-- ";
        c = 0x66377A1 ^ 0x66376D1;
        I = "q.mouse_y";
        C = "BARRIER";
        s = Float.intBitsToFloat(0x5F87B966 ^ 0x9E8FB966);
        p = 0xA64A9ED7 ^ 0xA64A9C66;
        u = "RARE";
        fa = "OMPenthouse";
        r = "redstone_lamp";
        E = "leaves_big_oak";
        Aa = ":";
        P = "collision_rotation_drag";
        Z = "dye_gray";
        D = Float.intBitsToFloat(0xD4FC830C ^ 0xEB28F9ED);
        k = Float.intBitsToFloat(0xBA74A4B5 ^ 0xF818A4B5);
        Da = "sun.arch.data.model";
        Ga = Float.intBitsToFloat(0x333CAB6E ^ 0x735067A3);
        B = "largeBiomes";
        q = "GL11.GL_LUMINANCE16_ALPHA16";
        x = 0xB39F21F1 ^ 0xB39FA063;
        z = "Item Aux";
        l = "GL11.GL_QUAD_STRIP";
        v = ", y: ";
        L = "copper";
        o = "mob.chicken.plop";
        H = "easeOutCubic";
        y = "east=true,north=false,south=false,up=false,west=false";
        F = "Unable to construct element ";
        W = 0x320C4C3B ^ 0x320C4B3D;
        Ka = 0xB6346160 ^ 0xB6D18453;
        ja = "hwh";
        m = "of.options.LAZY_CHUNK_LOADING";
        S = "fishing_rod_cast";
        Fa = "Texture object class";
        b = "GL14.GL_FOG_COORDINATE";
        ca = "weathered_copper_trapdoor";
        R = 0xC8ACEAC0 ^ 0xC8AC6B66;
        i = "Launched Version";
    }
}

