/*
 * Decompiled with CFR 0.152.
 */
public final class ERa_1 {
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final float fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final double t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Ia = "textures/blocks/destroy_stage_3.png";
        Fa = 0x6B840A3 ^ 0x6B8C0F1;
        J = "ofMipmapType";
        M = "GL14.GL_CONSTANT_COLOR";
        E = "snowball";
        O = "Piece1.Shape16";
        a = "selectWorld.seedInfo";
        r = "textColor_";
        la = "tick";
        d = "Expected values: ";
        p = "STREAM_SEND_METADATA";
        x = "X0_Y90";
        l = "Error loading texture: ";
        I = "commands.scoreboard.players.usage";
        P = 0x5134D51D ^ 0x5134D489;
        Ga = "OPEN_INVENTORY";
        H = "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0007\u0003\u0007\u0004\u0007";
        g = "commands.banlist.usage";
        j = "server_brand";
        G = "tile.piston.in";
        h = "path_";
        C = 0xB5BED8F5 ^ 0xB5BED8E5;
        Ha = 0x5721FF87 ^ 0x5721B02C;
        Aa = "WEAPON";
        fa = Float.intBitsToFloat(0x7DF44DB8 ^ 0xBC70D61E);
        c = "EQUALS";
        S = "translucent";
        m = " Kbps";
        R = 0xC2C028FE ^ 0xC2C0AC19;
        y = Double.longBitsToDouble(0x333EF56B4BB73314L ^ 0xCE6F56B4BB73314L);
        e = "[ \t]*const[ \t]*float[ \t]*eyeBrightnessHalflife[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        Ja = " gui, ";
        q = 0x1D47A5F6 ^ 0x1D47A721;
        ga = "commands.scoreboard.objectives.add.success";
        n = "API";
        N = "GL11.GL_STENCIL";
        t = Double.longBitsToDouble(0xC3DE746220A54806L ^ 0x838A746220A54806L);
        ja = "Error saving: ";
        k = "ofShowFps";
        z = "STRIPE_DOWNLEFT";
        K = Float.intBitsToFloat(0xAE8253ED ^ 0x915B9E8D);
        f = "d.discount";
        Q = "MinecartCommandBlock";
        Y = "options.fullscreen";
        W = "CD";
        F = "progress";
        w = "gbuffers_hand";
        o = 0xEAE40DA9 ^ 0xEAE40EF9;
        Ka = 0xE08C0998 ^ 0x1F73F665;
        V = "GL11.GL_MAP1_VERTEX_3";
        Z = "textures/body/wings_pink.png";
        L = Float.intBitsToFloat(0x76105763 ^ 0xC96D27C7);
        v = "shaderPack";
        b = "vertical+horizontal";
        ca = "[?] ";
        X = "createWorld.customize.custom.useStrongholds";
        T = 0xA8BFEC0 ^ 0xA8BFE6C;
        U = "entity";
        D = "commands.scoreboard.players.operation.usage";
        s = "zip";
        i = Float.intBitsToFloat(0x36592F45 ^ 0x8B2CEDCA);
        Da = "Body.Shape8";
        A = "waxed_exposed_cut_copper";
        B = "stat.itemsButton";
        u = "Snowball";
    }

    public ERa_1() {
        ERa_1 a2;
    }
}

