/*
 * Decompiled with CFR 0.152.
 */
public final class eta {
    public static final String Ia;
    public static final double la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final float e;
    public static final String G;
    public static final double D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        ca = " / ";
        v = 0x7056BED ^ 0x7843DDC;
        fa = "Block being updated";
        X = "hard";
        Y = "Invalid icon for server ";
        F = "value.";
        a = "Oops.";
        j = "silver_concrete";
        i = "textures/entity/wolf/wolf_collar.png";
        l = "multiplayer.texturePrompt.line2";
        Aa = "atlas/";
        o = "createWorld.customize.custom.heightScale";
        P = Float.intBitsToFloat(0xF7FA304A ^ 0xC8333FB3);
        s = 0x4E9EB3AC ^ 0x4E9E2FFF;
        Z = ", hardness=";
        z = "[^a-z]";
        Q = "baked_potato";
        U = "overrideHeight";
        L = "!0 & !1 & !2 & 3 & 3+6";
        p = 0x2560BBF ^ 0x2560DFF;
        O = "GL11.GL_CLIENT_ATTRIB_STACK_DEPTH";
        n = "Invalid image";
        J = "GL11.GL_LUMINANCE12_ALPHA4";
        h = "nether_wa rt_stage_[0-2]";
        M = "deadbush";
        S = "NeCTB";
        m = Float.intBitsToFloat(0x6F118CEE ^ 0xAE901574);
        k = "half_horizontal";
        R = 0xF0B846BF ^ 0xF0B852B5;
        e = Float.intBitsToFloat(0x51049016 ^ 0x10A49016);
        x = Float.intBitsToFloat(0xC2C6DA70 ^ 0x388BC16);
        I = "Giant";
        Ha = "lava_bucket";
        T = "F";
        V = "bts";
        Ja = "east=true,north=false,south=true,west=false";
        B = Float.intBitsToFloat(0x88EA9A0A ^ 0xB64030A1);
        q = "CACAO_BEANS";
        Da = 0x59F7C063 ^ 0x59F74313;
        y = "GL_MAX_TEXTURE_IMAGE_UNITS: ";
        E = "sound_";
        la = Double.longBitsToDouble(0xE7ECEEC1FF5FE05DL ^ 0xA76EEEC1FF5FE05DL);
        u = "EVERYTHING";
        K = "inf";
        d = "creeper.primed";
        r = "HAT";
        b = Float.intBitsToFloat(0x8C23C017 ^ 0xB3E6CA7C);
        ga = "glazed_terracotta3";
        g = 0x8F3D6D0D ^ 0x8F3D6C0E;
        ja = "Suffix";
        c = "livingEntityBaseTick";
        Ia = "commands.title.usage";
        f = "Fortress";
        w = "\u0412\u044b \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e";
        D = Double.longBitsToDouble(0xBF40FA6CE48C48FCL ^ 0x9606B1603FF00EL);
        A = "options.stream.chat.enabled.streaming";
        Ka = "ANVIL";
        t = "Function '%s' requires at least %s arguments. %s are given!";
        Ga = "Uncommon";
        W = "itemInHand_";
        C = "polished_blackstone_brick_wall";
        H = "GL11.GL_MAX_MODELVIEW_STACK_DEPTH";
        G = "east=true,north=true,south=true,up=false,west=false";
        N = "11a";
    }

    public eta() {
        eta a2;
    }
}

