/*
 * Decompiled with CFR 0.152.
 */
public final class eta {
    public static final String Ia;
    public static final double la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final float e;
    public static final String G;
    public static final double D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        ca = " / ";
        v = 8476209 /* ZKM Deobf Int */;
        fa = "Block being updated";
        X = "hard";
        Y = "Invalid icon for server ";
        F = "value.";
        a = "Oops.";
        j = "silver_concrete";
        i = "textures/entity/wolf/wolf_collar.png";
        l = "multiplayer.texturePrompt.line2";
        Aa = "atlas/";
        o = "createWorld.customize.custom.heightScale";
        P = 1.5707999467849731F /* ZKM Deobf */;
        s = 40019 /* ZKM Deobf Int */;
        Z = ", hardness=";
        z = "[^a-z]";
        Q = "baked_potato";
        U = "overrideHeight";
        L = "!0 & !1 & !2 & 3 & 3+6";
        p = 1600 /* ZKM Deobf Int */;
        O = "GL11.GL_CLIENT_ATTRIB_STACK_DEPTH";
        n = "Invalid image";
        J = "GL11.GL_LUMINANCE12_ALPHA4";
        h = "nether_wa rt_stage_[0-2]";
        M = "deadbush";
        S = "NeCTB";
        m = -16.200000762939453F /* ZKM Deobf */;
        k = "half_horizontal";
        R = 5130 /* ZKM Deobf Int */;
        e = 20.0F /* ZKM Deobf */;
        x = -12.899999618530273F /* ZKM Deobf */;
        I = "Giant";
        Ha = "lava_bucket";
        T = "F";
        V = "bts";
        Ja = "east=true,north=false,south=true,west=false";
        B = 0.3333333432674408F /* ZKM Deobf */;
        q = "CACAO_BEANS";
        Da = 33648 /* ZKM Deobf Int */;
        y = "GL_MAX_TEXTURE_IMAGE_UNITS: ";
        E = "sound_";
        la = 576.0D /* ZKM Deobf */;
        u = "EVERYTHING";
        K = "inf";
        d = "creeper.primed";
        r = "HAT";
        b = 1.539380431175232F /* ZKM Deobf */;
        ga = "glazed_terracotta3";
        g = 259 /* ZKM Deobf Int */;
        ja = "Suffix";
        c = "livingEntityBaseTick";
        Ia = "commands.title.usage";
        f = "Fortress";
        w = "\u0412\u044b \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0442\u0435\u043b\u044c\u043d\u043e";
        D = -0.35918367346938773D /* ZKM Deobf */;
        A = "options.stream.chat.enabled.streaming";
        Ka = "ANVIL";
        t = "Function '%s' requires at least %s arguments. %s are given!";
        Ga = "Uncommon";
        W = "itemInHand_";
        C = "polished_blackstone_brick_wall";
        H = "GL11.GL_MAX_MODELVIEW_STACK_DEPTH";
        G = "east=true,north=true,south=true,up=false,west=false";
        N = "11a";
    }

    public eta() {
        eta a2;
    }
}

