/*
 * Decompiled with CFR 0.152.
 */
public final class fPa {
    public static final float ea;
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final float ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final double ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final long U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final float a;
    public static final int b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final float A;
    public static final String I;

    public fPa() {
        fPa a2;
    }

    static {
        M = "drawMode_";
        F = "facing=north,half=top,shape=outer_right";
        L = "STATIONARY";
        J = "shadow postprocess";
        ga = 65 /* ZKM Deobf Int */;
        ha = 4.199999809265137F /* ZKM Deobf */;
        K = "nightVision";
        j = 3192 /* ZKM Deobf Int */;
        ia = "doubleClick_";
        y = "BEB";
        v = "teams";
        x = "head.upperhead";
        ca = 0.05D /* ZKM Deobf */;
        l = "GL13.GL_SOURCE0_ALPHA";
        Ka = "fire_resistance";
        Aa = "Texture ";
        s = "of.options.CLOUD_HEIGHT";
        N = 32861 /* ZKM Deobf Int */;
        Ea = "textures/entity/wither/wither.png";
        Ha = "expire_on_contact";
        t = 93 /* ZKM Deobf Int */;
        h = "GL_MAX_COLOR_ATTACHMENTS_EXT: ";
        c = "Multiple vertex elements of the same type other than UVs are not supported. Forcing type to UV.";
        D = "commands.deop.success";
        U = 0xF4BF339696B7854FL ^ 0xF4BF339696B7D88EL;
        ja = "#E#";
        Ga = 4610 /* ZKM Deobf Int */;
        la = "-X";
        W = "wall_nse";
        I = "Right10";
        P = 347 /* ZKM Deobf Int */;
        Ia = "ofRainSplash:";
        Ma = "key.hotbar.6";
        Fa = "PATH";
        d = "#%04d/%d%s";
        e = 2928 /* ZKM Deobf Int */;
        C = "No particle_effect.basic_render_parameters was found...";
        b = 239 /* ZKM Deobf Int */;
        fa = "textures/entity/chest/christmas_double.png";
        Da = "hbr";
        X = "DIM1";
        Y = 795 /* ZKM Deobf Int */;
        Ca = "pulling_2";
        f = "random_damp";
        q = "GL11.GL_TEXTURE_ENV";
        Q = "easeInCirc";
        H = 32858 /* ZKM Deobf Int */;
        R = "#.###";
        S = "OPENING";
        r = "GL11.GL_LINE_TOKEN";
        o = "EnchantTable";
        G = "hurtDeathAnimationDisabled_";
        p = "PIGSCENE";
        n = "math.random";
        i = 32 /* ZKM Deobf Int */;
        ba = -0.33230000734329224F /* ZKM Deobf */;
        Ja = "GL13.GL_SAMPLE_ALPHA_TO_ONE";
        E = "Piece1.Shape12";
        u = "torch_on";
        A = -6.599999904632568F /* ZKM Deobf */;
        B = "os_version";
        z = 111 /* ZKM Deobf Int */;
        V = "waterBreathing";
        O = "GL13.GL_TEXTURE16";
        k = "OutputSignal";
        g = "xTile";
        m = 670 /* ZKM Deobf Int */;
        T = 6396257 /* ZKM Deobf Int */;
        ea = 4096.0F /* ZKM Deobf */;
        a = 2.1500000953674316F /* ZKM Deobf */;
        Z = 9900000 /* ZKM Deobf Int */;
        w = "GL11.GL_PROJECTION_STACK_DEPTH";
    }
}

