/*
 * Decompiled with CFR 0.152.
 */
public final class fPa {
    public static final float ea;
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final float ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final double ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final long U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final float a;
    public static final int b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final float A;
    public static final String I;

    public fPa() {
        fPa a2;
    }

    static {
        M = "drawMode_";
        F = "facing=north,half=top,shape=outer_right";
        L = "STATIONARY";
        J = "shadow postprocess";
        ga = 0x1925C60D ^ 0x1925C64C;
        ha = Float.intBitsToFloat(0xC32C7156 ^ 0x83AA1730);
        K = "nightVision";
        j = 0xE2EF41FF ^ 0xE2EF4D87;
        ia = "doubleClick_";
        y = "BEB";
        v = "teams";
        x = "head.upperhead";
        ca = Double.longBitsToDouble(0xACDF3F3823502629L ^ 0x9376A6A1BAC9BFB3L);
        l = "GL13.GL_SOURCE0_ALPHA";
        Ka = "fire_resistance";
        Aa = "Texture ";
        s = "of.options.CLOUD_HEIGHT";
        N = 0x6BDEA609 ^ 0x6BDE2654;
        Ea = "textures/entity/wither/wither.png";
        Ha = "expire_on_contact";
        t = 0xA85AD8DB ^ 0xA85AD886;
        h = "GL_MAX_COLOR_ATTACHMENTS_EXT: ";
        c = "Multiple vertex elements of the same type other than UVs are not supported. Forcing type to UV.";
        D = "commands.deop.success";
        U = 0xF4BF339696B7854FL ^ 0xF4BF339696B7D88EL;
        ja = "#E#";
        Ga = 0xD40FE55C ^ 0xD40FF75E;
        la = "-X";
        W = "wall_nse";
        I = "Right10";
        P = 0xD34782B8 ^ 0xD34783E3;
        Ia = "ofRainSplash:";
        Ma = "key.hotbar.6";
        Fa = "PATH";
        d = "#%04d/%d%s";
        e = 0x840ABC2 ^ 0x840A0B2;
        C = "No particle_effect.basic_render_parameters was found...";
        b = 0x27D25A8B ^ 0x27D25A64;
        fa = "textures/entity/chest/christmas_double.png";
        Da = "hbr";
        X = "DIM1";
        Y = 0x68644282 ^ 0x68644199;
        Ca = "pulling_2";
        f = "random_damp";
        q = "GL11.GL_TEXTURE_ENV";
        Q = "easeInCirc";
        H = 0xC4A8C040 ^ 0xC4A8401A;
        R = "#.###";
        S = "OPENING";
        r = "GL11.GL_LINE_TOKEN";
        o = "EnchantTable";
        G = "hurtDeathAnimationDisabled_";
        p = "PIGSCENE";
        n = "math.random";
        i = 0x80F07679 ^ 0x80F07659;
        ba = Float.intBitsToFloat(0x76786041 ^ 0xC8D2437B);
        Ja = "GL13.GL_SAMPLE_ALPHA_TO_ONE";
        E = "Piece1.Shape12";
        u = "torch_on";
        A = Float.intBitsToFloat(0x34EB609 ^ 0xC39D853A);
        B = "os_version";
        z = 0x504798F6 ^ 0x50479899;
        V = "waterBreathing";
        O = "GL13.GL_TEXTURE16";
        k = "OutputSignal";
        g = "xTile";
        m = 0xF8ACF7B3 ^ 0xF8ACF52D;
        T = 0x160512ED ^ 0x16648B8C;
        ea = Float.intBitsToFloat(0xAABC040C ^ 0xEF3C040C);
        a = Float.intBitsToFloat(0x32FE7008 ^ 0x72F7E992);
        Z = 0x4A0776AA ^ 0x4A90794A;
        w = "GL11.GL_PROJECTION_STACK_DEPTH";
    }
}

