/*
 * Decompiled with CFR 0.152.
 */
public final class fpa_1 {
    public static final String ma;
    public static final String La;
    public static final String ka;
    public static final String da;
    public static final String Ba;
    public static final String aa;
    public static final float ea;
    public static final String Ea;
    public static final float Ca;
    public static final float ia;
    public static final String Ma;
    public static final double ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final float Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final double S;
    public static final String Z;
    public static final String Y;
    public static final double r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final float Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final double o;
    public static final int h;
    public static final double K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final double a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final float G;
    public static final int D;
    public static final int f;
    public static final String F;
    public static final long g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final float M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Ja = "tuffSlab";
        Da = Float.intBitsToFloat(0x254A6B46 ^ 0x9B2E07AE);
        Y = "PushZ";
        Fa = 0x1DBBE306 ^ 0x1DBBF305;
        ha = "scoreboard";
        j = "minecraft:crafting_table";
        d = "RightLeg1";
        F = "stone";
        Ha = "bamboo_fence_gate";
        U = "Pet.top";
        e = 0x1BBE8454 ^ 0x1BBE85D1;
        Q = Float.intBitsToFloat(0xE1C3A25 ^ 0xB1805B83);
        m = Float.intBitsToFloat(0xED38F17 ^ 0x310C25B3);
        t = 0x1C402177 ^ 0x1C403376;
        la = "SUSPENDED_DEPTH";
        W = "STREAM_MIC_TOGGLE_BEHAVIOR";
        O = "leftLeg.leftLeg";
        J = "an";
        ba = Double.longBitsToDouble(0xC3EC1E00EA4B28D0L ^ 0x83BA9E00EA4B28D0L);
        ea = Float.intBitsToFloat(0x8A7B3DD8 ^ 0xB48B9E0F);
        C = "Font loading error";
        ma = "wooden_axe";
        G = Float.intBitsToFloat(0x71814629 ^ 0xB0394629);
        a = Double.longBitsToDouble(0xFEA1BDD1EE127F7AL ^ 0xBEC3BDD1EE127F7AL);
        Aa = "options.stream.fps";
        q = "GL11.GL_AND";
        f = 0x988CD826 ^ 0x988CD527;
        g = 0x8772CEEF35B0B096L ^ 0x8772CEEF35B08A0EL;
        fa = "useMonuments";
        i = "emerald_ore";
        v = 0xC637FD ^ 0xC63C58;
        La = "beef";
        ca = 0x610659FF ^ 0x6106D1B5;
        H = 0xE15E55F9 ^ 0xE15E40F9;
        E = "barrier";
        ka = "complete";
        A = "ViSH";
        M = Float.intBitsToFloat(0x92E9E0E9 ^ 0x528F868F);
        S = Double.longBitsToDouble(0x1A0C02D0EAE9A5CBL ^ 0x5A2A02D0EAE9A5CBL);
        x = 0x2374D274 ^ 0xDC832D8B;
        Ia = "V";
        u = "Saving entity NBT";
        K = Double.longBitsToDouble(0x39F8D82F2F4277CCL ^ 0x61E50E15F788CB3L);
        Ga = "Why did you do that?";
        da = "\u00a7a";
        Ka = "andesiteStairs";
        X = "textures/pet/cloudpet.png";
        Ea = "misc";
        N = Float.intBitsToFloat(0x5F69827E ^ 0x1FCFE418);
        T = "particles_alpha";
        ia = Float.intBitsToFloat(0xBA8949EF ^ 0x7B1949EF);
        Z = "bambooBlock";
        V = "Head.Shape7";
        r = Double.longBitsToDouble(0x73076126564BA343L ^ 0x33A76126564BA343L);
        L = "resin_block";
        h = 0x82FBA427 ^ 0x82FBA568;
        B = "CZ";
        n = 0x8B6890AA ^ 0x8B6860AB;
        I = "the player acts as the camera";
        Ca = Float.intBitsToFloat(0x89A6135C ^ 0x4880753A);
        ja = "Shaders.init pre";
        b = "resource_pack[";
        z = "big";
        p = "silver_wool";
        y = "pets";
        w = "assets/minecraft/blockstates/sand.json";
        o = Double.longBitsToDouble(0x36E01593C1DFE271L ^ 0x76E21593C1DFE271L);
        Ba = "lapisCount";
        ga = 0x5199A374 ^ 0x5199A1F5;
        R = "dark_oak_planks";
        aa = "\u5044";
        k = "uniform [ _a-zA-Z0-9]+ centerDepthSmooth;.*";
        P = "yyyy-MM-dd_HH.mm.ss";
        Ma = "No match blocks: ";
        D = 0x5BC26F57 ^ 0x5B620A17;
        s = "max";
        l = "selectWorld.allowCommands.info";
        c = "textures/gui/container/personalization.png";
    }

    public fpa_1() {
        fpa_1 a2;
    }
}

