/*
 * Decompiled with CFR 0.152.
 */
public final class FPa_3 {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final double T;
    public static final float p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final long h;
    public static final String K;
    public static final int H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    static {
        Z = "33";
        P = "cacheIndex.bin";
        k = "AffectedEntities";
        W = "crimson_fence_gate";
        c = 1456435 /* ZKM Deobf Int */;
        r = "beginRenderPass";
        g = "ShowParticles";
        I = 52428800 /* ZKM Deobf Int */;
        B = "oooooO";
        q = "GL11.GL_LINE_RESET_TOKEN";
        x = "There is no such operator '";
        U = 16777088 /* ZKM Deobf Int */;
        E = "F12";
        S = "sign";
        d = "GL11.GL_RGB5_A1";
        X = "shadow drawbuffers";
        u = "random.door_open";
        V = "GL11.GL_LINE";
        m = -1.0122909545898438F /* ZKM Deobf */;
        o = 7.800000190734863F /* ZKM Deobf */;
        i = "HealF";
        a = "createWorld.customize.custom.fixedBiome";
        Q = "menu.convertingLevel";
        G = "%.2f, %.2f, %.2f";
        ca = "weakness";
        R = "bambooPlanks";
        Y = ", particle: ";
        h = 0x40FF2F70934BDCF8L ^ 0x40FF2F70934BD53CL;
        N = "del sfb";
        D = "Right45";
        O = "specular";
        e = 198 /* ZKM Deobf Int */;
        v = "localhost";
        K = "granite_slab_double";
        A = "commands.gamemode.success.other";
        y = 224.0D /* ZKM Deobf */;
        Da = "iron_hoe";
        p = 0.0024999999441206455F /* ZKM Deobf */;
        s = 1012 /* ZKM Deobf Int */;
        b = "headd";
        Ja = "Entity";
        j = "GL12.GL_TEXTURE_DEPTH";
        M = "&e/cam target [none|self]&f: \u0423\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u0446\u0435\u043b\u044c \u043a\u0430\u043c\u0435\u0440\u044b";
        ja = "commands.enchant.notFound";
        T = 4.0D /* ZKM Deobf */;
        z = "INTEGER";
        f = "GL11.GL_INDEX_ARRAY";
        L = "Name error at: ";
        n = "assets/minecraft/blockstates/podzol.json";
        C = "bowl";
        l = "stairsStoneBrickSmooth";
        J = "c.items";
        la = "min_speed_threshold";
        Ha = "eTextClock_";
        Ga = "never";
        ga = ", lightLevel=";
        t = 34187121 /* ZKM Deobf Int */;
        F = 52 /* ZKM Deobf Int */;
        w = "commands.difficulty.usage";
        Aa = "ofCustomColors";
        Ia = "Encountered multiple top tags, only one expected";
        Ka = "east=true,north=false,south=true,up=true,west=false";
        fa = "banned-players.json";
        H = 20225 /* ZKM Deobf Int */;
    }

    public FPa_3() {
        FPa_3 a2;
    }
}

