/*
 * Decompiled with CFR 0.152.
 */
public final class Fpa_2 {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final long ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final int W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final int d;
    public static final float a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        T = "flying";
        Z = "spreadplayers";
        H = "half";
        h = "Shape16123";
        Ia = "amplified";
        z = "GL13.GL_ACTIVE_TEXTURE";
        D = "Shape62";
        S = 0xA6EB991E ^ 0xA6EB9B45;
        j = 0xE69F7CF7 ^ 0xE69FFC9A;
        ja = "shaders/post/color_convolve.json";
        P = "textures/entity/snowman.png";
        e = "BB";
        u = "sharpness";
        V = "A score component needs a least a name and an objective";
        N = " ms";
        Ka = "easeOutQuad";
        n = "COLORANIM";
        G = "GL11.GL_MAP2_INDEX";
        O = "textures/pet/owlpet.png";
        v = "skin";
        y = Double.longBitsToDouble(0xFB8124B6083DF31EL ^ 0xBBD364B6083DF31EL);
        d = 0x426A2222 ^ 0x426A20A4;
        t = Double.longBitsToDouble(0xFACF70E13EAC9B11L ^ 0x45D54603D5B0D83CL);
        ca = 0xECBE5FD9 ^ 0xECBE5FEE;
        Q = "proxyHost";
        Ja = "yellow_carpet";
        Da = "R32F";
        C = "Speed";
        F = "of.options.animations";
        U = "item.coal";
        i = "GL11.GL_TEXTURE_BORDER_COLOR";
        W = 0xCEE5711 ^ 0xC0ACD2B;
        w = Float.intBitsToFloat(0x8347829C ^ 0x3E645596);
        k = "RGB32UI";
        I = "delayExpr_";
        b = "*=";
        X = "Info log: ";
        o = Float.intBitsToFloat(0x356CE407 ^ 0x7710E407);
        M = "game.player.die";
        c = "night";
        x = "has_bottle_2";
        R = " [";
        A = "GL11.GL_RGBA";
        Y = 0x52A06AF2 ^ 0x52A040DB;
        g = "copper_ore";
        K = "shovelWood";
        E = "updated";
        Fa = " player ";
        la = "salmon";
        J = "of.options.ANIMATED_LAVA";
        l = "9b";
        r = "GL13.GL_CLIENT_ACTIVE_TEXTURE";
        Ga = 0xF0FCC6B5 ^ 0xF0FC5A3F;
        a = Float.intBitsToFloat(0x626ECC27 ^ 0xDD5C74E5);
        q = Float.intBitsToFloat(0x5D72FAEB ^ 0x1EF2FAEB);
        f = "potion.moveSlowdown";
        ga = 0xB28A10F4FD3E60F0L ^ 0xB28A10F4C6A4AAF0L;
        fa = "\u4edb";
        Aa = "SHCC";
        B = Float.intBitsToFloat(0x466D60F9 ^ 0x87F253CA);
        p = "legs";
        L = "Clouds";
        m = "Badly compressed packet - size of ";
        Ha = "of.options.SMOOTH_FPS";
        s = "forwards";
    }

    public Fpa_2() {
        Fpa_2 a2;
    }
}

