/*
 * Decompiled with CFR 0.152.
 */
public final class fpa_1 {
    public static final String ma;
    public static final String La;
    public static final String ka;
    public static final String da;
    public static final String Ba;
    public static final String aa;
    public static final float ea;
    public static final String Ea;
    public static final float Ca;
    public static final float ia;
    public static final String Ma;
    public static final double ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final float Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final double S;
    public static final String Z;
    public static final String Y;
    public static final double r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final float Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final double o;
    public static final int h;
    public static final double K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final double a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final float G;
    public static final int D;
    public static final int f;
    public static final String F;
    public static final long g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final float M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Ja = "tuffSlab";
        Da = -0.22307169437408447F /* ZKM Deobf */;
        Y = "PushZ";
        Fa = 4099 /* ZKM Deobf Int */;
        ha = "scoreboard";
        j = "minecraft:crafting_table";
        d = "RightLeg1";
        F = "stone";
        Ha = "bamboo_fence_gate";
        U = "Pet.top";
        e = 389 /* ZKM Deobf Int */;
        Q = -1.2217299938201904F /* ZKM Deobf */;
        m = 1.7473950386047363F /* ZKM Deobf */;
        t = 4609 /* ZKM Deobf Int */;
        la = "SUSPENDED_DEPTH";
        W = "STREAM_MIC_TOGGLE_BEHAVIOR";
        O = "leftLeg.leftLeg";
        J = "an";
        ba = 90.0D /* ZKM Deobf */;
        ea = 0.4699999988079071F /* ZKM Deobf */;
        C = "Font loading error";
        ma = "wooden_axe";
        G = -23.0F /* ZKM Deobf */;
        a = 144.0D /* ZKM Deobf */;
        Aa = "options.stream.fps";
        q = "GL11.GL_AND";
        f = 3329 /* ZKM Deobf Int */;
        g = 0x8772CEEF35B0B096L ^ 0x8772CEEF35B08A0EL;
        fa = "useMonuments";
        i = "emerald_ore";
        v = 2981 /* ZKM Deobf Int */;
        La = "beef";
        ca = 34890 /* ZKM Deobf Int */;
        H = 5376 /* ZKM Deobf Int */;
        E = "barrier";
        ka = "complete";
        A = "ViSH";
        M = -3.5999999046325684F /* ZKM Deobf */;
        S = 11.0D /* ZKM Deobf */;
        x = 4294443007 /* ZKM Deobf Int */;
        Ia = "V";
        u = "Saving entity NBT";
        K = 0.7042D /* ZKM Deobf */;
        Ga = "Why did you do that?";
        da = "\u00a7a";
        Ka = "andesiteStairs";
        X = "textures/pet/cloudpet.png";
        Ea = "misc";
        N = 5.199999809265137F /* ZKM Deobf */;
        T = "particles_alpha";
        ia = -18.0F /* ZKM Deobf */;
        Z = "bambooBlock";
        V = "Head.Shape7";
        r = 2048.0D /* ZKM Deobf */;
        L = "resin_block";
        h = 335 /* ZKM Deobf Int */;
        B = "CZ";
        n = 61441 /* ZKM Deobf Int */;
        I = "the player acts as the camera";
        Ca = -10.399999618530273F /* ZKM Deobf */;
        ja = "Shaders.init pre";
        b = "resource_pack[";
        z = "big";
        p = "silver_wool";
        y = "pets";
        w = "assets/minecraft/blockstates/sand.json";
        o = 2.25D /* ZKM Deobf */;
        Ba = "lapisCount";
        ga = 641 /* ZKM Deobf Int */;
        R = "dark_oak_planks";
        aa = "\u5044";
        k = "uniform [ _a-zA-Z0-9]+ centerDepthSmooth;.*";
        P = "yyyy-MM-dd_HH.mm.ss";
        Ma = "No match blocks: ";
        D = 10511680 /* ZKM Deobf Int */;
        s = "max";
        l = "selectWorld.allowCommands.info";
        c = "textures/gui/container/personalization.png";
    }

    public fpa_1() {
        fpa_1 a2;
    }
}

