/*
 * Decompiled with CFR 0.152.
 */
public final class fqa {
    public static final int ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final String ga;
    public static final long Da;
    public static final double ca;
    public static final String Ja;
    public static final String ja;
    public static final float Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final double O;
    public static final String t;
    public static final String R;
    public static final float Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final float w;
    public static final double W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final float e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final long J;
    public static final String A;
    public static final double I;

    public fqa() {
        fqa a2;
    }

    static {
        R = "0.7x";
        d = "!0 & 1 & 2 & 3 & 2+6";
        T = "Shape41";
        r = "URL";
        y = 30016 /* ZKM Deobf Int */;
        ia = 33326 /* ZKM Deobf Int */;
        ba = 32971 /* ZKM Deobf Int */;
        Ja = "\u0000\n\u0000\u0001\u0001\n\n\u0000\u0002\u0000\u0001\u0208\u0002\u001b\u0003\u1004\u0000\u0004\u1004\u0001\u0005\u1009\u0002\u0006\u1007\u0003\u0007\u1007\u0004\b\u1007\u0005\t\u100a\u0006\n\u001b";
        fa = "party/checkbox/active.png";
        a = "GRAPE";
        U = 0.5235987901687622F /* ZKM Deobf */;
        q = ", Particles: false";
        o = "direction_x";
        S = "EntityHorse";
        ca = 0.125D /* ZKM Deobf */;
        Q = 2.6179940700531006F /* ZKM Deobf */;
        N = "supported";
        s = 809 /* ZKM Deobf Int */;
        g = "textures/body/mercy_wings_orange.png";
        I = -0.8D /* ZKM Deobf */;
        j = "Demaster";
        K = 21.399999618530273F /* ZKM Deobf */;
        ga = "chunkMap";
        b = "NeSR";
        la = "clamp";
        n = "glazed_terracotta2";
        C = "Immitating block ID";
        i = "height_";
        J = 0xF68EDBCE43F00160L ^ 0xF68EDBCE43F001CFL;
        Da = 0x8A9FDBFBA1D8C59BL ^ 0x756024045E273A64L;
        Ma = "Left.Shape7123";
        t = "\u042f\u0440\u043a\u043e\u0441\u0442\u044c";
        O = 0.6600000262260437D /* ZKM Deobf */;
        p = "BlockLight";
        Ha = 600.0F /* ZKM Deobf */;
        P = "Accept";
        A = "GL11.GL_POLYGON_OFFSET_FILL";
        G = "UBYTE";
        u = "file:texteria/cache/";
        D = "GL15.GL_WEIGHT_ARRAY_BUFFER_BINDING";
        Ka = "resinBricks";
        f = 754 /* ZKM Deobf Int */;
        L = "Please avoid temperatures in the range 0.1 - 0.2 because of snow";
        Z = "Head.Shape4";
        X = "demo.day.";
        e = 0.2974289059638977F /* ZKM Deobf */;
        v = "\u0442\u043e\u0432\u0430\u0440\u0430\u043c\u0438, \u0447\u0442\u043e\u0431\u044b \u0435\u0433\u043e \u043f\u043e\u0442\u043e\u0440\u043e\u043f\u0438\u0442\u044c";
        ja = "renderClouds:true";
        k = "GL11.GL_NOOP";
        c = "const bool ";
        Ga = " tried to set an invalid carried item";
        w = 0.18000000715255737F /* ZKM Deobf */;
        Ia = 34193 /* ZKM Deobf Int */;
        m = -1.0867999792099F /* ZKM Deobf */;
        Fa = "FSAA Samples: ";
        V = "reinforcedDeepslate";
        W = 100.0D /* ZKM Deobf */;
        H = "extended";
        E = "sky";
        B = "pickup";
        Aa = "^#([A-Fa-f0-9]{6})$";
        h = "Unsuccessful in deleting contents.";
        x = "High";
        l = "netherBrick";
        ha = "sleep";
        z = "c.currency";
        F = "createWorld.customize.custom.size";
        Y = "dye_silver";
        M = "custom_direction";
    }
}

