/*
 * Decompiled with CFR 0.152.
 */
public final class FRa {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final float Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final float ca;
    public static final int Ja;
    public static final float ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final double S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final double k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public FRa() {
        FRa a2;
    }

    static {
        b = "Shape38";
        m = 4278190335 /* ZKM Deobf Int */;
        f = "potion.prefix.rank";
        Z = -1.0471980571746826F /* ZKM Deobf */;
        Ma = 1.9198620319366455F /* ZKM Deobf */;
        U = "downfalls[] size";
        w = "headd.head2";
        Ia = 735 /* ZKM Deobf Int */;
        v = "silk_touch";
        r = "transform_outfit";
        Ka = "Can't ping ";
        W = "data:";
        Ga = 10.0F /* ZKM Deobf */;
        Aa = "VimeStorage Executor";
        X = "Invalid call to Particle.setMiscTex";
        l = "GL11.GL_ORDER";
        t = "Player ";
        C = "Padding";
        p = "rightHand.bow3";
        J = "Shape50123";
        S = 107.0D /* ZKM Deobf */;
        Ca = "Unknown symmetry: ";
        h = 33879 /* ZKM Deobf Int */;
        q = "AMBIENT";
        z = "vw";
        e = "Back.8a";
        Ea = "Loaded shaderpack: ";
        ja = 1.6200000047683716F /* ZKM Deobf */;
        x = 555 /* ZKM Deobf Int */;
        B = -16.0F /* ZKM Deobf */;
        j = "Immitating block data";
        N = "deepslate_emerald_ore";
        Y = "\u041f\u0438\u0442\u043e\u043c\u0446\u044b";
        A = "bakeCake";
        s = "culling";
        u = 44975 /* ZKM Deobf Int */;
        I = "missing";
        Ja = 20336 /* ZKM Deobf Int */;
        D = "hatchetGold";
        o = "GL11.GL_MAP2_TEXTURE_COORD_2";
        F = "commands.summon.outOfWorld";
        Da = "textures/entity/villager/butcher.png";
        ba = "random.pop";
        ha = "bezier_right_time";
        L = "in_wall";
        E = "The root element of Bedrock particle should be an object!";
        P = 3504 /* ZKM Deobf Int */;
        M = "variable.particle_bounces";
        a = 30012 /* ZKM Deobf Int */;
        V = "DisplayOffset";
        fa = "GL11.GL_MAP2_TEXTURE_COORD_1";
        O = "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0003\u0000\u0001$\u0002)\u0003'\u0004\u1001\u0000\u0005\u100c\u0001";
        Q = " boxes, ";
        Fa = "diamondCount";
        R = ", matchTiles: ";
        H = 40050 /* ZKM Deobf Int */;
        ca = -1.5F /* ZKM Deobf */;
        d = "Value";
        k = 135.0D /* ZKM Deobf */;
        n = "deathScreen.score";
        G = 35714 /* ZKM Deobf Int */;
        ga = 32778 /* ZKM Deobf Int */;
        la = "stat.horseOneCm";
        y = "egg.spots.";
        Ha = "resultCase_";
        c = "stripped_bamboo_block";
        T = 10497.0F /* ZKM Deobf */;
        K = "\u00a7";
        g = 621 /* ZKM Deobf Int */;
        i = "[-+]?[0-9]+[s|S]";
        ia = "OR";
    }
}

