/*
 * Decompiled with CFR 0.152.
 */
public final class FRa {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final float Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final float ca;
    public static final int Ja;
    public static final float ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final double S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final double k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public FRa() {
        FRa a2;
    }

    static {
        b = "Shape38";
        m = 0xDC852410 ^ 0x238524EF;
        f = "potion.prefix.rank";
        Z = Float.intBitsToFloat(0xA07D2179 ^ 0x1FFB2BEF);
        Ma = Float.intBitsToFloat(0xD5347148 ^ 0xEAC1CF42);
        U = "downfalls[] size";
        w = "headd.head2";
        Ia = 0xE183BD04 ^ 0xE183BFDB;
        v = "silk_touch";
        r = "transform_outfit";
        Ka = "Can't ping ";
        W = "data:";
        Ga = Float.intBitsToFloat(0x4F721342 ^ 0xE521342);
        Aa = "VimeStorage Executor";
        X = "Invalid call to Particle.setMiscTex";
        l = "GL11.GL_ORDER";
        t = "Player ";
        C = "Padding";
        p = "rightHand.bow3";
        J = "Shape50123";
        S = Double.longBitsToDouble(0x17C8EFA4AED6D922L ^ 0x57922FA4AED6D922L);
        Ca = "Unknown symmetry: ";
        h = 0x87B10860 ^ 0x87B18C37;
        q = "AMBIENT";
        z = "vw";
        e = "Back.8a";
        Ea = "Loaded shaderpack: ";
        ja = Float.intBitsToFloat(0x12D4A4E0 ^ 0x2D1BF8C9);
        x = 0x8131E143 ^ 0x8131E368;
        B = Float.intBitsToFloat(0xC61E42FF ^ 0x79E42FF);
        j = "Immitating block data";
        N = "deepslate_emerald_ore";
        Y = "\u041f\u0438\u0442\u043e\u043c\u0446\u044b";
        A = "bakeCake";
        s = "culling";
        u = 0xF8311D7F ^ 0xF831B2D0;
        I = "missing";
        Ja = 0x986C9B50 ^ 0x986CD420;
        D = "hatchetGold";
        o = "GL11.GL_MAP2_TEXTURE_COORD_2";
        F = "commands.summon.outOfWorld";
        Da = "textures/entity/villager/butcher.png";
        ba = "random.pop";
        ha = "bezier_right_time";
        L = "in_wall";
        E = "The root element of Bedrock particle should be an object!";
        P = 0x7F965416 ^ 0x7F9659A6;
        M = "variable.particle_bounces";
        a = 0x223B6699 ^ 0x223B13A5;
        V = "DisplayOffset";
        fa = "GL11.GL_MAP2_TEXTURE_COORD_1";
        O = "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0003\u0000\u0001$\u0002)\u0003'\u0004\u1001\u0000\u0005\u100c\u0001";
        Q = " boxes, ";
        Fa = "diamondCount";
        R = ", matchTiles: ";
        H = 0x4061E323 ^ 0x40617F51;
        ca = Float.intBitsToFloat(0x6CC9E910 ^ 0xD309E910);
        d = "Value";
        k = Double.longBitsToDouble(0xB475208ED0CB75F0L ^ 0xF415C08ED0CB75F0L);
        n = "deathScreen.score";
        G = 0x681C0E0 ^ 0x6814B62;
        ga = 0x18DA5E29 ^ 0x18DADE23;
        la = "stat.horseOneCm";
        y = "egg.spots.";
        Ha = "resultCase_";
        c = "stripped_bamboo_block";
        T = Float.intBitsToFloat(0x5E2EF61D ^ 0x180AF21D);
        K = "\u00a7";
        g = 0x15DBA010 ^ 0x15DBA27D;
        i = "[-+]?[0-9]+[s|S]";
        ia = "OR";
    }
}

