/*
 * Decompiled with CFR 0.152.
 */
public final class Fsa {
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final double z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final float A;
    public static final String I;

    public Fsa() {
        Fsa a2;
    }

    static {
        k = "logo";
        Q = "stone_slab";
        W = "commands.enchant.usage";
        Aa = "Body.Shape19";
        X = "preRenderErrors";
        n = "Image {} {} {}x{}{} prepared in {} ms";
        r = "[Shaders] Error reading: ";
        o = "polishedTuffWall";
        N = "body.body7";
        V = "Given object couldn't be converted to value! ";
        q = 0x4475AC1F ^ 0x44758D2B;
        Da = "textures/body/batterfly_wings.png";
        P = "demonicwingstail.animation";
        B = "QUEUED";
        Ha = "GL11.GL_T";
        p = "commands.generic.entity.notFound";
        i = " found, only -45/-22.5/0/22.5/45 allowed";
        z = Double.longBitsToDouble(0xF9DBF58E085AAF32L ^ 0x397C858E085AAF32L);
        w = "\u0000\u0011\u0000\u0001\u0001\u0011\u0011\u0000\u0001\u0000\u0001\u0001\u0002\u0001\u0003\u0001\u0004\u1001\u0001\u0005\u1001\u0002\u0006\u1001\u0003\u0007\u1001\u0004\b\u1001\u0005\t\u1001\u0006\n\u1007\u0007\u000b\u1007\b\f\u1007\t\r\u1007\n\u000e\u1009\u000b\u000f\u001b\u0010\u1009\f\u0011\u1001\u0000";
        Z = "Shape112";
        U = "wooden_pickaxe";
        T = "action";
        t = "deepslateTileSlab";
        D = 0x8A829858 ^ 0x8A8298D6;
        c = "drag_scroll_mark";
        e = "box[";
        I = "%uuid%";
        J = 0x8331AC97 ^ 0x8331A0E5;
        b = "PLAYANIMATION";
        d = 0xCCD432FB ^ 0xCCD432E5;
        G = "GL11.GL_PIXEL_MAP_I_TO_R_SIZE";
        R = "eTable_";
        M = "emptyMap";
        u = "angleAnimSmart_";
        g = "overrideWidth";
        H = 0xD58EC99A ^ 0xD58EC929;
        fa = 0xD6EB8B17 ^ 0xD6EB7B1C;
        O = "Could not handle Texteria command ";
        ga = "commands.scoreboard.players.list.empty";
        ja = "commands.deop.usage";
        Ga = 0x31CCC3E4 ^ 0x31CC4721;
        f = "Out of memory";
        s = Float.intBitsToFloat(0x367983B6 ^ 0x89B08C6D);
        E = "Using framebuffer objects because ";
        l = "skull_skeleton";
        h = "Towards negative";
        A = Float.intBitsToFloat(0x76802E0D ^ 0x4B40AD1F);
        S = 0xA9C45B88 ^ 0x563BA401;
        v = "dynamic_item";
        K = "ofShowCapes";
        Ja = "leaves";
        ca = "Shape14";
        Ka = "STOPPARTICLES";
        m = "big_oak";
        L = "eLine_";
        la = 0x1685628F ^ 0x161B1DFE;
        C = "GL15.GL_STATIC_DRAW";
        j = "stat.mined";
        x = "double_plant";
        y = "diamond_leggings";
        F = 0x77645752 ^ 0x77388C87;
        a = "here";
        Y = "RGB32I";
    }
}

