/*
 * Decompiled with CFR 0.152.
 */
public final class fsa_1 {
    public static final float ba;
    public static final String ha;
    public static final float Fa;
    public static final float Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final int n;
    public static final String s;
    public static final double w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public fsa_1() {
        fsa_1 a2;
    }

    static {
        c = "shadow culling";
        e = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0004\u0002\u100c\u0000\u0003\u100c\u0001\u0004\u1007\u0002";
        q = "HitResult{type=";
        l = 30050 /* ZKM Deobf Int */;
        Fa = -7.570000171661377F /* ZKM Deobf */;
        P = "checkTexture: act: ";
        ba = 7.533332824707031F /* ZKM Deobf */;
        I = 629 /* ZKM Deobf Int */;
        H = 36756 /* ZKM Deobf Int */;
        d = "GL11.GL_LIGHT1";
        Ka = "Piece1.Shape1";
        n = 3479 /* ZKM Deobf Int */;
        k = 2256 /* ZKM Deobf Int */;
        x = "disconnect.genericReason";
        K = "Shape5123";
        D = "potion.potency.";
        y = "huggywuggy.animation";
        b = "COBBLESTONE";
        o = "LPT5";
        u = "Filesize was bigger than maximum allowed (got >= ";
        fa = "XL_X2";
        a = "minecraft:emitter_shape_point";
        F = "FLIP";
        O = "createWorld.customize.custom.riverSize";
        Ja = "Exception";
        E = 288 /* ZKM Deobf Int */;
        la = "shaders/post/scan_pincushion.json";
        Ha = "shade";
        U = "triangle_top";
        Q = "rxm";
        T = "whitelist";
        G = "steve";
        r = "VIME_ART";
        Z = "[ \t]*const[ \t]*bool[ \t]*shadowHardwareFiltering0[ \t]*=[ \t]*true[ \t]*;.*";
        ha = "birch_fence_gate";
        Ia = 0.949999988079071F /* ZKM Deobf */;
        ga = "prismarine_stairs";
        V = "cre";
        X = 32834 /* ZKM Deobf Int */;
        S = "https://mg-balancer.vimeworld.com";
        N = "neck.scale";
        g = " (incompatible)";
        M = 40004 /* ZKM Deobf Int */;
        R = 17855 /* ZKM Deobf Int */;
        f = "a number (";
        B = "options.difficulty.peaceful";
        Ga = "GL14.GL_MIN";
        j = "usedDrawBuffers: ";
        m = "X2";
        s = "Sunset";
        Da = -1.029744029045105F /* ZKM Deobf */;
        w = 0.8600000143051147D /* ZKM Deobf */;
        J = "MM";
        z = "Roofed Forest";
        A = "Left.Shape22123";
        p = 36759 /* ZKM Deobf Int */;
        L = 1.125F /* ZKM Deobf */;
        h = "sulphur";
        C = "Monster";
        ca = "Classic Flat";
        W = 30047 /* ZKM Deobf Int */;
        v = "RGBA8";
        i = "soundCase_";
        Y = "Could not load config (";
        ja = "sleep_time";
        t = "shaders/post/blobs2.json";
        Aa = "wall_n";
    }
}

