/*
 * Decompiled with CFR 0.152.
 */
public final class fsa_1 {
    public static final float ba;
    public static final String ha;
    public static final float Fa;
    public static final float Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final int n;
    public static final String s;
    public static final double w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public fsa_1() {
        fsa_1 a2;
    }

    static {
        c = "shadow culling";
        e = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0004\u0002\u100c\u0000\u0003\u100c\u0001\u0004\u1007\u0002";
        q = "HitResult{type=";
        l = 0x35110C ^ 0x35646E;
        Fa = Float.intBitsToFloat(0x155BFA62 ^ 0xD5A9C713);
        P = "checkTexture: act: ";
        ba = Float.intBitsToFloat(0xD8FEF68D ^ 0x980FE79D);
        I = 0xD0E66147 ^ 0xD0E66332;
        H = 0x61756B10 ^ 0x6175E484;
        d = "GL11.GL_LIGHT1";
        Ka = "Piece1.Shape1";
        n = 0xE4055149 ^ 0xE4055CDE;
        k = 0x129F1A0F ^ 0x129F12DF;
        x = "disconnect.genericReason";
        K = "Shape5123";
        D = "potion.potency.";
        y = "huggywuggy.animation";
        b = "COBBLESTONE";
        o = "LPT5";
        u = "Filesize was bigger than maximum allowed (got >= ";
        fa = "XL_X2";
        a = "minecraft:emitter_shape_point";
        F = "FLIP";
        O = "createWorld.customize.custom.riverSize";
        Ja = "Exception";
        E = 0x5CEE034B ^ 0x5CEE026B;
        la = "shaders/post/scan_pincushion.json";
        Ha = "shade";
        U = "triangle_top";
        Q = "rxm";
        T = "whitelist";
        G = "steve";
        r = "VIME_ART";
        Z = "[ \t]*const[ \t]*bool[ \t]*shadowHardwareFiltering0[ \t]*=[ \t]*true[ \t]*;.*";
        ha = "birch_fence_gate";
        Ia = Float.intBitsToFloat(0xC36052EC ^ 0xFC1361DF);
        ga = "prismarine_stairs";
        V = "cre";
        X = 0x4843A265 ^ 0x48432227;
        S = "https://mg-balancer.vimeworld.com";
        N = "neck.scale";
        g = " (incompatible)";
        M = 0x815F1875 ^ 0x815F8431;
        R = 0xAE3C18BF ^ 0xAE3C5D00;
        f = "a number (";
        B = "options.difficulty.peaceful";
        Ga = "GL14.GL_MIN";
        j = "usedDrawBuffers: ";
        m = "X2";
        s = "Sunset";
        Da = Float.intBitsToFloat(0x29057458 ^ 0x9686BAFF);
        w = Double.longBitsToDouble(0x6594E06DB3690566L ^ 0x5A7F657373690566L);
        J = "MM";
        z = "Roofed Forest";
        A = "Left.Shape22123";
        p = 0x388CDA29 ^ 0x388C55BE;
        L = Float.intBitsToFloat(0xB8A3693C ^ 0x8733693C);
        h = "sulphur";
        C = "Monster";
        ca = "Classic Flat";
        W = 0x28C6B334 ^ 0x28C6C66B;
        v = "RGBA8";
        i = "soundCase_";
        Y = "Could not load config (";
        ja = "sleep_time";
        t = "shaders/post/blobs2.json";
        Aa = "wall_n";
    }
}

