/*
 * Decompiled with CFR 0.152.
 */
public final class fta {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final int Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final long z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final float B;
    public static final long d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final double F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        E = "textures/entity/pig/pig.png";
        M = "tweakBlockDamage";
        N = "slot.inventory.";
        t = "optifine/lang/";
        D = Float.intBitsToFloat(0xF83E645E ^ 0xC6EE645E);
        ja = "Exception in world tick";
        fa = 0x4B0765B7 ^ 0xB4F89A68;
        o = "textures/body/batterfly_wings_white.png";
        c = Float.intBitsToFloat(0xE89CB8E5 ^ 0xAB0138E5);
        h = "*unknown*";
        k = "mangrove_slab";
        z = 0x8FE9305865C4CB60L ^ 0x8FE9305867417345L;
        x = "easeOutExpo";
        d = 0xF3B5BF03354CBBF3L ^ 0xF3B5BF03354CBBE7L;
        L = 0xC1EECA31 ^ 0xC1EEC166;
        Ka = 0x7203C3BA ^ 0x8DFC3CFA;
        i = "crimson_trapdoor";
        C = "ofFullscreenMode:";
        b = "replace_right_leg";
        n = "surface_only";
        P = "Shape72";
        Ha = "optifine/natural.properties";
        X = "rightLeg";
        R = "GL13.GL_SOURCE0_RGB";
        a = "COOL_WARM";
        O = "textures/entity/villager/librarian.png";
        g = 0xEF3CB659 ^ 0xEF3CBE8E;
        W = "13b";
        ga = "Leashed";
        H = "gl_caps[ARB_blend_func_extended]";
        la = "testforblock";
        q = "purple_concrete_powder";
        Z = "91AEAA56-376B-4498-935B-2F7F68070635";
        U = "Program disabled: ";
        Ja = 0x28C08239 ^ 0x28F48239;
        v = "exposedCutCopperSlab";
        u = "Head.Shape13";
        Ga = "tile.piston.out";
        ca = "More weights defined than skins, trimming weights: ";
        w = "magmaCream";
        Aa = Float.intBitsToFloat(0xE27891D6 ^ 0xDD51382A);
        Q = "OLD_LIGHTING";
        K = "[ \t]*const[ \t]*bool[ \t]*(shadowtex0Nearest|shadowtexNearest|shadow0MinMagNearest)[ \t]*=[ \t]*true[ \t]*;.*";
        Y = "ItemOptions{options=";
        G = "_cast";
        J = "easeInOutExpo";
        l = 0x1D822241 ^ 0x1D8222E2;
        B = Float.intBitsToFloat(0xF43F8D7B ^ 0xCBF682A3);
        j = "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0000\u0000\u0001\u0001\u0002\u0001\u0003\u0001\u0004\u0001\u0005\u0001\u0006\u0001\u0007\u0001\b\u0001\t\u0001";
        f = "touchscreen:";
        Da = "minecraft:emitter_lifetime_expression";
        T = "[/AD]";
        I = "You are not white-listed on this server!";
        r = "texture_layer_2";
        A = "fog-end";
        p = "Hell";
        F = Double.longBitsToDouble(0x709E8A938D65E464L ^ 0x4F3AF072CACBF01FL);
        V = "white-list.txt";
        e = "GL11.GL_C4UB_V3F";
        S = "RecordPlayer";
        m = "depthMask_";
        s = "magenta_carpet";
        y = "random.eat";
    }

    public fta() {
        fta a2;
    }
}

