/*
 * Decompiled with CFR 0.152.
 */
public final class GPa {
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final double fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final double W;
    public static final float q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final double g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public GPa() {
        GPa a2;
    }

    static {
        N = "SERVERBOUND";
        n = "modelOffset_";
        h = "pre beginRender";
        v = 16445632 /* ZKM Deobf Int */;
        D = "Head.16";
        ja = "GL12.GL_PROXY_TEXTURE_3D";
        s = "GL11.GL_PIXEL_MAP_A_TO_A";
        C = 54 /* ZKM Deobf Int */;
        u = "jungle_log";
        w = "createWorld.customize.custom.presets";
        M = "Failed to save options";
        Y = "menu.game";
        k = "GL11.GL_CLIP_PLANE2";
        O = "ambient.cave.cave";
        Ka = "double_rose";
        E = "\u0412\u043a\u043b\u044e\u0447\u0435\u043d\u044b";
        m = "mcpatcher/anim";
        F = "recheckGaps";
        I = "acrid";
        c = "depthNoiseScaleExponent";
        J = "0";
        fa = 0.800000011920929D /* ZKM Deobf */;
        L = "FT d";
        B = "TileEntities";
        o = "slot_";
        g = 0.02D /* ZKM Deobf */;
        Q = "'from' specifier exceeds the allowed boundaries: ";
        W = 100000000.0D /* ZKM Deobf */;
        j = "textures/pet/mushroom_red.png";
        f = "GL13.GL_COMPRESSED_ALPHA";
        R = "advMode.setCommand.success";
        z = "port_";
        A = "displayId";
        Ga = 612 /* ZKM Deobf Int */;
        G = 130 /* ZKM Deobf Int */;
        S = "textures/pet/bedwars_2017_";
        b = 660 /* ZKM Deobf Int */;
        d = "NVFogDistance.GL_EYE_PLANE_ABSOLUTE_NV";
        t = "untouching";
        T = 401 /* ZKM Deobf Int */;
        p = " rs ";
        e = "STOP_SLEEPING";
        Da = "gl_caps[ARB_draw_buffers]";
        l = "png";
        i = "black";
        Ja = 617 /* ZKM Deobf Int */;
        U = "crimsonTrapdoor";
        x = "oxygen";
        V = "L";
        Z = "flower_tulip_white";
        Ha = "fireCoralBlock";
        ca = "tts";
        K = "Type: ";
        a = "PLAYER";
        Aa = "textures/font/ascii.png";
        y = " is larger than protocol maximum of ";
        H = "X90_Y0";
        q = -0.5061454772949219F /* ZKM Deobf */;
        X = "diamond_horse_armor";
        r = "stat.enderchestOpened";
        P = "RightLeg.RL";
    }
}

