/*
 * Decompiled with CFR 0.152.
 */
public final class gQa {
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final int Da;
    public static final float ca;
    public static final int Ja;
    public static final int ja;
    public static final String Ha;
    public static final double Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final float X;
    public static final String y;
    public static final long U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public gQa() {
        gQa a2;
    }

    static {
        u = "of.options.HELD_ITEM_TOOLTIPS";
        M = "flowing_lava";
        d = "D#D";
        Ga = Double.longBitsToDouble(0x7A3AD392C2DB0B43L ^ 0x3AD81192C2DB0B43L);
        ja = 0x1B994772 ^ 0x1B99C773;
        Ka = "blockData";
        s = "streamChatUserFilter:";
        T = "options.skinCustomisation";
        f = "image_";
        V = 0x65D76260 ^ 0x65D762F5;
        L = "SPRUCE";
        P = 0xF7728843 ^ 0xF7728899;
        Ja = 0xF0F5AC36 ^ 0xF0F5B93B;
        b = Float.intBitsToFloat(0x3D880E7D ^ 0x7C580E7D);
        p = "GL11.GL_COPY_PIXEL_TOKEN";
        y = "Found IK modifier in BOBJ, but bone ";
        x = "textures/pet/spinner_fl1.png";
        k = ", items: [";
        Y = "motionZExpr_";
        K = "GL11.GL_NORMAL_ARRAY_TYPE";
        N = "~O ";
        Ha = "Invalid texture->mipmaps: expected array, was ";
        Da = 0x200201AD ^ 0x20020C3B;
        m = 0xF20ADD50 ^ 0xF20AD067;
        I = "DONE";
        v = "attach";
        l = "LINEAR";
        q = "createWorld.customize.flat.editLayer";
        H = "eButton_";
        C = 0x325892C4 ^ 0x32581A78;
        Fa = "scalevalCase_";
        o = "X90_Y90";
        Aa = "swampgrasscolor.png";
        fa = "bamboo_fence";
        Ia = "LeftHand";
        t = "GL12.GL_UNPACK_SKIP_IMAGES";
        w = "Hand";
        Z = "Description: ";
        J = "items/empty_armor_slot_helmet";
        B = " 2.1 ";
        D = "Invalid model_type for item ";
        F = "GL12.GL_UNSIGNED_SHORT_4_4_4_4";
        R = "SCALEXANIM";
        E = "dye_light_blue";
        X = Float.intBitsToFloat(0x818DB451 ^ 0x41C4BB8A);
        Q = "exposed_cut_copper_slab_double";
        la = 0xE75E0751 ^ 0xE75E8B87;
        i = "sizeval_";
        O = "ALL";
        S = "GL11.GL_SPOT_DIRECTION";
        r = "white";
        G = "lm";
        n = "scheduledExecutables";
        g = "HellRandomLevelSource";
        ga = "XpSeed";
        A = "of.options.shaders.ANTIALIASING";
        U = 0xC11FCFD0BF022875L ^ 0xC11FCFD0A6BDE475L;
        j = "reEntryProcessing";
        z = "ERRORTYPE";
        h = Float.intBitsToFloat(0x1C672B22 ^ 0xA2B84995);
        e = " xyz: ";
        W = "GL11.GL_DECR";
        a = 0x21F29F47 ^ 0x21F29E78;
        ca = Float.intBitsToFloat(0x95952DE1 ^ 0xD41D2DE1);
        c = "Front.13a";
    }
}

