/*
 * Decompiled with CFR 0.152.
 */
public final class gua {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final double V;
    public static final String z;
    public static final int X;
    public static final int y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final int t;
    public static final float R;
    public static final int Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final float e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public gua() {
        gua a2;
    }

    static {
        Ka = "waxed_exposed_copper_grate";
        n = "sound";
        X = 7425 /* ZKM Deobf Int */;
        b = "bread";
        a = "goo";
        x = "STATUS";
        G = "\n#define ";
        P = "Depth";
        K = "CaveSpider";
        q = "commands.replaceitem.usage";
        s = "0.5x";
        w = "[[ EXCEPTION ";
        N = "GL11.GL_SRC_COLOR";
        l = 60.0F /* ZKM Deobf */;
        c = "textures/body/exowings_green.png";
        h = "textures/entity/sign.png";
        E = "file://";
        r = "SvinPlay";
        ga = "ofFastMath";
        v = "attribute.modifier.plus.";
        R = 127.0F /* ZKM Deobf */;
        i = "SPIN";
        u = "root";
        k = "properties";
        L = "ELEMENTID2D";
        z = "keySneakButton";
        V = 30.0D /* ZKM Deobf */;
        e = 48000.0F /* ZKM Deobf */;
        B = "translation";
        Aa = "Invalid tiles, must be exactly 4: ";
        A = "game.hostile.hurt.fall.big";
        d = 30020 /* ZKM Deobf Int */;
        fa = "textures/gui/container/inventory.png";
        g = "particles";
        Ja = "GL11.GL_3_BYTES";
        M = "previousCameraPosition";
        m = "LOCAL";
        y = 4285988864 /* ZKM Deobf Int */;
        Q = 3035801 /* ZKM Deobf Int */;
        F = "orange_concrete";
        ja = "deepslateTileStairs";
        O = 379 /* ZKM Deobf Int */;
        ca = "GL11.GL_GREEN_BIAS";
        J = ", bold=";
        Ha = "\n\t";
        la = "EASE_OUT_ELASTIC";
        p = "double_plant_syringa_bottom";
        j = "cracked_deepslate_tiles";
        H = "chicken";
        o = "generic.knockbackResistance";
        W = "PONG";
        Da = "start + count must be <= size: ";
        I = "options.guiScale.small";
        C = "mac";
        Z = "alt";
        U = 3.819999933242798F /* ZKM Deobf */;
        Y = "HttpPipelineSender";
        Ga = "ips";
        S = 3415 /* ZKM Deobf Int */;
        t = 45238971 /* ZKM Deobf Int */;
        D = "iron_helmet";
        T = -6.75F /* ZKM Deobf */;
        f = "gl_caps[ARB_fragment_program]";
    }
}

