/*
 * Decompiled with CFR 0.152.
 */
public final class Gua_1 {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final long R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final int W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final String L;
    public static final float E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Gua_1() {
        Gua_1 a2;
    }

    static {
        L = "spreadMotionX_";
        M = 1797 /* ZKM Deobf Int */;
        l = " when I expected it to be pending; ignoring task";
        t = "Error loading normal texture: ";
        Z = "gbuffers_weather";
        W = 423 /* ZKM Deobf Int */;
        G = "iron_log";
        o = "redstone_torch";
        x = "translate";
        N = "OUTER_LEFT";
        S = 40134 /* ZKM Deobf Int */;
        q = 13761 /* ZKM Deobf Int */;
        r = "textures/body/neonwings_purple.png";
        n = "DARK_RED";
        C = "BROWN";
        g = 2965 /* ZKM Deobf Int */;
        ca = "uniforms[";
        Da = "waxed_exposed_copper";
        y = "of.general.ambiguous";
        R = 0xC251C8098B8C2801L ^ 0xC251C809F473D7FEL;
        P = "GL11.GL_POLYGON_OFFSET_POINT";
        I = "Failed encrypt AES-GSM because of unexpected errors";
        j = "budding_amethyst";
        w = 403 /* ZKM Deobf Int */;
        A = "HEAT_ICE";
        Aa = "textures/pet/normal_chest.png";
        m = "NeBCr";
        v = "uvs";
        U = 0.1745000034570694F /* ZKM Deobf */;
        K = "EASE_IN_QUINT";
        ja = "\u0422\u0435\u043d\u0438";
        fa = "q.gui_height";
        T = "FlatLevelSource";
        Ga = "sandStone";
        Y = "waxed_oxidized_cut_copper";
        h = "][generator_name]";
        ga = "Shadow framebuffer created.";
        V = 2164260863 /* ZKM Deobf Int */;
        d = "activator_rail";
        Ja = -85.0F /* ZKM Deobf */;
        e = 216 /* ZKM Deobf Int */;
        u = "Don't do that.";
        B = "OPTIFINE_JPM";
        D = "mob.blaze.hit";
        H = "doMobLoot";
        f = "mangrove_fence";
        p = "GRANITE";
        c = "mob.horse.donkey.death";
        a = "GL11.GL_DOMAIN";
        Ha = "bones";
        b = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\f\u0003\u100c\u0000\u0004\u1007\u0001";
        s = "Can't handle Texteria packet";
        J = "Tried to read NBT tag that was too big; tried to allocate: ";
        F = 222 /* ZKM Deobf Int */;
        Q = "Shape53";
        i = "easeInElastic";
        E = 0.6692150235176086F /* ZKM Deobf */;
        X = "shadowIntervalSize";
        la = ">>";
        Ka = "STRIPE_CENTER";
        z = "Feature being prepared";
        O = "shadow prepareterrain";
        k = " not found for bone ";
    }
}

