/*
 * Decompiled with CFR 0.152.
 */
public final class hpa {
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final float fa;
    public static final int Ka;
    public static final String Aa;
    public static final float S;
    public static final int Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final int T;
    public static final float p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final String J;
    public static final String A;
    public static final String I;

    public hpa() {
        hpa a2;
    }

    static {
        B = "Attempting to attack an invalid entity";
        Da = "oak_slab";
        Y = 686 /* ZKM Deobf Int */;
        Ka = 34178 /* ZKM Deobf Int */;
        s = "rightHand.bow2";
        Ga = 32876 /* ZKM Deobf Int */;
        V = "^\\s*#if(n)?def\\s+([A-Za-z0-9_]+)(\\s*)?$";
        a = "SOUTH";
        m = "/textures/";
        G = "chatHeightUnfocused";
        fa = 6.900000095367432F /* ZKM Deobf */;
        Q = 10796 /* ZKM Deobf Int */;
        E = "end_stone";
        w = "SCALEZVAL_NOT_SET";
        x = "XpLevel";
        r = "Unknown data type: ";
        T = 750 /* ZKM Deobf Int */;
        p = -0.2583000063896179F /* ZKM Deobf */;
        D = "Block model being tesselated";
        Ha = "flower";
        ca = "W#W";
        i = " is a stairs and should have 1 or 3 textures, got ";
        O = "Hardware shadow filtering enabled.";
        g = " are too big. Texture have no body";
        y = 7.0D /* ZKM Deobf */;
        c = "https://mc.vimeworld.ru/";
        C = "E199AD21-BA8A-4C53-8D13-6182D5C69D3A";
        t = "shadowcolor0Nearest";
        h = "clickEvent";
        J = "potion.prefix.dashing";
        W = "repeatDelay_";
        l = "Saving and pausing game...";
        ga = "of.options.ANIMATED_PORTAL";
        P = "EMIT";
        z = "GRAFFITI";
        X = "TexMinFilN";
        K = "GL11.GL_CURRENT_RASTER_INDEX";
        N = "gl_caps[ARB_vertex_blend]";
        I = "Head.Shape18";
        Z = 14 /* ZKM Deobf Int */;
        u = "item_search.png";
        e = "button";
        j = 2.9000000953674316F /* ZKM Deobf */;
        k = "FRLeg";
        U = "EASE_IN_EXPO";
        H = "gl_caps[ARB_fragment_program_shadow]";
        f = "carpet";
        Aa = "hoveredEntityId_";
        d = "socket closed";
        o = "notfound";
        A = "eRectangle_";
        M = "textures/entity/chest/normal_double.png";
        S = -1.0625F /* ZKM Deobf */;
        R = "0, 0.55, 0.45, 1";
        F = "POSITION";
        ja = "index can't be >= size: ";
        Ja = "Extreme Hills Edge";
        L = 2.4000000953674316F /* ZKM Deobf */;
        b = ")";
        q = "/\\* SHADOWHPL:[0-9\\.]+ \\*/.*";
        n = "Right33";
        v = "commands.gamerule.norule";
    }
}

