/*
 * Decompiled with CFR 0.152.
 */
public final class hqa_1 {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final double ha;
    public static final String Fa;
    public static final float Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final double Ka;
    public static final int Aa;
    public static final int S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final String R;
    public static final float Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final int h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        u = "mob_spawner";
        q = "hhb";
        y = "' defined";
        j = "cherryStairs";
        J = "Notch";
        E = "difficulty.lock.title";
        z = "Right.Right26";
        ca = "gui/rounding/round_fill_";
        Da = "doorDarkOak";
        A = "log3";
        d = "STREAM_FPS";
        K = 0xD730F0C5 ^ 0xD730F082;
        M = "Invalid sum of all weights: ";
        b = "FLLeg.Shape35";
        Fa = "straight_cross";
        Ka = Double.longBitsToDouble(0x6603D490D05FA002L ^ 0x59EFD490D05FA002L);
        Y = Float.intBitsToFloat(0xCEC29D3F ^ 0x8E5456DB);
        F = "chatHeightFocused";
        Ma = "game.player.swim.splash";
        N = "Invalid value: ";
        R = "Width";
        L = "parent";
        ba = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0001\u0000\u0001'\u0002\n\u0003\u0004\u0004\u1007\u0000";
        c = "Right32";
        m = "scaleXExact_";
        Ja = "Right.Right24";
        k = Float.intBitsToFloat(0xC3B58F9A ^ 0xFCF50F9A);
        w = Double.longBitsToDouble(0x6E2FD5759B38CCEEL ^ 0x2E5895759B38CCEEL);
        ja = "textures/body/fierywings_pink.png";
        Aa = 0xB035615A ^ 0xB074AC6E;
        I = "*** Reloading custom textures ***";
        Ia = Float.intBitsToFloat(0xFC1728B0 ^ 0xC311FD60);
        h = 0xE890DF42 ^ 0xE890902D;
        Z = "dynblock:";
        f = 0xADFA8723 ^ 0xADFA077F;
        fa = "assets/minecraft/blockstates/stone.json";
        e = "textures/entity/villager/farmer.png";
        B = "/cam ";
        t = Float.intBitsToFloat(0x45390866 ^ 0x84210866);
        Ha = "Player";
        l = Double.longBitsToDouble(0xE582F8056A33F8A3L ^ 0xDA6E34C9AA33F8A3L);
        H = "LeashKnot";
        o = "FULLSCREEN_MODE";
        ha = Double.longBitsToDouble(0xF348D39E5F0B7688L ^ 0xB308D39E5F0B7688L);
        C = "Entity: ";
        X = "spider_eyes";
        V = "shadow bind sfb";
        r = "ofLagometer:";
        W = "Multitexture: ";
        O = "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002<\u0000";
        Ga = " is a cube and should have 1 or 6 textures, got ";
        ia = "chiseled_brick";
        ga = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u1004\u0000\u0003\u1009\u0001";
        p = 0xD22F58F5 ^ 0xD22F5A4E;
        i = "sidebar";
        la = 0x8DB4CC32 ^ 0x8DB4CE4D;
        s = 0x65C9E1B4 ^ 0x65C9C7B4;
        n = "---- Minecraft Crash Report ----\n";
        U = "createWorld.customize.flat.layer.bottom";
        Q = Float.intBitsToFloat(0x1FBE860E ^ 0x20A1CFFB);
        g = 0xC7150459 ^ 0x630ACAB8;
        a = "commands.whitelist.add.failed";
        x = "BottomLeftRule";
        T = "Head.15";
        v = 0x9B6AA2CD ^ 0x9B6A246C;
        D = "GL13.GL_NORMAL_MAP";
        S = 0x3BBFE1B1 ^ 0x3BBF69A4;
        G = "Failed reading metadata of: ";
        P = ", entity=";
    }

    public hqa_1() {
        hqa_1 a2;
    }
}

