/*
 * Decompiled with CFR 0.152.
 */
public final class hqa_1 {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final double ha;
    public static final String Fa;
    public static final float Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final double Ka;
    public static final int Aa;
    public static final int S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final String R;
    public static final float Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final int h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        u = "mob_spawner";
        q = "hhb";
        y = "' defined";
        j = "cherryStairs";
        J = "Notch";
        E = "difficulty.lock.title";
        z = "Right.Right26";
        ca = "gui/rounding/round_fill_";
        Da = "doorDarkOak";
        A = "log3";
        d = "STREAM_FPS";
        K = 71 /* ZKM Deobf Int */;
        M = "Invalid sum of all weights: ";
        b = "FLLeg.Shape35";
        Fa = "straight_cross";
        Ka = 0.875D /* ZKM Deobf */;
        Y = 4.71238899230957F /* ZKM Deobf */;
        F = "chatHeightFocused";
        Ma = "game.player.swim.splash";
        N = "Invalid value: ";
        R = "Width";
        L = "parent";
        ba = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0001\u0000\u0001'\u0002\n\u0003\u0004\u0004\u1007\u0000";
        c = "Right32";
        m = "scaleXExact_";
        Ja = "Right.Right24";
        k = 0.751953125F /* ZKM Deobf */;
        w = 372.0D /* ZKM Deobf */;
        ja = "textures/body/fierywings_pink.png";
        Aa = 4312372 /* ZKM Deobf Int */;
        I = "*** Reloading custom textures ***";
        Ia = 0.5267000198364258F /* ZKM Deobf */;
        h = 20335 /* ZKM Deobf Int */;
        Z = "dynblock:";
        f = 32860 /* ZKM Deobf Int */;
        fa = "assets/minecraft/blockstates/stone.json";
        e = "textures/entity/villager/farmer.png";
        B = "/cam ";
        t = -9.5F /* ZKM Deobf */;
        Ha = "Player";
        l = 0.8999999761581421D /* ZKM Deobf */;
        H = "LeashKnot";
        o = "FULLSCREEN_MODE";
        ha = 32.0D /* ZKM Deobf */;
        C = "Entity: ";
        X = "spider_eyes";
        V = "shadow bind sfb";
        r = "ofLagometer:";
        W = "Multitexture: ";
        O = "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002<\u0000";
        Ga = " is a cube and should have 1 or 6 textures, got ";
        ia = "chiseled_brick";
        ga = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\u1004\u0000\u0003\u1009\u0001";
        p = 699 /* ZKM Deobf Int */;
        i = "sidebar";
        la = 639 /* ZKM Deobf Int */;
        s = 9728 /* ZKM Deobf Int */;
        n = "---- Minecraft Crash Report ----\n";
        U = "createWorld.customize.flat.layer.bottom";
        Q = 0.6222222447395325F /* ZKM Deobf */;
        g = 2753548001 /* ZKM Deobf Int */;
        a = "commands.whitelist.add.failed";
        x = "BottomLeftRule";
        T = "Head.15";
        v = 34465 /* ZKM Deobf Int */;
        D = "GL13.GL_NORMAL_MAP";
        S = 34837 /* ZKM Deobf Int */;
        G = "Failed reading metadata of: ";
        P = ", entity=";
    }

    public hqa_1() {
        hqa_1 a2;
    }
}

