/*
 * Decompiled with CFR 0.152.
 */
public final class Hra {
    public static final String Ma;
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final double la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final double Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final double S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final double t;
    public static final String R;
    public static final float Q;
    public static final double N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final int L;
    public static final String E;
    public static final long m;
    public static final String C;
    public static final String i;
    public static final long M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        c = "tripwire";
        L = 0x2B0A0441 ^ 0xD4ECC83F;
        Ga = Float.intBitsToFloat(0x1311C880 ^ 0x5025C880);
        h = Float.intBitsToFloat(0x96076B ^ 0xBEB5D061);
        w = "cookie";
        ga = "Enabled auto read";
        B = "profile-results-";
        k = "wetnessHalflife";
        ba = "followMouse_";
        t = Double.longBitsToDouble(0x7EF55358F028BF48L ^ 0x3EF19107195C1C08L);
        P = "mob.pig.death";
        J = "deathScreen.respawn";
        C = "glass_pink";
        Fa = "Entity ID";
        W = 0xBFD34A8D ^ 0xBFD3538D;
        Ma = "pardon";
        p = "Error loading specular texture: ";
        Aa = "GL11.GL_PIXEL_MAP_B_TO_B_SIZE";
        u = "overrideWidth:";
        f = "At least two points are needed!";
        fa = "FORCE_UNICODE_FONT";
        X = "GL11.GL_MAP1_GRID_DOMAIN";
        l = "SCREEN";
        i = "Attributes";
        g = Float.intBitsToFloat(0xED9D7265 ^ 0xACC57265);
        A = "Head.Shape19";
        T = "GL12.GL_TEXTURE_MAX_LOD";
        d = "DEATH";
        m = 0x305723FF366F2D3EL ^ 0x305723FF366F28E2L;
        M = 0x359E89D8A25A654FL ^ 0xCA6176275DA59AB1L;
        x = "pumpkinstem.png";
        R = "options.difficulty";
        I = ", valueDefault: ";
        K = "X-Minecraft-UUID";
        Y = "GRAHAM";
        ja = Float.intBitsToFloat(0xB0A02C1 ^ 0x49D602C1);
        a = "Metadata section name cannot be null";
        r = "ofVignette";
        e = 0x357B903A ^ 0x357BD42A;
        o = "record_mall";
        j = "Filtering";
        y = "price";
        N = Double.longBitsToDouble(0x9D59DBD4C64D4C08L ^ 0x229AE8E7F57E7F3BL);
        Ha = Double.longBitsToDouble(0x49EBC0BDA19F5379L ^ 0x762B636AA19F5379L);
        U = "the main menu and back to playing, but this may not have worked.";
        V = "Unbalanced quotation: ";
        G = "of.options.BETTER_GRASS";
        E = "stone_quartz_ore";
        H = Float.intBitsToFloat(0x1BB0AA78 ^ 0x253595FF);
        ca = "GL13.GL_TRANSPOSE_PROJECTION_MATRIX";
        Z = "textures/entity/cat/ocelot.png";
        F = "Couldn't parse an expression!";
        Q = Float.intBitsToFloat(0x53AA396 ^ 0xC452A396);
        la = Double.longBitsToDouble(0x165FBC6B9E40EB3DL ^ 0x56139C6B9E40EB3DL);
        v = "split_particle_count";
        s = "gl_caps[EXT_geometry_shader4]";
        Ka = "level.dat_mcr";
        S = Double.longBitsToDouble(0xAE4196302490CBABL ^ 0xEE26B6302490CBABL);
        O = 0xFA6C31FB ^ 0xFA6C3323;
        n = "CONNECTED";
        z = "commands.scoreboard.teams.join.success";
        Ia = "potion.prefix.suave";
        b = "stat.flowerPotted";
        Ja = "ItemActivationAnim";
        ha = Float.intBitsToFloat(0xC88FE4E3 ^ 0x77E98285);
        Da = "Failed to load player data for ";
        q = "GL11.GL_MAP1_TEXTURE_COORD_3";
        D = "\u0421\u043f\u0440\u0430\u0432\u0430 \u0441\u0432\u0435\u0440\u0445\u0443";
    }

    public Hra() {
        Hra a2;
    }
}

