/*
 * Decompiled with CFR 0.152.
 */
public final class Hra {
    public static final String Ma;
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final double la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final double Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final double S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final double t;
    public static final String R;
    public static final float Q;
    public static final double N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final int L;
    public static final String E;
    public static final long m;
    public static final String C;
    public static final String i;
    public static final long M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        c = "tripwire";
        L = 4293315710 /* ZKM Deobf Int */;
        Ga = 180.0F /* ZKM Deobf */;
        h = -0.1599999964237213F /* ZKM Deobf */;
        w = "cookie";
        ga = "Enabled auto read";
        B = "profile-results-";
        k = "wetnessHalflife";
        ba = "followMouse_";
        t = 2.5949095D /* ZKM Deobf */;
        P = "mob.pig.death";
        J = "deathScreen.respawn";
        C = "glass_pink";
        Fa = "Entity ID";
        W = 6400 /* ZKM Deobf Int */;
        Ma = "pardon";
        p = "Error loading specular texture: ";
        Aa = "GL11.GL_PIXEL_MAP_B_TO_B_SIZE";
        u = "overrideWidth:";
        f = "At least two points are needed!";
        fa = "FORCE_UNICODE_FONT";
        X = "GL11.GL_MAP1_GRID_DOMAIN";
        l = "SCREEN";
        i = "Attributes";
        g = 13.5F /* ZKM Deobf */;
        A = "Head.Shape19";
        T = "GL12.GL_TEXTURE_MAX_LOD";
        d = "DEATH";
        m = 0x305723FF366F2D3EL ^ 0x305723FF366F28E2L;
        M = 0x359E89D8A25A654FL ^ 0xCA6176275DA59AB1L;
        x = "pumpkinstem.png";
        R = "options.difficulty";
        I = ", valueDefault: ";
        K = "X-Minecraft-UUID";
        Y = "GRAHAM";
        ja = 110.0F /* ZKM Deobf */;
        a = "Metadata section name cannot be null";
        r = "ofVignette";
        e = 17424 /* ZKM Deobf Int */;
        o = "record_mall";
        j = "Filtering";
        y = "price";
        N = -0.15D /* ZKM Deobf */;
        Ha = 0.12999999523162842D /* ZKM Deobf */;
        U = "the main menu and back to playing, but this may not have worked.";
        V = "Unbalanced quotation: ";
        G = "of.options.BETTER_GRASS";
        E = "stone_quartz_ore";
        H = 0.2602503001689911F /* ZKM Deobf */;
        ca = "GL13.GL_TRANSPOSE_PROJECTION_MATRIX";
        Z = "textures/entity/cat/ocelot.png";
        F = "Couldn't parse an expression!";
        Q = -14.5F /* ZKM Deobf */;
        la = 56.25D /* ZKM Deobf */;
        v = "split_particle_count";
        s = "gl_caps[EXT_geometry_shader4]";
        Ka = "level.dat_mcr";
        S = 185.0D /* ZKM Deobf */;
        O = 728 /* ZKM Deobf Int */;
        n = "CONNECTED";
        z = "commands.scoreboard.teams.join.success";
        Ia = "potion.prefix.suave";
        b = "stat.flowerPotted";
        Ja = "ItemActivationAnim";
        ha = -0.8999999761581421F /* ZKM Deobf */;
        Da = "Failed to load player data for ";
        q = "GL11.GL_MAP1_TEXTURE_COORD_3";
        D = "\u0421\u043f\u0440\u0430\u0432\u0430 \u0441\u0432\u0435\u0440\u0445\u0443";
    }

    public Hra() {
        Hra a2;
    }
}

