/*
 * Decompiled with CFR 0.152.
 */
public final class hTa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final int ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final double fa;
    public static final String Ka;
    public static final double Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        W = "Back.5a";
        t = "This method should only be called for matching effects!";
        Q = "Towards negative X";
        Ga = 5013401 /* ZKM Deobf Int */;
        l = "shaders/post/blur.json";
        Fa = "channel_";
        w = 3.299999952316284F /* ZKM Deobf */;
        x = "\u0421\u0442\u0440\u0435\u043b\u044b";
        m = "Chunk file at ";
        c = -1.2216999530792236F /* ZKM Deobf */;
        r = "commands.scoreboard.players.test.failed";
        j = "villager/smith";
        n = "ARROWS";
        b = "green_glazed_terracotta";
        s = "GL11.GL_RGBA16";
        F = "broken aspect ratio and not an animation";
        h = "TOO_FAR_AWAY";
        p = "ENDER_SIGNAL";
        e = "of.options.shaders.packNone";
        V = "bambooDoor";
        ja = "double_plant_paeonia_bottom";
        o = 0.28125F /* ZKM Deobf */;
        X = 337 /* ZKM Deobf Int */;
        ga = 20255 /* ZKM Deobf Int */;
        Ha = "test/test.png";
        a = "32";
        q = "of.options.details";
        B = "COLORVAL_NOT_SET";
        N = "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0001\u0002\u0001\u0003\u0001";
        Ia = "assets/minecraft/models/block/diorite.json";
        f = "Teams";
        fa = 134.0D /* ZKM Deobf */;
        Z = "FEET";
        U = 3184 /* ZKM Deobf Int */;
        ca = 425 /* ZKM Deobf Int */;
        L = "GL15.GL_COLOR_ARRAY_BUFFER_BINDING";
        H = "commands.worldborder.get.success";
        z = 4294965296 /* ZKM Deobf Int */;
        M = "0 & 1 & !2 & !3 & 0+6";
        la = "preview";
        Ka = "mob.rabbit.death";
        k = "up_x";
        I = "key.back";
        Da = "NeSCLT";
        R = "reload";
        Ja = 6409 /* ZKM Deobf Int */;
        J = "Unsupported version";
        G = "SCALEANIM";
        v = 0.33161258697509766F /* ZKM Deobf */;
        E = "USHORT";
        T = "red_nether_brick";
        u = "uuid_";
        S = "GL11.GL_TRIANGLE_STRIP";
        O = "Body.Shape9";
        Y = 33901 /* ZKM Deobf Int */;
        g = ",y:";
        K = "arrowKnockback";
        D = "twinkle";
        y = "of.options.shaders.RENDER_RES_MUL";
        A = 723 /* ZKM Deobf Int */;
        d = "north";
        Aa = 456.0D /* ZKM Deobf */;
        ha = "inGround";
        P = 61445 /* ZKM Deobf Int */;
        i = "random.splash";
        C = "endHand";
    }

    public hTa_1() {
        hTa_1 a2;
    }
}

