/*
 * Decompiled with CFR 0.152.
 */
public final class IPa {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final double Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final float S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final float z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final double s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        n = "ofDynamicLights";
        Q = "FLIP_EAST";
        Ka = "Invalid program: ";
        g = "+4";
        D = "STREAM_CHAT_ENABLED";
        N = 10.440000534057617F /* ZKM Deobf */;
        b = 2898 /* ZKM Deobf Int */;
        P = "components";
        F = "GL11.GL_3D";
        m = "\u00a77\u00a75\u00a7o%txp%";
        Ga = "calcite";
        z = 0.42553192377090454F /* ZKM Deobf */;
        f = "deadFireCoralBlock";
        J = "Colormap";
        t = "The received string length is longer than maximum allowed (";
        x = 4294961296 /* ZKM Deobf Int */;
        c = "FLLeg.FLL2";
        la = "; // Shader option ";
        Z = "CHISELED";
        B = 10753 /* ZKM Deobf Int */;
        T = 33872 /* ZKM Deobf Int */;
        A = "noHurtCam:";
        r = 16711935 /* ZKM Deobf Int */;
        j = "dig.";
        Fa = "i";
        k = "sounds";
        S = 0.7599999904632568F /* ZKM Deobf */;
        X = "GL11.GL_RGB10";
        Da = "assets/minecraft/models/block/quartz_ore.json";
        I = "encrypt";
        Ja = "chat";
        ja = "ROTATE";
        K = "copperTrapdoor";
        fa = 0.9750000238418579F /* ZKM Deobf */;
        ga = "red_concrete";
        H = "bookshelf";
        W = "_";
        y = "srccolor";
        R = "gui/emotes/plus.png";
        Y = "GL11.GL_INVERT";
        Aa = "][generator_version]";
        h = "glass_gray";
        d = "commands.setblock.notFound";
        L = 16262179 /* ZKM Deobf Int */;
        O = "free";
        v = "mob.horse.land";
        a = "GL12.GL_UNSIGNED_INT_2_10_10_10_REV";
        E = "GL11.GL_PIXEL_MAP_I_TO_G_SIZE";
        ca = "scaleYvalCase_";
        V = "right_pants_leg";
        e = " is";
        G = "GL11.GL_TEXTURE_2D";
        u = "Body.Shape27";
        w = "Back.7b";
        Ia = "stained_glass_pane";
        l = 1020 /* ZKM Deobf Int */;
        C = "glass_pane_top_lime";
        p = "inFire";
        o = 1000000 /* ZKM Deobf Int */;
        M = "hermite";
        q = "blockstates/";
        s = 0.41999998688697815D /* ZKM Deobf */;
        Ha = 0.9100000262260437D /* ZKM Deobf */;
        U = 1540 /* ZKM Deobf Int */;
        i = "worldTime";
    }

    public IPa() {
        IPa a2;
    }
}

