/*
 * Decompiled with CFR 0.152.
 */
public final class iPa_1 {
    public static final float Fa;
    public static final String Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final int E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        w = "Texture being stitched together";
        R = "GL11.GL_VIEWPORT";
        O = "Deep Ocean";
        b = "mob.spider.death";
        j = "RED";
        r = "commands.clear.testing";
        Z = "of.options.LAGOMETER";
        V = Double.longBitsToDouble(0xC4E4EA59C35224D3L ^ 0xFB372CFE2CCF96FEL);
        x = "Level generator options";
        H = "&e/cam show <all:";
        ja = "fpslimit_wait";
        i = "useGlint";
        M = "eImage9Slice_";
        v = "SPELL";
        f = "/\\* GAUX4FORMAT:RGB16 \\*/.*";
        E = 0x14E93BF6 ^ 0x14E93A7F;
        L = Float.intBitsToFloat(0x3317E469 ^ 0x7095E469);
        Aa = "Block being collided with";
        Ja = "BedrockModel{";
        z = "PROGRESS_BAR";
        F = "realisticCollision";
        P = "Unable to start LAN server detection: ";
        l = 0x88D51CF0 ^ 0x88D580AD;
        g = "Shape6";
        Y = Float.intBitsToFloat(0xFADF183 ^ 0xB322ADAA);
        U = "GL11.GL_LOGIC_OP_MODE";
        y = "diamond_hoe";
        D = "options.chat.opacity";
        X = "GL13.GL_COMPRESSED_LUMINANCE_ALPHA";
        p = 0xC4A52764 ^ 0xC4052874;
        N = "commands.players.usage";
        Q = ", gui3d: ";
        Da = "nextBlockEntity";
        c = Double.longBitsToDouble(0xADC62F94A73BA565L ^ 0x92A64DD975CA0C99L);
        la = Float.intBitsToFloat(0x56D1542C ^ 0xEB491CBA);
        e = "textures/body/exowings_red.png";
        Ka = "ofCustomSky:";
        ca = 0xEDEB1D38 ^ 0xEDEB1DB3;
        K = 0x9D3E197D ^ 0x9D5C926A;
        S = "Error parsing animation keyframe value for model '";
        J = "CHAT";
        n = "potion.resistance";
        t = "\u0410\u043d\u0438\u043c\u0430\u0446\u0438\u044f \u0446\u0432\u0435\u0442\u0430 \u0442\u0435\u043a\u0441\u0442\u0430: ";
        B = "!0 & 1 & !2 & !3 & 1+6";
        Ga = "blockbuster:particle_collision_appearance";
        Ia = "facing=east,half=top,shape=outer_left";
        W = "\u0000\n\u0000\u0001\u0001\n\n\u0000\u0001\u0000\u0001\u0208\u0002$\u0003\u1007\u0000\u0004\u1007\u0001\u0005\u1001\u0002\u0006\u1001\u0003\u0007\u1001\u0004\b\u1007\u0005\t\u1007\u0006\n\u100c\u0007";
        h = "Checking entity block collision";
        T = "textures/pet/mushroom_nether_green.png";
        A = "angleXvalCase_";
        u = "geometry.unknown";
        d = Float.intBitsToFloat(0xE8237E94 ^ 0xD7DCD080);
        G = "sounds.json";
        fa = "mangroveStairs";
        Fa = Float.intBitsToFloat(0xD73DC15D ^ 0x69D32FAD);
        I = "right.Shape28";
        o = "cobbleWall";
        C = 0x53B16B50 ^ 0x53B1EB54;
        m = 0xBD4E3F80 ^ 0xBD4E2685;
        q = "chest_minecart";
        s = "GUARDIAN";
        ga = "TerrainPopulated";
        a = "chiseled_deepslate";
        k = "Left.Shape42123";
        Ha = 0x4DC17E7B ^ 0x4DC1FB7C;
    }

    public iPa_1() {
        iPa_1 a2;
    }
}

