/*
 * Decompiled with CFR 0.152.
 */
public final class Iqa {
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final long a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final int M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Iqa() {
        Iqa a2;
    }

    static {
        e = "\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 \u043c\u044b\u0448\u044c,";
        C = 5011004 /* ZKM Deobf Int */;
        N = 34974 /* ZKM Deobf Int */;
        i = "useNativeTransport:";
        Y = "tomato";
        la = 34011 /* ZKM Deobf Int */;
        Ja = "left_sleeve";
        F = "Block";
        T = "dye_red";
        a = 0x6E093A006E614093L ^ 0x6E093A1E9F371B46L;
        H = "minecart";
        Ha = "GAME";
        R = 10984804 /* ZKM Deobf Int */;
        S = 4866583 /* ZKM Deobf Int */;
        X = "GL11.GL_TEXTURE_GREEN_SIZE";
        p = "tile.oreRedstone.name";
        r = "eImage_";
        ga = "exposedCopperGrate";
        U = "format_version";
        Ga = "item.fireworks.flight";
        B = "widthval_";
        z = "potion.prefix.milky";
        h = "Piece1.Shape4";
        P = "Right28";
        o = "ANTIALIASING";
        l = "Old Chunk Storage is no longer supported.";
        Da = "achievement.openInventory";
        A = "PIG_ZOMBIE";
        q = "Invalid array length ";
        O = "pumpkin_seeds";
        D = -13.899999618530273F /* ZKM Deobf */;
        V = "protocol";
        y = 32881 /* ZKM Deobf Int */;
        I = "Quite honestly, I wouldn't worry myself about that.";
        v = "RightLeg.Shape11";
        u = "GameType";
        Aa = 36053 /* ZKM Deobf Int */;
        W = "S";
        m = 330 /* ZKM Deobf Int */;
        s = "Colors";
        ca = "GL Caps";
        Fa = "NORTH_WEST";
        f = "}";
        E = 6976549 /* ZKM Deobf Int */;
        t = 226 /* ZKM Deobf Int */;
        J = "GET";
        G = 2.130000114440918F /* ZKM Deobf */;
        M = 110 /* ZKM Deobf Int */;
        Q = "MC_GL_RENDERER_QUADRO";
        fa = "torch";
        Ka = "projectile_protection";
        g = "Creebet";
        c = ", burnSpeed=";
        n = "facing_camera_mode";
        Z = "of.options.VOID_PARTICLES";
        d = "mangrove_leaves";
        ba = "TOGGLE";
        L = "cprev(";
        K = "deepslate_brick_slab";
        b = "mob.cat.meow";
        Ia = "GL14.GL_TEXTURE_LOD_BIAS";
        j = "tripWire(?:Source)?";
        k = 35002 /* ZKM Deobf Int */;
        ja = "knockback";
        w = "compass";
        ha = 5926017 /* ZKM Deobf Int */;
        x = 3480 /* ZKM Deobf Int */;
    }
}

