/*
 * Decompiled with CFR 0.152.
 */
public final class Ira {
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final long X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final float p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final double K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        R = "black_concrete";
        ga = 85 /* ZKM Deobf Int */;
        j = 6000.0F /* ZKM Deobf */;
        O = "minecraft:blocks/soul_sand";
        Fa = "GLITCHY";
        K = 1e-06D /* ZKM Deobf */;
        ha = "Using GL 1.3 multitexturing.\n";
        y = "commands.scoreboard.players.reset.success";
        g = "Children";
        T = "ag";
        Y = "textures/body/exowings_yellow.png";
        Z = "exposedCutCopperStairs";
        t = 5125 /* ZKM Deobf Int */;
        Ga = "master";
        b = "_hovered.png";
        V = "punch";
        Da = "hatchetIron";
        a = "ofAnimatedPortal:";
        ba = "unknown entity with id ";
        x = "GL15.GL_BUFFER_MAPPED";
        Ka = 31.0F /* ZKM Deobf */;
        la = "chatVisibility:";
        L = "mob.horse.death";
        v = ", source: ";
        s = 32865 /* ZKM Deobf Int */;
        Ma = "emitter_transform_xz";
        A = 515 /* ZKM Deobf Int */;
        Q = "Error in class '";
        p = 0.20100000500679016F /* ZKM Deobf */;
        d = 1.5F /* ZKM Deobf */;
        f = "SHIFT_RIGHT";
        X = 0x358832B20042DA37L ^ 0xCA77CD4DFFBDD5C8L;
        z = 35003 /* ZKM Deobf Int */;
        D = "GL12.GL_SINGLE_COLOR";
        h = "Cold Taiga";
        m = 1003 /* ZKM Deobf Int */;
        B = 3571 /* ZKM Deobf Int */;
        Ia = 3355562 /* ZKM Deobf Int */;
        P = "Failed to open OpenAL device ";
        u = "Start capturing";
        W = 34176 /* ZKM Deobf Int */;
        k = "black_concrete_powder";
        o = "chatScale";
        i = 1030 /* ZKM Deobf Int */;
        w = "key.hotbar.1";
        Ja = 5578058 /* ZKM Deobf Int */;
        c = "d/";
        E = "MOVE";
        Ha = " draw buffers = ";
        ca = "textures/blocks/";
        ja = "available";
        e = "\" not found";
        J = "lerprotate";
        I = "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
        N = "leggingsGold";
        fa = "weathered_cut_copper_slab_double";
        n = "pillar";
        G = "Pinging...";
        H = "textures/entity/skeleton/skeleton.png";
        M = "trigger";
        F = "The End";
        Aa = "mineWood";
        r = "light_blue";
        C = "Left.Shape71123";
        q = "commands.worldborder.center.usage";
        S = "Scale";
        l = 2265 /* ZKM Deobf Int */;
        U = "CTRL";
    }

    public Ira() {
        Ira a2;
    }
}

