/*
 * Decompiled with CFR 0.152.
 */
public final class iSa {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final long R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final double D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final double k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        H = "item.fireworksCharge.";
        d = ", muted=";
        ja = "Left.Shape4123";
        a = "OpenGL";
        la = "textures/pet/spinner_green.png";
        S = "east=false,north=true,south=true,up=true,west=true";
        s = "GL11.GL_AUTO_NORMAL";
        g = "int";
        v = "beeNest";
        V = 4118 /* ZKM Deobf Int */;
        j = "leftStick.leftHorn";
        b = "SQUARE_TOP_LEFT";
        I = "GL11.GL_FOG_START";
        Ja = 0.5899999737739563F /* ZKM Deobf */;
        f = "' for item: '";
        r = 35715 /* ZKM Deobf Int */;
        T = "mc";
        P = 0.2D /* ZKM Deobf */;
        L = "Shape25123";
        G = "world-light-forced";
        Q = "Converting map!";
        Aa = "selectServer.direct";
        N = "Get available samples count";
        Ha = "Ice Plains";
        h = "pivot";
        w = "-- Head --\n";
        u = -2.1333000659942627F /* ZKM Deobf */;
        p = "scalexvalCase_";
        m = "options.gamma";
        fa = 0.05999999865889549F /* ZKM Deobf */;
        y = "Command to be executed";
        M = "useDungeons";
        k = -50.0D /* ZKM Deobf */;
        Y = "random";
        Z = "Grumm";
        o = "Not all emotes loaded";
        X = "saturation";
        R = 0x33DE2A0AA879815FL ^ 0x33DE2A0AA887D175L;
        A = "commands.testforblock.failed.nbt";
        K = "rangeChecks";
        O = "sunos";
        W = "l";
        Da = "assets/minecraft/models/block/orientable_vertical.json";
        E = "composite7";
        c = "exposedCopperTrapdoor";
        Ga = "iron_leggings";
        n = "gbuffers_block";
        e = 1792 /* ZKM Deobf Int */;
        t = "text.boss";
        q = "optionsof.txt";
        F = 30025 /* ZKM Deobf Int */;
        ga = "cherry_log";
        Ka = "small";
        B = "waxed_oxidized_copper_grate";
        x = 43 /* ZKM Deobf Int */;
        l = "Wasteland";
        C = "Y_ROT";
        U = "blocks/destroy_stage_9";
        z = "[Shaders] Profile already parsed: ";
        i = "\u0412\u0435\u0440\u0442\u0438\u043a\u0430\u043b\u044c\u043d\u043e";
        ca = 92 /* ZKM Deobf Int */;
        D = 142.0D /* ZKM Deobf */;
        J = "Biome \"";
    }

    public iSa() {
        iSa a2;
    }
}

