/*
 * Decompiled with CFR 0.152.
 */
public final class ISa_1 {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final double ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final int V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final double u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final float a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public ISa_1() {
        ISa_1 a2;
    }

    static {
        L = "Control";
        ga = "verdant";
        I = 0xFEFBA255 ^ 0xFEFB2964;
        T = "streamKbps:";
        A = "jungle_planks";
        h = 0xEE3B2F0B ^ 0xEECD9D0A;
        n = "[Shaders] Error: ";
        p = "createWorld.customize.flat.addLayer";
        m = "mipmap";
        W = "GL15.GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING";
        j = "potion.healthBoost";
        J = "variable.emitter_random_1";
        Q = 0x8E7325DD ^ 0x8E732EDA;
        ja = "Loading ";
        G = "Scaled non power of 2: ";
        q = "Tall";
        l = 0x109E5436 ^ 0x109E5F8E;
        O = "ingotIron";
        z = 0x9628663 ^ 0x9628B30;
        X = "grid";
        r = "container.dropper";
        f = "stat.depleted";
        t = "block/fence_inventory";
        w = "level.dat";
        F = "Entity being loaded";
        E = 0xBCC72D12 ^ 0xBCC72D34;
        P = " [pos ";
        K = "Head.11";
        Da = "armorTextColor:";
        i = "EASE_IN_OUT_QUART";
        U = "depthNoiseScaleX";
        H = "textures/entity/horse/horse_markings_whitefield.png";
        la = "textures/blocks/destroy_stage_4.png";
        Ga = "max_health";
        N = 0xBE539E4B ^ 0xBE539355;
        g = "Head.33";
        x = "HALF_VERTICAL";
        B = "blockDiamond";
        M = "tracker";
        R = "\u0000\f\u0000\u0001\u0001\f\f\u0000\u0001\u0000\u0001\u021a\u0002\u100f\u0000\u0003\u100c\u0002\u0004\u100c\u0003\u0005\u1007\u0004\u0006\u1006\u0005\u0007\u1006\u0006\b\u1009\u0007\t\u1208\u0001\n\u100c\b\u000b\u1004\t\f\u1004\n";
        Aa = "ladder";
        o = "pb";
        D = "R3_G3_B2";
        v = "brown_wool";
        a = Float.intBitsToFloat(0x5184DBB ^ 0x47AC4DBB);
        d = "Entity being checked for collision";
        ca = Double.longBitsToDouble(0xE91D4BC83C2EC479L ^ 0xD6E98704F0E208B4L);
        k = "shadow endRender";
        V = 0xDBA7AFA8 ^ 0xDBA7AEDA;
        S = 0x60405447 ^ 0x6040554D;
        Z = "onClick_";
        y = "Couldn't read statistics file ";
        u = Double.longBitsToDouble(0xF314FC419566B102L ^ 0xCCF4F470B38FC9D7L);
        c = "textures/blocks/destroy_stage_9.png";
        Ka = "stoneSlab2";
        C = "paleOakDoor";
        s = "warpedNylium";
        fa = "java.vm.vendor";
        e = "Couldn't save chunk";
        Ha = "ACACIA_SAPLING";
        b = "o";
        Ja = "GL13.GL_TEXTURE3";
        Y = 0xA093073D ^ 0xA09305C8;
    }
}

