/*
 * Decompiled with CFR 0.152.
 */
public final class isa_2 {
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final float z;
    public static final float X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final double K;
    public static final String H;
    public static final String c;
    public static final long B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public isa_2() {
        isa_2 a2;
    }

    static {
        v = "connection";
        a = "Nearest-Nearest";
        Ja = "Entity's Rider";
        J = "Invalid spawn egg color: ";
        e = "follow-speed";
        H = "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u001b\u0002\u1009\u0000";
        ca = " more ...";
        l = "mob.wolf.bark";
        M = 0xF3F77800 ^ 0xF3F77530;
        j = "textureCase_";
        Aa = Float.intBitsToFloat(0x185EB432 ^ 0x592278FF);
        s = 0x3DFB48B0 ^ 0x3DFB499B;
        x = "BestShortSideFit";
        h = "commands.scoreboard.teams.list.player.empty";
        L = "Ambiguous shader option: ";
        X = Float.intBitsToFloat(0x9F4A76A0 ^ 0x206F95F4);
        P = "removing player mount";
        I = "y_";
        c = "LEASH_HITCH";
        Y = " to be a Boolean, was ";
        b = "Head.12";
        V = "mount.onboard";
        K = Double.longBitsToDouble(0xDDB7F92A0670E476L ^ 0xE259417BEDF5FACEL);
        la = 0x633321A2 ^ 0x63332354;
        Q = 0x9C1447E6 ^ 0x9CD58627;
        k = "align_";
        ga = "Invalid shapeless recipe: unknown type ";
        U = "LINE_STRIP";
        Da = "Mipped Cutout";
        w = "mob.sheep.say";
        u = "Movement Speed";
        A = " bytes extra whilst reading packet ";
        f = "NETHERITE";
        T = "SET_ROW";
        m = 0x47841630 ^ 0x47841D56;
        B = 0x5DB071C6FD3F503DL ^ 0x5DB071C6FD3F57EEL;
        y = "q.mouse_x";
        t = "party cleared";
        Ka = "piston";
        ja = "commands.trigger.invalidPlayer";
        E = "moveSlowdown";
        Z = "chiseled_quartz_block";
        d = "LEFT_CLICK_BLOCK";
        r = "Pet.Ribbon5";
        N = "mob.guardian.flop";
        g = "~~NULL~~";
        i = "chat.copy";
        Ha = "potatoes_stage_[0-3]";
        q = "VCR: muted {}";
        n = "Piece1.Shape3";
        C = "eyeAltitude";
        R = 0x78B932DF ^ 0x78B9B681;
        F = "assets/minecraft/models/block/gold_ore.json";
        G = "texturepackicon";
        S = "coal_ore";
        O = "streamFps";
        fa = "other_head";
        p = "EASTER";
        o = 0xA5F4E84 ^ 0xA5F4C03;
        z = Float.intBitsToFloat(0x95C29588 ^ 0x545E9588);
        W = Float.intBitsToFloat(0x6EB60F0D ^ 0x513AC3C0);
        D = "R8_SNORM";
        Ga = "gbufferPreviousModelView";
    }
}

