/*
 * Decompiled with CFR 0.152.
 */
public final class ITa {
    public static final long Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final double a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final int E;
    public static final int m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        r = "texture_helmet";
        N = "STRIPE_RIGHT";
        i = 2822 /* ZKM Deobf Int */;
        Ga = "Left.Shape51123";
        M = "Piece1.Shape52";
        fa = "Resource location being registered";
        p = "Kicked by an operator.";
        ga = "stat.beaconInteraction";
        I = "SEND_AUDIO_END";
        la = "description";
        J = "commands.seed.usage";
        m = 32901 /* ZKM Deobf Int */;
        Ha = "effectTextAnimation:";
        O = "Shape65123";
        ja = "Natural Textures: Parsing default configuration \"";
        y = "peaceful";
        Aa = "timeSync";
        q = "NOT_POSSIBLE_HERE";
        k = "mob.cat.purreow";
        W = "dynamic-item-";
        R = "porkchopCooked";
        U = "SENSITIVITY";
        Q = "CREDITS";
        K = "NeCSR";
        S = "textures/entity/iron_golem.png";
        Ia = 0xFD6719A860E4CFA4L ^ 0xFD6719A860E4CFDBL;
        A = 29 /* ZKM Deobf Int */;
        j = ":0";
        Da = 133 /* ZKM Deobf Int */;
        ca = "][hardcore]";
        f = "WALK";
        t = " != ";
        b = "textures/entity/banner/";
        d = "demo.help.later";
        c = 819 /* ZKM Deobf Int */;
        u = "Rare";
        e = "startAt_";
        E = 26 /* ZKM Deobf Int */;
        B = "glowstone_dust";
        s = "#define MC_VERSION ";
        o = "EDIT3D";
        g = "fogMode";
        L = -0.012500000186264515F /* ZKM Deobf */;
        C = " cannot receive string arguments!";
        x = "wall_banner";
        n = 9987 /* ZKM Deobf Int */;
        Ja = "give";
        H = "of.general.smart";
        h = 2963 /* ZKM Deobf Int */;
        P = -0.0D /* ZKM Deobf */;
        F = "center";
        Z = "faces";
        Y = ", texture=";
        D = "Using GL 1.3 texture combiners.\n";
        l = "separation";
        v = 0.06981319934129715F /* ZKM Deobf */;
        a = 40.0D /* ZKM Deobf */;
        V = 62 /* ZKM Deobf Int */;
        X = "monsterStoneEgg";
        Ka = "Could not set level chunk biomes, array length is ";
        T = "mcpatcher/";
        w = "items/";
        z = "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208";
        G = "potion.prefix.sparkling";
    }

    public ITa() {
        ITa a2;
    }
}

