/*
 * Decompiled with CFR 0.152.
 */
public final class Jpa {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final int Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final float y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        h = "Left.Shape12123";
        W = "cobbledDeepslateWall";
        z = 0x5ABAA708 ^ 0x5ABAA550;
        n = 0xE3DE44D0 ^ 0xE3DE45F7;
        X = 0x17631A46 ^ 0x17631147;
        L = "commands.time.query";
        S = "DYNAMIC_FOV";
        H = "gamma:";
        fa = "CQ";
        Z = 0x7EF55E11 ^ 0x7EF55D47;
        R = ".properties";
        ga = "avg_tick_ms";
        Aa = "Steps";
        m = "game.tnt.primed";
        i = Float.intBitsToFloat(0x44F44219 ^ 0x85BCB7DA);
        I = "bamboo_mosaic_slab_double";
        a = "smooth_diorite";
        f = "ADD_PLAYER";
        Ga = 0x4AF7CCD9 ^ 0x4AF7CE75;
        U = "bookcase";
        c = "commands.generic.double.tooBig";
        M = "streamBytesPerPixel";
        J = "potion.confusion";
        Q = "mob.rabbit.hurt";
        Fa = "Java Virtual Machine not being allocated enough";
        N = "waxedExposedCutCopper";
        p = "Unsupported mob type for DoorInteractGoal";
        b = "unreferenced value";
        O = "THIRD PARTY";
        Ha = 0xC088C0A3 ^ 0xC088C035;
        w = "chiseled";
        V = "([A-Z])([0-9]+)(.*)";
        q = "display";
        ja = "Failed Start with id ";
        x = "\u0000\u0003\u0001\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1006\u0000\u00024\u0000\u00034\u0000";
        D = "potion.invisibility";
        T = "commands.scoreboard.teams.list.player.count";
        P = "Mipmaps not possible (power of 2 dimensions needed), texture: ";
        l = "Invalid player action";
        t = "Connection";
        C = "IN_AIR";
        s = 0xC9E4FE66 ^ 0xC9E4FFC0;
        r = Float.intBitsToFloat(0xD271BB00 ^ 0x960BBB00);
        k = "join";
        Y = " is a slab and should have 1 or 3 textures, got ";
        j = "rearfoot.main";
        e = "polished_deepslate_slab";
        la = "GL11.GL_AUX3";
        v = "EASY";
        ca = "FLAME";
        Ka = "#line ";
        g = Float.intBitsToFloat(0x9ACD6DB7 ^ 0x24AE3E4F);
        u = "^https?://(?:textures\\.minecraft\\.net/texture/[a-zA-Z0-9_.-]+|mc\\.vimeworld.(?:ru|com)/launcher/(?:skins|cloaks)/[%a-zA-Z0-9\u0410-\u042f\u0430-\u044f_.-]+\\.png(?:\\?.+)?)$";
        E = "Screen render details";
        Da = "impelYOnTop_";
        Ia = "resinBrickSlab";
        y = Float.intBitsToFloat(0xA6CEB3BA ^ 0x99EEB3BA);
        F = "farmsunflower.animation";
        G = "CRACKED_STONEBRICK";
        A = "soundCategory_";
        Ja = 0x402B3669 ^ 0x402B340A;
        o = "FLLeg.Shape34";
        d = 0xF6C13E91 ^ 0xF708FD91;
        K = 0xDDD40AE3 ^ 0xDDD47FA0;
        B = Float.intBitsToFloat(0x7DF21F83 ^ 0x41D1C889);
    }

    public Jpa() {
        Jpa a2;
    }
}

