/*
 * Decompiled with CFR 0.152.
 */
public final class Jpa {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final int Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final float y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        h = "Left.Shape12123";
        W = "cobbledDeepslateWall";
        z = 600 /* ZKM Deobf Int */;
        n = 295 /* ZKM Deobf Int */;
        X = 2817 /* ZKM Deobf Int */;
        L = "commands.time.query";
        S = "DYNAMIC_FOV";
        H = "gamma:";
        fa = "CQ";
        Z = 854 /* ZKM Deobf Int */;
        R = ".properties";
        ga = "avg_tick_ms";
        Aa = "Steps";
        m = "game.tnt.primed";
        i = -12.5600004196167F /* ZKM Deobf */;
        I = "bamboo_mosaic_slab_double";
        a = "smooth_diorite";
        f = "ADD_PLAYER";
        Ga = 684 /* ZKM Deobf Int */;
        U = "bookcase";
        c = "commands.generic.double.tooBig";
        M = "streamBytesPerPixel";
        J = "potion.confusion";
        Q = "mob.rabbit.hurt";
        Fa = "Java Virtual Machine not being allocated enough";
        N = "waxedExposedCutCopper";
        p = "Unsupported mob type for DoorInteractGoal";
        b = "unreferenced value";
        O = "THIRD PARTY";
        Ha = 150 /* ZKM Deobf Int */;
        w = "chiseled";
        V = "([A-Z])([0-9]+)(.*)";
        q = "display";
        ja = "Failed Start with id ";
        x = "\u0000\u0003\u0001\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1006\u0000\u00024\u0000\u00034\u0000";
        D = "potion.invisibility";
        T = "commands.scoreboard.teams.list.player.count";
        P = "Mipmaps not possible (power of 2 dimensions needed), texture: ";
        l = "Invalid player action";
        t = "Connection";
        C = "IN_AIR";
        s = 422 /* ZKM Deobf Int */;
        r = 1000.0F /* ZKM Deobf */;
        k = "join";
        Y = " is a slab and should have 1 or 3 textures, got ";
        j = "rearfoot.main";
        e = "polished_deepslate_slab";
        la = "GL11.GL_AUX3";
        v = "EASY";
        ca = "FLAME";
        Ka = "#line ";
        g = -0.22200000286102295F /* ZKM Deobf */;
        u = "^https?://(?:textures\\.minecraft\\.net/texture/[a-zA-Z0-9_.-]+|mc\\.vimeworld.(?:ru|com)/launcher/(?:skins|cloaks)/[%a-zA-Z0-9\u0410-\u042f\u0430-\u044f_.-]+\\.png(?:\\?.+)?)$";
        E = "Screen render details";
        Da = "impelYOnTop_";
        Ia = "resinBrickSlab";
        y = 0.625F /* ZKM Deobf */;
        F = "farmsunflower.animation";
        G = "CRACKED_STONEBRICK";
        A = "soundCategory_";
        Ja = 611 /* ZKM Deobf Int */;
        o = "FLLeg.Shape34";
        d = 29999872 /* ZKM Deobf Int */;
        K = 30019 /* ZKM Deobf Int */;
        B = 0.009999999776482582F /* ZKM Deobf */;
    }

    public Jpa() {
        Jpa a2;
    }
}

