/*
 * Decompiled with CFR 0.152.
 */
public final class JPa_1 {
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final double ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final float N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final float w;
    public static final int W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public JPa_1() {
        JPa_1 a2;
    }

    static {
        S = "cherrySlab";
        t = "ADD2DGROUP";
        C = "gifSpeed_";
        W = 0x3BC207AF ^ 0x3BC202AF;
        Ha = "ender_pearl";
        Da = "double_wooden_slab";
        n = "Left.Shape14123";
        Ka = "pardon-ip";
        M = 0x95387D11 ^ 0x9538FC2A;
        j = "PERFORMANCE";
        Ja = "commands.whitelist.add.success";
        k = "stone_monster_egg";
        ba = "C:\\Dev\\minecraft-1.8.8\\src\\minecraft\\assets\\minidot\\models\\body";
        b = Float.intBitsToFloat(0x44D8988B ^ 0x85F90111);
        Fa = "reducedDebugInfo:";
        v = "GL13.GL_SAMPLE_COVERAGE";
        F = "right.Shape45";
        V = "font_";
        J = "helm:";
        Q = 0x3E992B3F ^ 0x3E99B768;
        Y = 0x5E1EE45E ^ 0x5E1E6F12;
        w = Float.intBitsToFloat(0x6A29626E ^ 0xD4E06D97);
        d = "Right3";
        l = "minecraft:items/barrier";
        Ga = "cauldron_(?:bottom|inner|side|top)";
        H = "left_side";
        B = 0x99FAF386 ^ 0x99F00CD6;
        q = 0x6171CE7 ^ 0x61780BB;
        L = "Level storage version";
        m = "item.banner.";
        T = Float.intBitsToFloat(0x72916B20 ^ 0x4D950D46);
        e = "FT sd";
        s = 0x99635398 ^ 0x665868A3;
        ga = 0x6599CBE5 ^ 0x6599CB9E;
        D = "generatorOptions";
        N = Float.intBitsToFloat(0xADF2248C ^ 0xADF2248C);
        g = "textures/entity/wolf/wolf.png";
        Z = " CPS";
        r = "menu.quit";
        ca = "Color";
        I = "GL13.GL_SUBTRACT";
        P = "Couldn't load trade info";
        U = "GL14.GL_FUNC_SUBTRACT";
        Ia = "q.entity.pitch";
        f = "0 & !1 & 2 & 3 & 2+6";
        x = "[ \t]*const[ \t]*bool[ \t]*(shadowtex1Mipmap)[ \t]*=[ \t]*true[ \t]*;.*";
        G = "os.name";
        c = Float.intBitsToFloat(0xB6E38663 ^ 0x8821093F);
        u = "CHEST";
        fa = "OUT: [{}:{}] {}";
        ha = Float.intBitsToFloat(0x24FAD1C9 ^ 0x6449E2FA);
        A = "GL11.GL_MODELVIEW_STACK_DEPTH";
        O = "Motion";
        z = "Reset";
        a = "Generating mipmaps for frame";
        o = "stat.cakeSlicesEaten";
        h = "&a\u0420\u0435\u0436\u0438\u043c \u0441\u0433\u043b\u0430\u0436\u0438\u0432\u0430\u043d\u0438\u044f \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d \u043d\u0430 &f";
        ja = Double.longBitsToDouble(0x544F77EB7429AED9L ^ 0x6BBC44D8471A9DEAL);
        Aa = "hide-exp";
        p = "missingno";
        E = 0xAF3B445F ^ 0xAF2B445F;
        y = "brown";
        R = "mob.guardian.elder.hit";
        K = "mossybrick";
        la = 0x6B11F894 ^ 0x6B11EC92;
        X = "arthropods";
        i = "0.85, 0, 0.15, 1";
    }
}

