/*
 * Decompiled with CFR 0.152.
 */
public final class JPa_1 {
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final double ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final float N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final float w;
    public static final int W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public JPa_1() {
        JPa_1 a2;
    }

    static {
        S = "cherrySlab";
        t = "ADD2DGROUP";
        C = "gifSpeed_";
        W = 1280 /* ZKM Deobf Int */;
        Ha = "ender_pearl";
        Da = "double_wooden_slab";
        n = "Left.Shape14123";
        Ka = "pardon-ip";
        M = 33083 /* ZKM Deobf Int */;
        j = "PERFORMANCE";
        Ja = "commands.whitelist.add.success";
        k = "stone_monster_egg";
        ba = "C:\\Dev\\minecraft-1.8.8\\src\\minecraft\\assets\\minidot\\models\\body";
        b = -10.100000381469727F /* ZKM Deobf */;
        Fa = "reducedDebugInfo:";
        v = "GL13.GL_SAMPLE_COVERAGE";
        F = "right.Shape45";
        V = "font_";
        J = "helm:";
        Q = 40023 /* ZKM Deobf Int */;
        Y = 35660 /* ZKM Deobf Int */;
        w = -0.3926999866962433F /* ZKM Deobf */;
        d = "Right3";
        l = "minecraft:items/barrier";
        Ga = "cauldron_(?:bottom|inner|side|top)";
        H = "left_side";
        B = 720720 /* ZKM Deobf Int */;
        q = 40028 /* ZKM Deobf Int */;
        L = "Level storage version";
        m = "item.banner.";
        T = 0.5171874761581421F /* ZKM Deobf */;
        e = "FT sd";
        s = 4282071867 /* ZKM Deobf Int */;
        ga = 123 /* ZKM Deobf Int */;
        D = "generatorOptions";
        N = 0.0F /* ZKM Deobf */;
        g = "textures/entity/wolf/wolf.png";
        Z = " CPS";
        r = "menu.quit";
        ca = "Color";
        I = "GL13.GL_SUBTRACT";
        P = "Couldn't load trade info";
        U = "GL14.GL_FUNC_SUBTRACT";
        Ia = "q.entity.pitch";
        f = "0 & !1 & 2 & 3 & 2+6";
        x = "[ \t]*const[ \t]*bool[ \t]*(shadowtex1Mipmap)[ \t]*=[ \t]*true[ \t]*;.*";
        G = "os.name";
        c = 0.3799999952316284F /* ZKM Deobf */;
        u = "CHEST";
        fa = "OUT: [{}:{}] {}";
        ha = 5.599999904632568F /* ZKM Deobf */;
        A = "GL11.GL_MODELVIEW_STACK_DEPTH";
        O = "Motion";
        z = "Reset";
        a = "Generating mipmaps for frame";
        o = "stat.cakeSlicesEaten";
        h = "&a\u0420\u0435\u0436\u0438\u043c \u0441\u0433\u043b\u0430\u0436\u0438\u0432\u0430\u043d\u0438\u044f \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d \u043d\u0430 &f";
        ja = 1.2D /* ZKM Deobf */;
        Aa = "hide-exp";
        p = "missingno";
        E = 1048576 /* ZKM Deobf Int */;
        y = "brown";
        R = "mob.guardian.elder.hit";
        K = "mossybrick";
        la = 5126 /* ZKM Deobf Int */;
        X = "arthropods";
        i = "0.85, 0, 0.15, 1";
    }
}

