/*
 * Decompiled with CFR 0.152.
 */
public final class Jra {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final double la;
    public static final String ga;
    public static final double Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final float S;
    public static final float Z;
    public static final int Y;
    public static final String r;
    public static final long V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final float n;
    public static final float s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final int K;
    public static final float H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final double m;
    public static final String C;
    public static final int i;
    public static final double M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final double A;
    public static final String I;

    static {
        E = "Rain time: %d (now: %b), thunder time: %d (now: %b)";
        p = "pale_oak_fence";
        G = "easeInBack";
        s = Float.intBitsToFloat(0x101CE4E1 ^ 0x2A587F47);
        Ja = Float.intBitsToFloat(0xD00A788 ^ 0x32DFC179);
        la = Double.longBitsToDouble(0x5B676FCDA872395FL ^ 0x1BC765B57C8FCAE9L);
        l = "C:\\Dev\\minecraft-1.8.8\\src\\minecraft\\assets\\minidot\\models\\pet";
        Da = Double.longBitsToDouble(0x75768F36A46FFFAL ^ 0x38D9D0A281C3E142L);
        Ka = "upper_slab";
        Y = 0x8407D2C4 ^ 0x84075A3B;
        Ma = " found, only 0/90/180/270 allowed";
        B = "Invalid dimension ID: ";
        H = Float.intBitsToFloat(0x2C282D3D ^ 0xEC86A1DA);
        q = "respiration";
        ba = "math.abs";
        V = 0x85D054962523AB87L ^ 0x85D054962523AB8FL;
        m = Double.longBitsToDouble(0x98194AAB063F01D3L ^ 0xA7E54AAB063F01D3L);
        u = "clayHardened";
        f = "\u0000";
        n = Float.intBitsToFloat(0xD6452EB2 ^ 0x16E05E16);
        S = Float.intBitsToFloat(0xF8073ABA ^ 0xB8173ABA);
        Q = "MINECART_MOB_SPAWNER";
        t = 0x4AD26041 ^ 0x4AD26095;
        k = "Non-integrated multiplayer server";
        v = "Float";
        Z = Float.intBitsToFloat(0x746BDF1C ^ 0x4B22D0C7);
        D = "GL11.GL_POINT_TOKEN";
        fa = "milk";
        Ca = "GL11.GL_DRAW_PIXEL_TOKEN";
        N = "sunAngle";
        o = 0xBB5D260D ^ 0xBB5D2661;
        ia = "srcalpha";
        b = "setCamera";
        L = "glasspane.properties";
        R = "GL11.GL_LIGHT2";
        C = "GL13.GL_SAMPLES";
        y = "key.playerlist";
        ca = "lvl";
        j = "ao:";
        P = "M8";
        T = Float.intBitsToFloat(0x6E3C98B ^ 0x4C54D28B);
        I = "easeInOutElastic";
        W = "Left.Shape23123";
        ja = "tubeCoralBlock";
        F = "variable.emitter_random_2";
        z = " x";
        x = "CLEAR2D";
        r = "waterlily";
        h = "colortex3";
        Fa = 0x82AD092D ^ 0x7D52F6DA;
        Ha = "VC: Player start talking '{}'";
        M = Double.longBitsToDouble(0xA61DA15BBB58AA64L ^ 0x99910D538A7E431DL);
        g = "GL13.GL_TRANSPOSE_COLOR_MATRIX";
        U = 0x50489609 ^ 0x50488581;
        d = "waxed_oxidized_cut_copper_slab_double";
        a = "createWorld.customize.custom.biomeScaleOffset";
        Ga = "Unknown format: ";
        ha = "UPDATE_GAME_MODE";
        Ia = "Unknown connect: ";
        i = 0x1509FE9A ^ 0x15097672;
        K = 0x8885E496 ^ 0x8885E634;
        w = "num_particles";
        c = 0x25F3C8C8 ^ 0x25F3DAC0;
        A = Double.longBitsToDouble(0x2C99C2E8229222F3L ^ 0x13705B71BB0BBB69L);
        X = "Server closed";
        J = "Container mask texture ";
        O = "crimson_stairs";
        ga = "redstoneLight";
        Ea = "shaders/post/notch.json";
        e = "commands.stats.block.set.usage";
        Aa = "Skipped: ";
    }

    public Jra() {
        Jra a2;
    }
}

