/*
 * Decompiled with CFR 0.152.
 */
public final class Jra {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final double la;
    public static final String ga;
    public static final double Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final float S;
    public static final float Z;
    public static final int Y;
    public static final String r;
    public static final long V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final float n;
    public static final float s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final int K;
    public static final float H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final double m;
    public static final String C;
    public static final int i;
    public static final double M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final double A;
    public static final String I;

    static {
        E = "Rain time: %d (now: %b), thunder time: %d (now: %b)";
        p = "pale_oak_fence";
        G = "easeInBack";
        s = 0.000750000006519258F /* ZKM Deobf */;
        Ja = 1.7453290224075317F /* ZKM Deobf */;
        la = 2053.236D /* ZKM Deobf */;
        l = "C:\\Dev\\minecraft-1.8.8\\src\\minecraft\\assets\\minidot\\models\\pet";
        Da = 0.015D /* ZKM Deobf */;
        Ka = "upper_slab";
        Y = 35071 /* ZKM Deobf Int */;
        Ma = " found, only 0/90/180/270 allowed";
        B = "Invalid dimension ID: ";
        H = -5.454699993133545F /* ZKM Deobf */;
        q = "respiration";
        ba = "math.abs";
        V = 0x85D054962523AB87L ^ 0x85D054962523AB8FL;
        m = 1.75D /* ZKM Deobf */;
        u = "clayHardened";
        f = "\u0000";
        n = -5.170000076293945F /* ZKM Deobf */;
        S = 2.25F /* ZKM Deobf */;
        Q = "MINECART_MOB_SPAWNER";
        t = 212 /* ZKM Deobf Int */;
        k = "Non-integrated multiplayer server";
        v = "Float";
        Z = 0.7853981852531433F /* ZKM Deobf */;
        D = "GL11.GL_POINT_TOKEN";
        fa = "milk";
        Ca = "GL11.GL_DRAW_PIXEL_TOKEN";
        N = "sunAngle";
        o = 108 /* ZKM Deobf Int */;
        ia = "srcalpha";
        b = "setCamera";
        L = "glasspane.properties";
        R = "GL11.GL_LIGHT2";
        C = "GL13.GL_SAMPLES";
        y = "key.playerlist";
        ca = "lvl";
        j = "ao:";
        P = "M8";
        T = 6000000.0F /* ZKM Deobf */;
        I = "easeInOutElastic";
        W = "Left.Shape23123";
        ja = "tubeCoralBlock";
        F = "variable.emitter_random_2";
        z = " x";
        x = "CLEAR2D";
        r = "waterlily";
        h = "colortex3";
        Fa = 4294967287 /* ZKM Deobf Int */;
        Ha = "VC: Player start talking '{}'";
        M = 0.014D /* ZKM Deobf */;
        g = "GL13.GL_TRANSPOSE_COLOR_MATRIX";
        U = 5000 /* ZKM Deobf Int */;
        d = "waxed_oxidized_cut_copper_slab_double";
        a = "createWorld.customize.custom.biomeScaleOffset";
        Ga = "Unknown format: ";
        ha = "UPDATE_GAME_MODE";
        Ia = "Unknown connect: ";
        i = 35048 /* ZKM Deobf Int */;
        K = 674 /* ZKM Deobf Int */;
        w = "num_particles";
        c = 4616 /* ZKM Deobf Int */;
        A = 0.8D /* ZKM Deobf */;
        X = "Server closed";
        J = "Container mask texture ";
        O = "crimson_stairs";
        ga = "redstoneLight";
        Ea = "shaders/post/notch.json";
        e = "commands.stats.block.set.usage";
        Aa = "Skipped: ";
    }

    public Jra() {
        Jra a2;
    }
}

