/*
 * Decompiled with CFR 0.152.
 */
public final class jRa_1 {
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final long Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final int X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final double T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final float x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final float J;
    public static final String A;
    public static final float I;

    public jRa_1() {
        jRa_1 a2;
    }

    static {
        ca = "Head.24";
        P = "SMOOTHBRICK";
        w = "minecraft:music.game.end";
        s = "JungleEdge";
        H = "ofFullscreenMode";
        i = "Right.Right56";
        Y = "GL14.GL_SECONDARY_COLOR_ARRAY_POINTER";
        f = "GL11.GL_DEPTH_COMPONENT";
        e = 20349 /* ZKM Deobf Int */;
        ha = "square_bottom_left";
        v = 102 /* ZKM Deobf Int */;
        Aa = "nether_star";
        k = 396 /* ZKM Deobf Int */;
        q = 49 /* ZKM Deobf Int */;
        j = "TileID";
        z = "math.acos";
        L = "multiplayer";
        M = ", type: ";
        la = "ArmorItem";
        Ia = "key.sprint";
        E = "attribute [_a-zA-Z0-9]+ mc_Entity.*";
        p = "curly_border";
        I = -15.899999618530273F /* ZKM Deobf */;
        Ma = "ooooOo";
        V = 2912 /* ZKM Deobf Int */;
        g = 3008 /* ZKM Deobf Int */;
        h = "glass_pane_top_light_blue";
        O = "NeSC";
        Da = 0x5254DBE41F72498BL ^ 0x5254DBE41F7240A2L;
        X = 75 /* ZKM Deobf Int */;
        Fa = "STOP_SNEAKING";
        C = 40072 /* ZKM Deobf Int */;
        Ha = ", tcache: ";
        R = "Vendor:  ";
        fa = "gaux1";
        Ja = "jungle_stairs";
        n = "yyyy-MM-dd HH:mm:ss Z";
        K = "GL14.GL_SECONDARY_COLOR_ARRAY_STRIDE";
        d = "GL13.GL_TEXTURE22";
        m = 516 /* ZKM Deobf Int */;
        t = "instant_damage";
        Ca = "Invalid interval: ";
        J = 1.3333333730697632F /* ZKM Deobf */;
        y = 32914 /* ZKM Deobf Int */;
        b = "GL11.GL_4_BYTES";
        Ka = "flower_houstonia";
        ia = "commands.scoreboard.teams.add.success";
        u = 3837580 /* ZKM Deobf Int */;
        c = "Right40";
        a = "DARK_AQUA";
        Q = "item.skull.player.name";
        N = "Entity is already tracked!";
        o = "GL11.GL_FOG_DENSITY";
        ba = 705 /* ZKM Deobf Int */;
        Z = "GL11.GL_COLOR";
        G = "_s";
        D = "TRIANGLE_BOTTOM";
        ja = 1013904223 /* ZKM Deobf Int */;
        ga = 823 /* ZKM Deobf Int */;
        l = 673 /* ZKM Deobf Int */;
        r = "textures/entity/armorstand/wood.png";
        S = "#-";
        A = "commands.worldborder.usage";
        B = "seeds_melon";
        Ga = "mob.chickenplop";
        F = "Pet.Ribbon1";
        W = "SPAWNER";
        x = 12.899999618530273F /* ZKM Deobf */;
        U = "Right.Right5";
        T = 2.70158D /* ZKM Deobf */;
    }
}

