/*
 * Decompiled with CFR 0.152.
 */
public final class jRa_1 {
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final long Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final int X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final double T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final float x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final float J;
    public static final String A;
    public static final float I;

    public jRa_1() {
        jRa_1 a2;
    }

    static {
        ca = "Head.24";
        P = "SMOOTHBRICK";
        w = "minecraft:music.game.end";
        s = "JungleEdge";
        H = "ofFullscreenMode";
        i = "Right.Right56";
        Y = "GL14.GL_SECONDARY_COLOR_ARRAY_POINTER";
        f = "GL11.GL_DEPTH_COMPONENT";
        e = 0x938D1FD3 ^ 0x938D50AE;
        ha = "square_bottom_left";
        v = 0x28228C03 ^ 0x28228C65;
        Aa = "nether_star";
        k = 0x8AF7EF8C ^ 0x8AF7EE00;
        q = 0xC6BE7886 ^ 0xC6BE78B7;
        j = "TileID";
        z = "math.acos";
        L = "multiplayer";
        M = ", type: ";
        la = "ArmorItem";
        Ia = "key.sprint";
        E = "attribute [_a-zA-Z0-9]+ mc_Entity.*";
        p = "curly_border";
        I = Float.intBitsToFloat(0x72AB2F5C ^ 0xB3D5493A);
        Ma = "ooooOo";
        V = 0x9B3DF083 ^ 0x9B3DFBE3;
        g = 0xCF88D858 ^ 0xCF88D398;
        h = "glass_pane_top_light_blue";
        O = "NeSC";
        Da = 0x5254DBE41F72498BL ^ 0x5254DBE41F7240A2L;
        X = 0x4FF64E0D ^ 0x4FF64E46;
        Fa = "STOP_SNEAKING";
        C = 0x3A687347 ^ 0x3A68EFCF;
        Ha = ", tcache: ";
        R = "Vendor:  ";
        fa = "gaux1";
        Ja = "jungle_stairs";
        n = "yyyy-MM-dd HH:mm:ss Z";
        K = "GL14.GL_SECONDARY_COLOR_ARRAY_STRIDE";
        d = "GL13.GL_TEXTURE22";
        m = 0xDD617695 ^ 0xDD617491;
        t = "instant_damage";
        Ca = "Invalid interval: ";
        J = Float.intBitsToFloat(0x27FC0E48 ^ 0x1856A4E3);
        y = 0x83C813E9 ^ 0x83C8937B;
        b = "GL11.GL_4_BYTES";
        Ka = "flower_houstonia";
        ia = "commands.scoreboard.teams.add.success";
        u = 0x23264AA1 ^ 0x231CC42D;
        c = "Right40";
        a = "DARK_AQUA";
        Q = "item.skull.player.name";
        N = "Entity is already tracked!";
        o = "GL11.GL_FOG_DENSITY";
        ba = 0x4B9A9421 ^ 0x4B9A96E0;
        Z = "GL11.GL_COLOR";
        G = "_s";
        D = "TRIANGLE_BOTTOM";
        ja = 0x38FE8354 ^ 0x490700B;
        ga = 0xA3E14EB ^ 0xA3E17DC;
        l = 0xB705E5C4 ^ 0xB705E765;
        r = "textures/entity/armorstand/wood.png";
        S = "#-";
        A = "commands.worldborder.usage";
        B = "seeds_melon";
        Ga = "mob.chickenplop";
        F = "Pet.Ribbon1";
        W = "SPAWNER";
        x = Float.intBitsToFloat(0xD601E916 ^ 0x974F8F70);
        U = "Right.Right5";
        T = Double.longBitsToDouble(0x9836C2ECCD6CF11L ^ 0x4986F0FB354AF7A1L);
    }
}

