/*
 * Decompiled with CFR 0.152.
 */
public final class Jsa {
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final float Da;
    public static final int ca;
    public static final String Ja;
    public static final int ja;
    public static final int Ha;
    public static final int Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final long S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final int K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final double d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Jsa() {
        Jsa a2;
    }

    static {
        x = "GL11.GL_AUX1";
        Ia = "data:image/png;base64,";
        Da = 0.301972895860672F /* ZKM Deobf */;
        d = -300.0D /* ZKM Deobf */;
        n = "stat.generalButton";
        p = "of.options.CHUNK_UPDATES";
        ca = 3221225472 /* ZKM Deobf Int */;
        N = "selectWorld.cheats";
        v = "\u0420\u0430\u0437\u043c\u0435\u0440 \u0442\u0435\u043a\u0441\u0442\u0430: ";
        H = 411 /* ZKM Deobf Int */;
        G = "armorTags:";
        Aa = "Connecting to ";
        a = "FRLeg.Shape37";
        k = "math.ln";
        P = "CustomSky properties: ";
        K = 9402184 /* ZKM Deobf Int */;
        D = "File: ";
        Q = "ARB_vertex_shader is ";
        i = "Unsigned Byte";
        s = 623 /* ZKM Deobf Int */;
        fa = 32895 /* ZKM Deobf Int */;
        Y = "cmdcam";
        Fa = "endBlockEntities";
        o = -11.0F /* ZKM Deobf */;
        Ha = 3042 /* ZKM Deobf Int */;
        S = 0xEA71FF3655E981ACL ^ 0xEA71FF3655E981A7L;
        z = "invulnerable";
        y = "0.45, 0, 0.55, 1";
        E = "resin_bricks";
        J = "enderman/enderman";
        M = "bedrock-player-pet";
        la = 4026531839 /* ZKM Deobf Int */;
        e = "GL11.GL_BITMAP";
        r = "Shape55123";
        Ja = "(Unknown)";
        w = "Invalid tile ID: ";
        t = "GL11.GL_POINT_SMOOTH_HINT";
        b = "LAND";
        I = "Current Language";
        q = "day";
        c = "CustomItems: ";
        F = "VC: Disconnected";
        L = "offset";
        g = "\u0420\u0430\u0434\u0443\u0433\u0430";
        R = "50% - 10";
        ga = "Pausing channel {}";
        Ga = 4294967200 /* ZKM Deobf Int */;
        U = 388 /* ZKM Deobf Int */;
        T = "commands.stats.failed";
        A = "NaturalTextures: Unknown type: ";
        O = "mob.horse.donkey.hit";
        ja = 690 /* ZKM Deobf Int */;
        u = "blockcrack_";
        Ka = "modifiers_";
        ha = 90 /* ZKM Deobf Int */;
        h = "q.hotbar_slot";
        f = "SYRINGA";
        V = 136.0D /* ZKM Deobf */;
        l = "ofAutoSaveTicks";
        C = "keyTextBold:";
        X = "magenta_stained_glass_pane";
        Z = 1.2999999523162842F /* ZKM Deobf */;
        m = "Facing: %s (%s) (%.1f / %.1f)";
        B = "textures/entity/horse/horse_black.png";
        ba = "valueCase_";
        W = "resourcePacks:";
        j = "cherryTrapdoor";
    }
}

