/*
 * Decompiled with CFR 0.152.
 */
public final class Jsa {
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final float Da;
    public static final int ca;
    public static final String Ja;
    public static final int ja;
    public static final int Ha;
    public static final int Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final long S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final int K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final double d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Jsa() {
        Jsa a2;
    }

    static {
        x = "GL11.GL_AUX1";
        Ia = "data:image/png;base64,";
        Da = Float.intBitsToFloat(0x9E807EC1 ^ 0xA01AE2F0);
        d = Double.longBitsToDouble(0xD7741D91E0E50EDFL ^ 0x1706DD91E0E50EDFL);
        n = "stat.generalButton";
        p = "of.options.CHUNK_UPDATES";
        ca = 0xFB573960 ^ 0x3B573960;
        N = "selectWorld.cheats";
        v = "\u0420\u0430\u0437\u043c\u0435\u0440 \u0442\u0435\u043a\u0441\u0442\u0430: ";
        H = 0x30169207 ^ 0x3016939C;
        G = "armorTags:";
        Aa = "Connecting to ";
        a = "FRLeg.Shape37";
        k = "math.ln";
        P = "CustomSky properties: ";
        K = 0xF5E22F9D ^ 0xF56D58D5;
        D = "File: ";
        Q = "ARB_vertex_shader is ";
        i = "Unsigned Byte";
        s = 0xB0BA10E2 ^ 0xB0BA128D;
        fa = 0x478C6145 ^ 0x478CE13A;
        Y = "cmdcam";
        Fa = "endBlockEntities";
        o = Float.intBitsToFloat(0xE3B8ECD5 ^ 0x2288ECD5);
        Ha = 0x6D80E3F5 ^ 0x6D80E817;
        S = 0xEA71FF3655E981ACL ^ 0xEA71FF3655E981A7L;
        z = "invulnerable";
        y = "0.45, 0, 0.55, 1";
        E = "resin_bricks";
        J = "enderman/enderman";
        M = "bedrock-player-pet";
        la = 0x13206E89 ^ 0xFCDF9176;
        e = "GL11.GL_BITMAP";
        r = "Shape55123";
        Ja = "(Unknown)";
        w = "Invalid tile ID: ";
        t = "GL11.GL_POINT_SMOOTH_HINT";
        b = "LAND";
        I = "Current Language";
        q = "day";
        c = "CustomItems: ";
        F = "VC: Disconnected";
        L = "offset";
        g = "\u0420\u0430\u0434\u0443\u0433\u0430";
        R = "50% - 10";
        ga = "Pausing channel {}";
        Ga = 0x2928434E ^ 0xD6D7BCEE;
        U = 0xAD4C98D8 ^ 0xAD4C995C;
        T = "commands.stats.failed";
        A = "NaturalTextures: Unknown type: ";
        O = "mob.horse.donkey.hit";
        ja = 0x163CE268 ^ 0x163CE0DA;
        u = "blockcrack_";
        Ka = "modifiers_";
        ha = 0x1D86C429 ^ 0x1D86C473;
        h = "q.hotbar_slot";
        f = "SYRINGA";
        V = Double.longBitsToDouble(0x6B88B00E3E726132L ^ 0x2BE9B00E3E726132L);
        l = "ofAutoSaveTicks";
        C = "keyTextBold:";
        X = "magenta_stained_glass_pane";
        Z = Float.intBitsToFloat(0xC9E53328 ^ 0xF643554E);
        m = "Facing: %s (%s) (%.1f / %.1f)";
        B = "textures/entity/horse/horse_black.png";
        ba = "valueCase_";
        W = "resourcePacks:";
        j = "cherryTrapdoor";
    }
}

