/*
 * Decompiled with CFR 0.152.
 */
public final class KPa {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final long E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final double I;

    public KPa() {
        KPa a2;
    }

    static {
        Ja = "Invalid statistic in ";
        j = "rightLeg.rightLeg";
        t = "enable";
        C = ".png";
        e = " ticks";
        S = "Stitching texture atlas";
        u = "weights.";
        J = "block/cube_all";
        P = "catmullrom";
        b = "Rendering chunk";
        M = "Natural Textures: Texture not found: \"";
        q = "item.brewingStand.name";
        L = "particle_effect";
        s = "SkyLight";
        la = "facing=north,half=top,shape=outer_left";
        v = 4286611584 /* ZKM Deobf Int */;
        U = "gaux4";
        H = "OPEN_URL";
        X = "commands.summon.tagError";
        w = 0.9900000095367432F /* ZKM Deobf */;
        ga = "effectEnabled:";
        i = -21.649999618530273F /* ZKM Deobf */;
        y = 2.0D /* ZKM Deobf */;
        V = "leggingsDiamond";
        a = "BLL2";
        l = "MISS";
        ja = "VC Output -> {}";
        ca = 631 /* ZKM Deobf Int */;
        Ga = "andesiteSlab";
        Z = "Quad: ";
        p = "arm_action";
        n = "\u0425\u043e\u0442\u043a\u0435\u0439 \u0434\u043b\u044f \u0430\u043a\u0442\u0438\u0432\u0430\u0446\u0438\u0438";
        N = "Explosion";
        W = "Ocean";
        h = "OS";
        d = -5.539999961853027F /* ZKM Deobf */;
        r = "GL13.GL_SAMPLE_COVERAGE_VALUE";
        Q = "Function '";
        I = -0.5D /* ZKM Deobf */;
        A = "ViStart";
        Y = 652 /* ZKM Deobf Int */;
        k = 1.0000009536743164F /* ZKM Deobf */;
        Ka = "slider_track";
        Ha = 16440917 /* ZKM Deobf Int */;
        o = "9";
        Ia = "biomeDepthOffset";
        fa = 6912 /* ZKM Deobf Int */;
        G = "Ticking connection";
        T = "deathScreen.title.hardcore";
        E = 0xD31E5D952D4A476CL ^ 0xD31E5D952D4A4348L;
        g = 268 /* ZKM Deobf Int */;
        f = "windows-1251";
        O = "MODEL";
        K = "ACCEPTED";
        R = "R11F_G11F_B10F";
        c = "disarmed";
        m = "q.entity.headYaw";
        D = "VC: In audio cs ";
        z = "textures/pet/spinner_yellow.png";
        B = "selector";
        Da = "GL11.GL_ZOOM_X";
        F = "/shaders/world";
        Aa = 0.00390625F /* ZKM Deobf */;
        x = "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0438\u0442\u044c\u0441\u044f";
    }
}

