/*
 * Decompiled with CFR 0.152.
 */
public final class kPa_1 {
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final float Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final float S;
    public static final double Z;
    public static final String Y;
    public static final double r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final float y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final float I;

    static {
        f = "progress_";
        s = "GL11.GL_FEEDBACK_BUFFER_TYPE";
        G = "enumConstantDirectory";
        Ha = -90.0F /* ZKM Deobf */;
        R = "Eyes";
        H = "mob.endermen.idle";
        a = "furnace_minecart";
        u = "AttributeModifiers";
        v = "CanPickUpLoot";
        Ja = "minecraft:chest";
        j = "item.canPlace";
        r = 214.0D /* ZKM Deobf */;
        Aa = "chiseled_copper";
        n = "CAMERAPATH";
        C = "square_bottom_right";
        N = "protocolVersion_";
        B = "GL11.GL_INDEX_SHIFT";
        w = "commands.scoreboard.objectives.add.displayTooLong";
        ga = "Left.Shape8123";
        m = "display_update";
        Y = "textures/gui/container/anvil.png";
        z = "Rendering Particle";
        g = "extra";
        L = "stat.workbenchInteraction";
        ca = "selectWorld.conversion";
        Ga = -11.399999618530273F /* ZKM Deobf */;
        Z = 6.283185307179586D /* ZKM Deobf */;
        K = "Could not post to ";
        Ka = "rx";
        e = "gl_caps[ARB_uniform_buffer_object]";
        fa = "assets/minecraft/models/block/gravel.json";
        ja = "Trail";
        P = "FLLeg";
        l = "FAILED_DOWNLOAD";
        V = 33309 /* ZKM Deobf Int */;
        p = "Wolf";
        x = "~";
        W = 0.3499999940395355F /* ZKM Deobf */;
        M = "\u0421\u0432\u0435\u0440\u043d\u0443\u0442\u044c";
        D = "getSeedBytes";
        o = "foodExhaustionLevel";
        q = " was kicked for floating too long!";
        y = 7.5F /* ZKM Deobf */;
        A = "textures/entity/rabbit/toast.png";
        Da = "options.guiScale.x7";
        Q = "dynamicHandLight";
        F = "Tried to read NBT tag with too high complexity, depth > 512";
        t = "textures/gui/presets/madness.png";
        J = "Java Version";
        O = "instantSpell";
        U = 34070 /* ZKM Deobf Int */;
        X = "monster_egg";
        S = 9.0F /* ZKM Deobf */;
        i = "GL13.GL_COMBINE_ALPHA";
        d = 93.75F /* ZKM Deobf */;
        k = "5a";
        E = "cherry_trapdoor";
        b = 34015 /* ZKM Deobf Int */;
        I = -4.699999809265137F /* ZKM Deobf */;
        c = "move";
        T = "GL11.GL_MAX_TEXTURE_STACK_DEPTH";
        h = "Ribbon1";
    }

    public kPa_1() {
        kPa_1 a2;
    }
}

