/*
 * Decompiled with CFR 0.152.
 */
public final class kpa_2 {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final float Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final int Ga;
    public static final float fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final double z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final double u;
    public static final String O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final double e;
    public static final float G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final double g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        C = "villager/priest";
        q = "BLLeg.BLL1";
        p = "GL11.GL_TEXTURE_COORD_ARRAY";
        N = "token_";
        b = "goldMinHeight";
        s = "entity_id";
        R = ",ban=";
        D = "Ticking screen";
        v = "assets/minecraft/blockstates/netherrack.json";
        Ka = 0x8F803596 ^ 0x8F808E16;
        ga = "ThreadedAnvilChunkStorage ({}): All chunks are saved";
        Aa = "Music";
        la = "LOOK_AT_ENTITY_ID";
        ba = "Shape22123";
        i = 0xC36744A6 ^ 0xC3674DA7;
        a = "of.message.java64Bit";
        u = Double.longBitsToDouble(0x78D7DDB8DD9E2B0EL ^ 0xC71E44217D9E2B0EL);
        o = "armorDurabilityBar";
        Ia = Float.intBitsToFloat(0x7B396AFF ^ 0x3B445DB3);
        A = "icon-";
        e = Double.longBitsToDouble(0xB549AC86DFA24FA0L ^ 0xF543AC86DFA24FA0L);
        Ga = 0x30127ED2 ^ 0x30127F67;
        n = "\u041f\u0430\u0442\u0438";
        l = Double.longBitsToDouble(0x5081E2542224B5EAL ^ 0x1003C2542224B5EAL);
        k = "centerDepthSmooth";
        H = "Entity's Exact location";
        V = "muttonCooked";
        M = "of.message.shaders.aa1";
        c = "Couldn't save stats";
        w = 0x92090C2E ^ 0x6DF6F3D5;
        Ja = "whitelist.json";
        X = "deepslate_redstone_ore";
        O = "iron_horse_armor";
        m = "\u0000\u0005\u0001\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\u0007\u00037\u0000\u0004<\u0000\u0005?\u0000";
        U = 0x4B0553A4 ^ 0x4B055E15;
        T = "TexMinFilS";
        L = "BODY_FRONT_BOTTOM";
        f = "gl_caps[EXT_packed_depth_stencil]";
        d = "GL11.GL_COLOR_ARRAY_STRIDE";
        W = "\u041f\u0440\u0430\u0432\u043e";
        K = "name_";
        fa = Float.intBitsToFloat(0x23429C83 ^ 0xE35B0519);
        y = "entity.Cat.name";
        Ha = 0x93981096 ^ 0x9398100E;
        x = "cherry_log_stripped";
        g = Double.longBitsToDouble(0xC98AF58CD24DE0BDL ^ 0x99EF58CD24DE0BDL);
        S = "GL11.GL_INDEX_ARRAY_STRIDE";
        ha = "Reset model renderers";
        Y = "texts/credits.txt";
        G = Float.intBitsToFloat(0xECF64E09 ^ 0x2DA64E09);
        z = Double.longBitsToDouble(0x974D9EEAEF599A3AL ^ 0xA8E326BB04DC8482L);
        F = "green_stained_hardened_clay";
        E = "Shape40";
        I = "glass_light_blue";
        Z = "gui/rounding/round_border_";
        h = "commands.stats.cleared";
        Da = "commands.kill.successful";
        P = "GL11.GL_LUMINANCE_ALPHA";
        Fa = "TAB";
        r = 0x745280B3 ^ 0x745282CF;
        Q = "%[^%]+%";
        J = 0x810A0736 ^ 0x810A0435;
        j = "commands.difficulty.success";
        ja = "ZoGa";
        ca = "Shape3";
        B = "options.stream.systemVolume";
        t = Double.longBitsToDouble(0xA5447293F0621224L ^ 0xE5247293F0621224L);
    }

    public kpa_2() {
        kpa_2 a2;
    }
}

