/*
 * Decompiled with CFR 0.152.
 */
public final class kpa_2 {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final float Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final int Ga;
    public static final float fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final double z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final double u;
    public static final String O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final double e;
    public static final float G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final double g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        C = "villager/priest";
        q = "BLLeg.BLL1";
        p = "GL11.GL_TEXTURE_COORD_ARRAY";
        N = "token_";
        b = "goldMinHeight";
        s = "entity_id";
        R = ",ban=";
        D = "Ticking screen";
        v = "assets/minecraft/blockstates/netherrack.json";
        Ka = 48000 /* ZKM Deobf Int */;
        ga = "ThreadedAnvilChunkStorage ({}): All chunks are saved";
        Aa = "Music";
        la = "LOOK_AT_ENTITY_ID";
        ba = "Shape22123";
        i = 2305 /* ZKM Deobf Int */;
        a = "of.message.java64Bit";
        u = -0.20000000298023224D /* ZKM Deobf */;
        o = "armorDurabilityBar";
        Ia = 3.9565000534057617F /* ZKM Deobf */;
        A = "icon-";
        e = 3.25D /* ZKM Deobf */;
        Ga = 437 /* ZKM Deobf Int */;
        n = "\u041f\u0430\u0442\u0438";
        l = 580.0D /* ZKM Deobf */;
        k = "centerDepthSmooth";
        H = "Entity's Exact location";
        V = "muttonCooked";
        M = "of.message.shaders.aa1";
        c = "Couldn't save stats";
        w = 4294967291 /* ZKM Deobf Int */;
        Ja = "whitelist.json";
        X = "deepslate_redstone_ore";
        O = "iron_horse_armor";
        m = "\u0000\u0005\u0001\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\u0007\u00037\u0000\u0004<\u0000\u0005?\u0000";
        U = 3505 /* ZKM Deobf Int */;
        T = "TexMinFilS";
        L = "BODY_FRONT_BOTTOM";
        f = "gl_caps[EXT_packed_depth_stencil]";
        d = "GL11.GL_COLOR_ARRAY_STRIDE";
        W = "\u041f\u0440\u0430\u0432\u043e";
        K = "name_";
        fa = -2.4000000953674316F /* ZKM Deobf */;
        y = "entity.Cat.name";
        Ha = 152 /* ZKM Deobf Int */;
        x = "cherry_log_stripped";
        g = -5.0D /* ZKM Deobf */;
        S = "GL11.GL_INDEX_ARRAY_STRIDE";
        ha = "Reset model renderers";
        Y = "texts/credits.txt";
        G = -13.0F /* ZKM Deobf */;
        z = 0.06D /* ZKM Deobf */;
        F = "green_stained_hardened_clay";
        E = "Shape40";
        I = "glass_light_blue";
        Z = "gui/rounding/round_border_";
        h = "commands.stats.cleared";
        Da = "commands.kill.successful";
        P = "GL11.GL_LUMINANCE_ALPHA";
        Fa = "TAB";
        r = 636 /* ZKM Deobf Int */;
        Q = "%[^%]+%";
        J = 771 /* ZKM Deobf Int */;
        j = "commands.difficulty.success";
        ja = "ZoGa";
        ca = "Shape3";
        B = "options.stream.systemVolume";
        t = 128.0D /* ZKM Deobf */;
    }

    public kpa_2() {
        kpa_2 a2;
    }
}

