/*
 * Decompiled with CFR 0.152.
 */
public final class kra {
    public static final String da;
    public static final String Ba;
    public static final float aa;
    public static final int ea;
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final float ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final int ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final long ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final long G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final long J;
    public static final int A;
    public static final String I;

    public kra() {
        kra a2;
    }

    static {
        I = "Body.Shape24";
        J = 0x4550F03BBFFF535BL ^ 0x4550F03BBFFF5D4BL;
        E = "cobblestone_slab";
        Z = "Objectives";
        N = 3.0299999713897705F /* ZKM Deobf */;
        ba = 0.9599999785423279F /* ZKM Deobf */;
        R = "LOADING";
        ea = 32902 /* ZKM Deobf Int */;
        P = 2262 /* ZKM Deobf Int */;
        i = "tuffBrickStairs";
        O = "textures/body/mercy_wings_purple.png";
        y = "newSize must be >= 0: ";
        Ca = ".desc";
        Ja = "damageMask";
        aa = -0.1745329201221466F /* ZKM Deobf */;
        b = "\u0414\u043b\u044f \u043f\u0440\u0438\u043c\u0435\u043d\u0435\u043d\u0438\u044f \u044d\u0442\u043e\u0433\u043e \u0442\u0438\u043f\u0430 \u043f\u0435\u0440\u0441\u043e\u043d\u0430\u043b\u0438\u0437\u0430\u0446\u0438\u0438";
        j = 835 /* ZKM Deobf Int */;
        S = 20386 /* ZKM Deobf Int */;
        Q = "effectTextSize";
        Y = "FOOTSTEP";
        o = 675 /* ZKM Deobf Int */;
        Ea = "off";
        e = "BORDER";
        Fa = "generic";
        d = "graniteWall";
        v = "resource_";
        m = 399 /* ZKM Deobf Int */;
        K = "GL11.GL_TEXTURE_BINDING_1D";
        Ga = "out_of_game";
        Ma = "orange_wool";
        q = 16387 /* ZKM Deobf Int */;
        n = "Silverfish";
        M = "assets/minidot/itemmeta/";
        B = "pale_oak_door";
        u = "GL11.GL_GREEN_SCALE";
        H = "removeWhenParentRemove_";
        la = 32823 /* ZKM Deobf Int */;
        Da = 20211 /* ZKM Deobf Int */;
        ja = 0xC198E3403FD9D461L ^ 0xC198E3403FD93E01L;
        c = "SlotColorRadius";
        Ha = "mob.horse.skeleton.hit";
        g = "wet";
        l = "mobSpellAmbient";
        s = "Eye brightness halflife: ";
        p = "animators";
        L = 4100 /* ZKM Deobf Int */;
        t = "GL11.GL_UNSIGNED_INT";
        h = "\u041a\u043d\u043e\u043f\u043a\u0430 \u043f\u0440\u044b\u0436\u043a\u0430";
        a = 702 /* ZKM Deobf Int */;
        r = "gameMode.";
        Ia = "onARail";
        Ka = 2421182544 /* ZKM Deobf Int */;
        D = "Aztec";
        T = -1.72787606716156F /* ZKM Deobf */;
        W = "GL15.GL_BUFFER_USAGE";
        x = "banlist";
        z = "VC: disconnect";
        ha = "mipmapLevels";
        F = 1615855616 /* ZKM Deobf Int */;
        X = 32696 /* ZKM Deobf Int */;
        f = "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0004\u0003\u0002\u0004\n";
        da = "Block location";
        ca = "SPACER";
        C = "Skipping Piece with id ";
        w = 252 /* ZKM Deobf Int */;
        G = 0x300CE468459AD76EL ^ 0x300CE468459AD76CL;
        ia = "\u042d\u0444\u0444\u0435\u043a\u0442\u044b \u0437\u0435\u043b\u0438\u0439";
        Ba = "Unsupported mob for MoveThroughVillageGoal";
        ga = 3169 /* ZKM Deobf Int */;
        A = 13274213 /* ZKM Deobf Int */;
        Aa = "granite";
        fa = "scaleX_";
        V = "Time: ";
        k = "d";
        U = 41 /* ZKM Deobf Int */;
    }
}

