/*
 * Decompiled with CFR 0.152.
 */
public final class kTa {
    public static final int ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final double Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final double v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final double B;
    public static final int d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final float J;
    public static final String A;
    public static final String I;

    public kTa() {
        kTa a2;
    }

    static {
        f = "Could not load snowflake particles";
        M = "gl_caps[ARB_texture_buffer_object]";
        C = "saddle";
        H = "VC: Unexpected error in VoiceChatClient handlePing";
        P = Double.longBitsToDouble(0x6FD007653FC510A2L ^ 0x2F1380E53FC510A2L);
        fa = "assets/minecraft/models/block/sand.json";
        la = "lock";
        Ka = 0xD3EE7C1C ^ 0xD3EE71A8;
        d = 0x425D4121 ^ 0x425D4C7A;
        k = "biomeScaleOffset";
        r = "FIREWORK";
        a = "EASE_IN_SINE";
        w = 0x912CA72E ^ 0x912CBE2C;
        F = "LeftHandSwing";
        c = "leather";
        O = "blocks/destroy_stage_4";
        z = "commands.generic.num.invalid";
        q = "SPACE_EVENLY";
        ga = "chiseled_resin_bricks";
        i = "ambient.weather.rain";
        s = "SmartLeaves: Model is not cube, side: ";
        ca = "Invalid sounds.json";
        K = "yExpr_";
        j = 0x995F8FAD ^ 0x995F8FB9;
        p = "Sunflower Plains";
        B = Double.longBitsToDouble(0x6FB1C5398515F163L ^ 0x5051C5398515F163L);
        A = "mob.blaze.breathe";
        U = "texture.potion_bottle_drinkable";
        Y = 0xB1E5AF5C ^ 0xB1E5AA5F;
        y = "GL11.GL_AUX0";
        G = "NETHER";
        Ga = "GL14.GL_FOG_COORDINATE_ARRAY";
        u = "GL11.GL_DEPTH";
        I = "Teleport to player";
        S = "Failed to read zip file ";
        Z = "right.Shape52";
        Ja = "mipmapLevels:";
        e = "oxidized_copper_trapdoor";
        m = 0xABA33A1B ^ 0xABA3B857;
        b = 0xC9F29F11 ^ 0xC9F26F02;
        R = "2x";
        ha = "[ \t]*const[ \t]*bool[ \t]*(shadowtex1Nearest|shadow1MinMagNearest)[ \t]*=[ \t]*true[ \t]*;.*";
        o = 0x9E6EF4B3 ^ 0x9E6EDDB2;
        l = "commands.compare.tooManyBlocks";
        Q = Double.longBitsToDouble(0x1CA4788AF2AC3A2AL ^ 0xA34A1EEC94CA5C4CL);
        D = "scrollOffsetValCase_";
        Aa = "tag";
        x = "\u4ee8";
        Fa = 0xE46860E6 ^ 0xE468602B;
        g = 0xD517C338 ^ 0xD517C321;
        ba = 0x2451366D ^ 0x24513C6F;
        J = Float.intBitsToFloat(0x53A5EB14 ^ 0x6F50299B);
        E = " frames";
        X = "\\{([^}]{1,2})}";
        N = "gbuffers_textured";
        v = Double.longBitsToDouble(0xA90B298FCB9AE0BAL ^ 0x96EB8A58C1A7901EL);
        Da = "options.fboEnable";
        V = "buildingBlocks";
        L = "gui_";
        t = "filterempty";
        T = 0x3AAF07ED ^ 0x3AAF0755;
        Ha = "orange_stained_glass_pane";
        h = "pendingConnection";
        n = "Failed while reading minidot/emotes/models/{}/{}.json";
        Ia = "Animation ";
        W = "%.2f,%.2f,%.2f - %s";
        ja = "SERVER";
    }
}

