/*
 * Decompiled with CFR 0.152.
 */
public final class kTa {
    public static final int ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final double Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final double v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final double B;
    public static final int d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final float J;
    public static final String A;
    public static final String I;

    public kTa() {
        kTa a2;
    }

    static {
        f = "Could not load snowflake particles";
        M = "gl_caps[ARB_texture_buffer_object]";
        C = "saddle";
        H = "VC: Unexpected error in VoiceChatClient handlePing";
        P = 9999.0D /* ZKM Deobf */;
        fa = "assets/minecraft/models/block/sand.json";
        la = "lock";
        Ka = 3508 /* ZKM Deobf Int */;
        d = 3419 /* ZKM Deobf Int */;
        k = "biomeScaleOffset";
        r = "FIREWORK";
        a = "EASE_IN_SINE";
        w = 6402 /* ZKM Deobf Int */;
        F = "LeftHandSwing";
        c = "leather";
        O = "blocks/destroy_stage_4";
        z = "commands.generic.num.invalid";
        q = "SPACE_EVENLY";
        ga = "chiseled_resin_bricks";
        i = "ambient.weather.rain";
        s = "SmartLeaves: Model is not cube, side: ";
        ca = "Invalid sounds.json";
        K = "yExpr_";
        j = 20 /* ZKM Deobf Int */;
        p = "Sunflower Plains";
        B = 0.5D /* ZKM Deobf */;
        A = "mob.blaze.breathe";
        U = "texture.potion_bottle_drinkable";
        Y = 1283 /* ZKM Deobf Int */;
        y = "GL11.GL_AUX0";
        G = "NETHER";
        Ga = "GL14.GL_FOG_COORDINATE_ARRAY";
        u = "GL11.GL_DEPTH";
        I = "Teleport to player";
        S = "Failed to read zip file ";
        Z = "right.Shape52";
        Ja = "mipmapLevels:";
        e = "oxidized_copper_trapdoor";
        m = 33356 /* ZKM Deobf Int */;
        b = 61459 /* ZKM Deobf Int */;
        R = "2x";
        ha = "[ \t]*const[ \t]*bool[ \t]*(shadowtex1Nearest|shadow1MinMagNearest)[ \t]*=[ \t]*true[ \t]*;.*";
        o = 10497 /* ZKM Deobf Int */;
        l = "commands.compare.tooManyBlocks";
        Q = -0.95D /* ZKM Deobf */;
        D = "scrollOffsetValCase_";
        Aa = "tag";
        x = "\u4ee8";
        Fa = 205 /* ZKM Deobf Int */;
        g = 25 /* ZKM Deobf Int */;
        ba = 2562 /* ZKM Deobf Int */;
        J = 0.029999999329447746F /* ZKM Deobf */;
        E = " frames";
        X = "\\{([^}]{1,2})}";
        N = "gbuffers_textured";
        v = 0.52D /* ZKM Deobf */;
        Da = "options.fboEnable";
        V = "buildingBlocks";
        L = "gui_";
        t = "filterempty";
        T = 184 /* ZKM Deobf Int */;
        Ha = "orange_stained_glass_pane";
        h = "pendingConnection";
        n = "Failed while reading minidot/emotes/models/{}/{}.json";
        Ia = "Animation ";
        W = "%.2f,%.2f,%.2f - %s";
        ja = "SERVER";
    }
}

