/*
 * Decompiled with CFR 0.152.
 */
public final class kua {
    public static final String ha;
    public static final float Fa;
    public static final int Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final double Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final int r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final float a;
    public static final float b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public kua() {
        kua a2;
    }

    static {
        U = "SUBTITLE";
        Q = "selectWorld.renameTitle";
        F = "regex:";
        P = "cake_(?:bottom|inner|side|top)";
        x = "Old Hand Light";
        r = 2868903935 /* ZKM Deobf Int */;
        z = "Right.Right57";
        G = "mcpatcher/colormap/";
        L = "pack.png";
        o = "F5";
        N = "Shape14123";
        X = "keepAlive";
        g = "gl_caps[ARB_shader_objects]";
        l = 268435456 /* ZKM Deobf Int */;
        Ga = 0.3795918367346939D /* ZKM Deobf */;
        s = "secret";
        q = "shadowtex0Mipmap";
        C = "X0_Y180";
        E = "Slot";
        K = "auxtarget";
        Fa = 0.15625F /* ZKM Deobf */;
        T = 3057 /* ZKM Deobf Int */;
        h = "ofRenderDistanceChunks";
        w = 0.9999D /* ZKM Deobf */;
        V = 0.381D /* ZKM Deobf */;
        k = 3.9000000953674316F /* ZKM Deobf */;
        I = "assets/minecraft/models/block/stone.json";
        m = "BLACK_IRON";
        ja = "LPT9";
        fa = "sounds/";
        n = "left_pants_leg";
        ga = "fern";
        d = "dioriteStairs";
        v = "commands.execute.usage";
        u = "\u25b2";
        ca = 2651799 /* ZKM Deobf Int */;
        R = "arrowInfinite";
        e = "STRAIGHT";
        a = -18.75F /* ZKM Deobf */;
        Z = "ofProfiler:";
        Aa = "Failed to save player data for ";
        b = -3.299999952316284F /* ZKM Deobf */;
        la = "stat.bannerCleaned";
        Y = 2896 /* ZKM Deobf Int */;
        M = "commands.time.set";
        A = "abs";
        Ka = "Monument";
        ha = "AO Level: ";
        Ha = "DISCONNECT";
        j = "Shape2";
        W = "RIDEABLE";
        Ia = 4294967202 /* ZKM Deobf Int */;
        c = "C: %d/%d %sD: %d, %s";
        O = "GL13.GL_MAX_TEXTURE_UNITS";
        B = 346 /* ZKM Deobf Int */;
        H = "CREATIVE";
        D = 189 /* ZKM Deobf Int */;
        J = "PINK_TULIP";
        f = "Oh - I know what I did wrong!";
        S = "textures/body/neonwings_blue.png";
        Ja = "ADD2D";
        p = 40047 /* ZKM Deobf Int */;
        Da = "buddingAmethyst";
        i = "createWorld.customize.flat.layer.top";
        t = "spreadDuration_";
        y = "Client out of date!";
    }
}

