/*
 * Decompiled with CFR 0.152.
 */
public final class kua {
    public static final String ha;
    public static final float Fa;
    public static final int Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final double Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final int r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final float a;
    public static final float b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public kua() {
        kua a2;
    }

    static {
        U = "SUBTITLE";
        Q = "selectWorld.renameTitle";
        F = "regex:";
        P = "cake_(?:bottom|inner|side|top)";
        x = "Old Hand Light";
        r = 0xF12DC3A8 ^ 0x5BD23C57;
        z = "Right.Right57";
        G = "mcpatcher/colormap/";
        L = "pack.png";
        o = "F5";
        N = "Shape14123";
        X = "keepAlive";
        g = "gl_caps[ARB_shader_objects]";
        l = 0xF59DE5C3 ^ 0xE59DE5C3;
        Ga = Double.longBitsToDouble(0xB1CF5501D2812A53L ^ 0x8E171E3A5DA78315L);
        s = "secret";
        q = "shadowtex0Mipmap";
        C = "X0_Y180";
        E = "Slot";
        K = "auxtarget";
        Fa = Float.intBitsToFloat(0x49A47E77 ^ 0x77847E77);
        T = 0x5C3C21B9 ^ 0x5C3C2A48;
        h = "ofRenderDistanceChunks";
        w = Double.longBitsToDouble(0x4B473392A66520F5L ^ 0x74A8CCBCEE8D87EBL);
        V = Double.longBitsToDouble(0x9605F9B52FFE8D3FL ^ 0xA9DD9BF8FD0F24C3L);
        k = Float.intBitsToFloat(0x89167D7F ^ 0xC96FE4E5);
        I = "assets/minecraft/models/block/stone.json";
        m = "BLACK_IRON";
        ja = "LPT9";
        fa = "sounds/";
        n = "left_pants_leg";
        ga = "fern";
        d = "dioriteStairs";
        v = "commands.execute.usage";
        u = "\u25b2";
        ca = 0x219D0F40 ^ 0x21B579D7;
        R = "arrowInfinite";
        e = "STRAIGHT";
        a = Float.intBitsToFloat(0xB7CEDA5D ^ 0x7658DA5D);
        Z = "ofProfiler:";
        Aa = "Failed to save player data for ";
        b = Float.intBitsToFloat(0x7E5A9E25 ^ 0xBE09AD16);
        la = "stat.bannerCleaned";
        Y = 0x83546878 ^ 0x83546328;
        M = "commands.time.set";
        A = "abs";
        Ka = "Monument";
        ha = "AO Level: ";
        Ha = "DISCONNECT";
        j = "Shape2";
        W = "RIDEABLE";
        Ia = 0x7613BAB3 ^ 0x89EC4511;
        c = "C: %d/%d %sD: %d, %s";
        O = "GL13.GL_MAX_TEXTURE_UNITS";
        B = 0xBB36D84C ^ 0xBB36D916;
        H = "CREATIVE";
        D = 0x86A2591E ^ 0x86A259A3;
        J = "PINK_TULIP";
        f = "Oh - I know what I did wrong!";
        S = "textures/body/neonwings_blue.png";
        Ja = "ADD2D";
        p = 0x24B2FC7 ^ 0x24BB3A8;
        Da = "buddingAmethyst";
        i = "createWorld.customize.flat.layer.top";
        t = "spreadDuration_";
        y = "Client out of date!";
    }
}

