/*
 * Decompiled with CFR 0.152.
 */
public final class lPa_1 {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final float X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final long s;
    public static final String w;
    public static final String W;
    public static final float q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final double K;
    public static final int H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        O = "SOUNDS";
        Q = "builtin/clock";
        Ja = 310 /* ZKM Deobf Int */;
        A = "game.hostile.hurt.fall.small";
        d = "0.33, 1, 0.68, 1";
        P = "redNetherBrickStairs";
        U = "[ \t]*const[ \t]*bool[ \t]*\\w+Clear[ \t]*=[ \t]*false[ \t]*;.*";
        q = -0.349065899848938F /* ZKM Deobf */;
        ja = "spread";
        H = 436 /* ZKM Deobf Int */;
        Y = "CHANGE_PAGE";
        fa = "ENTITY_DIED";
        M = "Field modifiers field not found";
        E = "replace_head";
        t = 3418 /* ZKM Deobf Int */;
        V = "ID";
        S = "Right6";
        Da = "\u0412\u041a\u041b";
        N = "save";
        x = 34022 /* ZKM Deobf Int */;
        C = "GL11.GL_LINE_WIDTH_RANGE";
        I = "Head.Shape15";
        m = 4294956800 /* ZKM Deobf Int */;
        Ka = "Right.Right15";
        a = "useStrongholds";
        ca = 693 /* ZKM Deobf Int */;
        D = "glass_pane_top";
        Ga = "golden_axe";
        i = "_%s";
        Aa = "),";
        r = "L_X2";
        Ia = "Cannot get property ";
        X = -10.300000190734863F /* ZKM Deobf */;
        Ha = "ofAnimatedRedstone";
        L = "commandBlockOutput";
        u = "VC: Unexpected error in VoiceChatClient handleVoiceTimeout";
        e = ", frameCount=";
        o = ". Response: ";
        ga = "cat/red";
        J = "ANGLEZ";
        w = "GL11.GL_MAX_LIST_NESTING";
        h = "REGISTERDYNAMICITEM";
        la = "Invalid block ID: ";
        F = "Difficulty";
        K = 6.0D /* ZKM Deobf */;
        z = "box_uv";
        v = 759 /* ZKM Deobf Int */;
        T = "radius_";
        k = "IDLE";
        f = "Shape70123";
        g = "RADIAL_PROGRESS_TIMER";
        R = "UPDATE_DISPLAY_NAME";
        l = 85.0F /* ZKM Deobf */;
        n = "C ";
        G = "display_frequency";
        y = "square_top_left";
        B = 19133 /* ZKM Deobf Int */;
        W = "4F";
        j = "Body.Shape1";
        c = "double_plant_fern_top";
        p = 59 /* ZKM Deobf Int */;
        s = 0x47C455DEA60BA5A5L ^ 0x1822BE8E61BE920FL;
        b = "uv_height";
        Z = "achievement.ghast";
    }

    public lPa_1() {
        lPa_1 a2;
    }
}

