/*
 * Decompiled with CFR 0.152.
 */
public final class lQa {
    public static final String ea;
    public static final String Ea;
    public static final float Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final int ha;
    public static final double Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final int Z;
    public static final float Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final int W;
    public static final int q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final float D;
    public static final double f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public lQa() {
        lQa a2;
    }

    static {
        ja = "selectWorld.title";
        a = "(Error finding chunk loc)";
        j = "double_plant_sundlower_top";
        Ia = "Min value of ";
        s = 4264967296 /* ZKM Deobf Int */;
        M = "corn";
        i = "MSCorridor";
        A = "dio";
        L = "step_UV";
        P = "No tiles defined for vertical+horizontal: ";
        x = 9216 /* ZKM Deobf Int */;
        y = "GL11.GL_RENDERER";
        Aa = "wooden_hoe";
        u = "gl_caps[ARB_copy_buffer]";
        b = "dark_oak_log_stripped";
        p = "\u041a\u0430\u043c\u0435\u0440\u0430 &e>&f ";
        R = 58 /* ZKM Deobf Int */;
        C = 2039587 /* ZKM Deobf Int */;
        J = "biomeDepthWeight";
        ia = "glass_magenta";
        D = -0.171875F /* ZKM Deobf */;
        ea = "\u5142";
        l = 0.019999999552965164D /* ZKM Deobf */;
        V = "options.languageWarning";
        W = 806 /* ZKM Deobf Int */;
        Z = 33385 /* ZKM Deobf Int */;
        Ma = "playerdata";
        Q = " x ";
        T = "Couldn't set command block";
        Fa = 148.0D /* ZKM Deobf */;
        t = "facing=east,half=bottom,shape=inner_left";
        fa = "M9";
        v = "commands.scoreboard.teams.leave.success";
        Y = 41.0F /* ZKM Deobf */;
        ca = "east=false,north=false,south=false,up=true,west=false";
        F = "textures/pet/persona_grand_arcades_sphere.png";
        r = 4287478431 /* ZKM Deobf Int */;
        K = "moisture";
        q = 408 /* ZKM Deobf Int */;
        H = 13421772 /* ZKM Deobf Int */;
        e = "Fail in CommandHelp";
        d = "TextureAnimation: Invalid coordinates";
        Ca = -0.1875F /* ZKM Deobf */;
        w = "COIN";
        f = 3.141592653589793D /* ZKM Deobf */;
        ga = 1.1666666269302368F /* ZKM Deobf */;
        Ga = 3122 /* ZKM Deobf Int */;
        n = "STREAM_KBPS";
        ha = 34065 /* ZKM Deobf Int */;
        h = "commands.ban.usage";
        U = "Right0";
        c = "editEasing_";
        la = "Fuse";
        E = 10241 /* ZKM Deobf Int */;
        Ja = "offsetX_";
        Ha = "RightHand.Shape7";
        X = "AFFECTED_ENTITIES";
        m = 3121 /* ZKM Deobf Int */;
        N = "textures/entity/steve.png";
        ba = "Right.Right23";
        Ka = "color_";
        G = ">&f: \u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u043f\u0443\u0442\u044c \u0441 \u0440\u0435\u0436\u0438\u043c\u0430\u043c\u0438 \u0441\u0433\u043b\u0430\u0436\u0438\u0432\u0430\u043d\u0438\u044f";
        Da = "Wolf collar";
        o = "set tex, before";
        z = "Method must be join or leave for player constructor";
        O = 5632 /* ZKM Deobf Int */;
        S = 10795 /* ZKM Deobf Int */;
        B = "FALLING_BLOCK";
        I = "damage";
        Ea = "O o o";
        g = "options.chat.visibility.hidden";
        k = "flintAndSteel";
    }
}

