/*
 * Decompiled with CFR 0.152.
 */
public final class lQa {
    public static final String ea;
    public static final String Ea;
    public static final float Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final int ha;
    public static final double Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final int Z;
    public static final float Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final int W;
    public static final int q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final float D;
    public static final double f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public lQa() {
        lQa a2;
    }

    static {
        ja = "selectWorld.title";
        a = "(Error finding chunk loc)";
        j = "double_plant_sundlower_top";
        Ia = "Min value of ";
        s = 0x7E8EA8F1 ^ 0x80B89471;
        M = "corn";
        i = "MSCorridor";
        A = "dio";
        L = "step_UV";
        P = "No tiles defined for vertical+horizontal: ";
        x = 0xA9D32B7C ^ 0xA9D30F7C;
        y = "GL11.GL_RENDERER";
        Aa = "wooden_hoe";
        u = "gl_caps[ARB_copy_buffer]";
        b = "dark_oak_log_stripped";
        p = "\u041a\u0430\u043c\u0435\u0440\u0430 &e>&f ";
        R = 0xB640CC49 ^ 0xB640CC73;
        C = 0x7239CACC ^ 0x7226D5EF;
        J = "biomeDepthWeight";
        ia = "glass_magenta";
        D = Float.intBitsToFloat(0x3C4AF61F ^ 0x827AF61F);
        ea = "\u5142";
        l = Double.longBitsToDouble(0xCD67E238C1F92404L ^ 0xF2F398D981F92404L);
        V = "options.languageWarning";
        W = 0x5629093 ^ 0x56293B5;
        Z = 0x20E8DF89 ^ 0x20E85DE0;
        Ma = "playerdata";
        Q = " x ";
        T = "Couldn't set command block";
        Fa = Double.longBitsToDouble(0x93698E513301C88DL ^ 0xD30B0E513301C88DL);
        t = "facing=east,half=bottom,shape=inner_left";
        fa = "M9";
        v = "commands.scoreboard.teams.leave.success";
        Y = Float.intBitsToFloat(0x3E2A5A84 ^ 0x7C0E5A84);
        ca = "east=false,north=false,south=false,up=true,west=false";
        F = "textures/pet/persona_grand_arcades_sphere.png";
        r = 0x4D535C07 ^ 0xB2DEE698;
        K = "moisture";
        q = 0xC3278F0F ^ 0xC3278E97;
        H = 0xE186FA0C ^ 0xE14A36C0;
        e = "Fail in CommandHelp";
        d = "TextureAnimation: Invalid coordinates";
        Ca = Float.intBitsToFloat(0x43B35E85 ^ 0xFDF35E85);
        w = "COIN";
        f = Double.longBitsToDouble(0x47143C47B614B455L ^ 0x71D1DBCE250994DL);
        ga = Float.intBitsToFloat(0xC8F7DFAD ^ 0xF7628AF8);
        Ga = 0x4524C8ED ^ 0x4524C4DF;
        n = "STREAM_KBPS";
        ha = 0xAB573108 ^ 0xAB57B419;
        h = "commands.ban.usage";
        U = "Right0";
        c = "editEasing_";
        la = "Fuse";
        E = 0xA3434275 ^ 0xA3436A74;
        Ja = "offsetX_";
        Ha = "RightHand.Shape7";
        X = "AFFECTED_ENTITIES";
        m = 0x4CC8A5AF ^ 0x4CC8A99E;
        N = "textures/entity/steve.png";
        ba = "Right.Right23";
        Ka = "color_";
        G = ">&f: \u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u043f\u0443\u0442\u044c \u0441 \u0440\u0435\u0436\u0438\u043c\u0430\u043c\u0438 \u0441\u0433\u043b\u0430\u0436\u0438\u0432\u0430\u043d\u0438\u044f";
        Da = "Wolf collar";
        o = "set tex, before";
        z = "Method must be join or leave for player constructor";
        O = 0x1753B84A ^ 0x1753AE4A;
        S = 0x2EF2DCE5 ^ 0x2EF2F6CE;
        B = "FALLING_BLOCK";
        I = "damage";
        Ea = "O o o";
        g = "options.chat.visibility.hidden";
        k = "flintAndSteel";
    }
}

