/*
 * Decompiled with CFR 0.152.
 */
public final class lqa_2 {
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final double ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final double W;
    public static final String q;
    public static final double x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final float l;
    public static final String e;
    public static final float G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    static {
        U = "Dispose font {} ({}pt * {}) with {} pages";
        fa = "potion.digSlowDown";
        Y = "options.stream.mic_toggle.mute";
        q = "redstone_dust_cross";
        e = "\u0000#\u0001\u0000\u0001$#\u0000\u0000\u0000\u0001:\u0000\u0002<\u0000\u0003<\u0000\u0004<\u0000\u0005:\u0000\u0006<\u0000\u0007<\u0000\b<\u0000\t<\u0000\n<\u0000\u000b<\u0000\f<\u0000\r:\u0000\u000e<\u0000\u000f<\u0000\u0010<\u0000\u0011<\u0000\u0012<\u0000\u0013<\u0000\u0014:\u0000\u0015<\u0000\u0016<\u0000\u0018<\u0000\u0019<\u0000\u001a<\u0000\u001b<\u0000\u001c<\u0000\u001d<\u0000\u001e<\u0000\u001f<\u0000 <\u0000!<\u0000\"<\u0000#<\u0000$<\u0000";
        j = "bubbleCoralBlock";
        ca = -6.0D /* ZKM Deobf */;
        r = "LIME";
        o = "DeathTime";
        la = "wake";
        v = "container.repair.cost";
        g = "potion.prefix.thin";
        T = "' \u043d\u0435 \u0445\u0432\u0430\u0442\u0430\u0435\u0442 \u0433\u0440\u0430\u043d\u0435\u0439";
        c = "[Shaders] Worlds: ";
        t = "expirationDelay";
        N = 40038 /* ZKM Deobf Int */;
        k = "Head.Shape10";
        ja = "SIZEANIM";
        n = "written_book";
        B = "suggest_command";
        K = "glass_pane_top_purple";
        Z = "achievement.requires";
        F = "layer4";
        b = 7168 /* ZKM Deobf Int */;
        W = 0.8181818181818182D /* ZKM Deobf */;
        i = "gray_concrete_powder";
        S = "tile.bed.occupied";
        Q = "emotes:";
        O = "foodSaturationLevel";
        u = "HIGH";
        D = "Duplicate stat id: \"";
        y = "wheat";
        p = 14188339 /* ZKM Deobf Int */;
        w = "File not found";
        ga = 6.0F /* ZKM Deobf */;
        m = "cherry_fence_gate";
        H = "FAILED";
        s = 12 /* ZKM Deobf Int */;
        J = "collection";
        Aa = "\u0420\u0435\u0436\u0438\u043c \u0441\u044a\u0451\u043c\u043a\u0438";
        Ja = 1032 /* ZKM Deobf Int */;
        G = -0.5952000021934509F /* ZKM Deobf */;
        z = "portalForcer";
        a = "easingExpr_";
        I = 381 /* ZKM Deobf Int */;
        X = "waxed_exposed_cut_copper_slab_double";
        E = "bitField0_";
        C = "mossy_stone_brick_stairs";
        V = "Head.Shape9";
        l = 0.8299999833106995F /* ZKM Deobf */;
        L = "User Authenticator #";
        h = "spruce_fence";
        P = "ZANIM";
        Ga = "java.version";
        Ka = "mob.ghast.death";
        Da = "Failed to fetch mob spawner entity at (";
        Ha = "options_";
        A = "light_blue_stained_glass";
        M = "GL11.GL_CCW";
        f = 20147 /* ZKM Deobf Int */;
        d = "ofFogStart:";
        R = "DIRT";
        x = 1.8D /* ZKM Deobf */;
    }

    public lqa_2() {
        lqa_2 a2;
    }
}

