/*
 * Decompiled with CFR 0.152.
 */
public final class LQa_3 {
    public static final String da;
    public static final String Ba;
    public static final String aa;
    public static final String ea;
    public static final String Ea;
    public static final float Ca;
    public static final float ia;
    public static final int Ma;
    public static final int ba;
    public static final long ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final long ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final float Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final double X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final double b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final double E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        q = "Features";
        Ea = "ARMS_DEFAULT";
        D = "GRASS";
        fa = Float.intBitsToFloat(0x67749B75 ^ 0xD8566D9A);
        N = "Vertex Color";
        R = 0x6ACD67BC ^ 0x6ACD97B3;
        Ha = "GL14.GL_TEXTURE_COMPARE_FUNC";
        z = "vn";
        W = "options.saturation";
        g = "EAT";
        t = 0xFFC9CD02 ^ 0xFFC9F382;
        a = "xCenter";
        h = 0x75356E9 ^ 0x72DE987;
        Ja = 0x29D3AE70 ^ 0x29D3AF6E;
        u = "redstoneSize";
        r = "Shape3123";
        I = "[Shaders] Invalid block ID mapping: ";
        F = "Dynamic Hand Light";
        U = "TRANSLUCENT_BLOCKS";
        J = 0xA00F6C8F ^ 0xA00F60AF;
        Ba = "brainCoralBlock";
        A = "Shape5";
        Ma = 0x1502A093 ^ 0x1502A235;
        l = "Cipher creation failed!";
        j = "ePlayer_";
        V = "ofLagometer";
        ea = "hasPlacedChest2";
        H = "entitydata";
        L = "water.png";
        E = Double.longBitsToDouble(0xB82179618380FF6CL ^ 0x87C71F07E5E6990AL);
        ga = " packet ";
        y = "decrypt";
        x = "emerald_block";
        i = Float.intBitsToFloat(0x17D48D88 ^ 0xA88BEB7A);
        ba = 0xC1B81533 ^ 0xC1B8145C;
        Q = "potion.fireResistance";
        s = "[MiniDot] itemmeta directory does not exist";
        S = "SUCCESS_COUNT";
        Y = 0x11AF8000 ^ 0x11AF1C56;
        p = "Shape21";
        c = 0x3F97093D ^ 0x3F970918;
        ia = Float.intBitsToFloat(0xD88CF43C ^ 0xE3486F9A);
        X = Double.longBitsToDouble(0x77827310D10349F2L ^ 0x3790AA6CAE306820L);
        P = 0xB2FC9274 ^ 0xB2FCBA76;
        Aa = 0x16407137 ^ 0x16407208;
        ha = 0xE0664A7354D9CDD9L ^ 0x60664A7354D9CDD9L;
        la = "hasPlacedChest0";
        Ga = "commands.scoreboard.teams.option.noValue";
        C = "APPLICATION";
        ca = 0x3860E780E7176137L ^ 0x3860E780E7176127L;
        Ka = "animations/body/demonicwingstail_animation.json";
        T = "WARM";
        G = "\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u0438\u043d\u0433";
        v = 0x30F2FB32 ^ 0x30F2FEEE;
        w = Float.intBitsToFloat(0xD87FEAD2 ^ 0x67EEDCCC);
        aa = "textures/gui/widgets.png";
        b = Double.longBitsToDouble(0xEF245D9601B37BF1L ^ 0xD0C05D9601B37BF1L);
        n = "Initialization";
        M = "RESOURCE";
        Ca = Float.intBitsToFloat(0x414C0B8C ^ 0x806E1FF7);
        O = "SIDE";
        B = "key.fullscreen";
        da = "sx";
        Da = 0xDA2204A8 ^ 0xDA78C473;
        d = "commands.give.success";
        ja = "CORN";
        Ia = "shadowcolor1Mipmap";
        K = "GL11.GL_SELECTION_BUFFER_SIZE";
        Fa = "resourcePack.incompatible.new";
        o = "GL13.GL_RGB_SCALE";
        f = "remoteIds_";
        k = "x_";
        e = 0xD65C4C34 ^ 0xD65CC4D6;
        Z = Float.intBitsToFloat(0x4C6B7873 ^ 0xD437873);
        m = "textures/body/batterfly_wings_blue.png";
    }

    public LQa_3() {
        LQa_3 a2;
    }
}

