/*
 * Decompiled with CFR 0.152.
 */
public final class LQa_3 {
    public static final String da;
    public static final String Ba;
    public static final String aa;
    public static final String ea;
    public static final String Ea;
    public static final float Ca;
    public static final float ia;
    public static final int Ma;
    public static final int ba;
    public static final long ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final long ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final float Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final double X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final double b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final double E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        q = "Features";
        Ea = "ARMS_DEFAULT";
        D = "GRASS";
        fa = -0.6365804076194763F /* ZKM Deobf */;
        N = "Vertex Color";
        R = 61455 /* ZKM Deobf Int */;
        Ha = "GL14.GL_TEXTURE_COMPARE_FUNC";
        z = "vn";
        W = "options.saturation";
        g = "EAT";
        t = 16000 /* ZKM Deobf Int */;
        a = "xCenter";
        h = 8306542 /* ZKM Deobf Int */;
        Ja = 286 /* ZKM Deobf Int */;
        u = "redstoneSize";
        r = "Shape3123";
        I = "[Shaders] Invalid block ID mapping: ";
        F = "Dynamic Hand Light";
        U = "TRANSLUCENT_BLOCKS";
        J = 3104 /* ZKM Deobf Int */;
        Ba = "brainCoralBlock";
        A = "Shape5";
        Ma = 678 /* ZKM Deobf Int */;
        l = "Cipher creation failed!";
        j = "ePlayer_";
        V = "ofLagometer";
        ea = "hasPlacedChest2";
        H = "entitydata";
        L = "water.png";
        E = 0.7D /* ZKM Deobf */;
        ga = " packet ";
        y = "decrypt";
        x = "emerald_block";
        i = -0.8726645708084106F /* ZKM Deobf */;
        ba = 367 /* ZKM Deobf Int */;
        Q = "potion.fireResistance";
        s = "[MiniDot] itemmeta directory does not exist";
        S = "SUCCESS_COUNT";
        Y = 40022 /* ZKM Deobf Int */;
        p = "Shape21";
        c = 37 /* ZKM Deobf Int */;
        ia = 0.006000000052154064F /* ZKM Deobf */;
        X = 4.71238898038469D /* ZKM Deobf */;
        P = 10242 /* ZKM Deobf Int */;
        Aa = 831 /* ZKM Deobf Int */;
        ha = 0xE0664A7354D9CDD9L ^ 0x60664A7354D9CDD9L;
        la = "hasPlacedChest0";
        Ga = "commands.scoreboard.teams.option.noValue";
        C = "APPLICATION";
        ca = 0x3860E780E7176137L ^ 0x3860E780E7176127L;
        Ka = "animations/body/demonicwingstail_animation.json";
        T = "WARM";
        G = "\u041f\u043e\u043a\u0430\u0437\u044b\u0432\u0430\u0442\u044c \u043f\u0438\u043d\u0433";
        v = 1500 /* ZKM Deobf Int */;
        w = -1.1344640254974365F /* ZKM Deobf */;
        aa = "textures/gui/widgets.png";
        b = 0.625D /* ZKM Deobf */;
        n = "Initialization";
        M = "RESOURCE";
        Ca = -10.130000114440918F /* ZKM Deobf */;
        O = "SIDE";
        B = "key.fullscreen";
        da = "sx";
        Da = 5947611 /* ZKM Deobf Int */;
        d = "commands.give.success";
        ja = "CORN";
        Ia = "shadowcolor1Mipmap";
        K = "GL11.GL_SELECTION_BUFFER_SIZE";
        Fa = "resourcePack.incompatible.new";
        o = "GL13.GL_RGB_SCALE";
        f = "remoteIds_";
        k = "x_";
        e = 35042 /* ZKM Deobf Int */;
        Z = 10.5F /* ZKM Deobf */;
        m = "textures/body/batterfly_wings_blue.png";
    }

    public LQa_3() {
        LQa_3 a2;
    }
}

