/*
 * Decompiled with CFR 0.152.
 */
public final class LRa {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final int c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final double j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        Aa = "REMOVE3D";
        ha = "LPT6";
        Ga = "currency";
        o = "Shape28";
        G = 0xFD9427DC ^ 0x999427DC;
        Fa = "Blend Weight";
        P = Float.intBitsToFloat(0xD70D2262 ^ 0x17133619);
        t = "adjustableAngle_";
        l = "assets/minecraft/models/block/redstone_ore.json";
        a = "potato";
        Z = "https://texteria.vimeworld.com/file/";
        Ia = "XZ";
        Y = "white_concrete";
        x = "acacia";
        q = "CHANGE";
        A = 0x4AC95166 ^ 0x4AC950C4;
        d = Float.intBitsToFloat(0xE3C70CAF ^ 0xDCAC89B0);
        N = 0x65502B2B ^ 0x65502A4D;
        g = "fire";
        ga = Float.intBitsToFloat(0x2EEA8BC1 ^ 0x10BA3B33);
        C = "GL11.GL_FRONT_FACE";
        U = "menu.loadingLevel";
        Ja = Float.intBitsToFloat(0x796F1AD3 ^ 0xB87029E0);
        R = " // Shader option OFF";
        L = Double.longBitsToDouble(0x8AD5FDB368B38851L ^ 0xB50D8137DD6F4E6EL);
        h = 0xFDE2135A ^ 0xFDE29330;
        S = "hoverable_";
        f = "metadata";
        J = "gl_caps[EXT_rescale_normal]";
        r = Float.intBitsToFloat(0x8806BCDE ^ 0x3680B678);
        M = "eContainer_";
        s = "blockEntityId";
        Da = "lava_lake";
        e = " 3.2 ";
        Ka = "mcpatcher/ctm/";
        W = "Front.6a";
        I = "IsBaby";
        z = "mineshaft";
        y = "RightArm";
        fa = "Tail2";
        p = "GL11.GL_CLEAR";
        u = 0xAF32F06B ^ 0xAF32F149;
        n = "MODEL_PREVIEW";
        H = 0x9B88ADE7 ^ 0x9B88A44A;
        k = "death.fell.killer";
        j = Double.longBitsToDouble(0x963383889E9874ABL ^ 0xD66003889E9874ABL);
        w = "lanServer.scanning";
        ja = 0x5AE133AD ^ 0x5AE112AC;
        m = "mangrove_door";
        v = "waxed_oxidized_copper";
        ca = "of.options.mipmap.linear";
        Q = "repeat";
        Ha = "Valid";
        F = "shadow clear pre";
        K = " cannot support property ";
        la = "purpur_slab";
        X = "options.graphics.fancy";
        E = "Particle being rendered";
        i = "legacy_data";
        V = 0x6A356973 ^ 0x6A359983;
        T = "strippedBambooBlock";
        c = 0x83335FC1 ^ 0x833341C3;
        D = "frame";
        B = "spreadX_";
        O = "textures/gui/container/crafting_table.png";
        b = "chiseledTuffBricks";
    }

    public LRa() {
        LRa a2;
    }
}

