/*
 * Decompiled with CFR 0.152.
 */
public final class LRa {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final int c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final double j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        Aa = "REMOVE3D";
        ha = "LPT6";
        Ga = "currency";
        o = "Shape28";
        G = 1677721600 /* ZKM Deobf Int */;
        Fa = "Blend Weight";
        P = -2.4700000286102295F /* ZKM Deobf */;
        t = "adjustableAngle_";
        l = "assets/minecraft/models/block/redstone_ore.json";
        a = "potato";
        Z = "https://texteria.vimeworld.com/file/";
        Ia = "XZ";
        Y = "white_concrete";
        x = "acacia";
        q = "CHANGE";
        A = 418 /* ZKM Deobf Int */;
        d = 0.9200000166893005F /* ZKM Deobf */;
        N = 358 /* ZKM Deobf Int */;
        g = "fire";
        ga = 0.2037999927997589F /* ZKM Deobf */;
        C = "GL11.GL_FRONT_FACE";
        U = "menu.loadingLevel";
        Ja = -9.949999809265137F /* ZKM Deobf */;
        R = " // Shader option OFF";
        L = 0.3826D /* ZKM Deobf */;
        h = 32874 /* ZKM Deobf Int */;
        S = "hoverable_";
        f = "metadata";
        J = "gl_caps[EXT_rescale_normal]";
        r = -0.26179999113082886F /* ZKM Deobf */;
        M = "eContainer_";
        s = "blockEntityId";
        Da = "lava_lake";
        e = " 3.2 ";
        Ka = "mcpatcher/ctm/";
        W = "Front.6a";
        I = "IsBaby";
        z = "mineshaft";
        y = "RightArm";
        fa = "Tail2";
        p = "GL11.GL_CLEAR";
        u = 290 /* ZKM Deobf Int */;
        n = "MODEL_PREVIEW";
        H = 2477 /* ZKM Deobf Int */;
        k = "death.fell.killer";
        j = 78.0D /* ZKM Deobf */;
        w = "lanServer.scanning";
        ja = 8449 /* ZKM Deobf Int */;
        m = "mangrove_door";
        v = "waxed_oxidized_copper";
        ca = "of.options.mipmap.linear";
        Q = "repeat";
        Ha = "Valid";
        F = "shadow clear pre";
        K = " cannot support property ";
        la = "purpur_slab";
        X = "options.graphics.fancy";
        E = "Particle being rendered";
        i = "legacy_data";
        V = 61680 /* ZKM Deobf Int */;
        T = "strippedBambooBlock";
        c = 7682 /* ZKM Deobf Int */;
        D = "frame";
        B = "spreadX_";
        O = "textures/gui/container/crafting_table.png";
        b = "chiseledTuffBricks";
    }

    public LRa() {
        LRa a2;
    }
}

