/*
 * Decompiled with CFR 0.152.
 */
public final class Lra_1 {
    public static final int ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final double ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final double p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final double I;

    static {
        y = "intact";
        fa = "createWorld.customize.custom.coordinateScale";
        s = "][height]";
        t = "YZX";
        d = "curves";
        P = "COM2";
        x = 1018 /* ZKM Deobf Int */;
        Ka = "options.stream.chat.userFilter.subs";
        W = "idle";
        G = "Less weights defined than skins, expanding weights: ";
        Z = "Sending packet";
        n = "blueOrchid";
        L = 2852 /* ZKM Deobf Int */;
        b = 10387312 /* ZKM Deobf Int */;
        N = "Loaded all configs in ";
        l = "SmaIK";
        f = "gra";
        Aa = "chunkCache";
        C = "stone_slab2";
        B = "demo.help.buy";
        w = "CC";
        X = "customBlockManifest";
        a = "assets/minecraft/models/block/granite.json";
        S = "bamboo_mosaic_slab";
        h = "minecraft:items/empty_armor_slot_helmet";
        D = "No tiles defined for vertical: ";
        j = 36063 /* ZKM Deobf Int */;
        A = "srcrgb";
        Ia = 32875 /* ZKM Deobf Int */;
        K = "GL11.GL_PIXEL_MAP_I_TO_R";
        c = "1.8";
        ha = 5124 /* ZKM Deobf Int */;
        ca = "leaves_big_oak_opaque";
        z = "item.record.";
        E = "of.options.time.nightOnly";
        Y = "\u4ecb";
        la = "RADIAL_SLIDER";
        r = 40056 /* ZKM Deobf Int */;
        V = "[MiniDot] Could not read item meta file: ";
        k = 770 /* ZKM Deobf Int */;
        R = "tuffBricks";
        q = "viewWidth";
        ja = 250.0D /* ZKM Deobf */;
        T = "TERRAIN_TEXTURE";
        U = 34020 /* ZKM Deobf Int */;
        g = "commands.worldborder.set.usage";
        e = 27 /* ZKM Deobf Int */;
        Fa = "q.player_pos_z";
        H = "axis=y";
        i = "Witch";
        u = -0.12460000067949295F /* ZKM Deobf */;
        p = 123.0D /* ZKM Deobf */;
        ga = "body1";
        I = 0.6000000834465027D /* ZKM Deobf */;
        m = 1013 /* ZKM Deobf Int */;
        Da = -4.400000095367432F /* ZKM Deobf */;
        M = "block";
        Ja = "pulling_1";
        v = "minecraft:blocks/water_still";
        Q = "GL11.GL_LIST_BASE";
        J = "ALWAYS";
        Ha = "buildList";
        Ga = "Changing view distance to {}, from {}";
        o = "SKULL_AND_ROSES";
        O = "sky0.png";
        F = "drs";
    }

    public Lra_1() {
        Lra_1 a2;
    }
}

