/*
 * Decompiled with CFR 0.152.
 */
public final class Lsa {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final int Z;
    public static final int Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final float X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final long G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final int L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final int J;
    public static final float A;
    public static final String I;

    static {
        ga = "polished_tuff";
        g = 0x1ED9AA3C ^ 0x1ED9A926;
        J = 0x69D76B6D ^ 0x69D76A1B;
        fa = 0xC7F551AD ^ 0xC7F553DD;
        Y = 0xAAAAB054 ^ 0xAAAAB2CF;
        N = 0x37CA5715 ^ 0x37CA5425;
        Ja = "local";
        W = "onion";
        C = "GL11.GL_PROXY_TEXTURE_2D";
        X = Float.intBitsToFloat(0x7A26A44B ^ 0xBB86A44B);
        z = "Invalid daysLoop: ";
        Ka = "of.options.WEATHER";
        ia = "http://www.minecraft.net/store?source=demo";
        j = "GL14.GL_TEXTURE_DEPTH_SIZE";
        v = "commands.whitelist.remove.usage";
        Fa = "stat.timeSinceDeath";
        T = "GL11.GL_READ_BUFFER";
        r = "drawBack_";
        a = "scalexval_";
        Ma = "newAi";
        ha = "ry";
        m = "0.76, 0, 0.24, 1";
        P = "HEAD_ON_TOP";
        q = "slot.armor.legs";
        la = "GL11.GL_EDGE_FLAG_ARRAY";
        s = 0x7C69753B ^ 0x7C69E96E;
        A = Float.intBitsToFloat(0x65F5DEA1 ^ 0xA495DEA1);
        ca = "anim_time";
        f = ", chatClickEvent=";
        E = 0x501DD25E ^ 0x501DD17E;
        ja = "Toast";
        ba = "Invalid faces in: ";
        o = "Piece1.Shape62";
        Ha = "hide-hud-keystrokes";
        S = "textures/gui/title/background/panorama_0.png";
        c = Double.longBitsToDouble(0xD195F7CAF932A038L ^ 0xEE7087692E389D49L);
        w = "No particle_effect was found...";
        t = 0xA3F12E38 ^ 0xA3F1232D;
        M = "Right7";
        Ga = "cutCopperStairs";
        Da = "shouldRenderClouds";
        Z = 0xE754B49E ^ 0xE754B593;
        Q = "64";
        Ia = "Ribbon4";
        i = "40% better than a crash report.";
        b = "Missing ':' in ternary expression";
        p = "mud_bricks";
        B = "blue_stained_hardened_clay";
        F = "_shooting";
        y = "Pet.Ribbon4";
        x = "paleOakFenceGate";
        d = "SHOOT";
        u = "gui.toTitle";
        H = "of.options.animation.allOn";
        K = 0x5ACC17CD ^ 0x5ACC10CF;
        e = 0xAF37B54A ^ 0xAF37A64B;
        G = 0x3F2F57C1144510FDL ^ 0x3F2F57C11339A5CCL;
        n = "BOTTOM";
        Aa = 0x3E788A5D ^ 0x3EE81AFD;
        O = "potion.weakness";
        D = ".ogg";
        R = "shaders/post/art.json";
        I = "selectServer.hiddenAddress";
        h = "Profiler Position";
        V = 0x21A077A2 ^ 0x21A07562;
        k = Float.intBitsToFloat(0xF4A46AD5 ^ 0x4BA8A618);
        L = 0xF5A6BA46 ^ 0xF5A6BABE;
        U = "log2";
        l = "bootsIron";
    }

    public Lsa() {
        Lsa a2;
    }
}

