/*
 * Decompiled with CFR 0.152.
 */
public final class Lsa {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final int Z;
    public static final int Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final float X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final long G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final int L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final int J;
    public static final float A;
    public static final String I;

    static {
        ga = "polished_tuff";
        g = 794 /* ZKM Deobf Int */;
        J = 374 /* ZKM Deobf Int */;
        fa = 624 /* ZKM Deobf Int */;
        Y = 667 /* ZKM Deobf Int */;
        N = 816 /* ZKM Deobf Int */;
        Ja = "local";
        W = "onion";
        C = "GL11.GL_PROXY_TEXTURE_2D";
        X = -20.0F /* ZKM Deobf */;
        z = "Invalid daysLoop: ";
        Ka = "of.options.WEATHER";
        ia = "http://www.minecraft.net/store?source=demo";
        j = "GL14.GL_TEXTURE_DEPTH_SIZE";
        v = "commands.whitelist.remove.usage";
        Fa = "stat.timeSinceDeath";
        T = "GL11.GL_READ_BUFFER";
        r = "drawBack_";
        a = "scalexval_";
        Ma = "newAi";
        ha = "ry";
        m = "0.76, 0, 0.24, 1";
        P = "HEAD_ON_TOP";
        q = "slot.armor.legs";
        la = "GL11.GL_EDGE_FLAG_ARRAY";
        s = 40021 /* ZKM Deobf Int */;
        A = -14.0F /* ZKM Deobf */;
        ca = "anim_time";
        f = ", chatClickEvent=";
        E = 800 /* ZKM Deobf Int */;
        ja = "Toast";
        ba = "Invalid faces in: ";
        o = "Piece1.Shape62";
        Ha = "hide-hud-keystrokes";
        S = "textures/gui/title/background/panorama_0.png";
        c = 0.67D /* ZKM Deobf */;
        w = "No particle_effect was found...";
        t = 3349 /* ZKM Deobf Int */;
        M = "Right7";
        Ga = "cutCopperStairs";
        Da = "shouldRenderClouds";
        Z = 269 /* ZKM Deobf Int */;
        Q = "64";
        Ia = "Ribbon4";
        i = "40% better than a crash report.";
        b = "Missing ':' in ternary expression";
        p = "mud_bricks";
        B = "blue_stained_hardened_clay";
        F = "_shooting";
        y = "Pet.Ribbon4";
        x = "paleOakFenceGate";
        d = "SHOOT";
        u = "gui.toTitle";
        H = "of.options.animation.allOn";
        K = 1794 /* ZKM Deobf Int */;
        e = 4865 /* ZKM Deobf Int */;
        G = 0x3F2F57C1144510FDL ^ 0x3F2F57C11339A5CCL;
        n = "BOTTOM";
        Aa = 9474208 /* ZKM Deobf Int */;
        O = "potion.weakness";
        D = ".ogg";
        R = "shaders/post/art.json";
        I = "selectServer.hiddenAddress";
        h = "Profiler Position";
        V = 704 /* ZKM Deobf Int */;
        k = -0.550000011920929F /* ZKM Deobf */;
        L = 248 /* ZKM Deobf Int */;
        U = "log2";
        l = "bootsIron";
    }

    public Lsa() {
        Lsa a2;
    }
}

