/*
 * Decompiled with CFR 0.152.
 */
public final class lTa {
    public static final String ha = "Capabilities: ";
    public static final String Fa;
    public static final String Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final long n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final int o;
    public static final long h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final int l;
    public static final int e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final float J;
    public static final String A;
    public static final String I;

    static {
        ga = "SPELL_INSTANT";
        d = "Byte";
        F = "AllowFriendlyFire";
        r = "wdo";
        Z = -0.25F /* ZKM Deobf */;
        C = "commands.achievement.take.success.all";
        o = 1080 /* ZKM Deobf Int */;
        V = "moon";
        M = "PrimedTnt";
        Ha = "textures/misc/forcefield.png";
        D = 0.7200000286102295F /* ZKM Deobf */;
        P = "layer_";
        Ia = "selectWorld.deleteButton";
        Ka = 40053 /* ZKM Deobf Int */;
        j = "Beacon";
        la = 0.003000000026077032F /* ZKM Deobf */;
        Q = "Couldn't save statistic ";
        m = "Rendering screen";
        x = "textures/pet/owlpet2.png";
        Aa = "shadowHardwareFiltering";
        p = "SPECULAR_MAP";
        K = "Connection not keep-alive";
        f = "Pet.Ribbon7";
        b = 5.811946868896484F /* ZKM Deobf */;
        y = "damage.thorns";
        W = "/party disband";
        L = "GL11.GL_OR_INVERTED";
        z = "flint";
        A = "blocks";
        i = "random.break";
        v = 11.800000190734863F /* ZKM Deobf */;
        fa = "harm";
        g = "ambientocclusion";
        I = "bambooMosaic";
        Fa = "mob.zombiepig.zpigangry";
        Da = "GL11.GL_TEXTURE_BORDER";
        N = "SOUND";
        n = 0xF8D196F10FA917E4L ^ 0xF8D196F10FA930F4L;
        c = "memory_free";
        Ga = 6000001.0F /* ZKM Deobf */;
        u = 3171 /* ZKM Deobf Int */;
        O = "GL11.GL_MAP1_INDEX";
        G = "SET_COLOR";
        s = "I'm sorry, Dave.";
        R = "frustum_";
        Y = "linux";
        l = 11013646 /* ZKM Deobf Int */;
        ca = 35898 /* ZKM Deobf Int */;
        e = 9217 /* ZKM Deobf Int */;
        w = "GL11.GL_INCR";
        q = "GL11.GL_LINEAR_ATTENUATION";
        a = "index_";
        T = 0.6666666865348816F /* ZKM Deobf */;
        X = "Invalid Item!";
        U = "TeSH";
        H = "Notification";
        k = ", B: ";
        ja = "ln";
        B = "Right.Right12";
        Ja = "^[a-f0-9]{40}$";
        S = "textures/body/wings_green.png";
        t = "post";
        E = "LeftLeg.LL2";
        J = -1.020300030708313F /* ZKM Deobf */;
        h = 0xBD0FBA8C71CA7013L ^ 0xBD0FBA8C71CA7015L;
    }

    public lTa() {
        lTa a2;
    }
}

