/*
 * Decompiled with CFR 0.152.
 */
public final class lTa {
    public static final String ha = "Capabilities: ";
    public static final String Fa;
    public static final String Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final long n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final int o;
    public static final long h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final int l;
    public static final int e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final float J;
    public static final String A;
    public static final String I;

    static {
        ga = "SPELL_INSTANT";
        d = "Byte";
        F = "AllowFriendlyFire";
        r = "wdo";
        Z = Float.intBitsToFloat(0x2002E574 ^ 0x9E82E574);
        C = "commands.achievement.take.success.all";
        o = 0xC9F4BBEE ^ 0xC9F4BFD6;
        V = "moon";
        M = "PrimedTnt";
        Ha = "textures/misc/forcefield.png";
        D = Float.intBitsToFloat(0x54116640 ^ 0x6B2937AC);
        P = "layer_";
        Ia = "selectWorld.deleteButton";
        Ka = 0x83A61DB6 ^ 0x83A681C3;
        j = "Beacon";
        la = Float.intBitsToFloat(0xAB4BBFA ^ 0x31F0205C);
        Q = "Couldn't save statistic ";
        m = "Rendering screen";
        x = "textures/pet/owlpet2.png";
        Aa = "shadowHardwareFiltering";
        p = "SPECULAR_MAP";
        K = "Connection not keep-alive";
        f = "Pet.Ribbon7";
        b = Float.intBitsToFloat(0x2AF46A4C ^ 0x6A4D9134);
        y = "damage.thorns";
        W = "/party disband";
        L = "GL11.GL_OR_INVERTED";
        z = "flint";
        A = "blocks";
        i = "random.break";
        v = Float.intBitsToFloat(0x92DA06C0 ^ 0xD3E6CA0D);
        fa = "harm";
        g = "ambientocclusion";
        I = "bambooMosaic";
        Fa = "mob.zombiepig.zpigangry";
        Da = "GL11.GL_TEXTURE_BORDER";
        N = "SOUND";
        n = 0xF8D196F10FA917E4L ^ 0xF8D196F10FA930F4L;
        c = "memory_free";
        Ga = Float.intBitsToFloat(0x4C82143B ^ 0x6350F39);
        u = 0xEC499938 ^ 0xEC49955B;
        O = "GL11.GL_MAP1_INDEX";
        G = "SET_COLOR";
        s = "I'm sorry, Dave.";
        R = "frustum_";
        Y = "linux";
        l = 0xCE13579F ^ 0xCEBB5991;
        ca = 0xB1F4D66C ^ 0xB1F45A56;
        e = 0x671F62C5 ^ 0x671F46C4;
        w = "GL11.GL_INCR";
        q = "GL11.GL_LINEAR_ATTENUATION";
        a = "index_";
        T = Float.intBitsToFloat(0x8F0F0FF5 ^ 0xB025A55E);
        X = "Invalid Item!";
        U = "TeSH";
        H = "Notification";
        k = ", B: ";
        ja = "ln";
        B = "Right.Right12";
        Ja = "^[a-f0-9]{40}$";
        S = "textures/body/wings_green.png";
        t = "post";
        E = "LeftLeg.LL2";
        J = Float.intBitsToFloat(0xA459CBCA ^ 0x1BDB52FB);
        h = 0xBD0FBA8C71CA7013L ^ 0xBD0FBA8C71CA7015L;
    }

    public lTa() {
        lTa a2;
    }
}

