/*
 * Decompiled with CFR 0.152.
 */
public final class mPa {
    public static final double ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final float n;
    public static final double s;
    public static final int w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final long v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final int B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        S = "Invalid default width";
        k = "variable.particle_pos.x";
        L = "iron";
        fa = "wheat_seeds";
        g = "oak_sapling";
        Q = "beginUpdateChunks2";
        Aa = "22653B89-116E-49DC-9B6B-9971489B5BE5";
        G = 0xCDD0F355 ^ 0xCDD0716E;
        x = "FIREBALL";
        F = "gl_caps[EXT_blend_equation_separate]";
        V = "RGB8_SNORM";
        A = "Reconnect using hosts: ";
        Ma = "N/A (disabled)";
        N = "minecraft:music.game.end.dragon";
        E = "scaleval_";
        U = 0x5B7E2E20 ^ 0xE5E2E20;
        s = Double.longBitsToDouble(0xBCDAFC612618BE51L ^ 0xFC96FC612618BE51L);
        K = "variable.particle_speed.z";
        O = "Couldn't delete directory ";
        t = Float.intBitsToFloat(0xDF806234 ^ 0x6086B7E4);
        Z = "] ";
        a = "DILLERON";
        M = "RY";
        ga = 0xED24A83 ^ 0xED24BEF;
        la = "DEPRECATED BEHAVIOR";
        ha = "gl_caps[EXT_framebuffer_sRGB]";
        f = "offsetZExpr_";
        ja = "0.87, 0, 0.13, 1";
        i = "CTM name: ";
        y = 0xF6EE985A ^ 0xF6EE180C;
        P = "creative";
        e = "Biome B ID";
        X = "\u0426\u0432\u0435\u0442 \u0442\u0435\u043a\u0441\u0442\u0430:";
        Ga = "mob.cow.hurt";
        l = "blockdust_";
        Da = "potion.absorption";
        J = 0x7A4AF8E6 ^ 0x7A4AFA55;
        Ia = 0x3E5D2FF9 ^ 0x3E5D2F48;
        ba = "hr";
        B = 0xEA82DC9C ^ 0xEA82D73C;
        j = "minecraft:particle_expire_if_in_blocks";
        q = "Error setting window icon: ";
        D = "%/";
        v = 0x62CD14C4FEB22D8AL ^ 0x62CD14C4FEB21B3BL;
        Y = "Piece1.Shape31";
        b = " into ";
        w = 0xB8EBC813 ^ 0x4714B7EC;
        Ja = "prismarineShard";
        Ka = "GL12.GL_RESCALE_NORMAL";
        o = Float.intBitsToFloat(0x5AEEDB1 ^ 0x46FCEDB1);
        r = 0xA84284CE ^ 0xA84296C7;
        c = "glass_pane_top_black";
        I = "LastPlayed";
        ca = 0x839182FF ^ 0x8391821E;
        m = "Error saving configuration: ";
        W = 0xEA94AF6B ^ 0xEA947651;
        ia = Double.longBitsToDouble(0x61DD4D25EAB43847L ^ 0x5E43F574013126FFL);
        Ha = "stat.cauldronUsed";
        C = "mob.zombie.death";
        Fa = "\u041f\u0430\u0442\u0438 \u043d\u0435 \u0441\u043e\u0437\u0434\u0430\u043d\u043e";
        p = "thundering";
        n = Float.intBitsToFloat(0xD48AFBEC ^ 0x169CFBEC);
        z = "\u0423\u0432\u0435\u043b\u0438\u0447\u0435\u043d\u0438\u0435 +";
        d = 0xBBD35FBE ^ 0xBBD35CFE;
        R = "upperhead";
        u = "frustum";
        H = 0x4585D464 ^ 0x4585C464;
        T = "ACTION_NOT_SET";
        h = "double_fern";
    }

    public mPa() {
        mPa a2;
    }
}

