/*
 * Decompiled with CFR 0.152.
 */
public final class Mqa {
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final float O;
    public static final float t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        K = "math.hermite_blend";
        B = 5.099999904632568F /* ZKM Deobf */;
        X = "weatheredCutCopperSlab";
        k = "entity-id";
        l = "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0004\u0002\u100a\u0000\u0003\u1001\u0001\u0004\u1001\u0002\u0005\u1001\u0003\u0006\u1001\u0004";
        N = 0.125F /* ZKM Deobf */;
        m = "GL13.GL_TEXTURE4";
        v = "blindness";
        w = 1284 /* ZKM Deobf Int */;
        Ga = -0.11999999731779099F /* ZKM Deobf */;
        P = "const ";
        Z = "east=false,north=false,south=false,up=true,west=true";
        M = "XZY";
        r = -0.0266666691750288F /* ZKM Deobf */;
        fa = "potion.prefix.elegant";
        a = "glass_purple";
        Ja = "Blaze";
        C = "mob.horse.jump";
        p = "Comparing biomes";
        Y = "textures/blocks/destroy_stage_0.png";
        A = "fortune";
        U = "tile.bed.notSafe";
        z = " / \u041f\u0438\u043d\u0433: ";
        Ha = "GL11.GL_BLUE_BITS";
        n = "Piece2";
        o = "devtools";
        ja = 238 /* ZKM Deobf Int */;
        d = "Don't know how to handle ";
        V = "MASTER";
        H = "Invalid palette size: ";
        i = "blaze_rod";
        t = 1.4048000574111938F /* ZKM Deobf */;
        W = 3074 /* ZKM Deobf Int */;
        R = "Level Data Unobtainable";
        D = "rearleg.main";
        u = "FXAA 2x";
        h = "tulipRed";
        J = "variants";
        Aa = "neck";
        b = -0.0625F /* ZKM Deobf */;
        O = -1.003600001335144F /* ZKM Deobf */;
        j = "<empty>";
        c = "OfflinePlayer:";
        q = "polishedBlackstoneBrickWall";
        T = "Timeout ";
        S = "variable.particle_pos.distance";
        I = "\u4ed1  ";
        e = "length";
        y = "";
        E = "assets/minecraft/models/block/stone_mirrored.json";
        s = "lower";
        x = "pendingBlockEntities";
        g = "key.hotbar.5";
        F = "createWorld.customize.custom.mainNoiseScaleY";
        f = "Left.Shape20123";
        ca = "Load ShadersMod configuration.";
        G = "quartz_ore";
        L = "Couldn't render entity";
        Q = "Head.34";
        Ka = "Shaders can not be loaded, Antialiasing is enabled: ";
    }

    public Mqa() {
        Mqa a2;
    }
}

