/*
 * Decompiled with CFR 0.152.
 */
public final class MQa_1 {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final int ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final int Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final long r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final float d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final long f;
    public static final String F;
    public static final int g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Ia = "SNOOPER_ENABLED";
        b = "+0-1-2-3&4-4+13";
        y = "OOoooOOOoooo! Spooky!";
        P = "ArrowAttackGoal requires Mob implements RangedAttackMob";
        fa = 0xD308726F ^ 0xD308557D;
        u = "lit_furnace";
        r = 0x54A4AB06A697EAL ^ 0x54A4AB06A697E0L;
        F = "hopper";
        T = "log";
        z = "Towards positive X";
        Ga = 0x9019E060 ^ 0x901968FB;
        C = "east=true,north=true,south=true,up=true,west=false";
        Ha = "helmet_";
        la = "commands.testfor.usage";
        ca = 0xF525BFDD ^ 0xF525FFD8;
        Y = "GL13.GL_TEXTURE30";
        a = 0xCE8110BB ^ 0xCE811142;
        B = Float.intBitsToFloat(0xD465201B ^ 0xEBD9201B);
        A = "gl_caps[ARB_color_buffer_float]";
        Ja = "GL11.GL_C3F_V3F";
        k = "magenta_wool";
        f = 0x9E308EAC16B07BACL ^ 0x9E308EAC16B07B6CL;
        K = "of.options.POTION_PARTICLES";
        Fa = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u1006\u0000\u0003\u1006\u0001";
        H = "Back.11a";
        d = Float.intBitsToFloat(0x30691 ^ 0x3F79E7D9);
        s = "selectWorld.renameButton";
        Z = 0xE0F013D9 ^ 0x9F0FEC27;
        e = "easeInOutCirc";
        o = "fog-color";
        O = "rabbit";
        U = "voicechat.log";
        M = "Array is empty.";
        p = "stairsWoodBirch";
        S = "PAEONIA";
        n = "orange_stained_hardened_clay";
        v = "dynamicLight_";
        q = "motionYExpr_";
        l = "EXPOSED_CUT_COPPER";
        ga = "random.drink";
        c = "FT ca";
        m = "<custom>";
        j = "Build: ";
        J = "spawnWither";
        Aa = "supported, and ";
        Da = 0xDDA10141 ^ 0xDDA90141;
        t = "shadowColor0Nearest";
        E = "Item Type";
        X = 0xF10DCEE1 ^ 0xF10DDEE0;
        V = "commands.time.usage";
        L = Float.intBitsToFloat(0x5691BCBD ^ 0x6991BCBD);
        x = "\u00a71";
        N = "stat.noteblockPlayed";
        g = 0x8A38BC0E ^ 0x8A384C04;
        G = "days";
        i = 0x91B21EA4 ^ 0x91B21F93;
        w = "#slice9#";
        Ka = "spruce_door";
        W = "Could not load sound file ";
        I = "{\"parent\": \"builtin/generated\",\"textures\": {";
        R = "Wq}31s[.g26K";
        h = "SHOW_ITEM";
        D = "commands.clear.usage";
        ja = 0x328B0FB0 ^ 0x328B8FD6;
        Q = "diorite_slab_double";
    }

    public MQa_1() {
        MQa_1 a2;
    }
}

