/*
 * Decompiled with CFR 0.152.
 */
public final class MTa {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final int Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final float y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final float i;
    public static final String M;
    public static final long k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public MTa() {
        MTa a2;
    }

    static {
        u = "Back.4a";
        Ka = "title.oldgl1";
        F = "GL12.GL_PACK_SKIP_IMAGES";
        w = "container.enchant.level.one";
        b = "prismarineBrickSlab";
        y = 2.5F /* ZKM Deobf */;
        S = "incompatibleResourcePacks";
        la = "gui/emotes/selected/";
        Da = "STRIKETHROUGH";
        Ja = "heightvalCase_";
        D = "multiplayer.stopSleeping";
        Ga = 510.0F /* ZKM Deobf */;
        U = 176 /* ZKM Deobf Int */;
        N = "shadowHardwareFiltering1";
        I = "stone_shovel";
        j = "lapisSpread";
        v = "uniform [ _a-zA-Z0-9]+ watershadow;.*";
        Ia = "shadowcolor0Mipmap";
        c = 4294967039 /* ZKM Deobf Int */;
        W = "ZYX";
        e = "Chunk has wrong size";
        K = 299999 /* ZKM Deobf Int */;
        J = "Level spawn location";
        Aa = -5.099999904632568F /* ZKM Deobf */;
        G = "Mesa Plateau F";
        M = "category_";
        B = "&a\u0421\u043a\u043e\u0440\u043e\u0441\u0442\u044c \u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f \u043a\u0430\u043c\u0435\u0440\u044b \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0430 \u043d\u0430 &f";
        H = "nbt.";
        E = "\u0000\u0004\u0001\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\f\u0002\u023b\u0000\u0003\u023b\u0000\u0004=\u0000";
        k = 0x31CE01B9250F4CEAL ^ 0x31CE01B91FD74EB5L;
        Z = "xtrafrancyz";
        ha = "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u021a\u0002\u100f\u0000\u0003\u1006\u0002\u0004\u1006\u0003\u0005\u1007\u0004\u0006\u1208\u0001";
        d = "6a";
        Ha = 13000 /* ZKM Deobf Int */;
        m = "entity.horse.name";
        i = 9.5F /* ZKM Deobf */;
        q = "\u4ef9";
        ca = "GL11.GL_PIXEL_MAP_I_TO_B";
        X = ".jpg";
        Y = "options.title";
        ja = 20294 /* ZKM Deobf Int */;
        Q = "ghast/ghast_shooting";
        a = "|";
        A = "options.renderDistance.normal";
        s = "General";
        p = "iron_ore";
        t = "GL11.GL_2_BYTES";
        ga = "Golems";
        n = ", name: ";
        o = -1.149999976158142F /* ZKM Deobf */;
        T = "Furnace";
        x = 33554432 /* ZKM Deobf Int */;
        P = "gui.no";
        l = 5931634 /* ZKM Deobf Int */;
        r = "Aborted";
        R = "diamondSize";
        h = "not-available";
        g = 6000 /* ZKM Deobf Int */;
        fa = "diode";
        f = ".tooltip.";
        z = 5379 /* ZKM Deobf Int */;
        Fa = "R32UI";
        L = "RandomSeed";
        V = "potion.prefix.diffuse";
        O = 1694498815 /* ZKM Deobf Int */;
        C = "glass_bottle";
    }
}

