/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  D
 *  YY
 */
public final class Naa_1
implements D {
    public final int graniteCount;
    public final boolean useLavaLakes;
    public final int redstoneMinHeight;
    public final int lavaLakeChance;
    public final float depthNoiseScaleExponent;
    public final int gravelMaxHeight;
    public final int diamondSize;
    public final int gravelCount;
    public final int gravelSize;
    public final int ironMinHeight;
    public final int dirtMinHeight;
    public final int diamondMaxHeight;
    public final float coordinateScale;
    public final int dirtCount;
    public final boolean useDungeons;
    public final int lapisCenterHeight;
    public final int lapisSize;
    public final boolean useStrongholds;
    public final int coalSize;
    public final int coalMaxHeight;
    public final int ironMaxHeight;
    public final int diamondMinHeight;
    public final float biomeDepthWeight;
    public final boolean useMonuments;
    public final int dioriteSize;
    public final float depthNoiseScaleX;
    public final int dungeonChance;
    public final int biomeSize;
    public final int gravelMinHeight;
    public final boolean useTemples;
    public final float biomeScaleWeight;
    public final int graniteMinHeight;
    public final float baseSize;
    public final int redstoneMaxHeight;
    public final int dioriteCount;
    public final int goldSize;
    public final int goldMaxHeight;
    public final int dirtSize;
    public final float mainNoiseScaleX;
    public final boolean useVillages;
    public final int goldCount;
    public final int lapisCount;
    public final int fixedBiome;
    public final int dioriteMaxHeight;
    public final int ironSize;
    public final float lowerLimitScale;
    public final float biomeDepthOffSet;
    public final int waterLakeChance;
    public final int coalMinHeight;
    public final float mainNoiseScaleY;
    public final int riverSize;
    public final int graniteMaxHeight;
    public final float stretchY;
    public final boolean useWaterLakes;
    public final int dirtMaxHeight;
    public final float depthNoiseScaleZ;
    public final int dioriteMinHeight;
    public final int coalCount;
    public final boolean useCaves;
    public final float mainNoiseScaleZ;
    public final int ironCount;
    public final int diamondCount;
    public final int redstoneCount;
    public final boolean useRavines;
    public final int graniteSize;
    public final int andesiteSize;
    public final float upperLimitScale;
    public final int andesiteMaxHeight;
    public final boolean useMineShafts;
    public final int andesiteMinHeight;
    public final float biomeScaleOffset;
    public final int goldMinHeight;
    public final boolean useLavaOceans;
    public final int redstoneSize;
    public final int andesiteCount;
    public final int lapisSpread;
    public final float heightScale;
    public final int seaLevel;

    public /* synthetic */ Naa_1(YY yY2, dY dY2) {
        Naa_1 c2 = yY2;
        Naa_1 b2 = this;
        b2((YY)c2);
    }

    private Naa_1(YY yY2) {
        Naa_1 a2;
        Naa_1 b2 = yY2;
        Naa_1 naa_1 = a2 = this;
        Naa_1 naa_12 = b2;
        Naa_1 naa_13 = a2;
        Naa_1 naa_14 = b2;
        Naa_1 naa_15 = a2;
        Naa_1 naa_16 = b2;
        Naa_1 naa_17 = a2;
        Naa_1 naa_18 = b2;
        Naa_1 naa_19 = a2;
        Naa_1 naa_110 = b2;
        Naa_1 naa_111 = a2;
        Naa_1 naa_112 = b2;
        Naa_1 naa_113 = a2;
        Naa_1 naa_114 = b2;
        Naa_1 naa_115 = a2;
        Naa_1 naa_116 = b2;
        Naa_1 naa_117 = a2;
        Naa_1 naa_118 = b2;
        Naa_1 naa_119 = a2;
        Naa_1 naa_120 = b2;
        Naa_1 naa_121 = a2;
        Naa_1 naa_122 = b2;
        Naa_1 naa_123 = a2;
        Naa_1 naa_124 = b2;
        Naa_1 naa_125 = a2;
        Naa_1 naa_126 = b2;
        Naa_1 naa_127 = a2;
        Naa_1 naa_128 = b2;
        Naa_1 naa_129 = a2;
        Naa_1 naa_130 = b2;
        Naa_1 naa_131 = a2;
        Naa_1 naa_132 = b2;
        Naa_1 naa_133 = a2;
        Naa_1 naa_134 = b2;
        Naa_1 naa_135 = a2;
        Naa_1 naa_136 = b2;
        Naa_1 naa_137 = a2;
        Naa_1 naa_138 = b2;
        Naa_1 naa_139 = a2;
        Naa_1 naa_140 = b2;
        Naa_1 naa_141 = a2;
        Naa_1 naa_142 = b2;
        Naa_1 naa_143 = a2;
        Naa_1 naa_144 = b2;
        Naa_1 naa_145 = a2;
        Naa_1 naa_146 = b2;
        Naa_1 naa_147 = a2;
        Naa_1 naa_148 = b2;
        Naa_1 naa_149 = a2;
        Naa_1 naa_150 = b2;
        Naa_1 naa_151 = a2;
        Naa_1 naa_152 = b2;
        a2.coordinateScale = ((YY)naa_152).coordinateScale;
        naa_151.heightScale = ((YY)naa_152).heightScale;
        naa_151.upperLimitScale = ((YY)b2).upperLimitScale;
        a2.lowerLimitScale = ((YY)naa_150).lowerLimitScale;
        naa_149.depthNoiseScaleX = ((YY)naa_150).depthNoiseScaleX;
        naa_149.depthNoiseScaleZ = ((YY)b2).depthNoiseScaleZ;
        a2.depthNoiseScaleExponent = ((YY)naa_148).depthNoiseScaleExponent;
        naa_147.mainNoiseScaleX = ((YY)naa_148).mainNoiseScaleX;
        naa_147.mainNoiseScaleY = ((YY)b2).mainNoiseScaleY;
        a2.mainNoiseScaleZ = ((YY)naa_146).mainNoiseScaleZ;
        naa_145.baseSize = ((YY)naa_146).baseSize;
        naa_145.stretchY = ((YY)b2).stretchY;
        a2.biomeDepthWeight = ((YY)naa_144).biomeDepthWeight;
        naa_143.biomeDepthOffSet = ((YY)naa_144).biomeDepthOffset;
        naa_143.biomeScaleWeight = ((YY)b2).biomeScaleWeight;
        a2.biomeScaleOffset = ((YY)naa_142).biomeScaleOffset;
        naa_141.seaLevel = ((YY)naa_142).seaLevel;
        naa_141.useCaves = ((YY)b2).useCaves;
        a2.useDungeons = ((YY)naa_140).useDungeons;
        naa_139.dungeonChance = ((YY)naa_140).dungeonChance;
        naa_139.useStrongholds = ((YY)b2).useStrongholds;
        a2.useVillages = ((YY)naa_138).useVillages;
        naa_137.useMineShafts = ((YY)naa_138).useMineShafts;
        naa_137.useTemples = ((YY)b2).useTemples;
        a2.useMonuments = ((YY)naa_136).useMonuments;
        naa_135.useRavines = ((YY)naa_136).useRavines;
        naa_135.useWaterLakes = ((YY)b2).useWaterLakes;
        a2.waterLakeChance = ((YY)naa_134).waterLakeChance;
        naa_133.useLavaLakes = ((YY)naa_134).useLavaLakes;
        naa_133.lavaLakeChance = ((YY)b2).lavaLakeChance;
        a2.useLavaOceans = ((YY)naa_132).useLavaOceans;
        naa_131.fixedBiome = ((YY)naa_132).fixedBiome;
        naa_131.biomeSize = ((YY)b2).biomeSize;
        a2.riverSize = ((YY)naa_130).riverSize;
        naa_129.dirtSize = ((YY)naa_130).dirtSize;
        naa_129.dirtCount = ((YY)b2).dirtCount;
        a2.dirtMinHeight = ((YY)naa_128).dirtMinHeight;
        naa_127.dirtMaxHeight = ((YY)naa_128).dirtMaxHeight;
        naa_127.gravelSize = ((YY)b2).gravelSize;
        a2.gravelCount = ((YY)naa_126).gravelCount;
        naa_125.gravelMinHeight = ((YY)naa_126).gravelMinHeight;
        naa_125.gravelMaxHeight = ((YY)b2).gravelMaxHeight;
        a2.graniteSize = ((YY)naa_124).graniteSize;
        naa_123.graniteCount = ((YY)naa_124).graniteCount;
        naa_123.graniteMinHeight = ((YY)b2).graniteMinHeight;
        a2.graniteMaxHeight = ((YY)naa_122).graniteMaxHeight;
        naa_121.dioriteSize = ((YY)naa_122).dioriteSize;
        naa_121.dioriteCount = ((YY)b2).dioriteCount;
        a2.dioriteMinHeight = ((YY)naa_120).dioriteMinHeight;
        naa_119.dioriteMaxHeight = ((YY)naa_120).dioriteMaxHeight;
        naa_119.andesiteSize = ((YY)b2).andesiteSize;
        a2.andesiteCount = ((YY)naa_118).andesiteCount;
        naa_117.andesiteMinHeight = ((YY)naa_118).andesiteMinHeight;
        naa_117.andesiteMaxHeight = ((YY)b2).andesiteMaxHeight;
        a2.coalSize = ((YY)naa_116).coalSize;
        naa_115.coalCount = ((YY)naa_116).coalCount;
        naa_115.coalMinHeight = ((YY)b2).coalMinHeight;
        a2.coalMaxHeight = ((YY)naa_114).coalMaxHeight;
        naa_113.ironSize = ((YY)naa_114).ironSize;
        naa_113.ironCount = ((YY)b2).ironCount;
        a2.ironMinHeight = ((YY)naa_112).ironMinHeight;
        naa_111.ironMaxHeight = ((YY)naa_112).ironMaxHeight;
        naa_111.goldSize = ((YY)b2).goldSize;
        a2.goldCount = ((YY)naa_110).goldCount;
        naa_19.goldMinHeight = ((YY)naa_110).goldMinHeight;
        naa_19.goldMaxHeight = ((YY)b2).goldMaxHeight;
        a2.redstoneSize = ((YY)naa_18).redstoneSize;
        naa_17.redstoneCount = ((YY)naa_18).redstoneCount;
        naa_17.redstoneMinHeight = ((YY)b2).redstoneMinHeight;
        a2.redstoneMaxHeight = ((YY)naa_16).redstoneMaxHeight;
        naa_15.diamondSize = ((YY)naa_16).diamondSize;
        naa_15.diamondCount = ((YY)b2).diamondCount;
        a2.diamondMinHeight = ((YY)naa_14).diamondMinHeight;
        naa_13.diamondMaxHeight = ((YY)naa_14).diamondMaxHeight;
        naa_13.lapisSize = ((YY)b2).lapisSize;
        a2.lapisCount = ((YY)naa_12).lapisCount;
        naa_1.lapisCenterHeight = ((YY)naa_12).lapisCenterHeight;
        naa_1.lapisSpread = ((YY)b2).lapisSpread;
    }
}

