/*
 * Decompiled with CFR 0.152.
 */
public final class Npa {
    public static final int Fa;
    public static final String Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final double Ka;
    public static final int Aa;
    public static final int S;
    public static final float Z;
    public static final double Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final float a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final double f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    public Npa() {
        Npa a2;
    }

    static {
        u = "GL11.GL_DEPTH_TEST";
        P = "sz";
        q = "String too big (was ";
        p = "Right.Right58";
        l = "Left.Shape32123";
        X = "%(?:(\\d+)\\$)?([A-Za-z%]|$)";
        g = "q.skin.hat";
        a = 9.374999046325684F /* ZKM Deobf */;
        i = "rym";
        n = "TEXT_TIMER";
        H = "scaleXExpr_";
        Fa = 999 /* ZKM Deobf Int */;
        v = "Right47";
        S = 16776437 /* ZKM Deobf Int */;
        t = "Ticking Particle";
        I = "GREATER_THAN";
        L = ".mcmeta";
        ca = "DOWN";
        f = 2500.0D /* ZKM Deobf */;
        e = "_stained_glass";
        Z = 3.2300000190734863F /* ZKM Deobf */;
        R = "COM7";
        M = "GL11.GL_CONSTANT_ATTENUATION";
        V = "placeholderColor_";
        Ka = 0.46875D /* ZKM Deobf */;
        h = "seamless";
        J = 1800 /* ZKM Deobf Int */;
        c = "sky.end";
        k = 376 /* ZKM Deobf Int */;
        b = "animationId_";
        ga = "Invalid forwards & up combination";
        Ia = "netherBrickWall";
        Ja = "commands.gamerule.success";
        Aa = 3188 /* ZKM Deobf Int */;
        O = "note.";
        A = "commands.scoreboard.objectives.usage";
        B = "R16_SNORM";
        m = "BODY_BACK";
        d = "DISPENSER";
        ja = "Replaced sound event location {}";
        N = "Overworld";
        o = "LOGIN";
        r = 0.7063935995101929F /* ZKM Deobf */;
        y = "shadow entities";
        G = "rotation_rate";
        D = 3509 /* ZKM Deobf Int */;
        x = "Max Health";
        la = -12.399999618530273F /* ZKM Deobf */;
        fa = "\u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u0441\u0442\u0430\u0442\u0443\u0441 \u043d\u0430\u0447\u0438\u043d\u0430\u044f \u043e\u0442 \"\u043f\u0440\u0430\u0439\u043c\"";
        s = "ARCHIVED";
        Ga = 2039713 /* ZKM Deobf Int */;
        E = "tooltip_";
        Ha = "ofConnectedTextures";
        Q = "SUCCESS";
        W = "BOMB";
        C = "Player is either on another team or not on any team. Cannot remove from team '";
        K = "RGB16_SNORM";
        Da = "trapped_chest";
        U = "CookTime";
        z = "%%";
        Y = 0.0005000000237487257D /* ZKM Deobf */;
        j = "SHPH";
        T = " I ";
        w = "assets/minecraft/models/block/diamond_block.json";
        F = 3572 /* ZKM Deobf Int */;
    }
}

