/*
 * Decompiled with CFR 0.152.
 */
public final class nqa {
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final long i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public nqa() {
        nqa a2;
    }

    static {
        n = "\\G([-!]?[\\w-]*)(?:$|,)";
        S = "_carpet";
        ja = 34921 /* ZKM Deobf Int */;
        Ha = "options.snooper.title";
        u = "titanium_ore";
        x = "coalMaxHeight";
        b = "goldNugget";
        Z = "ofLazyChunkLoading:";
        la = 0.03490658476948738F /* ZKM Deobf */;
        w = "TEXT_INPUT";
        i = 0x296395CF01889891L ^ 0x296395CF01889891L;
        E = "slowness";
        fa = "demo.help.jump";
        G = "hide-armor";
        v = "copper_trapdoor";
        z = "COM9";
        h = "cubic";
        r = "(Session ID is ";
        Ja = "Disabled auto read";
        Q = "GL11.GL_CURRENT_RASTER_POSITION";
        P = "GL15.GL_WRITE_ONLY";
        g = "cobbledDeepslate";
        R = 654 /* ZKM Deobf Int */;
        m = "concrete";
        T = "SkullType";
        Da = "F9";
        O = 767 /* ZKM Deobf Int */;
        H = "effectScale";
        Ga = "Packet ";
        a = "([\u0430-\u044f\u0410-\u042f\u0451\u0401]|[a-zA-Z]|[0-9])";
        l = "EDIT2D";
        C = 390 /* ZKM Deobf Int */;
        I = 2967 /* ZKM Deobf Int */;
        f = 6404 /* ZKM Deobf Int */;
        J = "easing";
        c = "+0-1+2+3+13&4-4";
        t = "\u4efb ";
        ga = "UPDATE_LATENCY";
        e = 687 /* ZKM Deobf Int */;
        Aa = "forceUnicodeFont";
        D = "options.stream.micToggleBehavior";
        k = "shaders/post/blobs.json";
        K = "[/MOTD][AD]";
        F = "rabbitRaw";
        X = "shaders/post/phosphor.json";
        ca = "minecraft:particle_expire_if_not_in_blocks";
        B = "19";
        A = "\u00a7f";
        L = 663 /* ZKM Deobf Int */;
        Ka = "Right15";
        W = 33324 /* ZKM Deobf Int */;
        U = "cos";
        q = "ScaleGUI";
        N = 1920 /* ZKM Deobf Int */;
        V = "demo.help.title";
        d = 35049 /* ZKM Deobf Int */;
        p = "Body.Shape30";
        y = "cacao_beans";
        M = "textures/environment/snow.png";
        o = "TexMagFilS";
        Y = "Batching chunks";
        j = "HOPS";
        s = "pathfind";
    }
}

