/*
 * Decompiled with CFR 0.152.
 */
public final class NQa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final float la;
    public static final float ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final float y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final int J;
    public static final int A;
    public static final String I;

    public NQa_1() {
        NQa_1 a2;
    }

    static {
        a = "Save ShadersMod configuration.";
        e = "onFire";
        j = 0xEDFC17AB ^ 0xEDFC27A8;
        o = "Invalid client command!";
        B = 0xE31625EF ^ 0xE3D57122;
        Ha = "cocoa_stage_[0-2]";
        c = "poison";
        p = "Shape43123";
        l = "http://mc.vimeworld.com/";
        S = "jeb_";
        n = "F7";
        D = "GL12.GL_UNSIGNED_BYTE_2_3_3_REV";
        s = Float.intBitsToFloat(0xA1E9F378 ^ 0x1EC92A04);
        m = Float.intBitsToFloat(0x1A8D4E0E ^ 0xDA0D4E0E);
        Ka = "minecraft:emitter_rate_instant";
        Ga = " \u0438\u0437 10";
        T = "auxtargets";
        F = "\u041d\u0443\u0431\u0430\u0441";
        X = "https:";
        ga = Float.intBitsToFloat(0xC02FAE2D ^ 0x15C9D1E);
        G = "stat.fallOneCm";
        g = "advMode.setCommand";
        P = "GL11.GL_LIGHT6";
        Z = "amount";
        N = "tulipPink";
        R = "mob.guardian.land.idle";
        u = "EASE_IN_OUT_SINE";
        I = "path";
        V = ") is not a valid type. Ignoring.";
        Da = "cape";
        w = "[ \t]*const[ \t]*bool[ \t]*(shadowcolor1Nearest|shadowColor1Nearest|shadowColor1MinMagNearest)[ \t]*=[ \t]*true[ \t]*;.*";
        H = "options.renderDistance";
        C = "+";
        ja = "rotation";
        k = "WEATHERED_CUT_COPPER";
        A = 0xD701177F ^ 0x28FEE890;
        q = "sticky";
        i = "input";
        M = "party_info";
        Q = 0xFADC19D9 ^ 0xFADC1877;
        t = "water_still";
        b = "step.";
        ha = "[%02d] ";
        h = "\u00a7r";
        ca = 0x4AF6129B ^ 0x4AF68EDB;
        x = "Head.Shape21";
        d = Float.intBitsToFloat(0xB0234304 ^ 0x70C34304);
        J = 0x73DE7BE7 ^ 0x73DEFF1A;
        Y = Float.intBitsToFloat(0xF5751BF7 ^ 0xB60A1BF7);
        r = "Could not save configuration (";
        E = "texture.potion_overlay";
        U = "LightningBolt";
        W = "dynamic/%s_%d";
        f = "GL11.GL_TEXTURE_GEN_Q";
        Fa = "bow_pulling_0";
        L = 0x23A6242E ^ 0x23A624A1;
        O = "animations";
        K = 0x2A6CA9F9 ^ 0x2A6CAB46;
        Ja = "of.options.SMOOTH_BIOMES";
        la = Float.intBitsToFloat(0xD6F00E26 ^ 0x17FE6840);
        fa = "rabbit_hide";
        v = "endStoneBrickSlab";
        Aa = 0xD3D3C976 ^ 0xD3D3CA61;
        Ia = "checkLight";
        y = Float.intBitsToFloat(0xDA4ECD9 ^ 0xCDB82014);
        z = "HIDE_WITH_CHESTPLATE";
    }
}

