/*
 * Decompiled with CFR 0.152.
 */
public final class NQa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final float la;
    public static final float ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final float y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final int J;
    public static final int A;
    public static final String I;

    public NQa_1() {
        NQa_1 a2;
    }

    static {
        a = "Save ShadersMod configuration.";
        e = "onFire";
        j = 12291 /* ZKM Deobf Int */;
        o = "Invalid client command!";
        B = 12801229 /* ZKM Deobf Int */;
        Ha = "cocoa_stage_[0-2]";
        c = "poison";
        p = "Shape43123";
        l = "http://mc.vimeworld.com/";
        S = "jeb_";
        n = "F7";
        D = "GL12.GL_UNSIGNED_BYTE_2_3_3_REV";
        s = -0.6283185482025146F /* ZKM Deobf */;
        m = -4.0F /* ZKM Deobf */;
        Ka = "minecraft:emitter_rate_instant";
        Ga = " \u0438\u0437 10";
        T = "auxtargets";
        F = "\u041d\u0443\u0431\u0430\u0441";
        X = "https:";
        ga = -15.199999809265137F /* ZKM Deobf */;
        G = "stat.fallOneCm";
        g = "advMode.setCommand";
        P = "GL11.GL_LIGHT6";
        Z = "amount";
        N = "tulipPink";
        R = "mob.guardian.land.idle";
        u = "EASE_IN_OUT_SINE";
        I = "path";
        V = ") is not a valid type. Ignoring.";
        Da = "cape";
        w = "[ \t]*const[ \t]*bool[ \t]*(shadowcolor1Nearest|shadowColor1Nearest|shadowColor1MinMagNearest)[ \t]*=[ \t]*true[ \t]*;.*";
        H = "options.renderDistance";
        C = "+";
        ja = "rotation";
        k = "WEATHERED_CUT_COPPER";
        A = 4294967279 /* ZKM Deobf Int */;
        q = "sticky";
        i = "input";
        M = "party_info";
        Q = 430 /* ZKM Deobf Int */;
        t = "water_still";
        b = "step.";
        ha = "[%02d] ";
        h = "\u00a7r";
        ca = 40000 /* ZKM Deobf Int */;
        x = "Head.Shape21";
        d = -7.0F /* ZKM Deobf */;
        J = 34045 /* ZKM Deobf Int */;
        Y = 255.0F /* ZKM Deobf */;
        r = "Could not save configuration (";
        E = "texture.potion_overlay";
        U = "LightningBolt";
        W = "dynamic/%s_%d";
        f = "GL11.GL_TEXTURE_GEN_Q";
        Fa = "bow_pulling_0";
        L = 143 /* ZKM Deobf Int */;
        O = "animations";
        K = 703 /* ZKM Deobf Int */;
        Ja = "of.options.SMOOTH_BIOMES";
        la = -8.899999618530273F /* ZKM Deobf */;
        fa = "rabbit_hide";
        v = "endStoneBrickSlab";
        Aa = 791 /* ZKM Deobf Int */;
        Ia = "checkLight";
        y = -2.450000047683716F /* ZKM Deobf */;
        z = "HIDE_WITH_CHESTPLATE";
    }
}

