/*
 * Decompiled with CFR 0.152.
 */
public final class NSa {
    public static final int la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final int S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final float B;
    public static final float d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Da = "ProgramFiles(X86)";
        b = -6.0F /* ZKM Deobf */;
        ja = "gl_caps[ARB_map_buffer_alignment]";
        B = 30.0F /* ZKM Deobf */;
        V = "\u041e\u0448\u0438\u0431\u043a\u0430. ";
        Q = "commands.spawnpoint.success";
        K = "textures/gui/presets/isles.png";
        N = "--- END PROFILE DUMP ---\n\n";
        ga = 206 /* ZKM Deobf Int */;
        G = "Back-face Translucent";
        k = "SIS";
        T = 32872 /* ZKM Deobf Int */;
        n = "OXIDIZED_COPPER";
        c = -32.0F /* ZKM Deobf */;
        ca = "blackstoneWall";
        F = "wooden_shovel";
        x = "minecraft:blocks/snow";
        I = "GL11.GL_MAP2_GRID_SEGMENTS";
        S = 677 /* ZKM Deobf Int */;
        R = "debug_all_block_states";
        a = "create";
        la = 10592673 /* ZKM Deobf Int */;
        j = "of.message.fr.shaders2";
        fa = "chiseled_tuff";
        X = "GL11.GL_EXTENSIONS";
        Ka = "tile.workbench.name";
        v = 61456 /* ZKM Deobf Int */;
        q = "mob.ghast.moan";
        d = 0.062437500804662704F /* ZKM Deobf */;
        l = "commands.setblock.usage";
        f = "pm";
        u = "east=true,north=false,south=false,up=true,west=true";
        r = "Setting user: ";
        w = "bookshelf.properties";
        h = "Head.Shape20";
        W = "Dinnerbone";
        t = "rose";
        O = ", value=";
        Ja = "commands.playsound.usage";
        Y = 807 /* ZKM Deobf Int */;
        s = 10485760 /* ZKM Deobf Int */;
        C = "\u043f\u043e\u0441\u043b\u0435 \u0438\u0445 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f \u0438 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f \u0437\u0430\u043d\u043e\u0432\u043e, \u0438\u043b\u0438 \u043f\u0440\u0438";
        D = "regular";
        L = "More weights defined than tiles, trimming weights: ";
        z = "disconnect.spam";
        Aa = 10065 /* ZKM Deobf Int */;
        e = "[ \t]*const[ \t]*int[ \t]*superSamplingLevel[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        E = "GL14.GL_SECONDARY_COLOR_ARRAY_TYPE";
        A = "green";
        y = "potionValue";
        i = "iron_door";
        Ga = ", type=";
        m = "stained_glass";
        P = "AUTO";
        p = "ofCloudsHeight";
        g = "EyeOfEnderSignal";
        Z = "The player name '";
        J = "textures/gui/presets/luck.png";
        o = "GL15.GL_BUFFER_SIZE";
        U = 32993 /* ZKM Deobf Int */;
        H = "math.lerp";
        M = "party/slider.png";
        Ha = "titleAndSubtitle";
    }

    public NSa() {
        NSa a2;
    }
}

