/*
 * Decompiled with CFR 0.152.
 */
public final class Nta {
    public static final String Fa;
    public static final double Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final float Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final long Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final double B;
    public static final String d;
    public static final double a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final float L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        N = "oxidizedChiseledCopper";
        z = "GL11.GL_COLOR_MATERIAL";
        m = "RightLeg.RightLeg2";
        X = "random.orb";
        b = "Right.Right47";
        o = "GL11.GL_C4F_N3F_V3F";
        f = "GL11.GL_LIGHTING";
        R = "echo";
        U = "stat.useItem.";
        M = "minHeight";
        W = "nalcCaptureOpenDevice";
        J = "Shape63123";
        P = "str_ends";
        H = "audioSession_";
        Ka = "TEXT_PLACEHOLDER";
        q = "disabled";
        e = "OPEN_FILE";
        i = "prepender";
        Y = "uniform [ _a-zA-Z0-9]+ shadowtex1;.*";
        l = "Unable to allocate sprite for glyph '";
        K = 34140 /* ZKM Deobf Int */;
        s = 4282392608 /* ZKM Deobf Int */;
        p = 609 /* ZKM Deobf Int */;
        t = "east=true,north=true,south=false,west=true";
        S = "inner_right";
        Fa = "angleYvalCase_";
        Ia = 0.996999979019165D /* ZKM Deobf */;
        Ha = "little";
        ga = "ench";
        fa = 30021 /* ZKM Deobf Int */;
        A = "http://mc.vimeworld.ru/";
        T = "down";
        Da = "FRAMERATE_LIMIT";
        j = "HEARTS";
        Q = "_pulling_0";
        Z = 0x4131351A59E8214BL ^ 0x4131351A59E82CE7L;
        y = "obfuscated";
        h = 32897 /* ZKM Deobf Int */;
        x = "commands.worldborder.damage.amount.usage";
        r = 3569 /* ZKM Deobf Int */;
        ca = "00000000-0000-0000-0000-000000000000";
        n = "Jungle";
        Aa = "autumn_grass.png";
        Ja = 778 /* ZKM Deobf Int */;
        O = "disable-cps-limit";
        E = 231871 /* ZKM Deobf Int */;
        g = "commands.worldborder.set.success";
        d = "textures/body/fierywings_blue.png";
        F = 37191 /* ZKM Deobf Int */;
        u = "SET_WARNING_BLOCKS";
        Ga = 0.24975000321865082F /* ZKM Deobf */;
        I = "textures/gui/server_selection.png";
        v = "commands.trigger.usage";
        ja = "snooper_partner";
        k = "bambooFenceGate";
        L = -14.399999618530273F /* ZKM Deobf */;
        c = "nether_brick_slab";
        G = "servers/";
        B = 0.007499999832361937D /* ZKM Deobf */;
        D = "%d game time, %d day time";
        la = "lime_glazed_terracotta";
        w = "demo.help.movement";
        C = "commands.summon.success";
        a = -0.25D /* ZKM Deobf */;
        V = "Elder";
    }

    public Nta() {
        Nta a2;
    }
}

