/*
 * Decompiled with CFR 0.152.
 */
public final class NTa_1 {
    public static final double Ea;
    public static final String Ca;
    public static final float ia;
    public static final String Ma;
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final double la;
    public static final int ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final int e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final long J;
    public static final String A;
    public static final int I;

    public NTa_1() {
        NTa_1 a2;
    }

    static {
        f = "DIAGONAL_RIGHT";
        M = "Probably not. Jar signature remains and client brand is untouched.";
        L = "Cutout";
        h = 0x27622A77 ^ 0x27622BDA;
        V = 0xA99FB29D ^ 0xA99FBE8D;
        Ha = "Get static field error";
        P = 0xBCCDC40D ^ 0xBCCDCFED;
        Ea = Double.longBitsToDouble(0xD5227ECB97A6551FL ^ 0x6AC418ADF1C03379L);
        m = "GL11.GL_LINE_SMOOTH";
        H = "GL13.GL_TEXTURE_CUBE_MAP_POSITIVE_Y";
        v = "Right12";
        G = "No OpenGL 2.0";
        N = ", yDelta: ";
        b = "Texture {} with size {}x{} limits mip level from {} to {}";
        d = "options.reducedDebugInfo";
        Ca = "_glass_";
        u = "\u042d\u0444\u0444\u0435\u043a\u0442 \u0441\u043c\u0435\u0440\u0442\u0438";
        W = "addServer.add";
        C = 0xDC6ECB00 ^ 0xDC6ECB0A;
        S = "AES";
        D = Float.intBitsToFloat(0x7C83BC0D ^ 0xC2308F3E);
        e = 0xDF3D5EAD ^ 0x190E042;
        ca = 0xD7A5EB17 ^ 0xD7A5E60A;
        K = "stat.talkedToVillager";
        a = "Translucent";
        Ma = "gbuffers_entities";
        fa = "streamSystemVolume";
        p = "Reloading ResourceManager: ";
        q = "commands.weather.thunder";
        I = 0x250CA339 ^ 0x25DB70EA;
        ba = "gl_max_texture_size";
        Ia = "commands.trigger.success";
        Y = "spruce_trapdoor";
        U = "west";
        n = "Could not save crash report to ";
        A = "C:\\Dev\\minecraft-1.8.8\\src\\minecraft\\assets\\minidot\\models\\mask";
        Z = "Classic Lighting";
        c = Float.intBitsToFloat(0x5B3120BA ^ 0x642120BA);
        z = "ofRandomMobs";
        ia = Float.intBitsToFloat(0x2E855787 ^ 0x158645E8);
        g = "mc_Entity";
        t = "gameDir";
        r = "createWorld.customize.custom.upperLimitScale";
        Ka = Float.intBitsToFloat(0xCEB9BA7D ^ 0xF3668119);
        s = "maxHeight.";
        B = "\u0412\u044b\u0431\u043e\u0440 \u044d\u043c\u043e\u0446\u0438\u0439";
        w = 0x94DCA401 ^ 0x94DC3858;
        F = "Snowy Kingdom";
        Fa = "roomState_";
        T = "OptiFine_1.8.8_HD_U_H8";
        Aa = "14";
        x = "height";
        Q = "composite";
        E = "whitelist_enabled";
        O = "menu.shareToLan";
        Da = "\u041a\u043d\u043e\u043f\u043a\u0438 \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044f";
        o = 0x9CA62736 ^ 0x9CA6AAB5;
        k = 0x7DA9206F ^ 0x7DA95554;
        ga = 0x5417EBAC ^ 0x54176BE3;
        R = "half_slab";
        l = 0x3A989FC ^ 0x3497652;
        ja = "ThrownEgg";
        i = "Bat";
        Ja = "driedKelpBlock";
        y = "all_outside";
        la = Double.longBitsToDouble(0x4B16AE84BD7452F7L ^ 0xB446E84BD7452F7L);
        J = 0x94BB574D3EDF3574L ^ 0x94BB574D3EDF1F8CL;
        ha = Float.intBitsToFloat(0xF0EA58AA ^ 0x30696B99);
        j = "UUIDMost";
        Ga = "GL11.GL_MULT";
        X = 0x4E53A3F9 ^ 0x4E532380;
    }
}

