/*
 * Decompiled with CFR 0.152.
 */
public final class NTa_1 {
    public static final double Ea;
    public static final String Ca;
    public static final float ia;
    public static final String Ma;
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final double la;
    public static final int ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final int e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final long J;
    public static final String A;
    public static final int I;

    public NTa_1() {
        NTa_1 a2;
    }

    static {
        f = "DIAGONAL_RIGHT";
        M = "Probably not. Jar signature remains and client brand is untouched.";
        L = "Cutout";
        h = 429 /* ZKM Deobf Int */;
        V = 3088 /* ZKM Deobf Int */;
        Ha = "Get static field error";
        P = 3040 /* ZKM Deobf Int */;
        Ea = -0.7D /* ZKM Deobf */;
        m = "GL11.GL_LINE_SMOOTH";
        H = "GL13.GL_TEXTURE_CUBE_MAP_POSITIVE_Y";
        v = "Right12";
        G = "No OpenGL 2.0";
        N = ", yDelta: ";
        b = "Texture {} with size {}x{} limits mip level from {} to {}";
        d = "options.reducedDebugInfo";
        Ca = "_glass_";
        u = "\u042d\u0444\u0444\u0435\u043a\u0442 \u0441\u043c\u0435\u0440\u0442\u0438";
        W = "addServer.add";
        C = 10 /* ZKM Deobf Int */;
        S = "AES";
        D = -0.3499999940395355F /* ZKM Deobf */;
        e = 3735928559 /* ZKM Deobf Int */;
        ca = 3357 /* ZKM Deobf Int */;
        K = "stat.talkedToVillager";
        a = "Translucent";
        Ma = "gbuffers_entities";
        fa = "streamSystemVolume";
        p = "Reloading ResourceManager: ";
        q = "commands.weather.thunder";
        I = 14144467 /* ZKM Deobf Int */;
        ba = "gl_max_texture_size";
        Ia = "commands.trigger.success";
        Y = "spruce_trapdoor";
        U = "west";
        n = "Could not save crash report to ";
        A = "C:\\Dev\\minecraft-1.8.8\\src\\minecraft\\assets\\minidot\\models\\mask";
        Z = "Classic Lighting";
        c = 0.5625F /* ZKM Deobf */;
        z = "ofRandomMobs";
        ia = 0.0020000000949949026F /* ZKM Deobf */;
        g = "mc_Entity";
        t = "gameDir";
        r = "createWorld.customize.custom.upperLimitScale";
        Ka = 0.10899999737739563F /* ZKM Deobf */;
        s = "maxHeight.";
        B = "\u0412\u044b\u0431\u043e\u0440 \u044d\u043c\u043e\u0446\u0438\u0439";
        w = 40025 /* ZKM Deobf Int */;
        F = "Snowy Kingdom";
        Fa = "roomState_";
        T = "OptiFine_1.8.8_HD_U_H8";
        Aa = "14";
        x = "height";
        Q = "composite";
        E = "whitelist_enabled";
        O = "menu.shareToLan";
        Da = "\u041a\u043d\u043e\u043f\u043a\u0438 \u0434\u0432\u0438\u0436\u0435\u043d\u0438\u044f";
        o = 36227 /* ZKM Deobf Int */;
        k = 30011 /* ZKM Deobf Int */;
        ga = 32847 /* ZKM Deobf Int */;
        R = "half_slab";
        l = 14745518 /* ZKM Deobf Int */;
        ja = "ThrownEgg";
        i = "Bat";
        Ja = "driedKelpBlock";
        y = "all_outside";
        la = 75.0D /* ZKM Deobf */;
        J = 0x94BB574D3EDF3574L ^ 0x94BB574D3EDF1F8CL;
        ha = -4.099999904632568F /* ZKM Deobf */;
        j = "UUIDMost";
        Ga = "GL11.GL_MULT";
        X = 32889 /* ZKM Deobf Int */;
    }
}

