/*
 * Decompiled with CFR 0.152.
 */
public final class opa {
    public static final String Da;
    public static final int ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final float z;
    public static final int X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final long R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final double I;

    static {
        l = "bezier_left_time";
        x = "LeftLeg.LeftLeg4";
        d = "userProperties";
        Ja = 3351 /* ZKM Deobf Int */;
        j = "body2";
        J = "Failed set loaded flag";
        ca = 36758 /* ZKM Deobf Int */;
        i = "Back.9b";
        Y = 3348 /* ZKM Deobf Int */;
        W = "ScoreComponent{name='";
        Ga = "netherStalk_[0-2]";
        T = "uv_width";
        y = "playsound";
        V = "_far";
        H = "carrotOnAStick";
        U = 1.6277135610580444F /* ZKM Deobf */;
        X = 32913 /* ZKM Deobf Int */;
        z = -135.0F /* ZKM Deobf */;
        S = "silver_stained_glass";
        a = "symmetry";
        L = "Body.Shape21";
        Da = "Shape19";
        b = 40026 /* ZKM Deobf Int */;
        f = "Something's taking too long! '";
        o = "Left.Shape31123";
        s = "Unbalanced curly brackets {}: ";
        g = "textures/body/neonwings_yellow.png";
        v = "Body.Shape10";
        K = ", expected to find a JsonArray";
        E = "22";
        w = 65536 /* ZKM Deobf Int */;
        fa = "level://";
        ja = "BLOCK_ALTERNATIVES";
        Aa = "silver";
        h = "h";
        c = "InSize";
        k = "Quitting";
        D = "cod";
        q = "worldborder";
        r = "chestplateIron";
        Z = "of.options.FOG_FANCY";
        P = "blue_orchid";
        t = "LINES_Z";
        m = "row_";
        A = "anvil_slightly_damaged";
        p = "Page 1 of 3";
        M = "##TNetworkInfoHud";
        n = 12288 /* ZKM Deobf Int */;
        N = "HasReproduced";
        O = "RightLeg.Shape13";
        Ka = "streamChatUserFilter";
        I = -0.8999999761581421D /* ZKM Deobf */;
        u = "items";
        F = "Reading NBT data";
        G = "chiseledDeepslate";
        R = 0x25442E4D9B604710L ^ 0x25442E4D9B9FB8EFL;
        Ha = "Block being ticked";
        e = "impelY_";
        C = "commands.stats.success";
        B = "Shaderpack check list error. Code ";
        Q = "uniform";
    }

    public opa() {
        opa a2;
    }
}

