/*
 * Decompiled with CFR 0.152.
 */
public final class POa {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final float v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final int M;
    public static final float k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        e = "textures/misc/pumpkinblur.png";
        x = 0x7D0123B1 ^ 0x7D012FC8;
        S = " must be 0 or greater";
        Da = Float.intBitsToFloat(0x8FFF5156 ^ 0x306FF281);
        Fa = "FRAGMENT";
        j = "GL11.GL_T4F_V4F";
        k = Float.intBitsToFloat(0x703F5531 ^ 0xB3085531);
        q = "GL11.GL_NORMAL_ARRAY_STRIDE";
        p = "Must be 64 pixels wide";
        Q = "wither";
        i = "slot.armor.head";
        la = "stat.crouchOneCm";
        d = "HoverEvent{action=";
        Ja = "exposed_cut_copper_stairs";
        ga = Float.intBitsToFloat(0xAD5D8475 ^ 0xEEFD8475);
        b = "of.options.CLOUDS";
        V = "/shaders/lang/";
        ha = "Comparator";
        H = "Sun";
        u = "Could not initialize MiniDot models";
        X = "titleColor_";
        fa = "[Shaders] Invalid block ID: ";
        v = Float.intBitsToFloat(0xD60863 ^ 0x41F20863);
        s = "underwaterOverlay";
        B = 0x9976C63D ^ 0x99C48AE5;
        P = "Unknown block name %s";
        g = "Piece2.Shape12";
        w = "Ribbon5";
        D = 0xA1F10806 ^ 0xA1F1222C;
        c = "GL15.GL_STREAM_COPY";
        Y = 0x422BA01E ^ 0x422BA2FC;
        M = 0xA7168C0D ^ 0xA7160C47;
        r = "doorAcacia";
        m = 0x92B5962B ^ 0x92B596CE;
        n = "DebugLevelSource";
        A = "ELEMENT_EXISTS";
        Aa = Float.intBitsToFloat(0x7FF867B7 ^ 0x3E5067B7);
        T = "textures/pet/android.png";
        U = "MC_GL_VENDOR_INTEL";
        y = "facing=west,half=bottom,shape=straight";
        z = "visibility";
        Ha = "GL13.GL_PROXY_TEXTURE_CUBE_MAP";
        N = "of.options.shaders.TWEAK_BLOCK_DAMAGE";
        W = "myceliumparticle.png";
        J = 0x189C5273 ^ 0x189C50DA;
        o = Float.intBitsToFloat(0x899B7191 ^ 0xB557BD5C);
        Ga = "*cracks redstone whip*";
        f = "Expected ";
        G = "uv[";
        O = "CHAT_LINKS";
        E = "&a\u041f\u0443\u0442\u044c \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d \u0432 \u043b\u043e\u0433";
        l = Float.intBitsToFloat(0x565B8756 ^ 0x16ED932D);
        Ka = "Filesize is bigger than maximum allowed (file is ";
        K = "eProgressTimer_";
        ca = "Something changed (";
        h = "kf";
        ja = Float.intBitsToFloat(0x4E4DED3A ^ 0x8E1DED3A);
        Z = "matchItems";
        a = "angleYval_";
        t = "textures/body/garlands1.png";
        Ia = "golden_pickaxe";
        L = "%2.3f";
        I = "cut_copper_stairs";
        C = 0xD665B3B7 ^ 0xD665B285;
        F = "useProgram ";
        R = "leftLow";
    }

    public POa() {
        POa a2;
    }
}

