/*
 * Decompiled with CFR 0.152.
 */
public final class POa {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final float v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final int M;
    public static final float k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        e = "textures/misc/pumpkinblur.png";
        x = 3193 /* ZKM Deobf Int */;
        S = " must be 0 or greater";
        Da = -1.1299999952316284F /* ZKM Deobf */;
        Fa = "FRAGMENT";
        j = "GL11.GL_T4F_V4F";
        k = -183.0F /* ZKM Deobf */;
        q = "GL11.GL_NORMAL_ARRAY_STRIDE";
        p = "Must be 64 pixels wide";
        Q = "wither";
        i = "slot.armor.head";
        la = "stat.crouchOneCm";
        d = "HoverEvent{action=";
        Ja = "exposed_cut_copper_stairs";
        ga = 320.0F /* ZKM Deobf */;
        b = "of.options.CLOUDS";
        V = "/shaders/lang/";
        ha = "Comparator";
        H = "Sun";
        u = "Could not initialize MiniDot models";
        X = "titleColor_";
        fa = "[Shaders] Invalid block ID: ";
        v = 10.25F /* ZKM Deobf */;
        s = "underwaterOverlay";
        B = 11685080 /* ZKM Deobf Int */;
        P = "Unknown block name %s";
        g = "Piece2.Shape12";
        w = "Ribbon5";
        D = 10794 /* ZKM Deobf Int */;
        c = "GL15.GL_STREAM_COPY";
        Y = 738 /* ZKM Deobf Int */;
        M = 32842 /* ZKM Deobf Int */;
        r = "doorAcacia";
        m = 229 /* ZKM Deobf Int */;
        n = "DebugLevelSource";
        A = "ELEMENT_EXISTS";
        Aa = 21.0F /* ZKM Deobf */;
        T = "textures/pet/android.png";
        U = "MC_GL_VENDOR_INTEL";
        y = "facing=west,half=bottom,shape=straight";
        z = "visibility";
        Ha = "GL13.GL_PROXY_TEXTURE_CUBE_MAP";
        N = "of.options.shaders.TWEAK_BLOCK_DAMAGE";
        W = "myceliumparticle.png";
        J = 681 /* ZKM Deobf Int */;
        o = 0.02500000037252903F /* ZKM Deobf */;
        Ga = "*cracks redstone whip*";
        f = "Expected ";
        G = "uv[";
        O = "CHAT_LINKS";
        E = "&a\u041f\u0443\u0442\u044c \u0441\u043e\u0445\u0440\u0430\u043d\u0435\u043d \u0432 \u043b\u043e\u0433";
        l = 5.690000057220459F /* ZKM Deobf */;
        Ka = "Filesize is bigger than maximum allowed (file is ";
        K = "eProgressTimer_";
        ca = "Something changed (";
        h = "kf";
        ja = -3.25F /* ZKM Deobf */;
        Z = "matchItems";
        a = "angleYval_";
        t = "textures/body/garlands1.png";
        Ia = "golden_pickaxe";
        L = "%2.3f";
        I = "cut_copper_stairs";
        C = 306 /* ZKM Deobf Int */;
        F = "useProgram ";
        R = "leftLow";
    }

    public POa() {
        POa a2;
    }
}

