/*
 * Decompiled with CFR 0.152.
 */
public final class Ppa_2 {
    public static final String Ja;
    public static final String ja;
    public static final float Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final double N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final float J;
    public static final int A;
    public static final String I;

    static {
        I = "start can't be > end: ";
        M = "with";
        w = "GL14.GL_MAX_TEXTURE_LOD_BIAS";
        e = "\u041a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044f";
        i = 36761 /* ZKM Deobf Int */;
        j = "%s/%s/%s";
        F = "container.enchant.clue";
        k = "Right.Right55";
        C = "Invalid pitch";
        a = "Remove not allowed.";
        Ha = -2.5F /* ZKM Deobf */;
        s = "ofTime:";
        d = "Unable to get CW facing for axis ";
        x = "\u0413\u043e\u043b\u043e\u0432\u0430";
        n = "EXPLOSION_HUGE";
        Z = "scaleYExact_";
        A = 33880 /* ZKM Deobf Int */;
        H = "selectServer.deleteButton";
        Ja = "animations/pet/megabox_animation.json";
        U = "of.options.DROPPED_ITEMS";
        K = 117 /* ZKM Deobf Int */;
        T = "Guardian";
        fa = "Left.Shape37123";
        y = "easeInOutBack";
        ja = "CRACKED";
        R = "SALMON";
        Q = 2983 /* ZKM Deobf Int */;
        V = "gl_caps[ARB_map_buffer_range]";
        L = "warped_door";
        h = "' \u043d\u0435 \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u0435\u0442\u0441\u044f";
        D = "Particle Type";
        v = "VOID";
        W = "\u0441\u0438\u043d\u0438\u043c \u0446\u0432\u0435\u0442\u043e\u043c \u0432 \u0434\u0435\u0440\u0435\u0432\u0435.";
        S = 2944 /* ZKM Deobf Int */;
        f = "warped_trapdoor";
        P = "RHOMBUS_MIDDLE";
        J = 0.8552113175392151F /* ZKM Deobf */;
        q = "shaders/post/spider.json";
        u = "Unsupported mob type for FollowOwnerGoal";
        E = ", subSlots=";
        p = "BODY";
        X = "screenHeight_";
        b = "transportation";
        g = "https://";
        Ka = 5383 /* ZKM Deobf Int */;
        z = "[ \t]*const[ \t]*bool[ \t]*generateShadowColorMipmap[ \t]*=[ \t]*true[ \t]*;.*";
        N = 730.0D /* ZKM Deobf */;
        Aa = "horizontal";
        m = "deepslateBrickSlab";
        O = "Error executing task";
        t = "mangrove_fence_gate";
        G = "GL11.GL_MAP1_COLOR_4";
        Y = "GL11.GL_MODULATE";
        c = "lime_wool";
        Ga = "xExact_";
        r = "eyeBrightnessHalflife";
        l = "GL11.GL_POLYGON_MODE";
        o = "of.message.an.shaders1";
        B = " \u00a77=\u00a7a ";
    }

    public Ppa_2() {
        Ppa_2 a2;
    }
}

