/*
 * Decompiled with CFR 0.152.
 */
public final class pPa_1 {
    public static final String Ca;
    public static final int ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final float la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final int Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final double u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        j = "GL11.GL_NAND";
        E = "Biome ID is out of bounds: ";
        e = "oreRedstone";
        y = "1a";
        u = Double.longBitsToDouble(0x3C6EF7E76CEF3B5AL ^ 0x83D76E7ECCEF3B5AL);
        b = "PlayerCreated";
        d = "commands.worldborder.damage.buffer.success";
        Ga = 0x532F6E4C ^ 0x532F446B;
        a = "Block colormap: ";
        J = 0xA80B72EB ^ 0xA80BF28C;
        ba = "CLOUDS";
        t = "commands.generic.parameter.invalid";
        Ma = "redSandStone";
        L = "gray_stained_glass";
        Da = "0.5, 1, 0.89, 1";
        Ja = "fog.end";
        l = "HEART";
        p = "Back.2a";
        n = "flax";
        Ka = "' already exists!";
        f = 0x5ACDA54 ^ 0x5ACDA5F;
        ha = "chiseledbrick";
        ga = 0x5F74BD23 ^ 0xA05E20AC;
        i = "mob.villager.death";
        Ha = "commands.entitydata.failed";
        ia = 0x2B9273FA ^ 0x2B927EFA;
        F = "INTERRUPTED";
        s = "Right53";
        P = 0x29720F19 ^ 0x29728BE0;
        D = "GL11.GL_TRIANGLES";
        la = Float.intBitsToFloat(0x3B5349E ^ 0x42EFD5D6);
        O = 0xEA675FFA ^ 0xEA675D38;
        Z = "createWorld.customize.custom.useMonuments";
        Q = "HORSE";
        X = "commands.worldborder.center.success";
        m = ", ignitionSpeed=";
        G = 0x92C9372A ^ 0x92C9BFDA;
        R = 0xD39F059C ^ 0xD39F076F;
        M = "createWorld.customize.presets";
        Y = Float.intBitsToFloat(0x32B00221 ^ 0x8C37913F);
        w = "GL11.GL_INVALID_OPERATION";
        H = "bed_(?:feet|head)_(?:end|side|top)";
        ja = 0x296048D0 ^ 0x29604883;
        C = "textures/gui/container/creative_inventory/tab_";
        q = " cap ";
        W = 0x9EF92087 ^ 0x6006DF78;
        ca = "textures/entity/villager/priest.png";
        K = "Now with less numbers";
        x = Float.intBitsToFloat(0x30DD071B ^ 0x8F22FBA2);
        fa = 0x72619518 ^ 0x7261941E;
        T = Float.intBitsToFloat(0xF63ECD03 ^ 0x894132FC);
        Aa = "minX_";
        r = "commands.generic.exception";
        U = "MC_GL_RENDERER_OTHER";
        I = " - ";
        z = "\u4ecc";
        o = "Could not save profiler results to ";
        Ca = "/party leave";
        c = Float.intBitsToFloat(0xA06CBE1A ^ 0x9FF52780);
        S = 0xE6F977CB ^ 0xE6F93D77;
        h = "GRADIENT";
        v = "q.";
        Fa = "mob.cow.step";
        g = "netherrack";
        k = "(";
        V = "cyan_stained_hardened_clay";
        A = "showModels";
        B = "white_tulip";
        Ia = 0xBB7F310D ^ 0xBB7F3C98;
        N = "bytes where max allowed: ";
    }

    public pPa_1() {
        pPa_1 a2;
    }
}

