/*
 * Decompiled with CFR 0.152.
 */
public final class pPa_1 {
    public static final String Ca;
    public static final int ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final float la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final int Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final double u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        j = "GL11.GL_NAND";
        E = "Biome ID is out of bounds: ";
        e = "oreRedstone";
        y = "1a";
        u = -0.10000000149011612D /* ZKM Deobf */;
        b = "PlayerCreated";
        d = "commands.worldborder.damage.buffer.success";
        Ga = 10791 /* ZKM Deobf Int */;
        a = "Block colormap: ";
        J = 32871 /* ZKM Deobf Int */;
        ba = "CLOUDS";
        t = "commands.generic.parameter.invalid";
        Ma = "redSandStone";
        L = "gray_stained_glass";
        Da = "0.5, 1, 0.89, 1";
        Ja = "fog.end";
        l = "HEART";
        p = "Back.2a";
        n = "flax";
        Ka = "' already exists!";
        f = 11 /* ZKM Deobf Int */;
        ha = "chiseledbrick";
        ga = 4280982927 /* ZKM Deobf Int */;
        i = "mob.villager.death";
        Ha = "commands.entitydata.failed";
        ia = 3328 /* ZKM Deobf Int */;
        F = "INTERRUPTED";
        s = "Right53";
        P = 34041 /* ZKM Deobf Int */;
        D = "GL11.GL_TRIANGLES";
        la = 13.680000305175781F /* ZKM Deobf */;
        O = 706 /* ZKM Deobf Int */;
        Z = "createWorld.customize.custom.useMonuments";
        Q = "HORSE";
        X = "commands.worldborder.center.success";
        m = ", ignitionSpeed=";
        G = 35056 /* ZKM Deobf Int */;
        R = 755 /* ZKM Deobf Int */;
        M = "createWorld.customize.presets";
        Y = -0.2647942900657654F /* ZKM Deobf */;
        w = "GL11.GL_INVALID_OPERATION";
        H = "bed_(?:feet|head)_(?:end|side|top)";
        ja = 83 /* ZKM Deobf Int */;
        C = "textures/gui/container/creative_inventory/tab_";
        q = " cap ";
        W = 4278190079 /* ZKM Deobf Int */;
        ca = "textures/entity/villager/priest.png";
        K = "Now with less numbers";
        x = -1.999899983406067F /* ZKM Deobf */;
        fa = 262 /* ZKM Deobf Int */;
        T = 3.4028234663852886e+38F /* ZKM Deobf */;
        Aa = "minX_";
        r = "commands.generic.exception";
        U = "MC_GL_RENDERER_OTHER";
        I = " - ";
        z = "\u4ecc";
        o = "Could not save profiler results to ";
        Ca = "/party leave";
        c = 1.2000000476837158F /* ZKM Deobf */;
        S = 19132 /* ZKM Deobf Int */;
        h = "GRADIENT";
        v = "q.";
        Fa = "mob.cow.step";
        g = "netherrack";
        k = "(";
        V = "cyan_stained_hardened_clay";
        A = "showModels";
        B = "white_tulip";
        Ia = 3477 /* ZKM Deobf Int */;
        N = "bytes where max allowed: ";
    }

    public pPa_1() {
        pPa_1 a2;
    }
}

