/*
 * Decompiled with CFR 0.152.
 */
public final class pQa_1 {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final float X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final float u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final float s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        G = "Short";
        z = "right.Shape40";
        b = "options.stream.chat.enabled.always";
        P = 14737632 /* ZKM Deobf Int */;
        I = "CON";
        J = " as it does not match what we currently have (";
        A = "Ticking entity";
        L = "o o O";
        U = 33998 /* ZKM Deobf Int */;
        n = 10243 /* ZKM Deobf Int */;
        Q = "grass-colorm";
        W = 5858897 /* ZKM Deobf Int */;
        X = 0.3926999866962433F /* ZKM Deobf */;
        O = "EntryDoor";
        Fa = 371 /* ZKM Deobf Int */;
        R = 20304 /* ZKM Deobf Int */;
        o = "ROOT ";
        Ja = "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u100a\u0000";
        m = " colors: ";
        q = "shadow clear";
        t = 9984 /* ZKM Deobf Int */;
        Ma = "commands.clone.outOfWorld";
        j = 3345 /* ZKM Deobf Int */;
        E = "commands.generic.entity.invalidUuid";
        ca = "http:";
        B = "ACX";
        S = "ru_ru";
        Ga = "GL11.GL_CURRENT_RASTER_DISTANCE";
        g = "Invalid nonce!";
        C = "BorderSize";
        p = "rabbitCooked";
        e = "An objective with the name '";
        a = "fancyGraphics:";
        y = "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0208";
        V = 32904 /* ZKM Deobf Int */;
        h = "  ~";
        Ha = "9a";
        T = "glass";
        w = "2a";
        u = 2.549999952316284F /* ZKM Deobf */;
        Aa = "gl_caps[ARB_framebuffer_sRGB]";
        k = "hoverColorVal_";
        ga = -0.9700000286102295F /* ZKM Deobf */;
        s = -4.25F /* ZKM Deobf */;
        Ka = 2.701580047607422F /* ZKM Deobf */;
        F = 34069 /* ZKM Deobf Int */;
        v = 3332 /* ZKM Deobf Int */;
        Y = "ofAnimatedWater:";
        f = "ItemRotation";
        Ia = "Starting integrated server";
        x = "weatheredCopperTrapdoor";
        fa = 512.0F /* ZKM Deobf */;
        Da = "_minecraft._tcp.";
        K = "GL11.GL_PIXEL_MAP_B_TO_B";
        H = 15826224 /* ZKM Deobf Int */;
        Z = " #X";
        c = "GROWING";
        ia = "cs";
        ba = "NO_WRAP";
        ja = "1:00";
        l = "Air";
        ha = " cannot receive number arguments!";
        d = "WIDTH";
        r = "\\(";
        la = "rotate_y";
        N = 0.8100000023841858F /* ZKM Deobf */;
        M = "commands.effect.success";
        i = "left";
        D = "commands.summon.usage";
    }

    public pQa_1() {
        pQa_1 a2;
    }
}

