/*
 * Decompiled with CFR 0.152.
 */
public final class pQa_1 {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final float X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final float u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final float s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        G = "Short";
        z = "right.Shape40";
        b = "options.stream.chat.enabled.always";
        P = 0x5842F1CA ^ 0x58A2112A;
        I = "CON";
        J = " as it does not match what we currently have (";
        A = "Ticking entity";
        L = "o o O";
        U = 0xBC78535 ^ 0xBC701FB;
        n = 0x874A060D ^ 0x874A2E0E;
        Q = "grass-colorm";
        W = 0xAB360B7F ^ 0xAB6F6D2E;
        X = Float.intBitsToFloat(0xEB3B4F94 ^ 0xD5F2406D);
        O = "EntryDoor";
        Fa = 0x9EAC8CFD ^ 0x9EAC8D8E;
        R = 0x394C1A87 ^ 0x394C55D7;
        o = "ROOT ";
        Ja = "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u100a\u0000";
        m = " colors: ";
        q = "shadow clear";
        t = 0xE1CBE9E3 ^ 0xE1CBCEE3;
        Ma = "commands.clone.outOfWorld";
        j = 0x12F2196A ^ 0x12F2147B;
        E = "commands.generic.entity.invalidUuid";
        ca = "http:";
        B = "ACX";
        S = "ru_ru";
        Ga = "GL11.GL_CURRENT_RASTER_DISTANCE";
        g = "Invalid nonce!";
        C = "BorderSize";
        p = "rabbitCooked";
        e = "An objective with the name '";
        a = "fancyGraphics:";
        y = "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0208";
        V = 0x6BD55C28 ^ 0x6BD5DCA0;
        h = "  ~";
        Ha = "9a";
        T = "glass";
        w = "2a";
        u = Float.intBitsToFloat(0x282D5BFD ^ 0x680E68CE);
        Aa = "gl_caps[ARB_framebuffer_sRGB]";
        k = "hoverColorVal_";
        ga = Float.intBitsToFloat(0x24549476 ^ 0x9B2CC59A);
        s = Float.intBitsToFloat(0xF432411E ^ 0x34BA411E);
        Ka = Float.intBitsToFloat(0xD13573E2 ^ 0x91199552);
        F = 0x31B5EE1D ^ 0x31B56B08;
        v = 0x670941AB ^ 0x67094CAF;
        Y = "ofAnimatedWater:";
        f = "ItemRotation";
        Ia = "Starting integrated server";
        x = "weatheredCopperTrapdoor";
        fa = Float.intBitsToFloat(0x249BCCE9 ^ 0x609BCCE9);
        Da = "_minecraft._tcp.";
        K = "GL11.GL_PIXEL_MAP_B_TO_B";
        H = 0x50A09029 ^ 0x5051ED19;
        Z = " #X";
        c = "GROWING";
        ia = "cs";
        ba = "NO_WRAP";
        ja = "1:00";
        l = "Air";
        ha = " cannot receive number arguments!";
        d = "WIDTH";
        r = "\\(";
        la = "rotate_y";
        N = Float.intBitsToFloat(0x2E5B399D ^ 0x111465B4);
        M = "commands.effect.success";
        i = "left";
        D = "commands.summon.usage";
    }

    public pQa_1() {
        pQa_1 a2;
    }
}

