/*
 * Decompiled with CFR 0.152.
 */
public final class PRa {
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final int Z;
    public static final double Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final int D;
    public static final float f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final float E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public PRa() {
        PRa a2;
    }

    static {
        Ka = "attribute [_a-zA-Z0-9]+ mc_midTexCoord.*";
        x = "unbreaking";
        k = "spacing";
        i = "of.general.custom";
        Ha = "Weight";
        s = "container.minecart";
        O = "To prevent level corruption, the current game has quit.";
        w = "Invalid range list: ";
        Ga = "cosine";
        fa = "ofFastRender";
        n = "Keystrokes: ";
        ja = "hatchetWood";
        c = "endPortalFrame";
        J = "MODEL_NOT_SET";
        r = "glass_yellow";
        Z = 32836 /* ZKM Deobf Int */;
        Q = "spruceFence";
        T = "textures/particle/particles.png";
        L = 34464 /* ZKM Deobf Int */;
        l = "Invalid fadeIn/fadeOut times, sum is not 24h: ";
        Ia = "Undefined";
        U = 1000 /* ZKM Deobf Int */;
        ha = 30014 /* ZKM Deobf Int */;
        Da = "&a\u0414\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0430 &f";
        C = "minecartHopper";
        N = "\u043a\u043e\u0438\u043d\u0430";
        Aa = ".*gl_MultiTexCoord3.*";
        u = "Vec3d[";
        M = "TIME";
        ga = 1200 /* ZKM Deobf Int */;
        z = 2138367 /* ZKM Deobf Int */;
        p = "CUTOUT";
        E = 128.0F /* ZKM Deobf */;
        R = -2.4742000102996826F /* ZKM Deobf */;
        t = "GL14.GL_FOG_COORDINATE_ARRAY_TYPE";
        f = 0.33230000734329224F /* ZKM Deobf */;
        y = "GL13.GL_TEXTURE25";
        K = 20401 /* ZKM Deobf Int */;
        o = "redstoneMinHeight";
        m = 7936 /* ZKM Deobf Int */;
        F = "stretch_to_lifetime";
        G = 10.699999809265137F /* ZKM Deobf */;
        P = "commands.entitydata.usage";
        la = "dedicated";
        X = "of.options.RANDOM_MOBS";
        S = 34056 /* ZKM Deobf Int */;
        Fa = "Invalid amount of values specified (expected ";
        d = "PORTAL_PARTICLES";
        q = "playerCheckLight";
        H = "record_ward";
        a = "overpowered";
        Y = 512.0D /* ZKM Deobf */;
        W = "Front.9b";
        b = "trip_wire(?:_source)?";
        D = 136 /* ZKM Deobf Int */;
        A = "SKY";
        v = 833 /* ZKM Deobf Int */;
        j = "prismarineCrystals";
        h = "YELLOW";
        g = "options.particles.minimal";
        B = "horsearmorgold";
        I = "layer1";
        e = "Right.Right38";
        V = "Must be 64 pixels high";
        Ja = "shadowTranslucent";
        ca = "iron_shovel";
    }
}

