/*
 * Decompiled with CFR 0.152.
 */
public final class Psa {
    public static final double ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final float a;
    public static final String b;
    public static final int l;
    public static final int e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        j = "ViSmH";
        O = "polishedBlackstoneBrickSlab";
        l = 602 /* ZKM Deobf Int */;
        Ja = -2.75F /* ZKM Deobf */;
        Z = "RGBA16";
        t = 4096.0D /* ZKM Deobf */;
        ca = "_monster_egg";
        z = "REMOVE";
        Ka = "ati";
        G = "record_far";
        ga = 5.497787143782138D /* ZKM Deobf */;
        h = "Couldn't save server list";
        I = "%s format: %s";
        e = 8704 /* ZKM Deobf Int */;
        y = "CLEAR3D";
        Y = "ARMOR_HEAD";
        F = "LastUpdate";
        a = -5.699999809265137F /* ZKM Deobf */;
        R = "uniform [ _a-zA-Z0-9]+ gaux4;.*";
        M = 60 /* ZKM Deobf Int */;
        N = "Atlas path";
        S = "of.options.AF_LEVEL";
        Da = "cpu_cores";
        C = "diamond_chestplate";
        Ha = "rewardExp";
        D = 24.399999618530273F /* ZKM Deobf */;
        B = "commands.scoreboard.teams.list.count";
        p = ", tool=";
        s = "TaigaHills";
        g = "on";
        V = "Z";
        Ga = "commands.xp.success";
        n = 4283437072 /* ZKM Deobf Int */;
        W = "registry";
        u = "birch_slab";
        o = "resistance";
        K = 1036 /* ZKM Deobf Int */;
        L = "Level Name";
        ja = "mob.wither.spawn";
        d = "&";
        r = "jungle_slab";
        J = "interpolate";
        f = "of.options.save.default";
        w = "mob.creeper.death";
        T = "%s clear disabled";
        v = "coords_";
        P = 16711422 /* ZKM Deobf Int */;
        X = "GL13.GL_PRIMARY_COLOR";
        k = "WWW";
        fa = "INGAME";
        U = "Particles: ";
        q = "GL14.GL_FRAGMENT_DEPTH";
        Q = "dummy";
        E = "Shape60123";
        H = "GL14.GL_BLEND_DST_RGB";
        b = "model";
        x = "RAIN";
        Aa = "heldItemId";
        c = "textures/entity/horse/horse_skeleton.png";
        A = "roll";
        i = "PORTABILITY";
        m = 289 /* ZKM Deobf Int */;
    }

    public Psa() {
        Psa a2;
    }
}

