/*
 * Decompiled with CFR 0.152.
 */
public final class psa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final long Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final double q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final double D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final double C;
    public static final String i;
    public static final String M;
    public static final double k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        i = "custom";
        H = "mangrove_planks";
        ja = "walkSpeed";
        u = "movement";
        U = Float.intBitsToFloat(0x8E9273A3 ^ 0xB0F343D8);
        J = 0x3CD6D8A0 ^ 0x3C111F67;
        o = "RECONNECT";
        R = "commands.give.tagError";
        Ia = "mushroom_red";
        A = "clear_";
        w = "' - expected object, found ";
        G = Float.intBitsToFloat(0x4343046 ^ 0x451DA9DC);
        D = Double.longBitsToDouble(0x9F0FF4A7BA283666L ^ 0x5F06D55CEE6C1B7EL);
        K = "deepslate_brick_stairs";
        Ka = "hide_with_chestplate";
        f = "red_sandstone_wall";
        Q = "MiniDot";
        ca = "AES/GCM/NoPadding";
        v = "\u0000\u000b\u0002\u0000\u0001\u000b\u000b\u0000\u0007\u0000\u0001$\u0002$\u00039\u0000\u00049\u0000\u00054\u0001\u00064\u0001\u0007$\b$\t$\n$\u000b$";
        O = "loading single player";
        W = "score_";
        t = Float.intBitsToFloat(0x8C80320F ^ 0x3156455F);
        Fa = "cracked_stonebrick";
        fa = "wool";
        j = "Holder{width=";
        B = "CONNECTING";
        T = "Unable to create resourcepack folder: ";
        r = 0x1D6669EC ^ 0x1D666866;
        b = ", style=";
        y = "Failed to add player. {} already is in chunk {}, {}";
        Z = "uk_ua";
        m = "thirdperson_righthand";
        Ga = "q.helmet";
        ha = "potion.prefix.grenade";
        E = "streaming_";
        n = "q.gui_width";
        V = "party/checkbox/inactive.png";
        h = "Select a player to teleport to";
        z = "screenshot.failure";
        k = Double.longBitsToDouble(0xF15F4FF46BA39CEEL ^ 0xCEC6D66DF23A0574L);
        l = "leg";
        e = "options.snooper";
        p = "Weapon modifier";
        Ha = "Left.Shape5123";
        c = 0x75BED5C4 ^ 0x75BEC0C1;
        ga = "RabbitType";
        M = "GL13.GL_COMBINE";
        S = "STOP_DESTROY_BLOCK";
        C = Double.longBitsToDouble(0xDA97C68F76064A79L ^ 0xE500CCB206A59D73L);
        x = "SLIME";
        F = 0x3051C127 ^ 0x305141B7;
        P = "YEXPRANIM";
        Ja = Float.intBitsToFloat(0xDB3256C1 ^ 0xE40A46A3);
        X = "delta_time";
        I = "I'm working as hard as I can!";
        Aa = "apng";
        L = "block/cube_column";
        Y = 0x40539C9453FDB3B6L ^ 0x180268B91F68CC9BL;
        la = 0xCCB1D6D2 ^ 0xCCB1DBE7;
        q = Double.longBitsToDouble(0x1100B06D6E36ECFCL ^ 0x2ECBB8F76C43C9BAL);
        s = 0xA6CC73DA ^ 0xA6CC06EC;
        a = "replace_body";
        d = "textures/blocks/destroy_stage_8.png";
        N = Float.intBitsToFloat(0xB3917492 ^ 0x8DDDB85F);
        Da = "Netty Local Client IO #%d";
        g = "&e/cam goto <\u043d\u043e\u043c\u0435\u0440>&f: \u0422\u0435\u043b\u0435\u043f\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0442\u043e\u0447\u043a\u0443";
    }

    public psa_1() {
        psa_1 a2;
    }
}

