/*
 * Decompiled with CFR 0.152.
 */
public final class psa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final long Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final double q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final double D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final double C;
    public static final String i;
    public static final String M;
    public static final double k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        i = "custom";
        H = "mangrove_planks";
        ja = "walkSpeed";
        u = "movement";
        U = 0.21991150081157684F /* ZKM Deobf */;
        J = 13092807 /* ZKM Deobf Int */;
        o = "RECONNECT";
        R = "commands.give.tagError";
        Ia = "mushroom_red";
        A = "clear_";
        w = "' - expected object, found ";
        G = 10.600000381469727F /* ZKM Deobf */;
        D = -3.141592653589793D /* ZKM Deobf */;
        K = "deepslate_brick_stairs";
        Ka = "hide_with_chestplate";
        f = "red_sandstone_wall";
        Q = "MiniDot";
        ca = "AES/GCM/NoPadding";
        v = "\u0000\u000b\u0002\u0000\u0001\u000b\u000b\u0000\u0007\u0000\u0001$\u0002$\u00039\u0000\u00049\u0000\u00054\u0001\u00064\u0001\u0007$\b$\t$\n$\u000b$";
        O = "loading single player";
        W = "score_";
        t = -0.10471975803375244F /* ZKM Deobf */;
        Fa = "cracked_stonebrick";
        fa = "wool";
        j = "Holder{width=";
        B = "CONNECTING";
        T = "Unable to create resourcepack folder: ";
        r = 394 /* ZKM Deobf Int */;
        b = ", style=";
        y = "Failed to add player. {} already is in chunk {}, {}";
        Z = "uk_ua";
        m = "thirdperson_righthand";
        Ga = "q.helmet";
        ha = "potion.prefix.grenade";
        E = "streaming_";
        n = "q.gui_width";
        V = "party/checkbox/inactive.png";
        h = "Select a player to teleport to";
        z = "screenshot.failure";
        k = 0.025D /* ZKM Deobf */;
        l = "leg";
        e = "options.snooper";
        p = "Weapon modifier";
        Ha = "Left.Shape5123";
        c = 5381 /* ZKM Deobf Int */;
        ga = "RabbitType";
        M = "GL13.GL_COMBINE";
        S = "STOP_DESTROY_BLOCK";
        C = 0.0225D /* ZKM Deobf */;
        x = "SLIME";
        F = 32912 /* ZKM Deobf Int */;
        P = "YEXPRANIM";
        Ja = 0.718999981880188F /* ZKM Deobf */;
        X = "delta_time";
        I = "I'm working as hard as I can!";
        Aa = "apng";
        L = "block/cube_column";
        Y = 0x40539C9453FDB3B6L ^ 0x180268B91F68CC9BL;
        la = 3381 /* ZKM Deobf Int */;
        q = 0.2112D /* ZKM Deobf */;
        s = 30006 /* ZKM Deobf Int */;
        a = "replace_body";
        d = "textures/blocks/destroy_stage_8.png";
        N = 0.20000000298023224F /* ZKM Deobf */;
        Da = "Netty Local Client IO #%d";
        g = "&e/cam goto <\u043d\u043e\u043c\u0435\u0440>&f: \u0422\u0435\u043b\u0435\u043f\u043e\u0440\u0442\u0438\u0440\u043e\u0432\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0442\u043e\u0447\u043a\u0443";
    }

    public psa_1() {
        psa_1 a2;
    }
}

