/*
 * Decompiled with CFR 0.152.
 */
public final class pta {
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final float Da;
    public static final float ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final int r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final float H;
    public static final int c;
    public static final String B;
    public static final float d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public pta() {
        pta a2;
    }

    static {
        L = "tickPending";
        B = "gl_caps[EXT_separate_shader_objects]";
        H = -0.15707963705062866F /* ZKM Deobf */;
        G = "set";
        E = "HIDDEN";
        a = 4294967292 /* ZKM Deobf Int */;
        F = "diorite_wall";
        Y = "Couldn't parse ";
        Ca = "cobbled_deepslate_stairs";
        q = "textures/entity/witch.png";
        b = "Shape44123";
        m = "split_particle_speedThreshold";
        P = "of.options.shaders.shadersFolder";
        f = "No such minidot item: ";
        Z = 4294901759 /* ZKM Deobf Int */;
        W = "max_frame";
        r = 9999 /* ZKM Deobf Int */;
        k = 6913 /* ZKM Deobf Int */;
        I = "GL11.GL_INDEX_ARRAY_TYPE";
        Ka = 16777216 /* ZKM Deobf Int */;
        X = "streamMicToggleBehavior:";
        w = 3129871 /* ZKM Deobf Int */;
        O = "gray_wool";
        K = "resin_brick_stairs";
        M = "&e/cam clear&f: \u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435 \u0442\u043e\u0447\u043a\u0438";
        Ma = "\u0416\u0438\u0440\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442";
        S = "gl_caps[ARB_shadow]";
        o = "party";
        t = "\u0411\u0435\u0442\u0430";
        ja = "GL11.GL_ONE_MINUS_SRC_ALPHA";
        ia = "writable_book";
        Ja = "Why is it breaking :(";
        J = "of.options.ANIMATED_FIRE";
        ba = 115 /* ZKM Deobf Int */;
        n = "selectWorld.moreWorldOptions";
        p = "options-pvp.txt";
        U = 654311423 /* ZKM Deobf Int */;
        Da = -15.399999618530273F /* ZKM Deobf */;
        C = "chat.type.achievement";
        T = -13.449999809265137F /* ZKM Deobf */;
        u = 8193 /* ZKM Deobf Int */;
        s = "GL15.GL_ELEMENT_ARRAY_BUFFER_BINDING";
        y = "XXXXXXXX";
        la = 1034 /* ZKM Deobf Int */;
        v = "COLOR";
        V = 11.699999809265137F /* ZKM Deobf */;
        x = 4294967256 /* ZKM Deobf Int */;
        i = "direction";
        Fa = ".DS_Store";
        d = 0.6499999761581421F /* ZKM Deobf */;
        h = "commands.scoreboard.teams.remove.success";
        l = "C";
        R = 0.015609375201165676F /* ZKM Deobf */;
        e = "of.message.shaders.af2";
        c = 196 /* ZKM Deobf Int */;
        ga = "trackWidth_";
        ha = "This could be caused by a bug in the game or by the";
        Ga = "frame_time";
        Ia = "gl_caps[EXT_shadow_funcs]";
        N = "\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435";
        ca = -6.25F /* ZKM Deobf */;
        fa = "textures/entity/rabbit/caerbannog.png";
        D = "Failed while loading emote: {}";
        A = "gold";
        g = "STDERR";
        Ha = 353825 /* ZKM Deobf Int */;
        z = "assets/minecraft/models/block/grass_snowed.json";
        Aa = "gl_caps[ARB_draw_instanced]";
        j = "diorite_smooth";
        Q = "Invalid BlockModelRotation x: ";
    }
}

