/*
 * Decompiled with CFR 0.152.
 */
public final class pta {
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final float Da;
    public static final float ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final int r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final float H;
    public static final int c;
    public static final String B;
    public static final float d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public pta() {
        pta a2;
    }

    static {
        L = "tickPending";
        B = "gl_caps[EXT_separate_shader_objects]";
        H = Float.intBitsToFloat(0x66F01889 ^ 0xD8D0C1F5);
        G = "set";
        E = "HIDDEN";
        a = 0xABB769BE ^ 0x54489642;
        F = "diorite_wall";
        Y = "Couldn't parse ";
        Ca = "cobbled_deepslate_stairs";
        q = "textures/entity/witch.png";
        b = "Shape44123";
        m = "split_particle_speedThreshold";
        P = "of.options.shaders.shadersFolder";
        f = "No such minidot item: ";
        Z = 0x7AEE7251 ^ 0x85108DAE;
        W = "max_frame";
        r = 0x5F45804 ^ 0x5F47F0B;
        k = 0x79F5C42F ^ 0x79F5DF2E;
        I = "GL11.GL_INDEX_ARRAY_TYPE";
        Ka = 0x6553639B ^ 0x6453639B;
        X = "streamMicToggleBehavior:";
        w = 0x418B78AC ^ 0x41A4BAA3;
        O = "gray_wool";
        K = "resin_brick_stairs";
        M = "&e/cam clear&f: \u0423\u0434\u0430\u043b\u0438\u0442\u044c \u0432\u0441\u0435 \u0442\u043e\u0447\u043a\u0438";
        Ma = "\u0416\u0438\u0440\u043d\u044b\u0439 \u0442\u0435\u043a\u0441\u0442";
        S = "gl_caps[ARB_shadow]";
        o = "party";
        t = "\u0411\u0435\u0442\u0430";
        ja = "GL11.GL_ONE_MINUS_SRC_ALPHA";
        ia = "writable_book";
        Ja = "Why is it breaking :(";
        J = "of.options.ANIMATED_FIRE";
        ba = 0xD392DFF8 ^ 0xD392DF8B;
        n = "selectWorld.moreWorldOptions";
        p = "options-pvp.txt";
        U = 0x67753DFB ^ 0x418AC204;
        Da = Float.intBitsToFloat(0xA20437B ^ 0xCB56251D);
        C = "chat.type.achievement";
        T = Float.intBitsToFloat(0x30C3F927 ^ 0xF194CA14);
        u = 0xF77B77C5 ^ 0xF77B57C4;
        s = "GL15.GL_ELEMENT_ARRAY_BUFFER_BINDING";
        y = "XXXXXXXX";
        la = 0x7266DD7A ^ 0x7266D970;
        v = "COLOR";
        V = Float.intBitsToFloat(0xB8A9DCAF ^ 0xF992EF9C);
        x = 0x406983E7 ^ 0xBF967C3F;
        i = "direction";
        Fa = ".DS_Store";
        d = Float.intBitsToFloat(0xE93057DE ^ 0xD61631B8);
        h = "commands.scoreboard.teams.remove.success";
        l = "C";
        R = Float.intBitsToFloat(0x2978503E ^ 0x1507EE49);
        e = "of.message.shaders.af2";
        c = 0xAF2DAFBC ^ 0xAF2DAF78;
        ga = "trackWidth_";
        ha = "This could be caused by a bug in the game or by the";
        Ga = "frame_time";
        Ia = "gl_caps[EXT_shadow_funcs]";
        N = "\u041f\u043e\u0434\u0442\u0432\u0435\u0440\u0436\u0434\u0435\u043d\u0438\u0435";
        ca = Float.intBitsToFloat(0xD31D2674 ^ 0x13D52674);
        fa = "textures/entity/rabbit/caerbannog.png";
        D = "Failed while loading emote: {}";
        A = "gold";
        g = "STDERR";
        Ha = 0x4435C961 ^ 0x4430AF40;
        z = "assets/minecraft/models/block/grass_snowed.json";
        Aa = "gl_caps[ARB_draw_instanced]";
        j = "diorite_smooth";
        Q = "Invalid BlockModelRotation x: ";
    }
}

