/*
 * Decompiled with CFR 0.152.
 */
public final class Pua {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final double r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final int N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public Pua() {
        Pua a2;
    }

    static {
        W = "upload";
        la = "GL11.GL_RGBA12";
        M = "GHAST";
        g = "FPS: ";
        n = "mud_brick_stairs";
        V = "textures/entity/ghast/ghast_shooting.png";
        k = 0x3DCE59C9 ^ 0x3DCE5950;
        K = "Left.Shape10123";
        m = 0x9155837C ^ 0x910DF52F;
        fa = "gl_caps[EXT_draw_instanced]";
        B = "container.furnace";
        a = "textures/pet/zombie.png";
        I = 0x53823FB3 ^ 0x538236B3;
        w = "yellow_stained_glass";
        X = "nether_wart_stage_0";
        S = "rundll32 url.dll,FileProtocolHandler ";
        c = "Failed to instantiate ";
        T = 0xF1BEC50A ^ 0xF1BEC7A0;
        Q = "/emote.bobj";
        x = "multiplayer.title";
        h = "gl_caps[ARB_multisample]";
        ga = "iregex:";
        O = "Function is not supported";
        q = "HOUSTONIA";
        Y = "ARM";
        L = "flower(?:_(?:pot|dandelion|rose))?";
        b = 0xE936B414 ^ 0xE9EF7457;
        P = Float.intBitsToFloat(0x697F8796 ^ 0xAB018796);
        A = "GL11.GL_ALPHA8";
        C = "M3";
        Z = "slot.armor.feet";
        f = 0x4A86D572 ^ 0x4A86D7FD;
        d = 0x70599FE1 ^ 0x70D99FE1;
        Aa = "grass_top";
        F = 0x1A13BBA2 ^ 0x1A133346;
        t = "mob.zombie.metal";
        U = "GL13.GL_TEXTURE1";
        H = "\u041e\u0442\u043c\u0435\u043d\u0430";
        u = " when I expected it to be uploading; aborting task";
        ca = "horse.jumpStrength";
        R = 0x379CE508 ^ 0x379E7548;
        N = 0x383872EC ^ 0x38387399;
        Ga = "12b";
        j = "&e/cam start [\u0432\u0440\u0435\u043c\u044f]&f: \u0417\u0430\u043f\u0443\u0441\u0442\u0438\u0442\u044c \u0430\u043d\u0438\u043c\u0430\u0446\u0438\u044e (\u043d\u0430\u043f\u0440\u0438\u043c\u0435\u0440: /cam start 1m30s)";
        Ka = 0xFA0A1FC7 ^ 0xFA0A1F8E;
        ja = "Shape34123";
        l = "gl_caps[ARB_depth_texture]";
        Ja = "pos_";
        p = "CanBreakDoors";
        o = "options.stream.chat.userFilter.mods";
        s = "Time span: ";
        z = "bucket";
        G = "null (missing)";
        J = "*(";
        r = Double.longBitsToDouble(0x31E9D7BBECA4411L ^ 0x431C4407C1F965C3L);
        i = "assets/minecraft/models/block/cobblestone.json";
        Da = "textures/particle/particles";
        Ha = " for facing ";
        e = "options.stream.compression";
        D = "/\\* GAUX4FORMAT:RGB32F \\*/.*";
        E = "HOVERCOLORVAL_NOT_SET";
        v = "weight";
        y = "swordDiamond";
    }
}

