/*
 * Decompiled with CFR 0.152.
 */
public final class pua_1 {
    public static final String Ea;
    public static final int Ca;
    public static final double ia;
    public static final String Ma;
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final float Ia;
    public static final int la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final double Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final double t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final float e;
    public static final String G;
    public static final String D;
    public static final double f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final int k;
    public static final float j;
    public static final String J;
    public static final float A;
    public static final String I;

    public pua_1() {
        pua_1 a2;
    }

    static {
        U = "You have been idle for too long!";
        i = "legacy";
        f = Double.longBitsToDouble(0xB2DB5AD49781EF59L ^ 0xD335AD49781EF59L);
        H = "blockentities";
        C = "bt";
        P = Float.intBitsToFloat(0x513F759A ^ 0x91F3B957);
        ga = "advMode.allEntities";
        a = "^\\s*#define\\s+(\\w+)\\s+(-?[0-9\\.Ff]+|\\w+)\\s*(//.*)?$";
        k = 0xD34E7D2D ^ 0xD34E7FB5;
        R = 0x78C6E4B6 ^ 0x87B6B4E6;
        Y = "Unbreakable";
        q = "wall_nsew";
        y = "static";
        ja = ", waving=";
        u = "hide_cape";
        j = Float.intBitsToFloat(0xA7A6B637 ^ 0xE7EFB9EC);
        W = "GL11.GL_RENDER";
        v = "file:";
        L = "Invalid height";
        Ca = 0x32C449DF ^ 0x32C448B1;
        G = "SET_SIZE";
        la = 0x6BC858BB ^ 0x6BC8DC6B;
        c = "Initializing game";
        B = "copy shadow depth";
        x = "decoder";
        Ka = "inventory.binSlot";
        Ma = "AZTEC_2";
        Q = "ADVENTURE";
        Ha = Double.longBitsToDouble(0xAD8AB1F6D0097081L ^ 0xEDB9B1F6D0097081L);
        ca = "GL11.GL_LIST_INDEX";
        Aa = "Adding item to inventory";
        D = "cow/cow";
        V = "of.options.DYNAMIC_FOV";
        b = "Snowflake particle texture at ";
        s = ", dim: ";
        S = "mud_brick_slab";
        O = "waxedCutCopper";
        Ga = "fixIterateHover_";
        J = "tube_coral_block";
        l = "east=true,north=true,south=true,up=false,west=true";
        Ja = Float.intBitsToFloat(0xE2EE84A0 ^ 0x202684A0);
        t = Double.longBitsToDouble(0x42501569C003EA72L ^ 0x7DD01569C003EA72L);
        g = "yTile";
        r = "gray_stained_hardened_clay";
        p = "global";
        h = "options.language";
        Da = Float.intBitsToFloat(0x3254ABC1 ^ 0xFEEA17E1);
        ia = Double.longBitsToDouble(0x3CA8A84DE2C0718BL ^ 0x7CB1A84DE2C0718BL);
        M = 0x42EDB592 ^ 0x42EDB71F;
        e = Float.intBitsToFloat(0x89E6B0C1 ^ 0x4BD2B0C1);
        Z = "createWorld.customize.custom.useCaves";
        X = 0xDFB7DA20 ^ 0xDFB75A67;
        ba = "Error compiling vertex shader: ";
        fa = " ms, ";
        K = Float.intBitsToFloat(0x8EE0BC0C ^ 0xB159D076);
        Ea = "rainbow";
        N = "zTile";
        I = "BLLeg";
        F = 0xCD6FCB7D ^ 0x3210B482;
        z = "cooked_fish";
        ha = 0xA68E9D39 ^ 0xA68E0157;
        m = "commands.whitelist.disabled";
        o = 0x7CB486E0 ^ 0x834B791F;
        d = "ENTITY_HORSE";
        n = "\u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u0441 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0435\u043c";
        E = "Failed to load meta file: assets/minidot/itemmeta";
        Fa = "DIRECTION_Y";
        T = "MOSSY";
        w = "megabox.animation.legendary";
        A = Float.intBitsToFloat(0x2551EC99 ^ 0x640D2054);
        Ia = Float.intBitsToFloat(0x829881 ^ 0x40F29881);
    }
}

