/*
 * Decompiled with CFR 0.152.
 */
public final class pua_1 {
    public static final String Ea;
    public static final int Ca;
    public static final double ia;
    public static final String Ma;
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final float Ia;
    public static final int la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final double Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final double t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final float e;
    public static final String G;
    public static final String D;
    public static final double f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final int k;
    public static final float j;
    public static final String J;
    public static final float A;
    public static final String I;

    public pua_1() {
        pua_1 a2;
    }

    static {
        U = "You have been idle for too long!";
        i = "legacy";
        f = -0.75D /* ZKM Deobf */;
        H = "blockentities";
        C = "bt";
        P = -6.400000095367432F /* ZKM Deobf */;
        ga = "advMode.allEntities";
        a = "^\\s*#define\\s+(\\w+)\\s+(-?[0-9\\.Ff]+|\\w+)\\s*(//.*)?$";
        k = 664 /* ZKM Deobf Int */;
        R = 4285550672 /* ZKM Deobf Int */;
        Y = "Unbreakable";
        q = "wall_nsew";
        y = "static";
        ja = ", waving=";
        u = "hide_cape";
        j = 3.1415927410125732F /* ZKM Deobf */;
        W = "GL11.GL_RENDER";
        v = "file:";
        L = "Invalid height";
        Ca = 366 /* ZKM Deobf Int */;
        G = "SET_SIZE";
        la = 34000 /* ZKM Deobf Int */;
        c = "Initializing game";
        B = "copy shadow depth";
        x = "decoder";
        Ka = "inventory.binSlot";
        Ma = "AZTEC_2";
        Q = "ADVENTURE";
        Ha = 19.0D /* ZKM Deobf */;
        ca = "GL11.GL_LIST_INDEX";
        Aa = "Adding item to inventory";
        D = "cow/cow";
        V = "of.options.DYNAMIC_FOV";
        b = "Snowflake particle texture at ";
        s = ", dim: ";
        S = "mud_brick_slab";
        O = "waxedCutCopper";
        Ga = "fixIterateHover_";
        J = "tube_coral_block";
        l = "east=true,north=true,south=true,up=false,west=true";
        Ja = -100.0F /* ZKM Deobf */;
        t = 0.0078125D /* ZKM Deobf */;
        g = "yTile";
        r = "gray_stained_hardened_clay";
        p = "global";
        h = "options.language";
        Da = -100000000.0F /* ZKM Deobf */;
        ia = 6.25D /* ZKM Deobf */;
        M = 653 /* ZKM Deobf Int */;
        e = -45.0F /* ZKM Deobf */;
        Z = "createWorld.customize.custom.useCaves";
        X = 32839 /* ZKM Deobf Int */;
        ba = "Error compiling vertex shader: ";
        fa = " ms, ";
        K = 1.4486229419708252F /* ZKM Deobf */;
        Ea = "rainbow";
        N = "zTile";
        I = "BLLeg";
        F = 4286545919 /* ZKM Deobf Int */;
        z = "cooked_fish";
        ha = 40046 /* ZKM Deobf Int */;
        m = "commands.whitelist.disabled";
        o = 4294967295 /* ZKM Deobf Int */;
        d = "ENTITY_HORSE";
        n = "\u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430 \u0441 \u0441\u043e\u0435\u0434\u0438\u043d\u0435\u043d\u0438\u0435\u043c";
        E = "Failed to load meta file: assets/minidot/itemmeta";
        Fa = "DIRECTION_Y";
        T = "MOSSY";
        w = "megabox.animation.legendary";
        A = 13.800000190734863F /* ZKM Deobf */;
        Ia = 3.75F /* ZKM Deobf */;
    }
}

