/*
 * Decompiled with CFR 0.152.
 */
public final class qQa {
    public static final String ia;
    public static final long Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final double Aa;
    public static final String S;
    public static final int Z;
    public static final float Y;
    public static final String r;
    public static final double V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final double N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final double x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final float f;
    public static final String F;
    public static final double g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final float M;
    public static final int k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        e = "/shaders";
        E = "' ";
        Ha = "sneak";
        D = "tuff_brick_wall";
        Ia = "GL11.GL_PIXEL_MAP_S_TO_S";
        p = "workbench";
        A = "log_stripped1";
        ba = "Unknown unit '";
        r = "devices";
        q = "blue_glazed_terracotta";
        fa = "Profession";
        B = " sky, ";
        ca = "skins";
        Ja = "1-srccolor";
        j = "START_DESTROY_BLOCK";
        g = 1e-05D /* ZKM Deobf */;
        Ma = 0xED704DDB6ECA706CL ^ 0xED704DDB6EC97D2CL;
        X = 3570 /* ZKM Deobf Int */;
        l = "\n\r";
        I = "facing=south,half=bottom,shape=outer_right";
        z = "\u0423 \u0432\u0430\u0441 \u043d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e ";
        Y = 1.1344640254974365F /* ZKM Deobf */;
        Ga = "options.chat.title";
        Aa = 11.125D /* ZKM Deobf */;
        ia = "depthtex0";
        W = "light_blue_concrete";
        Q = " <= ";
        V = 1.4D /* ZKM Deobf */;
        Fa = 4095 /* ZKM Deobf Int */;
        c = "ofAnimatedTextures:";
        ha = "xvalCase_";
        K = "commands.scoreboard.players.name.tooLong";
        Ka = "walk";
        w = nanF /* ZKM Deobf */;
        M = -0.9300020933151245F /* ZKM Deobf */;
        L = "Non-standard palette size: ";
        C = 775 /* ZKM Deobf Int */;
        i = "pack_format";
        k = 8874850 /* ZKM Deobf Int */;
        b = "chatOpacity:";
        m = "nether_wart_stage_2";
        T = "ofDynamicFov:";
        n = "Shape38123";
        Z = 242 /* ZKM Deobf Int */;
        S = "angleRotationZ_";
        u = "Broken attribute base value";
        ja = "waxedExposedCutCopperStairs";
        G = "Head.Shape14";
        d = "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0007";
        t = "Invalid font->characters->default: expected object, was ";
        ga = "Missing PLTE chunk";
        f = -1.2000000476837158F /* ZKM Deobf */;
        N = 0.34D /* ZKM Deobf */;
        H = "writtenBook";
        x = 1e-08D /* ZKM Deobf */;
        U = "menu.disconnect";
        la = "SkyBlock:brawl_minimap";
        v = "stat.climbOneCm";
        F = "1.0";
        P = 1e-07D /* ZKM Deobf */;
        O = 16384 /* ZKM Deobf Int */;
        a = "terrain";
        Da = "(?i)\\u00A7[0-9A-FK-OR]";
        o = "No name found: ";
        h = "COLD";
        s = "BorderWarningTime";
        R = 10987431 /* ZKM Deobf Int */;
        J = 211 /* ZKM Deobf Int */;
        y = "doEntityDrops";
    }

    public qQa() {
        qQa a2;
    }
}

