/*
 * Decompiled with CFR 0.152.
 */
public final class Qqa_1 {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final float ca;
    public static final int Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final double V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final double b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        H = "S Y";
        w = "Could not save the list after removing a user.";
        x = -50.0F /* ZKM Deobf */;
        v = "ANGLEX";
        Ja = 134 /* ZKM Deobf Int */;
        Ia = 32779 /* ZKM Deobf Int */;
        Y = "remote_";
        fa = -0.4375F /* ZKM Deobf */;
        Z = "easeInOutQuint";
        i = 4294967288 /* ZKM Deobf Int */;
        o = "\u00a76\u0425\u0435\u043b\u043b\u043e\u0443\u0438\u043d\u0441\u043a\u0430\u044f \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044f";
        e = "mushroom_stew";
        X = "tuffWall";
        Ga = "\u0421\u0443\u043d\u0434\u0443\u043a";
        T = 2634762 /* ZKM Deobf Int */;
        P = " world, ";
        b = 0.4D /* ZKM Deobf */;
        u = "Right26";
        ga = "GL11.GL_DEPTH_BITS";
        s = "rabbitHide";
        ca = -0.37178608775138855F /* ZKM Deobf */;
        m = "lit";
        V = 0.034D /* ZKM Deobf */;
        B = 24000 /* ZKM Deobf Int */;
        N = "textures/";
        Fa = "commands.worldborder.add.usage";
        M = "active_time";
        p = 33340 /* ZKM Deobf Int */;
        la = " already loaded";
        S = 294 /* ZKM Deobf Int */;
        Ha = "Start: ";
        r = "HELLO";
        A = "carriedData";
        ja = 33189 /* ZKM Deobf Int */;
        z = "BLEND";
        ha = "Failed to handle packet for ";
        j = "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0002\u0003\n";
        q = "commands.tp.success";
        k = "nether_brick_stairs";
        h = 580 /* ZKM Deobf Int */;
        d = "Natural Textures: Valid only for textures from default resource pack";
        a = "rearfoot";
        Aa = "woolCarpet";
        I = "VIGNETTE";
        U = "dragon_egg";
        t = "Stacktrace:\n";
        F = "half_vertical_right";
        ba = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u1007\u0000\u0003\u1007\u0001\u0004\u1001\u0002";
        E = "p.items";
        O = "java.naming.provider.url";
        J = 2049 /* ZKM Deobf Int */;
        Q = "key.hotbar.4";
        W = "raspberry";
        g = "\u0000\u0001\u0000\u0000\u0002\u0002\u0001\u0000\u0001\u0000\u0002'";
        Ka = "forward";
        C = "livePrintingDelay_";
        Da = "floatPosition_";
        l = "CHAT_WIDTH";
        K = "GL11.GL_CW";
        G = "eRadialSlider_";
        f = "Leaked resource: '";
        n = "minecraft:dispenser";
        y = "tile.oreGold.name";
        R = 17.5F /* ZKM Deobf */;
        c = "shepherd";
        L = "LeftLeg.LeftLeg1";
        D = 4294967169 /* ZKM Deobf Int */;
    }

    public Qqa_1() {
        Qqa_1 a2;
    }
}

