/*
 * Decompiled with CFR 0.152.
 */
public final class Qra {
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final float G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final float E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final int J;
    public static final String A;
    public static final String I;

    static {
        F = "resourcePack.incompatible.old";
        z = "SMOOTH";
        ca = "key.forward";
        b = "Hat.Shape6";
        u = "demo.help.inventory";
        H = -3.5899999141693115F /* ZKM Deobf */;
        I = "ticking";
        T = "HALF_HORIZONTAL_MIRROR";
        c = "wall_ns";
        v = "shake";
        W = 4612 /* ZKM Deobf Int */;
        X = "commands.save.enabled";
        y = "Left.Shape11123";
        a = "Unknown option: ";
        f = "BLUE_ORCHID";
        k = "hdb";
        r = "mob.guardian.elder.idle";
        d = ", f=";
        V = "\u041b\u0435\u0432\u043e";
        q = "deathScreen.deleteWorld";
        i = "IntCache";
        p = "Piece2.Shape6";
        Ka = " #";
        h = "jump";
        x = "shaders/post/bits.json";
        R = "of.options.save.3min";
        m = "of.options.animation.allOff";
        L = 382 /* ZKM Deobf Int */;
        S = 649 /* ZKM Deobf Int */;
        fa = "Unknown (0x";
        B = "water_breathing";
        o = "TileEntityData";
        J = 4294967240 /* ZKM Deobf Int */;
        Ja = "Unbalanced square brackets []: ";
        Y = "Error writing: ";
        Ga = "lanServer.start";
        Aa = "Maximum texture size: ";
        n = "gl_caps[ARB_instanced_arrays]";
        U = "add";
        K = "slot.armor.chest";
        D = "stoneMoss";
        l = 36.0D /* ZKM Deobf */;
        P = "of.message.newVersion";
        C = "randomMirror_";
        M = "GL11.GL_T2F_C4F_N3F_V3F";
        ja = " is already defined";
        Z = -0.3125F /* ZKM Deobf */;
        E = -0.17419999837875366F /* ZKM Deobf */;
        Ha = "cactus";
        w = 799 /* ZKM Deobf Int */;
        j = -0.10000000149011612F /* ZKM Deobf */;
        s = "Display: %dx%d (%s)";
        Da = "ARB_vertex_buffer_object is supported.\n";
        N = "No valid image";
        t = "VC micro: '{}', '{}'";
        ga = "colors";
        Q = 61469 /* ZKM Deobf Int */;
        G = -2.8797929286956787F /* ZKM Deobf */;
        O = "max_scale";
        e = "show_achievement";
        A = "players_current";
        g = "br";
    }

    public Qra() {
        Qra a2;
    }
}

