/*
 * Decompiled with CFR 0.152.
 */
public final class Qsa_1 {
    public static final int ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final int Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final float U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final float f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final float M;
    public static final float k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        r = "No expiration_expression or max_lifetime was found in minecraft:particle_lifetime_expression component";
        Ma = "Server Pinger #%d";
        e = "tt";
        Ha = 0x959F240D ^ 0x959F2429;
        f = Float.intBitsToFloat(0xE97470B7 ^ 0x5746C096);
        A = "index out of bounds to set tag in tag list";
        W = "Tag type expected";
        t = "PADDING_1B";
        o = "commands.tellraw.usage";
        fa = "LIST";
        v = "SHOW_CAPES";
        ca = "client";
        P = 0x81E290D2 ^ 0x9E290D2;
        M = Float.intBitsToFloat(0xAF833383 ^ 0x10CA3C7A);
        Z = 0x478E63 ^ 0x35F6F9;
        n = 0xD59ED68 ^ 0xF2A65297;
        a = "cubic-bezier(";
        d = "slab";
        V = Float.intBitsToFloat(0xFC15480B ^ 0xC795C88A);
        C = "textures/entity/arrow.png";
        i = "8";
        Fa = "has_bottle_0";
        T = "chestplateChain";
        ba = "stat.dropperInspected";
        s = "scaleYExpr_";
        g = "commands.unbanip.invalid";
        ha = "DisplayName";
        N = Float.intBitsToFloat(0x9A4A046 ^ 0x3207774C);
        U = Float.intBitsToFloat(0x3296B773 ^ 0x71DEB773);
        O = "stonebricksmooth";
        Ja = "Couldn't ping server";
        Q = "MC_GL_VENDOR_ATI";
        k = Float.intBitsToFloat(0x6FA61420 ^ 0x2EA61420);
        X = 0xA6BF219C ^ 0xE6BF219C;
        B = Float.intBitsToFloat(0xF552208E ^ 0xB677208E);
        j = 0xAD80DAF7 ^ 0xAD805E3B;
        h = "unspecified";
        H = "catmull_rom";
        Ka = 0x90AEC49F ^ 0x90AED69A;
        G = ", members: ";
        w = Double.longBitsToDouble(0x8565B5B33DE6A6DCL ^ 0xC50875B33DE6A6DCL);
        z = "motionX_";
        m = "main";
        Ia = "fence_ns";
        F = "Cold Taiga Hills";
        L = "commands.defaultgamemode.success";
        q = "SET_CENTER";
        D = "Right.Right29";
        Y = "east_west";
        Aa = 0x41FB1D37 ^ 0x41096292;
        x = "angleZval_";
        R = "[VimeStorage] Could not load index from ";
        b = 0x22E2EBAF ^ 0x22929BDF;
        S = "\u0432\u0438\u043c\u0435\u0440\u0430";
        la = "_pulling_1";
        Da = "GL11.GL_UNPACK_ROW_LENGTH";
        Ga = "chest";
        u = "waxed_weathered_cut_copper_slab";
        y = "Right.Right36";
        c = "pumpkin";
        l = "commands.effect.success.removed.all";
        ja = "%5.3f";
        p = "GL11.GL_PERSPECTIVE_CORRECTION_HINT";
        ga = 0x5D18B3E3 ^ 0x5D18B179;
        ia = 0xBBC4F46C ^ 0xBBC4E303;
        K = "Right2";
        I = "GL14.GL_CONSTANT_ALPHA";
        E = "offsetXExpr_";
        J = "SCALEYVAL_NOT_SET";
    }

    public Qsa_1() {
        Qsa_1 a2;
    }
}

