/*
 * Decompiled with CFR 0.152.
 */
public final class QSa_2 {
    public static final int ia;
    public static final String Ma;
    public static final int ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final double x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        ja = "\u0421\u043d\u0430\u0447\u0430\u043b\u0430 \u043d\u043e\u0432\u0430\u044f";
        Ha = "Hat.Shape2";
        U = 13742497 /* ZKM Deobf Int */;
        i = 8355711 /* ZKM Deobf Int */;
        X = "diamond_helmet";
        p = 48 /* ZKM Deobf Int */;
        a = "Leash";
        r = "book.finalizeButton";
        D = "of.options.SMOOTH_WORLD";
        e = 4294943296 /* ZKM Deobf Int */;
        h = 0.05209999904036522F /* ZKM Deobf */;
        E = "times";
        Ma = "triggered";
        m = "folder";
        Q = "of.options.DYNAMIC_LIGHTS";
        Ga = "horse/";
        u = "Unable to parse metadata section of resourcepack: ";
        G = "birch_log_stripped";
        A = "beefCooked";
        j = "slimeball";
        la = "wear";
        T = "Received unrequested status";
        Ja = "PickupDelay";
        Z = "plant";
        ba = 2048 /* ZKM Deobf Int */;
        Fa = "Ping: (1.4-1.5.x) from {}:{}";
        I = "AQUA";
        g = "!=";
        J = "Shape32";
        s = "gl_caps[EXT_paletted_texture]";
        q = "Image shadow texture ";
        P = "player[";
        ia = 20000 /* ZKM Deobf Int */;
        S = "cherry_slab_double";
        L = 3.0999999046325684F /* ZKM Deobf */;
        Y = "Rendering Block Entity";
        Aa = "Shaders.uninit";
        K = "GL15.GL_BUFFER_MAP_POINTER";
        M = "crash-reports";
        V = 3359 /* ZKM Deobf Int */;
        w = 215 /* ZKM Deobf Int */;
        b = "dig.wood";
        v = "set tex, after";
        o = "golden_shovel";
        fa = 314 /* ZKM Deobf Int */;
        c = 0.007000000216066837D /* ZKM Deobf */;
        F = 761 /* ZKM Deobf Int */;
        Ia = "GL14.GL_INCR_WRAP";
        n = "Loading entity NBT";
        t = "textures/entity/horse/armor/horse_armor_gold.png";
        R = 161 /* ZKM Deobf Int */;
        ha = -2.490000009536743F /* ZKM Deobf */;
        H = "head1";
        B = "repeater";
        z = "\u0432 \u0432\u0430\u0448\u0435 \u043b\u043e\u0431\u0431\u0438";
        d = "CYAN";
        f = "POSITIVE";
        l = -20.0D /* ZKM Deobf */;
        C = 29999999 /* ZKM Deobf Int */;
        k = ", lowName='";
        y = "Invalid facing: ";
        W = "delete-custom-emote";
        x = infD /* ZKM Deobf */;
        O = "cracked_brick";
        Da = "VALIDATING";
        N = "Invalid grid U: ";
        ca = 34892 /* ZKM Deobf Int */;
        ga = "Shape30";
        Ka = "pC: %03d, pU: %1d, aB: %1d";
    }

    public QSa_2() {
        QSa_2 a2;
    }
}

