/*
 * Decompiled with CFR 0.152.
 */
public final class QSa_2 {
    public static final int ia;
    public static final String Ma;
    public static final int ba;
    public static final float ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final double x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        ja = "\u0421\u043d\u0430\u0447\u0430\u043b\u0430 \u043d\u043e\u0432\u0430\u044f";
        Ha = "Hat.Shape2";
        U = 0xE85D8173 ^ 0xE88C30D2;
        i = 0xCEB7D47C ^ 0xCEC8AB03;
        X = "diamond_helmet";
        p = 0x2DF5D6E0 ^ 0x2DF5D6D0;
        a = "Leash";
        r = "book.finalizeButton";
        D = "of.options.SMOOTH_WORLD";
        e = 0x37F5C8C8 ^ 0xC80A6A88;
        h = Float.intBitsToFloat(0x6D9415D1 ^ 0x50C1731E);
        E = "times";
        Ma = "triggered";
        m = "folder";
        Q = "of.options.DYNAMIC_LIGHTS";
        Ga = "horse/";
        u = "Unable to parse metadata section of resourcepack: ";
        G = "birch_log_stripped";
        A = "beefCooked";
        j = "slimeball";
        la = "wear";
        T = "Received unrequested status";
        Ja = "PickupDelay";
        Z = "plant";
        ba = 0xA5398423 ^ 0xA5398C23;
        Fa = "Ping: (1.4-1.5.x) from {}:{}";
        I = "AQUA";
        g = "!=";
        J = "Shape32";
        s = "gl_caps[EXT_paletted_texture]";
        q = "Image shadow texture ";
        P = "player[";
        ia = 0xF434DEDE ^ 0xF43490FE;
        S = "cherry_slab_double";
        L = Float.intBitsToFloat(0x2D4EAC54 ^ 0x6D08CA32);
        Y = "Rendering Block Entity";
        Aa = "Shaders.uninit";
        K = "GL15.GL_BUFFER_MAP_POINTER";
        M = "crash-reports";
        V = 0x7FA81748 ^ 0x7FA81A57;
        w = 0xD2FCBB9C ^ 0xD2FCBB4B;
        b = "dig.wood";
        v = "set tex, after";
        o = "golden_shovel";
        fa = 0x45DCAB3C ^ 0x45DCAA06;
        c = Double.longBitsToDouble(0x2FF8773CEC33A40DL ^ 0x1084DB34AC33A40DL);
        F = 0x52962F63 ^ 0x52962D9A;
        Ia = "GL14.GL_INCR_WRAP";
        n = "Loading entity NBT";
        t = "textures/entity/horse/armor/horse_armor_gold.png";
        R = 0x2A57C4B4 ^ 0x2A57C415;
        ha = Float.intBitsToFloat(0xF6D1887D ^ 0x36CED454);
        H = "head1";
        B = "repeater";
        z = "\u0432 \u0432\u0430\u0448\u0435 \u043b\u043e\u0431\u0431\u0438";
        d = "CYAN";
        f = "POSITIVE";
        l = Double.longBitsToDouble(0xF128DA1EEEA9896DL ^ 0x311CDA1EEEA9896DL);
        C = 0x61672525 ^ 0x60AEE65A;
        k = ", lowName='";
        y = "Invalid facing: ";
        W = "delete-custom-emote";
        x = Double.longBitsToDouble(0x458B0D5BB4E70071L ^ 0x3A7B0D5BB4E70071L);
        O = "cracked_brick";
        Da = "VALIDATING";
        N = "Invalid grid U: ";
        ca = 0x2D2EDC4E ^ 0x2D2E5402;
        ga = "Shape30";
        Ka = "pC: %03d, pU: %1d, aB: %1d";
    }

    public QSa_2() {
        QSa_2 a2;
    }
}

