/*
 * Decompiled with CFR 0.152.
 */
public final class QTa {
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final float z;
    public static final float X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    public QTa() {
        QTa a2;
    }

    static {
        la = "rotatevalCase_";
        A = "east=true,north=true,south=true,up=true,west=true";
        B = "bassattack";
        V = 0x60DB10C3 ^ 0x60DB1BF2;
        f = "warpedFenceGate";
        R = "!0 & !1 & 2 & 3";
        Ia = 0x74AB8016 ^ 0x8B7B50C6;
        o = 0x5E33FDCC ^ 0x5E33C219;
        l = "options.mipmapLevels";
        k = "RightHand.Shape2";
        I = "rotate_xyz";
        i = "Mega Taiga";
        J = "groups";
        Z = "lines";
        s = "Couldn't save screenshot";
        S = "SPACE_BETWEEN";
        j = 0xE468D8B8 ^ 0xE4685CED;
        z = Float.intBitsToFloat(0x4B0650E9 ^ 0xA00368F);
        e = ".postfix";
        w = "Shape8";
        Aa = Float.intBitsToFloat(0x19DF9EF9 ^ 0xA7D7E135);
        c = "of.options.shadersTitle";
        X = Float.intBitsToFloat(0x216FEFE6 ^ 0x67D46FE6);
        D = Float.intBitsToFloat(0x69126A0B ^ 0x579ADE32);
        G = Float.intBitsToFloat(0x5073E7D0 ^ 0x12BBE7D0);
        C = ".zip";
        ca = "fCa24rBgjVs36ZZ";
        K = "black_glazed_terracotta";
        M = "P: ";
        ja = "PARTICLES";
        ga = Float.intBitsToFloat(0xFEA057FC ^ 0x7EA057FC);
        h = "Response is null";
        y = "Invalid default frame time";
        d = 0xF535C7C9 ^ 0xF535C2C8;
        N = "leftStick";
        u = 0xAB587248 ^ 0x54235EF7;
        Ja = "Head.Shape11";
        q = "facing=south,half=top,shape=outer_right";
        ba = "stoneSlab";
        Ka = 0x74796BFB ^ 0x747966CD;
        g = "NETWORK_PACKETS";
        Y = "SPAWN";
        Ma = 0x1DC42A02 ^ 0x1D4075EF;
        H = 0x4758C7FB ^ 0xC7A7C704;
        r = "witchMagic";
        ha = "spreadMotionY_";
        ia = "cooked_salmon";
        Q = "nausea";
        Ha = 0x45F5CE8D ^ 0x45F5BBBF;
        v = "yellow";
        t = "gbuffers_spidereyes";
        F = "GL13.GL_TEXTURE_CUBE_MAP_POSITIVE_X";
        fa = "emotes/models/";
        L = "diamondsToYou";
        a = "REGULAR";
        Fa = "GL11.GL_RGB16";
        O = "id";
        U = Float.intBitsToFloat(0xD383D5C2 ^ 0x6C03D34F);
        E = 0xE4F04269 ^ 0xE4F04ED9;
        n = "GL11.GL_NO_ERROR";
        m = 0x1B69DB0E ^ 0xE55FE60E;
        T = "potion.blindness";
        W = "realistic_collision_drag";
        P = "entityShadows";
        x = " 4.0 ";
        Da = "mp";
        Ga = "dressed";
        b = "copy depth";
        p = "per_update_expression";
    }
}

