/*
 * Decompiled with CFR 0.152.
 */
public final class QTa {
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final float z;
    public static final float X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    public QTa() {
        QTa a2;
    }

    static {
        la = "rotatevalCase_";
        A = "east=true,north=true,south=true,up=true,west=true";
        B = "bassattack";
        V = 2865 /* ZKM Deobf Int */;
        f = "warpedFenceGate";
        R = "!0 & !1 & 2 & 3";
        Ia = 4291875024 /* ZKM Deobf Int */;
        o = 16341 /* ZKM Deobf Int */;
        l = "options.mipmapLevels";
        k = "RightHand.Shape2";
        I = "rotate_xyz";
        i = "Mega Taiga";
        J = "groups";
        Z = "lines";
        s = "Couldn't save screenshot";
        S = "SPACE_BETWEEN";
        j = 33877 /* ZKM Deobf Int */;
        z = 8.399999618530273F /* ZKM Deobf */;
        e = ".postfix";
        w = "Shape8";
        Aa = -0.13330000638961792F /* ZKM Deobf */;
        c = "of.options.shadersTitle";
        X = 24000.0F /* ZKM Deobf */;
        D = 0.2669999897480011F /* ZKM Deobf */;
        G = 100.0F /* ZKM Deobf */;
        C = ".zip";
        ca = "fCa24rBgjVs36ZZ";
        K = "black_glazed_terracotta";
        M = "P: ";
        ja = "PARTICLES";
        ga = -0.0F /* ZKM Deobf */;
        h = "Response is null";
        y = "Invalid default frame time";
        d = 1281 /* ZKM Deobf Int */;
        N = "leftStick";
        u = 4286262463 /* ZKM Deobf Int */;
        Ja = "Head.Shape11";
        q = "facing=south,half=top,shape=outer_right";
        ba = "stoneSlab";
        Ka = 3382 /* ZKM Deobf Int */;
        g = "NETWORK_PACKETS";
        Y = "SPAWN";
        Ma = 8675309 /* ZKM Deobf Int */;
        H = 2164195583 /* ZKM Deobf Int */;
        r = "witchMagic";
        ha = "spreadMotionY_";
        ia = "cooked_salmon";
        Q = "nausea";
        Ha = 30002 /* ZKM Deobf Int */;
        v = "yellow";
        t = "gbuffers_spidereyes";
        F = "GL13.GL_TEXTURE_CUBE_MAP_POSITIVE_X";
        fa = "emotes/models/";
        L = "diamondsToYou";
        a = "REGULAR";
        Fa = "GL11.GL_RGB16";
        O = "id";
        U = -1.0001999139785767F /* ZKM Deobf */;
        E = 3248 /* ZKM Deobf Int */;
        n = "GL11.GL_NO_ERROR";
        m = 4264967424 /* ZKM Deobf Int */;
        T = "potion.blindness";
        W = "realistic_collision_drag";
        P = "entityShadows";
        x = " 4.0 ";
        Da = "mp";
        Ga = "dressed";
        b = "copy depth";
        p = "per_update_expression";
    }
}

