/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  ABa
 *  BAa
 *  CAa
 *  Cca
 *  DBa
 *  EBa
 *  Eca
 *  FBa
 *  Fba
 *  GAa
 *  GBa
 *  Gba
 *  HCa
 *  Iba
 *  JAa
 *  JBa
 *  Jca
 *  Jda
 *  KBa
 *  Kda
 *  LAa
 *  LBa
 *  LCa
 *  Lba
 *  Lda
 *  Mba
 *  Mca
 *  QAa
 *  QCa
 *  RAa
 *  RBa
 *  RCa
 *  Rba
 *  UAa
 *  UBa
 *  WBa
 *  WCa
 *  XCa
 *  Xaa
 *  Xba
 *  ZAa
 *  ada
 *  bCa
 *  bba
 *  cBa
 *  cca
 *  dAa
 *  dCa
 *  dda
 *  fAa
 *  fda
 *  gAa
 *  hCa
 *  hba
 *  hca
 *  hda
 *  iCa
 *  ida
 *  jca
 *  lAa
 *  lba
 *  mAa
 *  mBa
 *  mda
 *  nca
 *  oAa
 *  oba
 *  pAa
 *  qBa
 *  sca
 *  tBa
 *  tba
 *  uCa
 *  vaa
 *  vca
 *  wBa
 *  wba
 *  wca
 *  xba
 *  yAa
 *  yba
 */
public final class rca_2
extends wBa {
    public rca_2(int n3) {
        rca_2 a2;
        int b2 = n3;
        rca_2 rca_22 = a2 = this;
        super(string, n2, b2, null);
        rca_22.registerPacket(RCa.CLIENTBOUND, dCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, cca.class);
        a2.registerPacket(RCa.CLIENTBOUND, XCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Mba.class);
        a2.registerPacket(RCa.CLIENTBOUND, Kda.class);
        a2.registerPacket(RCa.CLIENTBOUND, nba.class);
        a2.registerPacket(RCa.CLIENTBOUND, iCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, mBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, lba.class);
        a2.registerPacket(RCa.CLIENTBOUND, mda.class);
        a2.registerPacket(RCa.CLIENTBOUND, LCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, EBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, uCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, yba.class);
        a2.registerPacket(RCa.CLIENTBOUND, JBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Xaa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Sca.class);
        a2.registerPacket(RCa.CLIENTBOUND, HCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, xba.class);
        a2.registerPacket(RCa.CLIENTBOUND, QCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, hCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, ZCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, GAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Mca.class);
        a2.registerPacket(RCa.CLIENTBOUND, bba.class);
        a2.registerPacket(RCa.CLIENTBOUND, RAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, tAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Bca.class);
        a2.registerPacket(RCa.CLIENTBOUND, hba.class);
        a2.registerPacket(RCa.CLIENTBOUND, cCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, jca.class);
        a2.registerPacket(RCa.CLIENTBOUND, vaa.class);
        a2.registerPacket(RCa.CLIENTBOUND, vca.class);
        a2.registerPacket(RCa.CLIENTBOUND, DBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, eba.class);
        a2.registerPacket(RCa.CLIENTBOUND, wba.class);
        a2.registerPacket(RCa.CLIENTBOUND, Eca.class);
        a2.registerPacket(RCa.CLIENTBOUND, Fba.class);
        a2.registerPacket(RCa.CLIENTBOUND, VCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Xba.class);
        a2.registerPacket(RCa.CLIENTBOUND, bCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, ABa.class);
        a2.registerPacket(RCa.CLIENTBOUND, dda.class);
        a2.registerPacket(RCa.CLIENTBOUND, FBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, hda.class);
        a2.registerPacket(RCa.CLIENTBOUND, Jca.class);
        a2.registerPacket(RCa.CLIENTBOUND, nCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, tba.class);
        a2.registerPacket(RCa.CLIENTBOUND, zBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, GBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, yAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, ICa.class);
        a2.registerPacket(RCa.CLIENTBOUND, AAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, fda.class);
        a2.registerPacket(RCa.CLIENTBOUND, BAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, oAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, bda.class);
        a2.registerPacket(RCa.CLIENTBOUND, fAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, LAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Jda.class);
        a2.registerPacket(RCa.CLIENTBOUND, Iba.class);
        a2.registerPacket(RCa.CLIENTBOUND, ada.class);
        a2.registerPacket(RCa.CLIENTBOUND, Dca.class);
        a2.registerPacket(RCa.CLIENTBOUND, Cda.class);
        a2.registerPacket(RCa.CLIENTBOUND, mba.class);
        a2.registerPacket(RCa.CLIENTBOUND, oba.class);
        a2.registerPacket(RCa.CLIENTBOUND, UBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, pAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, Oca.class);
        a2.registerPacket(RCa.CLIENTBOUND, Gca.class);
        a2.registerPacket(RCa.CLIENTBOUND, WCa.class);
        a2.registerPacket(RCa.CLIENTBOUND, lAa.class);
        a2.registerPacket(RCa.CLIENTBOUND, OBa.class);
        a2.registerPacket(RCa.CLIENTBOUND, ZAa.class);
        a2.registerPacket(RCa.SERVERBOUND, cBa.class);
        a2.registerPacket(RCa.SERVERBOUND, wca.class);
        a2.registerPacket(RCa.SERVERBOUND, Lba.class);
        a2.registerPacket(RCa.SERVERBOUND, ida.class);
        a2.registerPacket(RCa.SERVERBOUND, dAa.class);
        a2.registerPacket(RCa.SERVERBOUND, Cca.class);
        a2.registerPacket(RCa.SERVERBOUND, QAa.class);
        a2.registerPacket(RCa.SERVERBOUND, mAa.class);
        a2.registerPacket(RCa.SERVERBOUND, CAa.class);
        a2.registerPacket(RCa.SERVERBOUND, WBa.class);
        a2.registerPacket(RCa.SERVERBOUND, LBa.class);
        a2.registerPacket(RCa.SERVERBOUND, RBa.class);
        a2.registerPacket(RCa.SERVERBOUND, Lda.class);
        a2.registerPacket(RCa.SERVERBOUND, nca.class);
        a2.registerPacket(RCa.SERVERBOUND, tBa.class);
        a2.registerPacket(RCa.SERVERBOUND, gAa.class);
        a2.registerPacket(RCa.SERVERBOUND, Gba.class);
        a2.registerPacket(RCa.SERVERBOUND, fca.class);
        a2.registerPacket(RCa.SERVERBOUND, KBa.class);
        a2.registerPacket(RCa.SERVERBOUND, sca.class);
        a2.registerPacket(RCa.SERVERBOUND, YAa.class);
        a2.registerPacket(RCa.SERVERBOUND, UAa.class);
        a2.registerPacket(RCa.SERVERBOUND, qBa.class);
        a2.registerPacket(RCa.SERVERBOUND, Rba.class);
        a2.registerPacket(RCa.SERVERBOUND, hca.class);
        a2.registerPacket(RCa.SERVERBOUND, JAa.class);
    }
}

