/*
 * Decompiled with CFR 0.152.
 */
public final class RPa_1 {
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final float Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final int j;
    public static final float J;
    public static final String A;
    public static final String I;

    static {
        u = "deathScreen.titleScreen";
        A = "port";
        J = Float.intBitsToFloat(0x987CFAC0 ^ 0x5948360D);
        Ga = "Getting block";
        k = Float.intBitsToFloat(0xF02037B9 ^ 0xB01037B9);
        f = 0x7C969C46 ^ 0x7C969D55;
        l = Float.intBitsToFloat(0x1E59FFD1 ^ 0x5BA3FFD1);
        D = "acos";
        d = 0xACD698FC ^ 0xACD60496;
        Da = 0x4CCADB11 ^ 0x4D031891;
        s = "textures/entity/wolf/wolf_tame.png";
        w = "GL14.GL_SECONDARY_COLOR_ARRAY_SIZE";
        ha = "18";
        L = 0xD9F790B2 ^ 0xD9F710B1;
        ja = "MESSAGE";
        B = "of.options.FIREWORK_PARTICLES";
        h = "hoeWood";
        T = "MIPMAP_TYPE";
        H = "commands.spawnpoint.usage";
        ga = "allowBlockAlternatives:";
        O = " B ";
        R = ") relighted ";
        r = 0x9CC18FAF ^ 0x9CC191AC;
        la = "MAGENTA";
        o = "Screen size";
        U = 0x115EB014 ^ 0x115E308A;
        P = "of.options.ANIMATED_REDSTONE";
        p = "Right9";
        Ka = "blocks/destroy_stage_8";
        ba = "Scaled: (%d, %d). Absolute: (%d, %d). Scale factor of %d";
        V = "gbufferPreviousProjection";
        M = "\u0000\u0011\u0001\u0001\u0001\u0011\u0011\u0000\u0002\u0000\u0001$\u0002\u1001\u0000\u0003\u1006\u0001\u0004$\u0005\u1007\u0002\u0006\u1004\u0003\u0007\u1004\u0004\b\u100c\u0005\t\u1009\u0006\n7\u0000\u000b\u023b\u0000\f\u1001\u0007\r\u1001\b\u000e\u1001\t\u000f\u1001\n\u0010\u1001\u000b\u0011\u1001\f";
        i = "GL11.GL_PIXEL_MAP_G_TO_G_SIZE";
        Y = "from";
        K = "hideForOtherTeams";
        a = "xporb.time";
        Aa = "com.sun.jndi.dns.timeout.retries";
        Z = "commands.achievement.give.success.all";
        b = "oxidizedCutCopperSlab";
        t = "Unexpected: ";
        F = "data_points";
        e = "NORMAL_3B";
        S = 0xEE6098F1 ^ 0xEE101068;
        n = "textures/pet/cat_gun.png";
        Ia = Float.intBitsToFloat(0x1D932027 ^ 0x5C2B2027);
        Ma = 0xB84BD33A ^ 0xB84BC13A;
        q = 0xC10CB276 ^ 0xC1094039;
        m = "variable.emitter_lifetime";
        Q = "wither/wither";
        z = "Demo_World";
        c = "stat.used";
        g = "^block([0-9]+).*$";
        fa = 0x90A43508 ^ 0x90A4A94D;
        E = "stats.tooltip.type.";
        W = "daylight_detector_inverted";
        ca = "options.sounds";
        x = "commands.tp.usage";
        C = "cobbled_deepslate_wall";
        v = 0x66CA827C ^ 0x66CA8016;
        Fa = "spell";
        N = "oceanmonument";
        I = "wasOnGround";
        y = "win";
        j = 0x569042F0 ^ 0x56903EF0;
        Ha = 0xB83169E5 ^ 0xB83168AB;
        X = "' from: '";
        G = "POW";
        Ja = 0x9DAA5770 ^ 0x9DAA5B40;
    }

    public RPa_1() {
        RPa_1 a2;
    }
}

