/*
 * Decompiled with CFR 0.152.
 */
public final class rQa {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final float ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final int Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final long v;
    public static final float o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final long l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final double k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public rQa() {
        rQa a2;
    }

    static {
        U = "shaders/post/creeper.json";
        O = "gold_nugget";
        Da = 0x1179ADA2 ^ 0x1179AD45;
        d = "[ \t]*const[ \t]*int[ \t]*shadowMapResolution[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        r = "oldLighting";
        e = 0x36523BAF ^ 0x36523B5C;
        u = "persistent_";
        m = "format: ";
        M = "model_leggings";
        w = 0x691422A6 ^ 0x6914206C;
        la = "set tex, current item options: ";
        q = "Fancy";
        b = ", end: ";
        ha = "GL11.GL_STENCIL_VALUE_MASK";
        E = "Right48";
        o = Float.intBitsToFloat(0x8A422806 ^ 0xB5D76E0D);
        x = 0x8C28E0E5 ^ 0x8C28ED35;
        T = "Keep-Alive";
        v = 0x417A104E04D181D7L ^ 0x417A104E04D181DEL;
        V = "waxed_oxidized_cut_copper_slab";
        Ia = "uniform [ _a-zA-Z0-9]+ gdepth;.*";
        ia = "Event source";
        G = "GL11.GL_INDEX_WRITEMASK";
        Q = "Number of tiles should be 1 for method: fixed.";
        Ga = "Water World";
        Ha = "Opening via system class!";
        Aa = 0x613D2569 ^ 0x613D2E2F;
        f = "THIRD_PERSON";
        s = 0xC17D3634 ^ 0xC17D3640;
        I = "fireworksCharge";
        B = "VC: record voice send ";
        fa = Float.intBitsToFloat(0x43BE8D29 ^ 0x20E41E4);
        R = "dripLava";
        J = "headingColor_";
        Fa = 0xEE6F2C96 ^ 0xEE6FACC3;
        t = "tree";
        p = 0x33CF15D0 ^ 0xCC30EA2E;
        a = "blue";
        j = "book.finalizeWarning";
        Ka = 0xEDEC4BB0 ^ 0xEDEC4966;
        h = "dig.glass";
        ga = "AttributeName";
        F = ", args=";
        g = 0xA52832D8 ^ 0xA528B245;
        X = "Couldn't load metadata info";
        Z = "Playing level event";
        ba = "cmd.exe /C start \"Open file\" \"%s\"";
        D = "SCALEVAL_NOT_SET";
        i = 0x111C3666 ^ 0x111C3618;
        n = "TexMinFilB";
        k = Double.longBitsToDouble(0xE30C6C6668A895B7L ^ 0xDC6764FC6ADDB0F1L);
        ja = "Saving players";
        c = "RandomMobs";
        L = "proxyPass";
        S = "brickWall";
        C = "\u4fa0";
        P = Double.longBitsToDouble(0x89EC1A1B30AB5C76L ^ 0xB66860FA7705480AL);
        z = "random.burp";
        A = "Snooper Timer";
        y = "#%04d%s";
        W = "   ";
        ca = Float.intBitsToFloat(0x4E2B3FD0 ^ 0xF1EC5A2E);
        N = "pink_glazed_terracotta";
        Ma = "Constructor error";
        Y = "red";
        Ja = "VC: Unexpected error in VoiceChatClient handleLostPackets";
        H = "PigZombie";
        K = 0x798202D7 ^ 0x7982000D;
        l = 0xD52674F6CB9E7FB9L ^ 0xD52674F6CB9E7DABL;
    }
}

