/*
 * Decompiled with CFR 0.152.
 */
public final class RQa_1 {
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final long ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final long N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final int s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final int a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final float F;
    public static final float g;
    public static final int L;
    public static final String E;
    public static final double m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final double k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        l = "[ \t]*const[ \t]*float[ \t]*drynessHalflife[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        Aa = "GENERIC";
        w = 224.0F /* ZKM Deobf */;
        r = "mob.zombie.hurt";
        B = 32911 /* ZKM Deobf Int */;
        q = "GL11.GL_STENCIL_CLEAR_VALUE";
        b = 78 /* ZKM Deobf Int */;
        L = 688 /* ZKM Deobf Int */;
        d = "VimeWorld.elapsedSkip";
        P = "Converting... ";
        Ha = "shadowcolor1";
        u = "Corrupt NBT tag";
        A = "textures/gui/container/beacon.png";
        i = "fps";
        S = "Unknown value type ";
        f = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u1007\u0000\u0003\u1009\u0001";
        H = "meshes";
        F = 0.44366195797920227F /* ZKM Deobf */;
        I = "\u0421\u0435\u0440\u0432\u0435\u0440 \u043d\u0430 \u0442\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u043e\u043c \u043e\u0431\u0441\u043b\u0443\u0436\u0438\u0432\u0430\u043d\u0438\u0438";
        Da = "LEGS_AROUND";
        a = 1000000000 /* ZKM Deobf Int */;
        N = 0x5386474A0C8E97E6L ^ 0x5386474A0C8E97DAL;
        ca = 0x97428265192DA997L ^ 0x982E72B0062B36A3L;
        K = "heights.";
        ba = "shaders/post/outline.json";
        T = "coal_block";
        X = "BLLeg.Shape41";
        C = "\u0410\u0432\u0442\u043e\u0440";
        M = "Right.Right32";
        U = "leftHorn";
        Z = 40058 /* ZKM Deobf Int */;
        Q = "ofProfiler";
        la = "of.options.ANIMATED_EXPLOSION";
        e = "wolf/wolf";
        V = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1001\u0000\u0002\u1006\u0001\u0003\u1006\u0002";
        E = "Disconnecting ";
        Ma = "textures/entity/enderdragon/dragon_eyes.png";
        h = "armorItemAmount:";
        ha = "Flower Forest";
        W = "damageBoost";
        ga = "seaLantern";
        y = "ops.txt";
        c = "game.player.swim";
        o = "mycelium_top";
        g = -0.9599310755729675F /* ZKM Deobf */;
        D = "ASCENDING_EAST";
        j = 5890 /* ZKM Deobf Int */;
        Y = "!0 & 1 & !2 & 3 & 3+6";
        k = 684.412D /* ZKM Deobf */;
        Ia = "Unsupported protocol: ";
        Ga = "colortex1";
        p = "MODELRESOURCE";
        m = 0.85D /* ZKM Deobf */;
        J = "head.nostril";
        ja = "mycelium";
        z = "Unable to create attribute: ";
        fa = "glassBottle";
        O = "\\\"";
        Fa = "5D6F0BA2-1186-46AC-B896-C61C5CEE99CC";
        Ka = 170.0F /* ZKM Deobf */;
        n = 435 /* ZKM Deobf Int */;
        s = 2917 /* ZKM Deobf Int */;
        Ja = "ANGLEXVAL_NOT_SET";
        t = "-0+1+2-3+13&4-4";
        v = "LL1";
        R = 135 /* ZKM Deobf Int */;
        x = 282 /* ZKM Deobf Int */;
        G = "\u0412\u044b\u043a\u043b\u044e\u0447\u0435\u043d\u044b";
    }

    public RQa_1() {
        RQa_1 a2;
    }
}

