/*
 * Decompiled with CFR 0.152.
 */
public final class rRa {
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final int Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final int F;
    public static final String g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final float C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public rRa() {
        rRa a2;
    }

    static {
        p = "Body.Shape17";
        Ka = "MC_OS_OTHER";
        l = 1.05D /* ZKM Deobf */;
        M = "ironSize";
        L = 0.45454545454545453D /* ZKM Deobf */;
        v = "LEGS_ON_TOP";
        Ga = "nether_brick_fence";
        b = "pickaxeIron";
        V = -0.02500000037252903F /* ZKM Deobf */;
        i = "GL11.GL_COLOR_ARRAY_TYPE";
        a = " load error";
        ga = "fogColor";
        Da = 4280953386 /* ZKM Deobf Int */;
        C = 1.7000000476837158F /* ZKM Deobf */;
        Z = "bs";
        c = "math.trunc";
        F = 16719904 /* ZKM Deobf Int */;
        Aa = "TITLE";
        t = "x.org";
        w = "rot";
        Y = "AFFECTED_ITEMS";
        u = "chat.link.warning";
        I = 302 /* ZKM Deobf Int */;
        la = "nether_wart_stage_1";
        j = "Pre startup";
        q = "uniform [ _a-zA-Z0-9]+ shadowcolor1;.*";
        y = "commands.scoreboard.allMatchesFailed";
        X = "x";
        Ja = "backFace.solid";
        ca = "LINES";
        E = "occupied";
        k = "RGBA32UI";
        z = "STRIPE_BOTTOM";
        G = "buildPickaxe";
        R = 91 /* ZKM Deobf Int */;
        P = "animationCase_";
        g = "ChestedHorse";
        n = "animations/pet/persona_grand_arcades_animation.json";
        N = "fov";
        S = 221 /* ZKM Deobf Int */;
        e = "netherGoldOre";
        O = "Invalid animation->frames: expected array, was ";
        x = 2900 /* ZKM Deobf Int */;
        h = "result_";
        s = "rightLeg.rightLeg1";
        o = "rm";
        U = "Piston";
        ja = "mob.zombie.step";
        K = "gameMode.changed";
        T = 0.0625F /* ZKM Deobf */;
        f = 160 /* ZKM Deobf Int */;
        D = "Unsigned Int";
        B = "Head.9";
        H = "7";
        A = "MINECART_TNT";
        Ha = "iceandsnow";
        m = "Max value of ";
        Q = 668 /* ZKM Deobf Int */;
        J = "Entity ";
        r = "of.options.TRANSLUCENT_BLOCKS";
        W = " to be a JsonObject, was ";
        d = "(?:.*)_copper_grate";
        fa = "Pet.Ribbon9";
    }
}

