/*
 * Decompiled with CFR 0.152.
 */
public final class rRa {
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final int Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final int F;
    public static final String g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final float C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public rRa() {
        rRa a2;
    }

    static {
        p = "Body.Shape17";
        Ka = "MC_OS_OTHER";
        l = Double.longBitsToDouble(0x44386CC2307E735CL ^ 0x7BC8A00EFCB2BF91L);
        M = "ironSize";
        L = Double.longBitsToDouble(0xFBD976CDB4C41514L ^ 0xC404618865B04803L);
        v = "LEGS_ON_TOP";
        Ga = "nether_brick_fence";
        b = "pickaxeIron";
        V = Float.intBitsToFloat(0x11BC0701 ^ 0xAD70CBCC);
        i = "GL11.GL_COLOR_ARRAY_TYPE";
        a = " load error";
        ga = "fogColor";
        Da = 0xB5A34D71 ^ 0x4A89675B;
        C = Float.intBitsToFloat(0x8ED1C027 ^ 0xB10859BD);
        Z = "bs";
        c = "math.trunc";
        F = 0xE4610B66 ^ 0xE49E2B46;
        Aa = "TITLE";
        t = "x.org";
        w = "rot";
        Y = "AFFECTED_ITEMS";
        u = "chat.link.warning";
        I = 0xD21C3214 ^ 0xD21C333A;
        la = "nether_wart_stage_1";
        j = "Pre startup";
        q = "uniform [ _a-zA-Z0-9]+ shadowcolor1;.*";
        y = "commands.scoreboard.allMatchesFailed";
        X = "x";
        Ja = "backFace.solid";
        ca = "LINES";
        E = "occupied";
        k = "RGBA32UI";
        z = "STRIPE_BOTTOM";
        G = "buildPickaxe";
        R = 0xB29E117E ^ 0xB29E1125;
        P = "animationCase_";
        g = "ChestedHorse";
        n = "animations/pet/persona_grand_arcades_animation.json";
        N = "fov";
        S = 0x4CE5D3A8 ^ 0x4CE5D375;
        e = "netherGoldOre";
        O = "Invalid animation->frames: expected array, was ";
        x = 0x1D861876 ^ 0x1D861322;
        h = "result_";
        s = "rightLeg.rightLeg1";
        o = "rm";
        U = "Piston";
        ja = "mob.zombie.step";
        K = "gameMode.changed";
        T = Float.intBitsToFloat(0xE39FAF27 ^ 0xDE1FAF27);
        f = 0x99829A02 ^ 0x99829AA2;
        D = "Unsigned Int";
        B = "Head.9";
        H = "7";
        A = "MINECART_TNT";
        Ha = "iceandsnow";
        m = "Max value of ";
        Q = 0x99DB4622 ^ 0x99DB44BE;
        J = "Entity ";
        r = "of.options.TRANSLUCENT_BLOCKS";
        W = " to be a JsonObject, was ";
        d = "(?:.*)_copper_grate";
        fa = "Pet.Ribbon9";
    }
}

