/*
 * Decompiled with CFR 0.152.
 */
public final class rSa {
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final int Ga;
    public static final int fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final int o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        e = "bow";
        m = "\u0000\t\u0000\u0001\u0001\n\t\u0000\u0001\u0000\u0001$\u0002\u1004\u0000\u0004\u1007\u0001\u0005\u1001\u0002\u0006\u1001\u0003\u0007\u1001\u0004\b\u1007\u0005\t\u1007\u0006\n\u100c\u0007";
        Aa = "Shape27123";
        L = "-0+1-2-3&4-4+13";
        g = "REPEAT_MIPMAP";
        Ka = 0x2E6926FB ^ 0x2E693FF3;
        s = "closeOnInventoryKey_";
        ia = "25";
        p = "gl_caps[ARB_vertex_program]";
        R = "Ooh. Shiny.";
        T = ",yaw:";
        D = "Front.12b";
        u = "SOUTH_WEST";
        c = "DYNAMIC_LIGHTS";
        r = "tr";
        w = "BRLeg.BRL1";
        t = "FRLeg.FRL1";
        X = "SHORT";
        a = "Tesselating block model";
        f = "gui/font/";
        ga = "Moon";
        j = 0x181C9197 ^ 0x181C1416;
        Ha = 0x41E0C933 ^ 0x41E0B689;
        Fa = "minecartChest";
        ba = "http://";
        J = "subtitle";
        Z = "GL15.GL_NORMAL_ARRAY_BUFFER_BINDING";
        n = "all_inside";
        Y = "GL11.GL_LINES";
        Ja = "stairsPurpur";
        N = "return ";
        V = "behavior_";
        Ga = 0x8EA93860 ^ 0x8EA91A61;
        E = 0xD7E338C7 ^ 0x4EF328D3;
        Q = "textures/pet/chipmunk.png";
        Ia = "supported, ";
        W = 0xFED5EAAE ^ 0xFED5E7B8;
        d = 0x39D4E6F8 ^ 0x39D46683;
        k = "GL12.GL_CLAMP_TO_EDGE";
        q = "\n#line ";
        ca = 0xEF369783 ^ 0xEF36E2C2;
        la = "innerSeams";
        I = "purple_stained_glass_pane";
        A = 0x39941C22 ^ 0x39940720;
        P = "tile.stone.andesite.name";
        y = "commands.summon.failed";
        v = Float.intBitsToFloat(0xB99B64C4 ^ 0x86464FCF);
        S = "pauseOnLostFocus:";
        h = 0xB012EE00 ^ 0xB012619B;
        B = 0x91BE801E ^ 0x91BE8FBE;
        x = "Pointer";
        fa = 0x1021F93E ^ 0x1021FB59;
        C = "key_";
        M = "[ \t]*const[ \t]*bool[ \t]*(shadowcolor0Mipmap|shadowColor0Mipmap)[ \t]*=[ \t]*true[ \t]*;.*";
        O = "cube_column";
        Da = 0xA45EA6FD ^ 0xA45EBFFA;
        i = 0x8EF05EE3 ^ 0x8EF05E8E;
        G = "Tick";
        ha = "Piece2.Shape17";
        U = 0x5BFC2422 ^ 0x5BFC5160;
        H = "CHAT_LINKS_PROMPT";
        b = "GL11.GL_DOUBLEBUFFER";
        ja = "key.spectatorOutlines";
        F = "UNDEFINED";
        Ma = 0x5521E427 ^ 0x5521CE27;
        z = 0xCAAAF30D ^ 0xCAAAD50C;
        o = 0x2E8F2270 ^ 0xD150DD8F;
        l = "LPT4";
        K = "glazed_terracotta1";
    }

    public rSa() {
        rSa a2;
    }
}

