/*
 * Decompiled with CFR 0.152.
 */
public final class rta {
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final float ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final float S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final float R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final float D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public rta() {
        rta a2;
    }

    static {
        ga = "Invalid metadata for '";
        f = 3352 /* ZKM Deobf Int */;
        p = "ground";
        n = 4294966297 /* ZKM Deobf Int */;
        Q = 7169 /* ZKM Deobf Int */;
        S = 2.3299999237060547F /* ZKM Deobf */;
        I = "commands.xp.success.negative.levels";
        Ja = "oxeyeDaisy";
        o = 0.25F /* ZKM Deobf */;
        r = "chainmail_chestplate";
        d = "Saddle";
        X = "Tex_n Mag: ";
        O = 16284963 /* ZKM Deobf Int */;
        ca = -1.268399953842163F /* ZKM Deobf */;
        Ka = 33991 /* ZKM Deobf Int */;
        N = "    ";
        V = "GL13.GL_TEXTURE27";
        U = " has no item?!";
        E = "GL14.GL_FOG_COORDINATE_ARRAY_POINTER";
        L = "Chicken";
        ja = "of.general.restart";
        j = "potion.prefix.bungling";
        t = "mall";
        c = 5391 /* ZKM Deobf Int */;
        s = " couldn't be hashed. Deleting it.";
        g = "Layer";
        H = "\u042d\u043c\u043e\u0434\u0437\u0438";
        y = "ofRenderDistanceChunks:";
        b = "INSERT_ROW";
        D = 0.01666666753590107F /* ZKM Deobf */;
        P = "grinch.animation";
        h = "dead_horn_coral_block";
        Ia = "TRIANGLES_TOP";
        w = 34066 /* ZKM Deobf Int */;
        ba = "bow1";
        K = 4800 /* ZKM Deobf Int */;
        A = "items.txt";
        M = "GL11.GL_STENCIL_FAIL";
        fa = "No tiles defined for horizontal+vertical: ";
        a = "[-+]?[0-9]+[b|B]";
        m = "hideServerAddress:";
        Ha = "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT";
        i = 395 /* ZKM Deobf Int */;
        Ma = 2882 /* ZKM Deobf Int */;
        W = "SelectorComponent{pattern='";
        ha = "fishingRod";
        x = "commands.spreadplayers.spreading.";
        T = "GL11.GL_POLYGON_TOKEN";
        e = "unlit_redstone_torch";
        Ga = "BODY_FRONT_TOP";
        Da = 354 /* ZKM Deobf Int */;
        la = "key.chat";
        k = 781 /* ZKM Deobf Int */;
        Y = "Mesa Plateau";
        C = "resin_brick_wall";
        Z = "Couldn't read ";
        B = "mcpatcher/cit/";
        q = "MC_GL_RENDERER_GEFORCE";
        R = 0.8125F /* ZKM Deobf */;
        G = 604 /* ZKM Deobf Int */;
        F = "Shape50";
        z = "_end";
        J = "GL11.GL_TEXTURE_ENV_COLOR";
        Fa = "SCALEZANIM";
        l = "Client Shutdown Thread";
        v = " Spikes";
        Aa = "level.dat_old";
        u = "iron_chestplate";
    }
}

