/*
 * Decompiled with CFR 0.152.
 */
public final class rta {
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final float ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final float S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final float R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final float D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public rta() {
        rta a2;
    }

    static {
        ga = "Invalid metadata for '";
        f = 0xACC1F6AC ^ 0xACC1FBB4;
        p = "ground";
        n = 0x578D1F37 ^ 0xA872E32E;
        Q = 0xA2AA8C4A ^ 0xA2AA904B;
        S = Float.intBitsToFloat(0xBF660914 ^ 0xFF7317AC);
        I = "commands.xp.success.negative.levels";
        Ja = "oxeyeDaisy";
        o = Float.intBitsToFloat(0x6CDE01C3 ^ 0x525E01C3);
        r = "chainmail_chestplate";
        d = "Saddle";
        X = "Tex_n Mag: ";
        O = 0x1BE24D9 ^ 0x14659FA;
        ca = Float.intBitsToFloat(0x3299C4A7 ^ 0x8D3B9E49);
        Ka = 0x4A303C8D ^ 0x4A30B84A;
        N = "    ";
        V = "GL13.GL_TEXTURE27";
        U = " has no item?!";
        E = "GL14.GL_FOG_COORDINATE_ARRAY_POINTER";
        L = "Chicken";
        ja = "of.general.restart";
        j = "potion.prefix.bungling";
        t = "mall";
        c = 0xAE94B5C9 ^ 0xAE94A0C6;
        s = " couldn't be hashed. Deleting it.";
        g = "Layer";
        H = "\u042d\u043c\u043e\u0434\u0437\u0438";
        y = "ofRenderDistanceChunks:";
        b = "INSERT_ROW";
        D = Float.intBitsToFloat(0x48BD166B ^ 0x74359EE2);
        P = "grinch.animation";
        h = "dead_horn_coral_block";
        Ia = "TRIANGLES_TOP";
        w = 0xB7A1C346 ^ 0xB7A14654;
        ba = "bow1";
        K = 0x7C226771 ^ 0x7C2275B1;
        A = "items.txt";
        M = "GL11.GL_STENCIL_FAIL";
        fa = "No tiles defined for horizontal+vertical: ";
        a = "[-+]?[0-9]+[b|B]";
        m = "hideServerAddress:";
        Ha = "GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT";
        i = 0xFD591508 ^ 0xFD591483;
        Ma = 0xA0DCC791 ^ 0xA0DCCCD3;
        W = "SelectorComponent{pattern='";
        ha = "fishingRod";
        x = "commands.spreadplayers.spreading.";
        T = "GL11.GL_POLYGON_TOKEN";
        e = "unlit_redstone_torch";
        Ga = "BODY_FRONT_TOP";
        Da = 0xCEC24E2D ^ 0xCEC24F4F;
        la = "key.chat";
        k = 0x8EDC13E9 ^ 0x8EDC10E4;
        Y = "Mesa Plateau";
        C = "resin_brick_wall";
        Z = "Couldn't read ";
        B = "mcpatcher/cit/";
        q = "MC_GL_RENDERER_GEFORCE";
        R = Float.intBitsToFloat(0x9A313C07 ^ 0xA5613C07);
        G = 0xEAABA37C ^ 0xEAABA120;
        F = "Shape50";
        z = "_end";
        J = "GL11.GL_TEXTURE_ENV_COLOR";
        Fa = "SCALEZANIM";
        l = "Client Shutdown Thread";
        v = " Spikes";
        Aa = "level.dat_old";
        u = "iron_chestplate";
    }
}

