/*
 * Decompiled with CFR 0.152.
 */
public final class rua {
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final int Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final double g;
    public static final String L;
    public static final int E;
    public static final int m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    public rua() {
        rua a2;
    }

    static {
        ca = "of.options.NATURAL_TEXTURES";
        d = "stat.walkOneCm";
        b = "ofDynamicFov";
        F = "GL13.GL_COMPRESSED_RGBA";
        B = 331 /* ZKM Deobf Int */;
        ia = "helmetGold";
        O = "SQUARE_TOP_RIGHT";
        Ja = "Invalid axis values: ";
        G = "ofSmoothBiomes:";
        Ma = "fboEnable:";
        Ga = "RG16";
        q = "GL11.GL_LINEAR_MIPMAP_LINEAR";
        H = "autumn-colors";
        A = "commands.scoreboard.teams.leave.usage";
        D = "wmo";
        Z = "EnderItems";
        m = 696 /* ZKM Deobf Int */;
        M = "builtin/empty";
        ha = "stripe_left";
        Ha = "Sections";
        c = 32000 /* ZKM Deobf Int */;
        g = 26.0D /* ZKM Deobf */;
        Aa = ";";
        a = "deathScreen.quit.confirm";
        h = 32915 /* ZKM Deobf Int */;
        I = " to ";
        j = "GL11.GL_DITHER";
        v = "body7";
        K = "\u041c\u0435\u043d\u044e \u0432\u0430\u0439\u043c\u043f\u0430\u0441\u0441\u0430";
        w = "Villages";
        Da = "LightPopulated";
        R = 9470285 /* ZKM Deobf Int */;
        p = "commands.scoreboard.objectives.add.alreadyExists";
        z = "GL11.GL_PASS_THROUGH_TOKEN";
        ja = 10797 /* ZKM Deobf Int */;
        T = 2930 /* ZKM Deobf Int */;
        U = 1.029744029045105F /* ZKM Deobf */;
        Q = "getChunk";
        E = 267 /* ZKM Deobf Int */;
        t = 36064 /* ZKM Deobf Int */;
        ga = "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0007";
        Ia = 4611 /* ZKM Deobf Int */;
        f = "username";
        u = "textures/pet/spinner_red.png";
        y = 150.0D /* ZKM Deobf */;
        la = "Items";
        r = "east=false,north=true,south=false,up=false,west=true";
        W = "Right.Right39";
        C = "glCheckFramebufferStatus returned unknown status:";
        s = "EatingHaystack";
        P = "Invalid";
        i = 748 /* ZKM Deobf Int */;
        Ka = 34029 /* ZKM Deobf Int */;
        J = 2689618000 /* ZKM Deobf Int */;
        fa = "SKULL";
        o = "mob.bat.hurt";
        L = "\u0412\u0430\u0439\u043c\u041f\u0430\u0441\u0441";
        l = "FRONT";
        e = 3694022 /* ZKM Deobf Int */;
        x = 32826 /* ZKM Deobf Int */;
        N = "librarian";
        X = "outer_left";
        V = "' in class '";
        Fa = "IMAGE_9SLICE";
        ba = "TextureAtlasSprite{name='";
        Y = 0.006666666828095913F /* ZKM Deobf */;
        n = "##TKeystrokesHud";
        S = "commands.scoreboard.objectives.remove.usage";
        k = "Making Request...";
    }
}

