/*
 * Decompiled with CFR 0.152.
 */
public final class sOa {
    public static final String ha = ", block: ";
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final float Ka;
    public static final int Aa;
    public static final int S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public sOa() {
        sOa a2;
    }

    static {
        Z = -8.0F /* ZKM Deobf */;
        c = "REDUCED_DEBUG_INFO";
        f = "Not yet implemented";
        m = "fire_aspect";
        Fa = "night_vision";
        B = "Failed to create vime storage temp file";
        i = 61458 /* ZKM Deobf Int */;
        A = "[-+]?[0-9]*\\.?[0-9]+";
        S = 193 /* ZKM Deobf Int */;
        ga = "Not supported";
        P = "hotbar-name-offset";
        R = "mangrove_stairs";
        D = 120 /* ZKM Deobf Int */;
        U = "VC: shutdown";
        F = 1021 /* ZKM Deobf Int */;
        Q = "graniteSize";
        r = "random.explode";
        n = "decayable";
        Ka = 0.6875F /* ZKM Deobf */;
        h = "sun.jnu.encoding";
        Y = "textures/gui/demo_background.png";
        g = 36161 /* ZKM Deobf Int */;
        p = 5169201 /* ZKM Deobf Int */;
        s = "GL13.GL_OPERAND0_RGB";
        N = "polished_blackstone_bricks";
        Ia = "createWorld.customize.presets.select";
        L = 2916 /* ZKM Deobf Int */;
        o = 1229209940 /* ZKM Deobf Int */;
        O = "commands.stats.block.clear.usage";
        C = "Body.Shape16";
        ca = "Piece2.Shape14";
        q = "BUTTON";
        Da = "east=true,north=false,south=false,west=true";
        G = "replace";
        W = 32849 /* ZKM Deobf Int */;
        E = "X0_Y270";
        la = "aspectRatio";
        M = "SpawnPotentials";
        K = 33085 /* ZKM Deobf Int */;
        k = "keyStatus";
        z = "achievement.mineWood";
        ja = "potion.prefix.flat";
        t = "session.lock";
        T = "Unsupported geometry version ";
        w = "Marker";
        u = "User-Agent";
        v = "of.options.RAIN";
        x = 146 /* ZKM Deobf Int */;
        a = "stat.breakItem";
        d = "GRADIENT_UP";
        Ja = "#include depth exceeded: ";
        l = "RADIUSANIM";
        H = "minecraft:blocks/obsidian";
        Aa = 16775294 /* ZKM Deobf Int */;
        Ga = "DebugSkinLoading";
        Ha = "run_time";
        J = "&c\u0426\u0435\u043b\u044c \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u0430";
        X = "Outdated server! I'm still on 1.8.8";
        b = "water-colorm";
        fa = 16579836 /* ZKM Deobf Int */;
        I = "GL11.GL_RGBA8";
        y = 61454 /* ZKM Deobf Int */;
        j = "HAND_DEPTH_MUL";
        e = "melon_block";
        V = "options.difficulty.hard";
    }
}

