/*
 * Decompiled with CFR 0.152.
 */
public final class sOa {
    public static final String ha = ", block: ";
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final float Ka;
    public static final int Aa;
    public static final int S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public sOa() {
        sOa a2;
    }

    static {
        Z = Float.intBitsToFloat(0x2D890F77 ^ 0xEC890F77);
        c = "REDUCED_DEBUG_INFO";
        f = "Not yet implemented";
        m = "fire_aspect";
        Fa = "night_vision";
        B = "Failed to create vime storage temp file";
        i = 0x235DCFF8 ^ 0x235D3FEA;
        A = "[-+]?[0-9]*\\.?[0-9]+";
        S = 0x66F4DC0E ^ 0x66F4DCCF;
        ga = "Not supported";
        P = "hotbar-name-offset";
        R = "mangrove_stairs";
        D = 0x66426B59 ^ 0x66426B21;
        U = "VC: shutdown";
        F = 0x42643604 ^ 0x426435F9;
        Q = "graniteSize";
        r = "random.explode";
        n = "decayable";
        Ka = Float.intBitsToFloat(0xA7900AE4 ^ 0x98A00AE4);
        h = "sun.jnu.encoding";
        Y = "textures/gui/demo_background.png";
        g = 0x1B86C6A8 ^ 0x1B864BE9;
        p = 0x4A01F6D8 ^ 0x4A4F16E9;
        s = "GL13.GL_OPERAND0_RGB";
        N = "polished_blackstone_bricks";
        Ia = "createWorld.customize.presets.select";
        L = 0x88EB14F0 ^ 0x88EB1F94;
        o = 0xD7CBBD8 ^ 0x4438FA8C;
        O = "commands.stats.block.clear.usage";
        C = "Body.Shape16";
        ca = "Piece2.Shape14";
        q = "BUTTON";
        Da = "east=true,north=false,south=false,west=true";
        G = "replace";
        W = 0x3B7D15CD ^ 0x3B7D959C;
        E = "X0_Y270";
        la = "aspectRatio";
        M = "SpawnPotentials";
        K = 0xFFE20C2D ^ 0xFFE28D10;
        k = "keyStatus";
        z = "achievement.mineWood";
        ja = "potion.prefix.flat";
        t = "session.lock";
        T = "Unsupported geometry version ";
        w = "Marker";
        u = "User-Agent";
        v = "of.options.RAIN";
        x = 0xD69646F1 ^ 0xD6964663;
        a = "stat.breakItem";
        d = "GRADIENT_UP";
        Ja = "#include depth exceeded: ";
        l = "RADIUSANIM";
        H = "minecraft:blocks/obsidian";
        Aa = 0x4B559D52 ^ 0x4BAA652C;
        Ga = "DebugSkinLoading";
        Ha = "run_time";
        J = "&c\u0426\u0435\u043b\u044c \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u0430";
        X = "Outdated server! I'm still on 1.8.8";
        b = "water-colorm";
        fa = 0xE593A725 ^ 0xE56F5BD9;
        I = "GL11.GL_RGBA8";
        y = 0xA7085125 ^ 0xA708A12B;
        j = "HAND_DEPTH_MUL";
        e = "melon_block";
        V = "options.difficulty.hard";
    }
}

