/*
 * Decompiled with CFR 0.152.
 */
public final class SOa_1 {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final double N;
    public static final String T;
    public static final String p;
    public static final float n;
    public static final float s;
    public static final double w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final long a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final double M;
    public static final String k;
    public static final String j;
    public static final double J;
    public static final int A;
    public static final float I;

    public SOa_1() {
        SOa_1 a2;
    }

    static {
        z = "random.door_close";
        c = " is a fence and should have 1 texture, got ";
        w = Double.longBitsToDouble(0xC7643D34114A8CCEL ^ 0x87483D34114A8CCEL);
        l = "gui.cancel";
        la = "commands.scoreboard.players.reset.usage";
        ja = "eDirectDraw_";
        B = Float.intBitsToFloat(0x6E16251B ^ 0xD287F455);
        ca = "Piece1.Shape26";
        Y = "dark_prismarine";
        v = "yh";
        J = Double.longBitsToDouble(0x5725E601F678E4B8L ^ 0x68EDE601F678E4B8L);
        K = "lowerLimitScale";
        O = 0x5164B1D3 ^ 0xAE9B412C;
        T = "decompress";
        E = "Head.Shape2";
        P = "selectWorld.enterSeed";
        Z = "melon";
        y = "Tried send packet with auto closed connection";
        i = "crimson_log_stripped";
        x = "Invalid server icon (unknown format)";
        q = "GL11.GL_LIGHT_MODEL_LOCAL_VIEWER";
        I = Float.intBitsToFloat(0x6795E948 ^ 0xA6BDE948);
        W = "neutral";
        t = "achievement.potion";
        Ja = Float.intBitsToFloat(0xBEC11343 ^ 0xF7EBF543);
        S = " just tried to change non-editable sign";
        h = "potion.moveSpeed";
        X = "Shape2123";
        C = 0xF6194645 ^ 0xF619C2AC;
        H = "Piece1.Shape17";
        Q = "VELOCITY";
        Aa = "cherryFence";
        u = "CHISELED_STONEBRICK";
        N = Double.longBitsToDouble(0xD8A422AC824A2B1DL ^ 0xE74A4DC5C62D1300L);
        ga = "nvidia";
        g = "ofDynamicLights:";
        n = Float.intBitsToFloat(0x3DF3A522 ^ 0xFEBBA522);
        j = "perspective";
        M = Double.longBitsToDouble(0x5049451EEA237802L ^ 0xEF8435BD3D294573L);
        Da = "double_plant_fern_bottom";
        L = "IMAGEDATA";
        A = 0xF911244 ^ 0xFDF8175;
        U = "depth_strider";
        m = "waxedOxidizedCutCopper";
        f = "Eyes.Shape18";
        fa = "NeCCS";
        V = "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\f\u0002<\u0000";
        R = "dark_oak_sapling";
        p = "wolf/wolf_collar";
        Ha = "eRadialProgressBar_";
        k = "Shape26123";
        b = "GL11.GL_FALSE";
        e = "ItemFrame";
        Ga = "Riding";
        s = Float.intBitsToFloat(0x73D4D10A ^ 0x32C81DC7);
        G = "defaultCharset";
        Ka = "\u0000\f\u0000\u0001\u0001\f\f\u0000\t\u0000\u0001\u001b\u0002\u001b\u0003\u1004\u0000\u0004\u100c\u0001\u0005\u001b\u0006\u001b\u0007\u001b\b\u001b\t\u001b\n\u001b\u000b\u001b\f\u1208\u0002";
        a = 0x8873EA8889D2B505L ^ 0x8873EA8889D2AA45L;
        r = "entity.mule.name";
        d = "setdisplay";
        F = "/icon";
        D = "SIGN";
        o = "GL14.GL_COLOR_SUM";
    }
}

