/*
 * Decompiled with CFR 0.152.
 */
public final class Spa_1 {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final int Ja;
    public static final int ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final long R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final double s;
    public static final String w;
    public static final String W;
    public static final long q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final int H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public Spa_1() {
        Spa_1 a2;
    }

    static {
        L = "starve";
        b = "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
        Y = "ofBetterSnow:";
        ja = 33000 /* ZKM Deobf Int */;
        g = "GL11.GL_AMBIENT_AND_DIFFUSE";
        o = "scaleyval_";
        Ja = 20314 /* ZKM Deobf Int */;
        la = "error getting microphones";
        e = "animation";
        R = 0x2805D727055C4EF3L ^ 0x2805D727055C4E65L;
        Q = "gl_caps[gl_max_vertex_attribs]";
        F = "textures/body/wings_blue.png";
        I = 32878 /* ZKM Deobf Int */;
        h = "LH1";
        v = 7455580 /* ZKM Deobf Int */;
        a = "displayFormat_";
        r = "Shape102";
        fa = "Head";
        q = 0xAF23B44EA1E68BB4L ^ 0xAF23B44EA1E68BFCL;
        P = "slime/slime";
        x = 725 /* ZKM Deobf Int */;
        Fa = "footstep";
        Aa = "Back.4b";
        t = "wo_";
        Ha = 9986 /* ZKM Deobf Int */;
        Ga = "frontfoot.main";
        j = "cobbledDeepslateSlab";
        Ia = "\u0000\r\u0002\u0001\u0001\r\r\u0000\u0001\u0000\u0001\u1006\u0000\u0002\u1001\u0001\u0003\u023b\u0000\u00047\u0000\u0005\u023b\u0001\u00067\u0001\u0007\u1001\u0002\b\u1001\u0003\t\u1007\u0004\n\u1007\u0005\u000b\u1009\u0006\f'\r\u1007\u0007";
        B = "PORTAL";
        Z = 10020 /* ZKM Deobf Int */;
        m = -0.9100000262260437F /* ZKM Deobf */;
        H = 61447 /* ZKM Deobf Int */;
        p = "\u0421\u043f\u0440\u0430\u0432\u0430 \u0441\u043d\u0438\u0437\u0443";
        U = "show_entity";
        O = "Left.Shape16123";
        T = "{}";
        N = "ServerChunkCache: ";
        c = 420.0D /* ZKM Deobf */;
        d = "SATURATION";
        u = "Frame sizes";
        ga = "expBottle";
        W = "goto";
        l = "commands.worldborder.damage.amount.success";
        G = "662A6B8D-DA3E-4C1C-8813-96EA6097278D";
        E = "index can't be > size: ";
        J = "com.sun.jndi.dns.DnsContextFactory";
        n = "HELMET";
        ba = "step_";
        Da = 8368696 /* ZKM Deobf Int */;
        K = 2962 /* ZKM Deobf Int */;
        k = "arrow";
        s = -1.5D /* ZKM Deobf */;
        ca = "AURAS";
        i = "mcpatcher/lightmap/world";
        ha = "item.comparator.name";
        S = "hellrock";
        M = "birch_fence";
        V = "ofSky:";
        y = 1e-09D /* ZKM Deobf */;
        X = "min_";
        A = "ofAoLevel:";
        D = "advMode.randomPlayer";
        f = 1006 /* ZKM Deobf Int */;
        w = "hinge";
        z = "item.diode.name";
        C = "minecraft:items/";
        Ka = "/hub";
    }
}

