/*
 * Decompiled with CFR 0.152.
 */
public final class SQa_2 {
    public static final String ha;
    public static final String Fa;
    public static final float Ia;
    public static final String la;
    public static final double ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final double S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final long n;
    public static final String s;
    public static final float w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final double F;
    public static final int g;
    public static final int L;
    public static final double E;
    public static final String m;
    public static final int C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        p = "comparator";
        z = "GL11.GL_SHININESS";
        w = -0.30000001192092896F /* ZKM Deobf */;
        l = "Anger";
        D = "frames_per_second";
        f = "black_stained_glass_pane";
        ja = "CURLY_BORDER";
        g = 349 /* ZKM Deobf Int */;
        c = "VCR: audio {}, {}";
        s = "RADIUS";
        L = 4294443256 /* ZKM Deobf Int */;
        Ha = "Disconnect reason: ";
        Y = "mob.silverfish.say";
        R = "chiseledTuff";
        o = "UV";
        Ga = "HEIGHTEXPRANIM";
        e = "Piece1.head";
        Z = "durability.png";
        m = "GL14.GL_GENERATE_MIPMAP";
        n = 0x22A4446BBC88778CL ^ 0x22A4446BBC887788L;
        Fa = "potion.prefix.acrid";
        Ia = -18.113300323486328F /* ZKM Deobf */;
        Da = "_slab";
        K = "AUTOSAVE_TICKS";
        r = "OCHRE";
        v = "{\"elements\":[{  \"from\": [0, 0, 0],   \"to\": [16, 16, 16],   \"faces\": {       \"down\": {\"uv\": [0, 0, 16, 16], \"texture\":\"\"}   }}]}";
        O = "tile.gravel.name";
        P = "warped";
        ca = 5888 /* ZKM Deobf Int */;
        ga = -0.35D /* ZKM Deobf */;
        y = "options.renderClouds";
        q = "creakingHeart";
        J = "createWorld.customize.custom.preset.drought";
        V = "GL13.GL_TEXTURE20";
        Aa = "textures/entity/chest/trapped.png";
        T = "hide-hud-effects";
        b = "z0";
        h = "death.fell.accident.";
        ha = "double_stone_slab2";
        Ka = 6724056 /* ZKM Deobf Int */;
        C = 30029 /* ZKM Deobf Int */;
        U = "low_left_leg";
        j = ", builtIn: ";
        u = "east=false,north=false,south=false,up=false,west=false";
        S = 536.0D /* ZKM Deobf */;
        x = "Texteria2D";
        t = 13.0D /* ZKM Deobf */;
        k = "textures/misc/enchanted_item_glint.png";
        E = -2.0D /* ZKM Deobf */;
        Q = "portal";
        M = "MOSSY_STONEBRICK";
        W = 8.600000381469727F /* ZKM Deobf */;
        G = "Couldn't make new level";
        N = "trapdoor";
        A = "squid";
        X = "gallium";
        a = "Bone Matrix";
        Ja = "fixed-view-yaw";
        H = "RRQ";
        i = 141 /* ZKM Deobf Int */;
        B = 32845 /* ZKM Deobf Int */;
        d = "OPAQUE";
        I = "STRIPE_MIDDLE";
        la = "sampler";
        fa = "\u041f\u0435\u0440\u0435\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435";
        F = 0.005D /* ZKM Deobf */;
    }

    public SQa_2() {
        SQa_2 a2;
    }
}

