/*
 * Decompiled with CFR 0.152.
 */
public final class Sqa_1 {
    public static final int Ma;
    public static final float ba;
    public static final String ha;
    public static final float Fa;
    public static final String Ia;
    public static final int la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final int ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final int Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Sqa_1() {
        Sqa_1 a2;
    }

    static {
        h = "prismarine_shard";
        y = "uses_auth";
        O = "fog-forced";
        Ia = "Chunk stats";
        Z = 0x38F477B ^ 0x38F4B2A;
        R = "coordinateScale";
        p = "LeftLeg.Shape16";
        s = "textures/pet/bimopet.png";
        M = "MARKER";
        e = "GL_MAX_DRAW_BUFFERS: ";
        la = 0xCD4A19A ^ 0xCD42560;
        Ha = 0xD59A907E ^ 0xD59A189E;
        m = "Front";
        Ga = "GL11.GL_VERTEX_ARRAY_STRIDE";
        Da = "\"Silently\" catching entity tracking error.";
        Ka = "VC: shutdown complete";
        d = " s";
        C = "Element render error (";
        P = Float.intBitsToFloat(0x831148F0 ^ 0x4208D16A);
        r = "Arrow";
        u = "melon_seeds";
        N = Float.intBitsToFloat(0xADF23BA6 ^ 0x97A66D88);
        W = "GL11.GL_COMPILE";
        b = "LOOK_AT_ENTITY_TYPE";
        X = "The objective name '";
        ha = "standing_banner";
        fa = "cut_copper_slab_double";
        f = "DONKEY_KONG";
        Q = "~~ ";
        x = "Map colour ID must be between 0 and 63 (inclusive)";
        L = Double.longBitsToDouble(0xA36EBE4D82A436C6L ^ 0xE370BE4D82A436C6L);
        a = "blue_stained_glass";
        ba = Float.intBitsToFloat(0xC9973805 ^ 0x8F6A19F);
        J = "All: ";
        Fa = Float.intBitsToFloat(0xB882D03B ^ 0x7984B65D);
        l = "combat";
        D = 0x956EC5DD ^ 0x956E59BC;
        T = "Am I not running fast enough? :(";
        I = "attribute.name.";
        n = "assets/minecraft/models/block/grass.json";
        ja = 0xC0E69505 ^ 0xC0E61D92;
        V = 0xDE64FA17 ^ 0xDE64F6E4;
        z = "gl_caps[EXT_vertex_weighting]";
        c = 0x8AF6CE40 ^ 0x8AF6CC19;
        A = "encoder";
        H = "waxed_cut_copper";
        K = "GL12.GL_LIGHT_MODEL_COLOR_CONTROL";
        t = "OBFUSCATED";
        Ja = Float.intBitsToFloat(0xD55B528C ^ 0x979B528C);
        ga = Float.intBitsToFloat(0xD4BDEC96 ^ 0x94FDED35);
        F = "TransferCooldown";
        v = "doorSpruce";
        Ma = 0x63E310F2 ^ 0x63E35FB6;
        B = "Illegal use of \\\": ";
        Aa = ", time=";
        G = "\u041a\u043e\u0434: 0x";
        S = "maxUses";
        w = "RESORT_TRANSPARENCY";
        E = "Options";
        i = "Sheared";
        ca = "anaglyph3d";
        o = "[ \t]*const[ \t]*float[ \t]*wetnessHalflife[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        j = "CUSTOM_ANIMATION";
        k = "Pos{x=";
        U = "of.options.SUN_MOON";
        g = Float.intBitsToFloat(0xF79AC398 ^ 0xC8C35A02);
        q = Float.intBitsToFloat(0xBFC99057 ^ 0xFC959057);
        Y = 0x4D9E2352 ^ 0x4D9E2040;
    }
}

