/*
 * Decompiled with CFR 0.152.
 */
public final class SQa_2 {
    public static final String ha;
    public static final String Fa;
    public static final float Ia;
    public static final String la;
    public static final double ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final double S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final long n;
    public static final String s;
    public static final float w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final double F;
    public static final int g;
    public static final int L;
    public static final double E;
    public static final String m;
    public static final int C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        p = "comparator";
        z = "GL11.GL_SHININESS";
        w = Float.intBitsToFloat(0xA7443538 ^ 0x19DDACA2);
        l = "Anger";
        D = "frames_per_second";
        f = "black_stained_glass_pane";
        ja = "CURLY_BORDER";
        g = 0xDE801EE1 ^ 0xDE801FBC;
        c = "VCR: audio {}, {}";
        s = "RADIUS";
        L = 0xAC72F3A5 ^ 0x538AF35D;
        Ha = "Disconnect reason: ";
        Y = "mob.silverfish.say";
        R = "chiseledTuff";
        o = "UV";
        Ga = "HEIGHTEXPRANIM";
        e = "Piece1.head";
        Z = "durability.png";
        m = "GL14.GL_GENERATE_MIPMAP";
        n = 0x22A4446BBC88778CL ^ 0x22A4446BBC887788L;
        Fa = "potion.prefix.acrid";
        Ia = Float.intBitsToFloat(0x4E92768D ^ 0x8F029E87);
        Da = "_slab";
        K = "AUTOSAVE_TICKS";
        r = "OCHRE";
        v = "{\"elements\":[{  \"from\": [0, 0, 0],   \"to\": [16, 16, 16],   \"faces\": {       \"down\": {\"uv\": [0, 0, 16, 16], \"texture\":\"\"}   }}]}";
        O = "tile.gravel.name";
        P = "warped";
        ca = 0x39FC1C26 ^ 0x39FC0B26;
        ga = Double.longBitsToDouble(0xEF38CBA7454A7135L ^ 0x50EEADC1232C1753L);
        y = "options.renderClouds";
        q = "creakingHeart";
        J = "createWorld.customize.custom.preset.drought";
        V = "GL13.GL_TEXTURE20";
        Aa = "textures/entity/chest/trapped.png";
        T = "hide-hud-effects";
        b = "z0";
        h = "death.fell.accident.";
        ha = "double_stone_slab2";
        Ka = 0xC4DACC37 ^ 0xC4BC55EF;
        C = 0xB6AFE263 ^ 0xB6AF972E;
        U = "low_left_leg";
        j = ", builtIn: ";
        u = "east=false,north=false,south=false,up=false,west=false";
        S = Double.longBitsToDouble(0x15378076D294DE3CL ^ 0x55B74076D294DE3CL);
        x = "Texteria2D";
        t = Double.longBitsToDouble(0xD08E63699D950A5BL ^ 0x90A463699D950A5BL);
        k = "textures/misc/enchanted_item_glint.png";
        E = Double.longBitsToDouble(0x66C541A2060D5495L ^ 0xA6C541A2060D5495L);
        Q = "portal";
        M = "MOSSY_STONEBRICK";
        W = Float.intBitsToFloat(0x9FA3F016 ^ 0xDEAA698C);
        G = "Couldn't make new level";
        N = "trapdoor";
        A = "squid";
        X = "gallium";
        a = "Bone Matrix";
        Ja = "fixed-view-yaw";
        H = "RRQ";
        i = 0xFDB519B3 ^ 0xFDB5193E;
        B = 0x9DD914D7 ^ 0x9DD9949A;
        d = "OPAQUE";
        I = "STRIPE_MIDDLE";
        la = "sampler";
        fa = "\u041f\u0435\u0440\u0435\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435";
        F = Double.longBitsToDouble(0x9BB0CDA575488B1EL ^ 0xA4C4B74432E69F65L);
    }

    public SQa_2() {
        SQa_2 a2;
    }
}

