/*
 * Decompiled with CFR 0.152.
 */
public final class Sqa_1 {
    public static final int Ma;
    public static final float ba;
    public static final String ha;
    public static final float Fa;
    public static final String Ia;
    public static final int la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final int ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final int Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final double L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Sqa_1() {
        Sqa_1 a2;
    }

    static {
        h = "prismarine_shard";
        y = "uses_auth";
        O = "fog-forced";
        Ia = "Chunk stats";
        Z = 3153 /* ZKM Deobf Int */;
        R = "coordinateScale";
        p = "LeftLeg.Shape16";
        s = "textures/pet/bimopet.png";
        M = "MARKER";
        e = "GL_MAX_DRAW_BUFFERS: ";
        la = 34042 /* ZKM Deobf Int */;
        Ha = 35040 /* ZKM Deobf Int */;
        m = "Front";
        Ga = "GL11.GL_VERTEX_ARRAY_STRIDE";
        Da = "\"Silently\" catching entity tracking error.";
        Ka = "VC: shutdown complete";
        d = " s";
        C = "Element render error (";
        P = -9.600000381469727F /* ZKM Deobf */;
        r = "Arrow";
        u = "melon_seeds";
        N = 0.0008099999977275729F /* ZKM Deobf */;
        W = "GL11.GL_COMPILE";
        b = "LOOK_AT_ENTITY_TYPE";
        X = "The objective name '";
        ha = "standing_banner";
        fa = "cut_copper_slab_double";
        f = "DONKEY_KONG";
        Q = "~~ ";
        x = "Map colour ID must be between 0 and 63 (inclusive)";
        L = 7.5D /* ZKM Deobf */;
        a = "blue_stained_glass";
        ba = -14.100000381469727F /* ZKM Deobf */;
        J = "All: ";
        Fa = -8.399999618530273F /* ZKM Deobf */;
        l = "combat";
        D = 40033 /* ZKM Deobf Int */;
        T = "Am I not running fast enough? :(";
        I = "attribute.name.";
        n = "assets/minecraft/models/block/grass.json";
        ja = 34967 /* ZKM Deobf Int */;
        V = 3315 /* ZKM Deobf Int */;
        z = "gl_caps[EXT_vertex_weighting]";
        c = 601 /* ZKM Deobf Int */;
        A = "encoder";
        H = "waxed_cut_copper";
        K = "GL12.GL_LIGHT_MODEL_COLOR_CONTROL";
        t = "OBFUSCATED";
        Ja = 96.0F /* ZKM Deobf */;
        ga = 3.0000998973846436F /* ZKM Deobf */;
        F = "TransferCooldown";
        v = "doorSpruce";
        Ma = 20292 /* ZKM Deobf Int */;
        B = "Illegal use of \\\": ";
        Aa = ", time=";
        G = "\u041a\u043e\u0434: 0x";
        S = "maxUses";
        w = "RESORT_TRANSPARENCY";
        E = "Options";
        i = "Sheared";
        ca = "anaglyph3d";
        o = "[ \t]*const[ \t]*float[ \t]*wetnessHalflife[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        j = "CUSTOM_ANIMATION";
        k = "Pos{x=";
        U = "of.options.SUN_MOON";
        g = 0.8500000238418579F /* ZKM Deobf */;
        q = 220.0F /* ZKM Deobf */;
        Y = 786 /* ZKM Deobf Int */;
    }
}

