/*
 * Decompiled with CFR 0.152.
 */
public final class sSa {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final float Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final float Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final float F;
    public static final String g;
    public static final String L;
    public static final float E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final int I;

    static {
        t = "commands.gamemode.usage";
        I = 0x4B68CED0 ^ 0xA9C2B001;
        J = "BREAKABLE";
        ca = "spreadMotionZ_";
        R = "???";
        Da = "Null returned as 'hitResult', this shouldn't happen!";
        Ia = "Left.Shape70123";
        F = Float.intBitsToFloat(0x7F0F0CCD ^ 0x3E296AAB);
        Ga = Float.intBitsToFloat(0xD08FDBF6 ^ 0x11D3173B);
        q = "SMALL_FIREBALL";
        H = "eTextTimer_";
        f = "Back.9a";
        O = "H";
        a = "+5-6-7";
        i = "TexMagFilN";
        Y = Float.intBitsToFloat(0x39AF49CC ^ 0xF8B0041F);
        K = "renderClouds:fast";
        P = " and ";
        l = "lit_pumpkin";
        ja = "name_tag";
        s = "GL13.GL_TEXTURE12";
        Z = "item.flowerPot.name";
        c = "moodSound";
        k = "stat.hopperInspected";
        d = "F4";
        Ha = "selectedItemName";
        X = "monsterPlacer";
        Ja = "Multiple values have the same name '";
        w = "acacia_leaves";
        U = "Biome not found: ";
        T = "keyframes";
        W = "streamPreferredServer";
        x = "\u041f\u0443\u0431\u043b\u0438\u0447\u043d\u043e\u0435 \u043f\u0430\u0442\u0438";
        o = "dungeonChance";
        fa = Float.intBitsToFloat(0x2149DBB7 ^ 0xE3E9DBB7);
        b = 0xD9A292A3 ^ 0xD9A20E69;
        D = 0x9DEA4B8C ^ 0x9DEA418C;
        Ka = "commands.scoreboard.players.set.tagMismatch";
        y = "blocks/destroy_stage_1";
        z = 0x3E34DC3B ^ 0x3E34DB38;
        e = 0x57A71A86 ^ 0x57A71BE1;
        N = "Internal server error";
        B = ", zDelta: ";
        A = 0x65876423 ^ 0x6587ECC9;
        S = "GL11.GL_LINEAR";
        L = "Center depth halflife: ";
        Q = Float.intBitsToFloat(0x1806178D ^ 0xA7DCF6C5);
        G = "createWorld.customize.custom.preset.mountains";
        n = "BedrockEmote item ";
        j = "blockIron";
        h = Float.intBitsToFloat(0x5C7DCD55 ^ 0x1E21CD55);
        p = "GAMMA";
        Fa = "dye_cyan";
        ga = "ENCHANTMENT_TABLE";
        r = "GL12.GL_TEXTURE_MAX_LEVEL";
        v = "GL11.GL_MAX_NAME_STACK_DEPTH";
        g = "srv";
        u = "cloudShadow";
        m = Float.intBitsToFloat(0x4B83C1B0 ^ 0xA8BC1B0);
        V = "<profile>";
        E = Float.intBitsToFloat(0xC1B28468 ^ 0x807A8468);
        Aa = "Leader zombie bonus";
        M = 0x25E25D9E ^ 0x25E2D957;
        la = "os.version";
        C = "ORANGE";
    }

    public sSa() {
        sSa a2;
    }
}

