/*
 * Decompiled with CFR 0.152.
 */
public final class Ssa_1 {
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final long Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final double fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final float M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final float A;
    public static final int I;

    static {
        Z = "light_";
        fa = Double.longBitsToDouble(0xD7901DED19E83B9AL ^ 0x684984748071A200L);
        ha = "new";
        r = "TRIANGLE_TOP";
        l = Float.intBitsToFloat(0x26772DD3 ^ 0x1AA15A83);
        N = "Encountered an unexpected exception";
        X = "dye_yellow";
        W = "selectWorld.delete";
        n = "Riches";
        H = "gbuffers_beaconbeam";
        S = "blackstone_stairs";
        y = "of.options.shaders.OLD_LIGHTING";
        K = Float.intBitsToFloat(0xA5310357 ^ 0x9ADFF350);
        o = Float.intBitsToFloat(0x5C3792B5 ^ 0x19ABD2B5);
        Da = "game.neutral.swim.splash";
        Y = "GL11.GL_FEEDBACK_BUFFER_POINTER";
        Q = "silver_ore";
        R = "creation_expression";
        G = " at (";
        k = 0x8894AAA5 ^ 0x8894E465;
        Fa = "Using ARB_multitexture.\n";
        f = "pickaxeDiamond";
        V = "facing=east,half=top,shape=straight";
        A = Float.intBitsToFloat(0xCA2F1760 ^ 0xB342453);
        D = "N";
        Ga = "gl_caps[EXT_texture_array]";
        P = "undead";
        x = "part";
        v = "doublePlant";
        Aa = "shadowColor0Mipmap";
        Ha = "rainTime";
        g = "killCow";
        B = "DIORITE";
        w = "SIZEEXPRANIM";
        h = "gray_stained_glass_pane";
        la = Float.intBitsToFloat(0xD74B7F6 ^ 0x3292D190);
        a = "mob.rabbit.idle";
        p = 0x33F43A80 ^ 0x33F4BE46;
        b = "*:**";
        ba = 0x9FDDE4F1 ^ 0x9FDDE6AC;
        s = 0xC7D9F71C ^ 0xC70BA80E;
        T = "moveSpeed";
        q = "Uninit";
        Ia = 0x9A2F624D81FBF398L ^ 0x9A2F624D81DBF398L;
        z = "{\"elements\":[{  \"from\": [0, 0, 0],   \"to\": [0, 0, 0],   \"faces\": {       \"down\": {\"uv\": [0, 0, 0, 0], \"texture\":\"missingno\"}   }}]}";
        m = "GL11.GL_TEXTURE_MATRIX";
        j = "north_west";
        O = "Ping";
        J = "\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435 '";
        e = 0x9047FA7E ^ 0x9047FB5B;
        C = "\u0000\r\u0001\u0001\u0001\r\r\u0000\u0000\u0000\u0001\u023b\u0000\u00027\u0000\u0003\u1208\u0000\u0004\u1007\u0001\u0005\u100c\u0002\u0006\u1001\u0003\u0007\u1001\u0004\b\u1007\u0005\t\u1004\u0006\n\u1001\u0007\u000b\u1001\b\f\u1001\t\r\u1001\n";
        F = "Texteria.debug";
        U = "of.options.MIPMAP_TYPE";
        E = "XL";
        u = 0xC8B39239 ^ 0xC8B39206;
        I = 0xDFBF530C ^ 0xDFBF5408;
        c = 0x143B4D9C ^ 0x143BCDF5;
        d = "sprintMode:";
        ja = "Update interval";
        M = Float.intBitsToFloat(0x1E4C38BD ^ 0x2084308F);
        ga = "Image texture {}x{} uploaded in {} ms";
        L = "CHAT_HEIGHT_UNFOCUSED";
        i = "ROTATEANIM";
        t = 0x47DDC2EF ^ 0x47DDB7BE;
        Ja = "drs_set";
        Ka = "<=";
        ca = "pale_oak_slab";
    }

    public Ssa_1() {
        Ssa_1 a2;
    }
}

