/*
 * Decompiled with CFR 0.152.
 */
public final class TOa {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final long ja;
    public static final String Ha;
    public static final double Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final float p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final int B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public TOa() {
        TOa a2;
    }

    static {
        Q = "&e/cam add [\u043d\u043e\u043c\u0435\u0440]&f: \u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u043e\u0447\u043a\u0443 \u0432 \u0442\u0435\u043a\u0443\u0449\u0435\u0439 \u043f\u043e\u0437\u0438\u0446\u0438\u0438";
        R = Float.intBitsToFloat(0xEC331E0B ^ 0x2DC31E0B);
        fa = "connect";
        e = "\u041c\u0430\u0441\u0448\u0442\u0430\u0431: ";
        x = "warped_nylium";
        d = "armorDurabilityBar:";
        Da = "Aztec2";
        c = Float.intBitsToFloat(0x581C0801 ^ 0xE72459EA);
        E = "replace_right_arm";
        A = 0x7964A614 ^ 0x7964A48D;
        V = 0x85734E6F ^ 0x7A8CB19E;
        p = Float.intBitsToFloat(0x87610EC5 ^ 0x47210EC5);
        ja = 0xA045D3D176892F56L ^ 0xA045D3D176893F56L;
        ga = "mainNoiseScaleY";
        l = 0xCE5F410C ^ 0xCE5FC5C7;
        Z = "pale_oak_fence_gate";
        m = "chestplate";
        f = "../src/minecraft/assets/minidot/itemmeta";
        K = "stat.killEntity.";
        Ja = 0xC1546EA9 ^ 0xC154FFE1;
        F = "ofSmoothWorld";
        C = "streamChatEnabled";
        W = "tnt";
        z = "Shape71123";
        k = "B9766B59-9566-4402-BC1F-2EE2A276D836";
        M = "MUSHROOM_BROWN";
        P = "Left.Shape21123";
        g = "math.round";
        Y = "CREEPER";
        S = "shape";
        s = "matrix";
        u = "F11";
        X = " values, found: ";
        Ha = "speed";
        r = Float.intBitsToFloat(0xB202C6BA ^ 0x8C2111B0);
        H = "The team name '";
        G = "'.";
        la = "grass_side_snowed";
        I = "redstone_dust_cross_overlay";
        ca = "SHS";
        Ga = Double.longBitsToDouble(0x1DA5AF97CB84FE70L ^ 0xA244360E521D67EAL);
        t = "\u00a78-@HIDDEN";
        b = "[-+]?[0-9]*\\.?[0-9]+[f|F]";
        Aa = "Why am I here?";
        o = "largesmoke";
        n = ", ";
        D = "Shape54";
        L = Float.intBitsToFloat(0x708A05B4 ^ 0x300C0F26);
        O = "crimson_planks";
        U = "ID #%d (%s // %s)";
        w = "defaultBackground_";
        Ka = "GL11.GL_TEXTURE_COORD_ARRAY_POINTER";
        B = 0xE11C38C5 ^ 0x1E968207;
        a = 0xF3BED30F ^ 0xF32DF72C;
        Ia = "cherry";
        q = "stat.damageTaken";
        y = "STOP_SPRINTING";
        j = "XPOrb";
        h = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0004\u0002\u100a\u0000\u0003\u1007\u0001\u0004\u1007\u0002";
        T = "- ";
        J = "packed_ice";
        v = "durationTicks";
        N = 0x6DC3DBDD ^ 0x6DC35E54;
        i = "characters";
    }
}

