/*
 * Decompiled with CFR 0.152.
 */
public final class tpa {
    public static final String ca;
    public static final long Ja;
    public static final float ja;
    public static final String Ha;
    public static final String Ga;
    public static final double fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final float h;
    public static final int K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final float M;
    public static final double k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        J = "ELEMENT_FOCUS";
        E = "0 & !1 & 2 & !3";
        U = "global:";
        a = "textures/body/garlands2.png";
        Z = "generic.followRange";
        O = "textures/entity/sheep/sheep.png";
        j = "idcounts";
        c = "NORTH_SOUTH";
        w = "dark_prismarine_stairs";
        f = "Invalid height: ";
        B = "map/";
        N = ".name";
        k = Double.longBitsToDouble(0x2CB0B344F39E54EBL ^ 0x13092ADD6A07CD71L);
        e = "INVENTORYNAME";
        h = Float.intBitsToFloat(0x241B7115 ^ 0x9BE2E88F);
        D = "GL11.GL_TEXTURE_INTERNAL_FORMAT";
        g = "hover_";
        Q = "container.beacon";
        s = "polished_deepslate";
        F = " OpenAL error ";
        Ha = ", name='";
        t = "Texture is newer than on disk ({}, {} > {})";
        q = "east=false,north=false,south=true,up=true,west=false";
        m = "mob.sheep.shear";
        V = "mob.horse.soft";
        M = Float.intBitsToFloat(0x9CDB787F ^ 0xA169C0B8);
        l = 0xD328A792 ^ 0xD328AC90;
        Ga = "Head.21";
        fa = Double.longBitsToDouble(0x9B32E42CAD30A553L ^ 0xA4D39071BA757427L);
        S = "element_";
        Y = "tail";
        Ja = 0x7534544E7F3A1CCFL ^ 0x7534544E7F3A1777L;
        K = 0x7B305082 ^ 0x7B3000E1;
        x = "ARBImaging.GL_BLEND_EQUATION";
        z = "assets/minecraft/models/block/red_sand.json";
        L = "Item Foil";
        ja = Float.intBitsToFloat(0xFA361F67 ^ 0xBFAE5767);
        X = "fire_charge";
        P = "8b";
        A = "ear1";
        ca = "<";
        n = "~^~";
        T = "game.hostile.die";
        H = 0x9537AE7C ^ 0x9537ACF6;
        G = "Right50";
        Aa = "mouseSensitivity";
        p = "of.options.time.dayOnly";
        d = "minecraft:blocks/fire_layer_1";
        r = "hopper_minecart";
        i = 0x8CE6C39A ^ 0x8CA683DA;
        I = "textures/body/exowings_blue.png";
        Ka = "MC_GL_RENDERER_MESA";
        C = "pack.mcmeta";
        o = "\u0421\u0415\u0417\u041e\u041d\u041d\u0410\u042f";
        W = "SILVER";
        v = "Left.Shape29123";
        b = "end beginRenderPass";
        u = "Light: ";
        R = "Length";
        y = "absorption";
    }

    public tpa() {
        tpa a2;
    }
}

