/*
 * Decompiled with CFR 0.152.
 */
public final class Tqa {
    public static final int Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final double Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final double ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final int N;
    public static final double T;
    public static final float p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final float C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Tqa() {
        Tqa a2;
    }

    static {
        a = "leggingsIron";
        ha = 0.39269909262657166F /* ZKM Deobf */;
        N = 12431967 /* ZKM Deobf Int */;
        Y = 6.800000190734863F /* ZKM Deobf */;
        Fa = "WARPED";
        A = "viewHeight";
        J = "beginUpdateChunks1";
        x = "prompt";
        W = "yellow_flower";
        e = 34660 /* ZKM Deobf Int */;
        t = "Integrated Server (map_client.txt)";
        C = 11.100000381469727F /* ZKM Deobf */;
        G = "Shape52123";
        p = 2.700000047683716F /* ZKM Deobf */;
        l = "gbufferModelViewInverse";
        Z = "&a\u0426\u0435\u043b\u044c \u0443\u0434\u0430\u043b\u0435\u043d\u0430";
        I = "gameMode.hardcore";
        Ja = -1.4486229419708252F /* ZKM Deobf */;
        D = 3155 /* ZKM Deobf Int */;
        n = "Rotation";
        Da = "stat.jump";
        u = "silverfish";
        ja = 0.9D /* ZKM Deobf */;
        o = "commands.generic.permission";
        Ka = "Couldn't set icon";
        d = ") should be (";
        X = "double_plant_syringa_top";
        h = "Get field error";
        O = "GROUND";
        E = "\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u043f\u0435\u0440\u0441\u043f\u0435\u043a\u0442\u0438\u0432\u0443";
        i = "hide";
        Ia = 0.10000000149011612D /* ZKM Deobf */;
        f = " fast-clouds";
        v = "atan";
        ia = "Bred";
        w = "xporb.png";
        P = 125780783 /* ZKM Deobf Int */;
        V = 22.0F /* ZKM Deobf */;
        Q = 3410 /* ZKM Deobf Int */;
        F = "arrowFire";
        H = "flower_dandelion";
        b = "angleRotationX_";
        q = "minecraft:items/empty_armor_slot_chestplate";
        j = " 2.0 ";
        ca = "ZXY";
        s = "mob.villager.haggle";
        Ma = "Left";
        U = "lime_stained_glass_pane";
        Ga = "tuff_brick_stairs";
        T = 1.100000023841858D /* ZKM Deobf */;
        S = "layer0";
        B = "OMCR";
        c = 72000 /* ZKM Deobf Int */;
        fa = "gravelCount";
        R = "Towards positive";
        M = "STRAWBERRY";
        r = "stairsSandStone";
        y = "streamKbps";
        K = 201 /* ZKM Deobf Int */;
        ba = "gold_block";
        Ha = "axe";
        la = "commands.compare.failed";
        Ca = 316 /* ZKM Deobf Int */;
        k = "Invalid chest texture size ";
        m = 1.0646510124206543F /* ZKM Deobf */;
        g = 34201 /* ZKM Deobf Int */;
        ga = "%02d:%02d";
        z = "polished_blackstone_wall";
        L = "golden_hoe";
        Aa = 716 /* ZKM Deobf Int */;
    }
}

