/*
 * Decompiled with CFR 0.152.
 */
public final class Tqa {
    public static final int Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final float ha;
    public static final String Fa;
    public static final double Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final double ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final int N;
    public static final double T;
    public static final float p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final float C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Tqa() {
        Tqa a2;
    }

    static {
        a = "leggingsIron";
        ha = Float.intBitsToFloat(0x7C5A64D2 ^ 0x42936B09);
        N = 0x4BFC30B7 ^ 0x4B4182E8;
        Y = Float.intBitsToFloat(0xFE84429D ^ 0xBE5DDB07);
        Fa = "WARPED";
        A = "viewHeight";
        J = "beginUpdateChunks1";
        x = "prompt";
        W = "yellow_flower";
        e = 0x1842F5EC ^ 0x18427288;
        t = "Integrated Server (map_client.txt)";
        C = Float.intBitsToFloat(0x5B2BF984 ^ 0x1A1A601E);
        G = "Shape52123";
        p = Float.intBitsToFloat(0xDEDA9C23 ^ 0x9EF650EE);
        l = "gbufferModelViewInverse";
        Z = "&a\u0426\u0435\u043b\u044c \u0443\u0434\u0430\u043b\u0435\u043d\u0430";
        I = "gameMode.hardcore";
        Ja = Float.intBitsToFloat(0xD9801898 ^ 0x663974E2);
        D = 0xE65BCFE8 ^ 0xE65BC3BB;
        n = "Rotation";
        Da = "stat.jump";
        u = "silverfish";
        ja = Double.longBitsToDouble(0x54C463E24FD7346L ^ 0x3AA08AF2E831BF8BL);
        o = "commands.generic.permission";
        Ka = "Couldn't set icon";
        d = ") should be (";
        X = "double_plant_syringa_top";
        h = "Get field error";
        O = "GROUND";
        E = "\u0412\u043a\u043b\u044e\u0447\u0438\u0442\u044c \u043f\u0435\u0440\u0441\u043f\u0435\u043a\u0442\u0438\u0432\u0443";
        i = "hide";
        Ia = Double.longBitsToDouble(0xAC33E15B3774D2B4L ^ 0x938A78C29774D2B4L);
        f = " fast-clouds";
        v = "atan";
        ia = "Bred";
        w = "xporb.png";
        P = 0xC1E540FE ^ 0xC69A03D1;
        V = Float.intBitsToFloat(0x1F0A78FD ^ 0x5EBA78FD);
        Q = 0xBDF7288B ^ 0xBDF725D9;
        F = "arrowFire";
        H = "flower_dandelion";
        b = "angleRotationX_";
        q = "minecraft:items/empty_armor_slot_chestplate";
        j = " 2.0 ";
        ca = "ZXY";
        s = "mob.villager.haggle";
        Ma = "Left";
        U = "lime_stained_glass_pane";
        Ga = "tuff_brick_stairs";
        T = Double.longBitsToDouble(0x4E26C3E4E4801590L ^ 0x71D75A7D44801590L);
        S = "layer0";
        B = "OMCR";
        c = 0x2E510C06 ^ 0x2E501546;
        fa = "gravelCount";
        R = "Towards positive";
        M = "STRAWBERRY";
        r = "stairsSandStone";
        y = "streamKbps";
        K = 0x63192F1B ^ 0x63192FD2;
        ba = "gold_block";
        Ha = "axe";
        la = "commands.compare.failed";
        Ca = 0x612851BB ^ 0x61285087;
        k = "Invalid chest texture size ";
        m = Float.intBitsToFloat(0x643EAFC ^ 0x39CBAC80);
        g = 0x651DACDA ^ 0x651D2943;
        ga = "%02d:%02d";
        z = "polished_blackstone_wall";
        L = "golden_hoe";
        Aa = 0x450A2095 ^ 0x450A2259;
    }
}

