/*
 * Decompiled with CFR 0.152.
 */
public final class TQa_1 {
    public static final String Fa = "ZIP";
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final double Ja;
    public static final int ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final float C;
    public static final float i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final String J;
    public static final String A;
    public static final String I;

    public TQa_1() {
        TQa_1 a2;
    }

    static {
        S = "help";
        W = "tuffStairs";
        Ja = 206.0D /* ZKM Deobf */;
        Z = -10.699999809265137F /* ZKM Deobf */;
        m = "CanPlaceOn";
        Ha = "\u00a76\u041e\u0441\u0435\u043d\u043d\u044f\u044f \u043a\u043e\u043b\u043b\u0435\u043a\u0446\u0438\u044f";
        f = "\u0421\u0432\u043e\u0431\u043e\u0434\u043d\u044b\u0439 \u0432\u0445\u043e\u0434 \u0434\u043b\u044f \u0432\u0441\u0435\u0445";
        y = "Career";
        la = "R16";
        H = "clear pre";
        C = 1.3962630033493042F /* ZKM Deobf */;
        r = "minecraft:anvil";
        X = "GL15.GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING";
        n = "FOG_FANCY";
        R = "thrown";
        M = "facing=north,half=top,shape=straight";
        p = "FOV";
        U = "math.pi";
        D = 634 /* ZKM Deobf Int */;
        O = "sea_lantern";
        l = "Failed decrypt AES-GSM because of unexpected errors";
        u = ") with size ";
        d = 1048575 /* ZKM Deobf Int */;
        Ia = "SSS";
        o = "RG8_SNORM";
        P = "HIDE_FOR_OWN_TEAM";
        Q = 718 /* ZKM Deobf Int */;
        h = "1";
        Da = "GL11.GL_INTENSITY";
        k = "GL15.GL_ARRAY_BUFFER_BINDING";
        b = "Dev";
        s = "textures/entity/wither/wither_armor.png";
        c = "options.renderDistance.short";
        ca = 35 /* ZKM Deobf Int */;
        x = "coalCount";
        fa = "Mipmap levels: ";
        ga = "\u0421\u043b\u0438\u0448\u043a\u043e\u043c \u043c\u0430\u043b\u0435\u043d\u044c\u043a\u0438\u0439";
        N = "normal/";
        L = "\u00b0";
        i = 0.16277135908603668F /* ZKM Deobf */;
        V = "commands.message.display.incoming";
        G = "Property not found: ";
        w = "GL11.GL_ACCUM_GREEN_BITS";
        A = "commands.scoreboard.objectives.setdisplay.invalidSlot";
        Ga = "Synched entity data";
        t = "achievement.buildHoe";
        B = "sandstone_slab";
        ja = 14377823 /* ZKM Deobf Int */;
        g = 2982 /* ZKM Deobf Int */;
        Y = "r.";
        q = "NORMAL";
        I = "objective";
        z = "left_arm";
        e = "tellraw";
        j = 6.099999904632568F /* ZKM Deobf */;
        J = "GL15.GL_BUFFER_ACCESS";
        a = 1002 /* ZKM Deobf Int */;
        Aa = 813 /* ZKM Deobf Int */;
        F = 3330 /* ZKM Deobf Int */;
        E = "GL11.GL_GREATER";
        T = "Piece1.Shape6";
        K = -0.3490658402442932F /* ZKM Deobf */;
        v = "crimson";
        Ka = "players";
    }
}

