/*
 * Decompiled with CFR 0.152.
 */
public final class tSa {
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final long u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final float h;
    public static final double K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        j = "12-15";
        ca = "SCALEXEXPRANIM";
        W = "Invalid match blocks: ";
        H = "commands.fill.outOfWorld";
        s = "lootBonus";
        v = "age";
        m = "white_stained_hardened_clay";
        h = 0.9422000050544739F /* ZKM Deobf */;
        C = 4294967203 /* ZKM Deobf Int */;
        a = "MiniDotItemTexture{name='";
        Z = "waxed_weathered_copper";
        e = "tex";
        J = "Left.Shape56123";
        y = "textures/blocks/destroy_stage_7.png";
        w = "_wall";
        l = "textures/entity/villager/smith.png";
        n = "orientable";
        M = "^\\s*#include\\s+\"([A-Za-z0-9_/\\.]+)\".*$";
        Aa = -0.3400000035762787F /* ZKM Deobf */;
        P = "KEYBOARDBIND";
        Ga = "deepslate_brick_wall";
        i = "textures/blocks/glass_";
        V = "explosion.player";
        p = "Set static final field error";
        x = "textures/map/map_icons.png";
        Q = "ascending_south";
        I = ", textures=";
        g = 633 /* ZKM Deobf Int */;
        d = "eBeamPartial_";
        S = "Surprise! Haha. Well, this is awkward.";
        A = "jump_boost";
        T = "layer2";
        X = "(?i)";
        D = "amethyst";
        G = "adventure";
        q = "createWorld.customize.custom.prev";
        t = "ViTRH";
        B = 5377 /* ZKM Deobf Int */;
        Ka = "Structure type";
        o = 834 /* ZKM Deobf Int */;
        Y = "end beginRender";
        ja = "sugar";
        Ha = "options.off";
        F = "fog.nether";
        U = "createWorld.customize.presets.list";
        f = 3249 /* ZKM Deobf Int */;
        N = "Could not add element to container '";
        fa = "demo";
        k = "disable-change-hide-gui";
        K = 0.08D /* ZKM Deobf */;
        z = "btex:";
        b = "SET_COLOR_ANIMATED";
        Ja = "itemmeta/_index.txt";
        L = "\u0423\u0441\u0442\u0430\u0440\u0435\u0432\u0448\u0438\u0439 \u043a\u043b\u0438\u0435\u043d\u0442";
        c = "keyMouseButtons";
        u = 0xA033D0393B48CB38L ^ 0xA033D0393B48B244L;
        O = "query";
        r = 16.66666603088379F /* ZKM Deobf */;
        E = "&a\u0422\u044b\u043a\u043d\u0438\u0442\u0435 \u043d\u0430 \u043b\u044e\u0431\u043e\u0439 \u0431\u043b\u043e\u043a/\u0438\u0433\u0440\u043e\u043a\u0430/\u0436\u0438\u0432\u043e\u0442\u043d\u043e\u0435";
        R = "fogTest_";
    }

    public tSa() {
        tSa a2;
    }
}

