/*
 * Decompiled with CFR 0.152.
 */
public final class tTa {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final float z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final double Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final long B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public tTa() {
        tTa a2;
    }

    static {
        b = "andesite_slab";
        O = "mossyStoneBrickStairs";
        w = "Follow Range";
        t = "Memory";
        H = "textures/entity/horse/donkey.png";
        j = "emojis.dev";
        ga = "addEnum error";
        Ja = "GL11.GL_UNPACK_LSB_FIRST";
        z = -0.0010000000474974513F /* ZKM Deobf */;
        d = "textures/environment/sun.png";
        U = "mob.horse.wood";
        ca = "snowshovel";
        V = "resource_packs";
        C = "anvil_very_damaged";
        p = "\u0423\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u043d\u0438\u0435";
        Ga = 15720061 /* ZKM Deobf Int */;
        m = "musicBlock";
        S = "gl_caps[ARB_arrays_of_arrays]";
        R = "HEAD_DEFAULT";
        o = "ENDER_CRYSTAL";
        x = "standing_sign";
        i = "mayBuild";
        Da = -0.6499999761581421F /* ZKM Deobf */;
        L = 191 /* ZKM Deobf Int */;
        T = "format";
        la = "thinGlass";
        s = "cow/mooshroom";
        I = "mob.wither.shoot";
        c = -30.0D /* ZKM Deobf */;
        q = "mob.endermen.death";
        y = "east=true,north=true,south=false,up=true,west=false";
        e = "mob.horse.breathe";
        F = "Local Difficulty: %.2f (Day %d)";
        v = "VimeWorld.logSession";
        W = "deepslateBricks";
        Ha = "edit_";
        A = 16777120 /* ZKM Deobf Int */;
        a = "Shall we play a game?";
        D = "//#define ";
        Ia = "poppy";
        M = "HIDE_WITH_LEGGINGS";
        N = 4294967197 /* ZKM Deobf Int */;
        u = "placedHiddenChest";
        Y = "reloading";
        K = "Invalid maxHeight: ";
        J = "rightStick";
        f = "fireworks.launch";
        k = "connectrandom";
        G = ", obfuscated=";
        Q = -0.6D /* ZKM Deobf */;
        Aa = "PLAYER_LIST_DATA";
        fa = "sculk";
        n = ", found one with ";
        Z = "shadowcolor0";
        B = 0x7FFF843F56A1D5A2L ^ 0x7FFF843F56A51385L;
        l = "pale_oak_log_stripped";
        X = 3252 /* ZKM Deobf Int */;
        E = "openPersonalization";
        r = 5725276 /* ZKM Deobf Int */;
        ja = "Right.Right11";
        P = "MINIDOT_PREVIEW";
        g = 3552 /* ZKM Deobf Int */;
        h = 5 /* ZKM Deobf Int */;
        Ka = 356 /* ZKM Deobf Int */;
    }
}

