/*
 * Decompiled with CFR 0.152.
 */
public final class tTa {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final float z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final double Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final long B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public tTa() {
        tTa a2;
    }

    static {
        b = "andesite_slab";
        O = "mossyStoneBrickStairs";
        w = "Follow Range";
        t = "Memory";
        H = "textures/entity/horse/donkey.png";
        j = "emojis.dev";
        ga = "addEnum error";
        Ja = "GL11.GL_UNPACK_LSB_FIRST";
        z = Float.intBitsToFloat(0x741CA62F ^ 0xCE9FB440);
        d = "textures/environment/sun.png";
        U = "mob.horse.wood";
        ca = "snowshovel";
        V = "resource_packs";
        C = "anvil_very_damaged";
        p = "\u0423\u0434\u0435\u0440\u0436\u0438\u0432\u0430\u043d\u0438\u0435";
        Ga = 0x3B505D0E ^ 0x3BBF8373;
        m = "musicBlock";
        S = "gl_caps[ARB_arrays_of_arrays]";
        R = "HEAD_DEFAULT";
        o = "ENDER_CRYSTAL";
        x = "standing_sign";
        i = "mayBuild";
        Da = Float.intBitsToFloat(0xC949D2C9 ^ 0x766FB4AF);
        L = 0xA03CD1D6 ^ 0xA03CD169;
        T = "format";
        la = "thinGlass";
        s = "cow/mooshroom";
        I = "mob.wither.shoot";
        c = Double.longBitsToDouble(0x4E8D3123549D11E8L ^ 0x8EB33123549D11E8L);
        q = "mob.endermen.death";
        y = "east=true,north=true,south=false,up=true,west=false";
        e = "mob.horse.breathe";
        F = "Local Difficulty: %.2f (Day %d)";
        v = "VimeWorld.logSession";
        W = "deepslateBricks";
        Ha = "edit_";
        A = 0xA0E77ACE ^ 0xA018856E;
        a = "Shall we play a game?";
        D = "//#define ";
        Ia = "poppy";
        M = "HIDE_WITH_LEGGINGS";
        N = 0xF72C7FF1 ^ 0x8D3806C;
        u = "placedHiddenChest";
        Y = "reloading";
        K = "Invalid maxHeight: ";
        J = "rightStick";
        f = "fireworks.launch";
        k = "connectrandom";
        G = ", obfuscated=";
        Q = Double.longBitsToDouble(0xF0DD37188ECACBFBL ^ 0x4F3E042BBDF9F8C8L);
        Aa = "PLAYER_LIST_DATA";
        fa = "sculk";
        n = ", found one with ";
        Z = "shadowcolor0";
        B = 0x7FFF843F56A1D5A2L ^ 0x7FFF843F56A51385L;
        l = "pale_oak_log_stripped";
        X = 0xC1488918 ^ 0xC14885AC;
        E = "openPersonalization";
        r = 0xE41C29E3 ^ 0xE44B75BF;
        ja = "Right.Right11";
        P = "MINIDOT_PREVIEW";
        g = 0x57919D7E ^ 0x5791909E;
        h = 0x74702143 ^ 0x74702146;
        Ka = 0xF53EAEBE ^ 0xF53EAFDA;
    }
}

