/*
 * Decompiled with CFR 0.152.
 */
public final class tua {
    public static final String Ma;
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final float r;
    public static final int V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final long Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    public tua() {
        tua a2;
    }

    static {
        m = "_exploding";
        Ma = "Error compiling fragment shader: ";
        D = "dirtMaxHeight";
        i = 0x6BB18A9B ^ 0x6BB18A33;
        v = "distance";
        w = 0x4A92831C ^ 0x4A928321;
        W = "LINE_LOOP";
        ja = 0x63A29619 ^ 0x63A29D4C;
        R = 0x1C93AF28 ^ 0x1C93AD5B;
        d = "\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u0442\u0435\u043a\u0441\u0442\u0430: ";
        J = 0x9198C05A ^ 0x9198CD4A;
        k = "armorStatus";
        E = ".dat.tmp";
        s = "keyMovementButtons:";
        e = "GL11.GL_LIGHT7";
        Ka = "enderman/enderman_eyes";
        ha = 0x6B016C85 ^ 0x6B016D17;
        G = 0x8D691AC3 ^ 0x8D691A34;
        ca = "objective='";
        Y = 0x8A8B8F2A ^ 0x8A8B8C36;
        B = "BEDROCK_OLD";
        ba = "green_concrete_powder";
        j = "Pet.Ribbon12";
        Aa = "frontfoot";
        h = "Amount";
        z = "dark_oak_fence_gate";
        x = "\u4f57";
        P = 0x44292FC ^ 0x443145C;
        I = "Durability: ";
        Z = "gaux3";
        Da = 0x9CDABD7 ^ 0x9CD2BA7;
        q = "SIZEVAL_NOT_SET";
        Ga = Float.intBitsToFloat(0x257DA2BF ^ 0x9A61C14E);
        X = 0xFB0BF2AD ^ 0xFB0BFA7C;
        S = "web";
        Ia = "commands.ban.failed";
        n = "player-collision-boxes";
        Q = 0x9BF7179CDFC95633L ^ 0x9BF7179CDFC903C3L;
        c = "scrollbarBackground_";
        M = "blockEntities";
        C = 0x4AE3A90B ^ 0x4AE3AA0B;
        U = 0x198B34F9 ^ 0x198B34E6;
        r = Float.intBitsToFloat(0xDE2161D2 ^ 0x9CE761D2);
        l = "Sound Library Loader";
        N = Float.intBitsToFloat(0xCCFCEE3A ^ 0xDEC94DB);
        Ja = "Loading NBT data";
        O = "Registering texture";
        u = "Biomes being compared";
        fa = "HIDE_WITH_BOOTS";
        A = "GL11.GL_MODELVIEW_MATRIX";
        T = "GL11.GL_ZERO";
        K = "tallgrass";
        a = "REQUESTS";
        t = "Invalid cubic-bezier expression: ";
        V = 0x87F0A118 ^ 0x87F0E11F;
        Ha = ", id=";
        F = "hopper_top";
        y = "No type defined: ";
        o = "Invalid times, required are: startFadeIn, endFadeIn and endFadeOut.";
        H = "_stained_hardened_clay";
        la = "CachingFontRenderer Enabled: ";
        f = "stone_brick_stairs";
        L = "commands.unban.failed";
        Fa = "' for the animation '";
        b = "GL11.GL_QUADS";
        ga = "darkOakFenceGate";
        p = "LPT1";
        g = "IMAGE_NOT_SET";
    }
}

