/*
 * Decompiled with CFR 0.152.
 */
public final class tua {
    public static final String Ma;
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final float r;
    public static final int V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final long Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    public tua() {
        tua a2;
    }

    static {
        m = "_exploding";
        Ma = "Error compiling fragment shader: ";
        D = "dirtMaxHeight";
        i = 168 /* ZKM Deobf Int */;
        v = "distance";
        w = 61 /* ZKM Deobf Int */;
        W = "LINE_LOOP";
        ja = 2901 /* ZKM Deobf Int */;
        R = 627 /* ZKM Deobf Int */;
        d = "\u0420\u0430\u0441\u043f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435 \u0442\u0435\u043a\u0441\u0442\u0430: ";
        J = 3344 /* ZKM Deobf Int */;
        k = "armorStatus";
        E = ".dat.tmp";
        s = "keyMovementButtons:";
        e = "GL11.GL_LIGHT7";
        Ka = "enderman/enderman_eyes";
        ha = 402 /* ZKM Deobf Int */;
        G = 247 /* ZKM Deobf Int */;
        ca = "objective='";
        Y = 796 /* ZKM Deobf Int */;
        B = "BEDROCK_OLD";
        ba = "green_concrete_powder";
        j = "Pet.Ribbon12";
        Aa = "frontfoot";
        h = "Amount";
        z = "dark_oak_fence_gate";
        x = "\u4f57";
        P = 100000 /* ZKM Deobf Int */;
        I = "Durability: ";
        Z = "gaux3";
        Da = 32880 /* ZKM Deobf Int */;
        q = "SIZEVAL_NOT_SET";
        Ga = -0.6108999848365784F /* ZKM Deobf */;
        X = 2257 /* ZKM Deobf Int */;
        S = "web";
        Ia = "commands.ban.failed";
        n = "player-collision-boxes";
        Q = 0x9BF7179CDFC95633L ^ 0x9BF7179CDFC903C3L;
        c = "scrollbarBackground_";
        M = "blockEntities";
        C = 768 /* ZKM Deobf Int */;
        U = 31 /* ZKM Deobf Int */;
        r = 99.0F /* ZKM Deobf */;
        l = "Sound Library Loader";
        N = -9.029999732971191F /* ZKM Deobf */;
        Ja = "Loading NBT data";
        O = "Registering texture";
        u = "Biomes being compared";
        fa = "HIDE_WITH_BOOTS";
        A = "GL11.GL_MODELVIEW_MATRIX";
        T = "GL11.GL_ZERO";
        K = "tallgrass";
        a = "REQUESTS";
        t = "Invalid cubic-bezier expression: ";
        V = 16391 /* ZKM Deobf Int */;
        Ha = ", id=";
        F = "hopper_top";
        y = "No type defined: ";
        o = "Invalid times, required are: startFadeIn, endFadeIn and endFadeOut.";
        H = "_stained_hardened_clay";
        la = "CachingFontRenderer Enabled: ";
        f = "stone_brick_stairs";
        L = "commands.unban.failed";
        Fa = "' for the animation '";
        b = "GL11.GL_QUADS";
        ga = "darkOakFenceGate";
        p = "LPT1";
        g = "IMAGE_NOT_SET";
    }
}

