/*
 * Decompiled with CFR 0.152.
 */
public final class uOa_1 {
    public static final float ba;
    public static final int ha;
    public static final int Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final int S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final float y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        U = "VCR: connected {}, {}";
        I = "assetIndex";
        N = "right.Shape51";
        u = "2b";
        c = "facing=north,half=bottom,shape=inner_left";
        Ga = "UPPER";
        V = "GL15.GL_STREAM_DRAW";
        F = 0x7A706A87 ^ 0x7A706AA8;
        Ha = "launched_version";
        a = "replace_left_arm";
        O = "Set final field error";
        j = "textures/gui/title/background/panorama_5.png";
        s = "\u25c0";
        Q = "selectWorld.mapFeatures.info";
        y = Float.intBitsToFloat(0x5DCE5559 ^ 0xE3982209);
        q = "DEFAULT";
        v = "gui/background.png";
        n = "We've tried to free up enough memory to let you go back to";
        A = "commands.scoreboard.players.operation.success";
        w = 0xB1B4222E ^ 0xB1B42028;
        X = "GL11.GL_PACK_SWAP_BYTES";
        ha = 0x9253965A ^ 0x92539D7B;
        la = "of.options.shaders";
        fa = "shadowColor0MinMagNearest";
        W = "_button";
        B = "-0+3-4+13";
        x = "Piece2.Shape9";
        Aa = "assets/minecraft/models/block/sandstone_normal.json";
        Fa = 0x54BBE6F6 ^ 0x54F7AABA;
        g = "bd";
        z = "textures/pet/chicken_baby.png";
        ja = " in ";
        J = "textures/entity/enderdragon/dragon.png";
        H = Float.intBitsToFloat(0x21D3935E ^ 0x63AD935E);
        E = "GL13.GL_CLAMP_TO_BORDER";
        D = "Front.11a";
        M = 0x9321E983 ^ 0x9321C983;
        b = "GL11.GL_AND_REVERSE";
        t = "keyTextColor";
        e = "resourcePacks";
        f = 0x2DA14C81 ^ 0x2DAE438E;
        l = "triangles_top";
        r = "models/block/";
        K = "swordStone";
        m = "Invalid spacing";
        p = 0x26C8D7BD ^ 0x26C8DA6E;
        R = Float.intBitsToFloat(0x4D6022E9 ^ 0x72F822E9);
        Ka = 0x7BDC6CEE ^ 0x7BDC6E6D;
        ba = Float.intBitsToFloat(0x68423DD2 ^ 0xD70EF11F);
        ga = "Set field error";
        Da = "east=false,north=false,south=true,up=false,west=true";
        i = "east=false,north=true,south=true,up=false,west=true";
        k = "world[";
        L = "minecraft:emitter_lifetime_once";
        G = "cooked";
        T = Float.intBitsToFloat(0xBAE19427 ^ 0x4F9DCB1);
        Ia = "weathered_chiseled_copper";
        Y = "worldDay";
        Z = 0x83554481 ^ 0x83A5E123;
        P = 0xDA7CE698 ^ 0xDA38D0BE;
        S = 0xF6E8451 ^ 0xF6E85FE;
        ca = 0x30A5CBFA ^ 0xCF5A357A;
        Ja = "y";
        d = "GL11.GL_RGB10_A2";
        o = "cooked_rabbit";
        h = "aesCipherHashServerId";
        C = ", glTextureId: ";
    }

    public uOa_1() {
        uOa_1 a2;
    }
}

