/*
 * Decompiled with CFR 0.152.
 */
public final class Upa {
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final float O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final double N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        ja = "txt:proto";
        d = -0.5204920768737793F /* ZKM Deobf */;
        T = "uv";
        P = 328 /* ZKM Deobf Int */;
        ga = 1.2566370964050293F /* ZKM Deobf */;
        x = "Texture animation: ";
        C = "BorderSizeLerpTarget";
        k = "commands.unbanip.success";
        Ja = "EnderDragon";
        M = "DIORITE_SMOOTH";
        S = "Invalid name";
        b = "Piece1.Shape112";
        t = "Affected level";
        E = "publish";
        Da = "Texteria";
        Ha = "createWorld.customize.custom.dungeonChance";
        I = "lucky_block";
        A = 34160 /* ZKM Deobf Int */;
        r = "BREWING_STAND";
        l = 1447446 /* ZKM Deobf Int */;
        m = "SMOOTH_FPS";
        n = " >= ";
        U = "Unknown synced attribute modifier";
        g = "magenta_glazed_terracotta";
        Q = "SHOW_FPS";
        q = "container.crafting";
        h = "ofAnimatedFire";
        f = "Problem";
        fa = "AMETHYST";
        O = 92.0F /* ZKM Deobf */;
        Aa = 999.0F /* ZKM Deobf */;
        K = "Size";
        s = "commands.playsound.playerTooFar";
        a = "GL13.GL_OPERAND2_RGB";
        c = "stat.boatOneCm";
        z = "\"layer";
        y = "SecurityHax hacked";
        B = 3158064 /* ZKM Deobf Int */;
        u = "stairsWoodJungle";
        e = "MC|PingHost";
        j = "stat.tradedWithVillager";
        L = "colorval_";
        i = "commands.scoreboard.players.enable.usage";
        X = "Entity Name";
        R = "XXX";
        Y = "stat.armorCleaned";
        F = "Image9Slice ";
        W = 2004 /* ZKM Deobf Int */;
        ca = "controls.resetAll";
        Ka = "record_cat";
        V = -4.289700031280518F /* ZKM Deobf */;
        G = "thunder";
        Z = "CLAMP";
        o = "BorderDamagePerBlock";
        N = -0.1D /* ZKM Deobf */;
        Ga = "\u0000\u0003\u0001\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002<\u0000\u0003:\u0000";
        H = "STONE";
        w = "GL15.GL_ARRAY_BUFFER";
        p = "SelectedItemSlot";
        J = "LEFT_SLEEVE";
        v = "lines_x";
        D = 56 /* ZKM Deobf Int */;
    }

    public Upa() {
        Upa a2;
    }
}

