/*
 * Decompiled with CFR 0.152.
 */
public final class uqa {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final float y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final String L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final double M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public uqa() {
        uqa a2;
    }

    static {
        Ka = "FT c";
        O = "resinBlock";
        n = "stat.treasureFished";
        X = "CB3F55D3-645C-4F38-A497-9C13A33DB5CF";
        Y = 30186 /* ZKM Deobf Int */;
        F = 4294967204 /* ZKM Deobf Int */;
        l = "textures/gui/container/brewing_stand.png";
        r = "item.fireworksCharge.fadeTo";
        c = "Savanna Plateau";
        v = "Java VM Version";
        z = "httpCacheDuration_";
        Q = "diamondMinHeight";
        a = 5127 /* ZKM Deobf Int */;
        R = "DIV";
        i = "endStoneBrickStairs";
        U = "Don't be sad. I'll do better next time, I promise!";
        L = "t/";
        B = "colortex5";
        w = "Right25";
        d = "PODZOL";
        e = "dns:";
        Ga = "empty";
        t = "textures/body/fierywings_red.png";
        A = 9474192 /* ZKM Deobf Int */;
        D = 35658 /* ZKM Deobf Int */;
        Ha = 32992 /* ZKM Deobf Int */;
        M = 60000000.0D /* ZKM Deobf */;
        N = "\u0434\u0440\u0443\u0437\u0435\u0439 \u0443\u0447\u0430\u0441\u0442\u043d\u0438\u043a\u043e\u0432";
        H = "BUST";
        Aa = "FLLeg.FLL1";
        h = "GIANT";
        x = "GL11.GL_OBJECT_LINEAR";
        Z = "warped_fence";
        s = "gl_caps[ARB_compatibility]";
        fa = "\u0411\u044b\u043b\u043e \u043e\u0431\u043d\u0430\u0440\u0443\u0436\u0435\u043d\u043e \u0432\u043c\u0435\u0448\u0430\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e \u0432 \u0438\u0433\u0440\u0443";
        Da = ", value='";
        G = "GL11.GL_BLUE_SCALE";
        S = "ScreenSize";
        u = -1.399999976158142F /* ZKM Deobf */;
        K = "scaleItems";
        C = "keyboard";
        ja = "open_file";
        p = "BEFORE_TOOLTIP";
        W = "RightLeg.Rp";
        P = "Startup";
        J = "Graham";
        I = "redSandstoneWall";
        k = 829 /* ZKM Deobf Int */;
        T = "RL2";
        m = "GL11.GL_TEXTURE_LUMINANCE_SIZE";
        j = "_log_stripped";
        ga = "sponge";
        o = "commands.blockdata.usage";
        la = "ARBImaging.GL_BLEND_COLOR";
        ca = "oak_log_stripped";
        b = 77 /* ZKM Deobf Int */;
        Ja = "hoeGold";
        y = 1.975000023841858F /* ZKM Deobf */;
        f = "\u041c\u0438\u043a\u0440\u043e\u0444\u043e\u043d";
        V = "bane_of_arthropods";
        q = "DisplaySlots";
        g = 2 /* ZKM Deobf Int */;
        E = 12623485 /* ZKM Deobf Int */;
    }
}

