/*
 * Decompiled with CFR 0.152.
 */
public final class Uqa_1 {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final long r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final int w;
    public static final int W;
    public static final String q;
    public static final double x;
    public static final int v;
    public static final long o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final double D;
    public static final float f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public Uqa_1() {
        Uqa_1 a2;
    }

    static {
        Ga = "RightLeg.RightLeg3";
        E = "ROW";
        d = "mob.magmacube.big";
        f = 0.6981316804885864F /* ZKM Deobf */;
        j = "waxedOxidizedCutCopperStairs";
        ha = "Not using framebuffer objects because ";
        e = "stal";
        r = 0x295141BD0BB5746EL ^ 0x295141BD0BB425EEL;
        w = 14238997 /* ZKM Deobf Int */;
        n = "/tp ";
        A = "steve/steve";
        I = 30032 /* ZKM Deobf Int */;
        K = "Texteria.printPackets";
        l = "model_type";
        y = "Pattern";
        k = "defaultStartAnimationDuration_";
        X = "screenX_";
        u = "PLAYERNAME";
        Ia = "waxedExposedChiseledCopper";
        c = "not ";
        F = 277 /* ZKM Deobf Int */;
        z = "Natural Textures: Invalid \"";
        W = 40083 /* ZKM Deobf Int */;
        D = 0.44000000000000006D /* ZKM Deobf */;
        H = "RX";
        i = "showModels:";
        Z = "mining_fatigue";
        b = "GL12.GL_TEXTURE_3D";
        Y = "RADIAL_PROGRESS_BAR";
        Q = 65280 /* ZKM Deobf Int */;
        a = "ASCENDING_WEST";
        U = "GL11.GL_FOG_HINT";
        S = "DIRECTION_X";
        V = "Sprinting speed boost";
        N = "Right14";
        C = 4738376 /* ZKM Deobf Int */;
        g = "pumpkin_stem";
        Ma = "SHOW_ACHIEVEMENT";
        t = "Enchant";
        p = "GL11.GL_COLOR_MATERIAL_FACE";
        M = "game.neutral.hurt";
        q = "GL11.GL_TEXTURE_WRAP_T";
        ba = "dragonEgg";
        s = 151 /* ZKM Deobf Int */;
        O = 420 /* ZKM Deobf Int */;
        Ja = 3490713616 /* ZKM Deobf Int */;
        Fa = "shears";
        T = "commands.clear.failure";
        ga = "ofNaturalTextures";
        Da = " MB/s";
        ia = "Shape57123";
        Ha = "arc.vn.s";
        R = 4353 /* ZKM Deobf Int */;
        v = 710 /* ZKM Deobf Int */;
        J = "GL11.GL_LIGHT_MODEL_AMBIENT";
        la = 4408131 /* ZKM Deobf Int */;
        h = 54.0F /* ZKM Deobf */;
        Aa = "redstoneCount";
        x = 0.3455D /* ZKM Deobf */;
        ja = "text.xpbar";
        P = 5121 /* ZKM Deobf Int */;
        m = "GL11.GL_TEXTURE_ENV_MODE";
        fa = "east=false,north=false,south=true,up=false,west=false";
        L = "You're mean.";
        o = 0x860670CB961BC904L ^ 0x860670CB961F5AE4L;
        Ea = "golden_horse_armor";
        B = " for dimension: ";
        Ca = "decorations";
        ca = 825 /* ZKM Deobf Int */;
        G = 10000 /* ZKM Deobf Int */;
        Ka = "RECORDS";
    }
}

