/*
 * Decompiled with CFR 0.152.
 */
public final class Uqa_1 {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final long r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final int Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final int w;
    public static final int W;
    public static final String q;
    public static final double x;
    public static final int v;
    public static final long o;
    public static final float h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final double D;
    public static final float f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public Uqa_1() {
        Uqa_1 a2;
    }

    static {
        Ga = "RightLeg.RightLeg3";
        E = "ROW";
        d = "mob.magmacube.big";
        f = Float.intBitsToFloat(0x21752053 ^ 0x1E479891);
        j = "waxedOxidizedCutCopperStairs";
        ha = "Not using framebuffer objects because ";
        e = "stal";
        r = 0x295141BD0BB5746EL ^ 0x295141BD0BB425EEL;
        w = 0x872F6D86 ^ 0x87F62893;
        n = "/tp ";
        A = "steve/steve";
        I = 0x8FAE8CAD ^ 0x8FAEF9FD;
        K = "Texteria.printPackets";
        l = "model_type";
        y = "Pattern";
        k = "defaultStartAnimationDuration_";
        X = "screenX_";
        u = "PLAYERNAME";
        Ia = "waxedExposedChiseledCopper";
        c = "not ";
        F = 0x61F4B7E8 ^ 0x61F4B6FD;
        z = "Natural Textures: Invalid \"";
        W = 0x23FADD56 ^ 0x23FA41C5;
        D = Double.longBitsToDouble(0xBCF7CAFFC6306FF5L ^ 0x832BE20A04BF33DFL);
        H = "RX";
        i = "showModels:";
        Z = "mining_fatigue";
        b = "GL12.GL_TEXTURE_3D";
        Y = "RADIAL_PROGRESS_BAR";
        Q = 0x940A9E7F ^ 0x940A617F;
        a = "ASCENDING_WEST";
        U = "GL11.GL_FOG_HINT";
        S = "DIRECTION_X";
        V = "Sprinting speed boost";
        N = "Right14";
        C = 0xA06F5920 ^ 0xA0271468;
        g = "pumpkin_stem";
        Ma = "SHOW_ACHIEVEMENT";
        t = "Enchant";
        p = "GL11.GL_COLOR_MATERIAL_FACE";
        M = "game.neutral.hurt";
        q = "GL11.GL_TEXTURE_WRAP_T";
        ba = "dragonEgg";
        s = 0xBD60730F ^ 0xBD607398;
        O = 0x3B4176CB ^ 0x3B41776F;
        Ja = 0x224AACFD ^ 0xF25ABCED;
        Fa = "shears";
        T = "commands.clear.failure";
        ga = "ofNaturalTextures";
        Da = " MB/s";
        ia = "Shape57123";
        Ha = "arc.vn.s";
        R = 0x566998AE ^ 0x566989AF;
        v = 0xEB52D0F7 ^ 0xEB52D231;
        J = "GL11.GL_LIGHT_MODEL_AMBIENT";
        la = 0x88272E96 ^ 0x88646DD5;
        h = Float.intBitsToFloat(0xF89D62E6 ^ 0xBAC562E6);
        Aa = "redstoneCount";
        x = Double.longBitsToDouble(0x9540100518D181A9L ^ 0xAA960CA910E0A740L);
        ja = "text.xpbar";
        P = 0x134834CA ^ 0x134820CB;
        m = "GL11.GL_TEXTURE_ENV_MODE";
        fa = "east=false,north=false,south=true,up=false,west=false";
        L = "You're mean.";
        o = 0x860670CB961BC904L ^ 0x860670CB961F5AE4L;
        Ea = "golden_horse_armor";
        B = " for dimension: ";
        Ca = "decorations";
        ca = 0x2E775FAF ^ 0x2E775C96;
        G = 0xDBCD6E90 ^ 0xDBCD4980;
        Ka = "RECORDS";
    }
}

