/*
 * Decompiled with CFR 0.152.
 */
public final class uSa {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final double W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final float l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final int L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final float A;
    public static final String I;

    public uSa() {
        uSa a2;
    }

    static {
        ca = "insertion";
        A = Float.intBitsToFloat(0xB3D37C1A ^ 0xF01B7C1A);
        h = "gl_caps[EXT_texture_lod_bias]";
        z = "Linear";
        Ga = "rotate_";
        D = "shadow readbuffer";
        v = "OpenGL Fancy fog: Not available (GL_NV_fog_distance)";
        f = "Minikotic";
        b = Float.intBitsToFloat(0x7756D7DA ^ 0xB6E6D7DA);
        Aa = Float.intBitsToFloat(0x76E22783 ^ 0xC9DF9F38);
        Ia = " is a cross and should have 1 texture, got ";
        x = "DisplayData";
        Z = "Hat";
        M = "variable.emitter_random_3";
        G = 0x1CFCC0E3 ^ 0x1CFC8F49;
        Da = "eSphere_";
        w = "foliage-colorm";
        T = Float.intBitsToFloat(0xD5F0DD17 ^ 0xEA919AB9);
        R = "Right.Right1";
        F = "lime_concrete";
        i = 0x1751A1DF ^ 0x1751A7DF;
        d = "Right27";
        ga = "[Shaders] Error: Failed framebuffer incomplete formats";
        U = "commands.generic.num.tooBig";
        o = "Shape56123";
        Ka = "Don't know how to serialize ";
        y = "The coordinate is out of range";
        la = "Stable";
        a = "GL11.GL_VENDOR";
        W = Double.longBitsToDouble(0xA38BF43F76DC59CFL ^ 0x9C48C70C45EF6AFCL);
        L = 0xA9B188DA ^ 0xA9B10920;
        c = "brewingStand";
        Y = "an object (";
        k = 0xEB8B9DD2 ^ 0xEB8B1FF8;
        t = "Error : MultiTexID.base mismatch: ";
        p = "stat.fishCaught";
        N = "glass_cyan";
        e = "\u0421\u0435\u0440\u0432\u0435\u0440 \u0432\u043e\u0439\u0441\u0447\u0430\u0442\u0430";
        E = 0xDC742F3A ^ 0xDC742F3A;
        Ja = "texture_boots";
        O = "textures/pet/spinner_white.png";
        K = "version";
        X = "entries";
        n = "GL11.GL_LEQUAL";
        J = "GL11.GL_AUX2";
        S = "text/html, image/gif, image/png";
        V = "IMAGE";
        q = 0xE31E514B ^ 0xE31E5AB9;
        Q = "bidirectional";
        r = "east=false,north=false,south=false,up=false,west=true";
        g = 0x12FDD82E ^ 0x12FDD496;
        ja = "bitField1_";
        j = "wmic cpu get name";
        l = Float.intBitsToFloat(0x40CCA8E1 ^ 0x80ED4364);
        fa = "JVM Flags";
        P = "outwards";
        s = "Missing ')' after ";
        u = "Now with extra numbers";
        I = "\u0412\u044b\u0439\u0442\u0438 \u0438\u0437 \u043f\u0430\u0442\u0438";
        Ha = "stainedGlassPane";
        H = 0xBB83E275 ^ 0xBB839732;
        B = "facing=south,half=bottom,shape=inner_left";
        C = "ofClouds";
        m = "enchantment";
    }
}

