/*
 * Decompiled with CFR 0.152.
 */
public final class uSa {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final double W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final float l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final int L;
    public static final int E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final float A;
    public static final String I;

    public uSa() {
        uSa a2;
    }

    static {
        ca = "insertion";
        A = 400.0F /* ZKM Deobf */;
        h = "gl_caps[EXT_texture_lod_bias]";
        z = "Linear";
        Ga = "rotate_";
        D = "shadow readbuffer";
        v = "OpenGL Fancy fog: Not available (GL_NV_fog_distance)";
        f = "Minikotic";
        b = -22.0F /* ZKM Deobf */;
        Aa = -0.741100013256073F /* ZKM Deobf */;
        Ia = " is a cross and should have 1 texture, got ";
        x = "DisplayData";
        Z = "Hat";
        M = "variable.emitter_random_3";
        G = 20394 /* ZKM Deobf Int */;
        Da = "eSphere_";
        w = "foliage-colorm";
        T = 0.8799999952316284F /* ZKM Deobf */;
        R = "Right.Right1";
        F = "lime_concrete";
        i = 1536 /* ZKM Deobf Int */;
        d = "Right27";
        ga = "[Shaders] Error: Failed framebuffer incomplete formats";
        U = "commands.generic.num.tooBig";
        o = "Shape56123";
        Ka = "Don't know how to serialize ";
        y = "The coordinate is out of range";
        la = "Stable";
        a = "GL11.GL_VENDOR";
        W = 0.15D /* ZKM Deobf */;
        L = 33274 /* ZKM Deobf Int */;
        c = "brewingStand";
        Y = "an object (";
        k = 33322 /* ZKM Deobf Int */;
        t = "Error : MultiTexID.base mismatch: ";
        p = "stat.fishCaught";
        N = "glass_cyan";
        e = "\u0421\u0435\u0440\u0432\u0435\u0440 \u0432\u043e\u0439\u0441\u0447\u0430\u0442\u0430";
        E = 0 /* ZKM Deobf Int */;
        Ja = "texture_boots";
        O = "textures/pet/spinner_white.png";
        K = "version";
        X = "entries";
        n = "GL11.GL_LEQUAL";
        J = "GL11.GL_AUX2";
        S = "text/html, image/gif, image/png";
        V = "IMAGE";
        q = 3058 /* ZKM Deobf Int */;
        Q = "bidirectional";
        r = "east=false,north=false,south=false,up=false,west=true";
        g = 3256 /* ZKM Deobf Int */;
        ja = "bitField1_";
        j = "wmic cpu get name";
        l = -2.5299999713897705F /* ZKM Deobf */;
        fa = "JVM Flags";
        P = "outwards";
        s = "Missing ')' after ";
        u = "Now with extra numbers";
        I = "\u0412\u044b\u0439\u0442\u0438 \u0438\u0437 \u043f\u0430\u0442\u0438";
        Ha = "stainedGlassPane";
        H = 30023 /* ZKM Deobf Int */;
        B = "facing=south,half=bottom,shape=inner_left";
        C = "ofClouds";
        m = "enchantment";
    }
}

