/*
 * Decompiled with CFR 0.152.
 */
public final class uua {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final float T;
    public static final int p;
    public static final int n;
    public static final int s;
    public static final String w;
    public static final int W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final double G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Fa = "Shape82";
        ja = "Reported exception thrown!";
        A = "tallying";
        H = "netherite";
        Ka = "easeInOutSine";
        z = 30008 /* ZKM Deobf Int */;
        x = "GL11.GL_VERTEX_ARRAY_TYPE";
        M = "BlockEntityTag";
        ha = "BAT";
        Da = "uuids";
        Q = "F3";
        a = "Stone Beach";
        S = "Body.Shape2";
        G = 0.9800000190734863D /* ZKM Deobf */;
        Ja = "math.floor";
        e = "SCALEXEXPR";
        Ia = "NEVER";
        f = "smoothBasalt";
        E = "GL11.GL_ONE_MINUS_DST_COLOR";
        q = 32908 /* ZKM Deobf Int */;
        n = 1728053247 /* ZKM Deobf Int */;
        C = 3409 /* ZKM Deobf Int */;
        r = "Match";
        j = "Duplicate item id: ";
        Aa = "Right13";
        N = 503 /* ZKM Deobf Int */;
        d = 502 /* ZKM Deobf Int */;
        b = "container.enchant.level.many";
        ba = "ofRain";
        v = "Armor Status HUD: ";
        k = "bootsNetherite";
        T = 900.0F /* ZKM Deobf */;
        Z = "No matchBlocks or matchTiles specified: ";
        c = "createWorld.customize.custom.depthNoiseScaleZ";
        B = "GL11.GL_DECAL";
        V = "VALUE_NOT_SET";
        Y = "short";
        J = "pi*2";
        X = 33881 /* ZKM Deobf Int */;
        Ga = "deepslate_tile_wall";
        u = "TrackOutput";
        la = "ALT";
        y = "assets/minecraft/models/block/mossy_cobblestone.json";
        F = "KEY";
        t = "Front.5b";
        L = "record_11";
        s = 13 /* ZKM Deobf Int */;
        w = "\u0423\u0432\u0435\u043b\u0438\u0447\u0435\u043d\u0438\u0435 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e";
        P = 635 /* ZKM Deobf Int */;
        fa = "polishedBlackstoneWall";
        g = 32894 /* ZKM Deobf Int */;
        W = 4293918719 /* ZKM Deobf Int */;
        ca = "%s\u00a7%d\u00a7%d";
        R = "sheep.";
        h = "vimers";
        U = "Invalid statistic/achievement!";
        Ha = " time ";
        l = "Shape25";
        i = "&c\u041d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u043e \u0443\u043a\u0430\u0437\u0430\u043d\u043e \u0432\u0440\u0435\u043c\u044f. \u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u0430\u044f \u0437\u0430\u043f\u0438\u0441\u044c: 1m30s, 15s, 2h \u0438 \u0442.\u0434.";
        m = 4354 /* ZKM Deobf Int */;
        ga = "minecraft:blocks/leaves_";
        o = 8.300000190734863F /* ZKM Deobf */;
        I = "SHSD";
        D = 32851 /* ZKM Deobf Int */;
        p = 6 /* ZKM Deobf Int */;
        K = "commands.give.block.notFound";
        O = "advancedItemTooltips";
    }

    public uua() {
        uua a2;
    }
}

