/*
 * Decompiled with CFR 0.152.
 */
public final class uua {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final float T;
    public static final int p;
    public static final int n;
    public static final int s;
    public static final String w;
    public static final int W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final double G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Fa = "Shape82";
        ja = "Reported exception thrown!";
        A = "tallying";
        H = "netherite";
        Ka = "easeInOutSine";
        z = 0xBB92C198 ^ 0xBB92B4A0;
        x = "GL11.GL_VERTEX_ARRAY_TYPE";
        M = "BlockEntityTag";
        ha = "BAT";
        Da = "uuids";
        Q = "F3";
        a = "Stone Beach";
        S = "Body.Shape2";
        G = Double.longBitsToDouble(0x9B36D6626F2690AFL ^ 0xA4D98A4B6F2690AFL);
        Ja = "math.floor";
        e = "SCALEXEXPR";
        Ia = "NEVER";
        f = "smoothBasalt";
        E = "GL11.GL_ONE_MINUS_DST_COLOR";
        q = 0x8AACC905 ^ 0x8AAC4989;
        n = 0xC6B6B80A ^ 0xA04947F5;
        C = 0x16F5032F ^ 0x16F50E7E;
        r = "Match";
        j = "Duplicate item id: ";
        Aa = "Right13";
        N = 0x8AEEC18C ^ 0x8AEEC07B;
        d = 0x9C364014 ^ 0x9C3641E2;
        b = "container.enchant.level.many";
        ba = "ofRain";
        v = "Armor Status HUD: ";
        k = "bootsNetherite";
        T = Float.intBitsToFloat(0x104EA00 ^ 0x4565EA00);
        Z = "No matchBlocks or matchTiles specified: ";
        c = "createWorld.customize.custom.depthNoiseScaleZ";
        B = "GL11.GL_DECAL";
        V = "VALUE_NOT_SET";
        Y = "short";
        J = "pi*2";
        X = 0xC24DE0BD ^ 0xC24D64E4;
        Ga = "deepslate_tile_wall";
        u = "TrackOutput";
        la = "ALT";
        y = "assets/minecraft/models/block/mossy_cobblestone.json";
        F = "KEY";
        t = "Front.5b";
        L = "record_11";
        s = 0xBD514634 ^ 0xBD514639;
        w = "\u0423\u0432\u0435\u043b\u0438\u0447\u0435\u043d\u0438\u0435 \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e";
        P = 0x7E9F48AA ^ 0x7E9F4AD1;
        fa = "polishedBlackstoneWall";
        g = 0xA915C18C ^ 0xA91541F2;
        W = 0xDAD7FDCE ^ 0x25380231;
        ca = "%s\u00a7%d\u00a7%d";
        R = "sheep.";
        h = "vimers";
        U = "Invalid statistic/achievement!";
        Ha = " time ";
        l = "Shape25";
        i = "&c\u041d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u043e \u0443\u043a\u0430\u0437\u0430\u043d\u043e \u0432\u0440\u0435\u043c\u044f. \u041f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u0430\u044f \u0437\u0430\u043f\u0438\u0441\u044c: 1m30s, 15s, 2h \u0438 \u0442.\u0434.";
        m = 0xB1A23F21 ^ 0xB1A22E23;
        ga = "minecraft:blocks/leaves_";
        o = Float.intBitsToFloat(0xFE1C0F1E ^ 0xBF18C3D3);
        I = "SHSD";
        D = 0xEAF29360 ^ 0xEAF21333;
        p = 0x9801686C ^ 0x9801686A;
        K = "commands.give.block.notFound";
        O = "advancedItemTooltips";
    }

    public uua() {
        uua a2;
    }
}

