/*
 * Decompiled with CFR 0.152.
 */
public final class vpa_2 {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final double fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final String U;
    public static final float P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final double w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final long c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final float g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final String J;
    public static final String A;
    public static final String I;

    public vpa_2() {
        vpa_2 a2;
    }

    static {
        p = "createWorld.customize.flat.removeLayer";
        o = 50 /* ZKM Deobf Int */;
        Aa = "RawBiomeBlock";
        i = 3187 /* ZKM Deobf Int */;
        Ja = 300 /* ZKM Deobf Int */;
        R = "assets/minecraft/models/block/elerald_block.json";
        j = -1.760699987411499F /* ZKM Deobf */;
        B = "addServer.title";
        z = "COPPER";
        O = "os_architecture";
        K = "selectWorld.recreate";
        N = 9923917 /* ZKM Deobf Int */;
        a = "Actions";
        P = -0.7853981852531433F /* ZKM Deobf */;
        c = 0x61777DD9C591C2BCL ^ 0x61777DD9C591C2FCL;
        w = 0.44999998807907104D /* ZKM Deobf */;
        d = "GL11.GL_RED_BITS";
        fa = 0.845D /* ZKM Deobf */;
        v = "GL12.GL_SEPARATE_SPECULAR_COLOR";
        X = "[Shaders] Error: Not enough draw buffers, needed: ";
        k = "houstonia";
        Y = "game.hostile.swim";
        Z = "gildedBlackstone";
        F = "Could not load config (Syntax errors on: ";
        la = "Right.Right25";
        t = "heightExpr_";
        Ga = "loop";
        b = "mcsounddomain";
        r = "assets";
        q = "textures/gui/icons.png";
        L = "MSStairs";
        E = "polished_tuff_slab_double";
        J = "Out of memory!";
        I = "\u0000\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u1007\u0000\u0003\u1006\u0001\u0004\u1004\u0002";
        T = "favicon";
        ca = "SNOWBALL";
        Q = "scaleGui";
        M = "LESS_THAN";
        G = "EXPLOSION_NORMAL";
        ga = "heldItemTooltips:";
        ja = "Invalid operation";
        x = "Affected screen";
        W = 407 /* ZKM Deobf Int */;
        n = "commands.banip.invalid";
        l = " closed!";
        m = "SCROLLOFFSETANIM";
        e = "GL13.GL_TEXTURE_BINDING_CUBE_MAP";
        S = "uniform [ _a-zA-Z0-9]+ gaux3;.*";
        U = "Right4";
        Ka = "GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER";
        h = 6975545 /* ZKM Deobf Int */;
        H = "\\";
        Ia = "gui.all";
        y = 20391 /* ZKM Deobf Int */;
        D = "waxedOxidizedCopper";
        V = ", arguments length: ";
        f = "Invalid Month: ";
        Ha = 619 /* ZKM Deobf Int */;
        u = "\u0000\u0005\u0002\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u1208\u0000\u00029\u0000\u00039\u0000\u00049\u0001\u00059\u0001";
        Da = "stat.dispenserInspected";
        C = "T";
        s = "OwnerUUID";
        g = -2.700000047683716F /* ZKM Deobf */;
        A = "M4";
    }
}

