/*
 * Decompiled with CFR 0.152.
 */
public final class vqa {
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final float p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final long f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final float M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final float A;
    public static final String I;

    static {
        X = "zCenter";
        Z = "GL11.GL_LIGHT3";
        Ha = "teamkill.";
        x = "offsetYExpr_";
        I = "Box";
        la = "oooOoo";
        p = 0.0997999981045723F /* ZKM Deobf */;
        Q = "PopSize";
        E = "GREEN";
        v = "dioriteMinHeight";
        D = "feather";
        t = "cobbled_deepslate_slab_double";
        F = 2147483647 /* ZKM Deobf Int */;
        a = "Pre render";
        w = "x0";
        B = "Hat.Shape5";
        H = "acacia_slab";
        R = "LEGGINGS";
        S = "GL11.GL_LUMINANCE12_ALPHA12";
        e = "SHADOW_CLIP_FRUSTRUM";
        C = "/party public off";
        h = 345 /* ZKM Deobf Int */;
        Da = "UtyCool";
        O = "commands.replaceitem.entity.usage";
        u = "Front.4b";
        ca = "size_UV";
        y = "white_glazed_terracotta";
        M = 0.09375F /* ZKM Deobf */;
        Ja = "CONSTANT";
        G = "Deleting old server resource pack ";
        P = -12.0D /* ZKM Deobf */;
        m = "multiplayer.player.left";
        d = "Failed to load pvp options";
        U = "gamemode";
        o = "commands.scoreboard.noMultiWildcard";
        b = "Level dimension";
        i = "Host";
        J = "stat.crafted";
        Ga = "yellow_wool";
        q = "[ \t]*const[ \t]*float[ \t]*ambientOcclusionLevel[ \t]*=[ \t]*-?[0-9.]+f?;.*";
        Y = 253 /* ZKM Deobf Int */;
        Ka = "Biomes";
        f = 0xBED20985C894D292L ^ 0xAAD772FB3FF353DDL;
        n = 9218 /* ZKM Deobf Int */;
        g = "Unable to locate sign at {}, {}, {}";
        r = 40012 /* ZKM Deobf Int */;
        T = -1.0F /* ZKM Deobf */;
        A = 18.0F /* ZKM Deobf */;
        Aa = "DANDELION";
        j = "GL11.GL_MAX_VIEWPORT_DIMS";
        fa = "; unable to load model: '";
        c = 2.5D /* ZKM Deobf */;
        N = "mud_brick_slab_double";
        s = "createWorld.customize.custom.baseSize";
        L = "container.enchant.lapis.one";
        V = "RGBA8_SNORM";
        k = "key.categories.inventory";
        z = "biomes[] size";
        ja = "inner_stairs";
        W = "jungle_fence_gate";
        K = "BEFORE_CHAT";
        ga = 20270 /* ZKM Deobf Int */;
        l = "You are banned from this server.";
    }

    public vqa() {
        vqa a2;
    }
}

