/*
 * Decompiled with CFR 0.152.
 */
public final class VQa_1 {
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final double Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final float n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final long i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public VQa_1() {
        VQa_1 a2;
    }

    static {
        Q = "Allocated: %2d%% %03dMB";
        Da = "deepslate_lapis_ore";
        y = "CLOUD_SHADOW";
        Ka = "GL15.GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING";
        d = 0x609802B1 ^ 0x609801A2;
        N = "Resuming channel {}";
        L = "Right57";
        B = "Shaders.init";
        Ga = "ConnectedTextures file not found: ";
        H = "But it works on my machine.";
        J = "jaw.jaw";
        Z = Double.longBitsToDouble(0xA53BB71E6E5987DDL ^ 0x9AE44942FF88C9E1L);
        o = "Prefix";
        k = "fishing_rod";
        Ha = "F8";
        r = "cat/ocelot";
        U = "Happy new year!";
        ca = "skull_zombie";
        Y = 0x58F8AA69 ^ 0x58F82E8C;
        fa = "acacia_trapdoor";
        b = "container.isLocked";
        s = "' contains illegal characters!";
        g = 0xC0AD11D ^ 0xF38A515D;
        O = "animations/pet/farmsunflower_animation.json";
        p = "Left.Shape55123";
        P = "World: (%d,%d,%d)";
        l = "TOURNAMENT";
        Ja = "armorTextType:";
        W = "Program loaded: ";
        I = "0.125";
        S = "kill";
        K = "HALLOWEEN";
        h = 0x7AF843F5 ^ 0x7AF836C0;
        V = "VC: Start connect";
        X = "LEG";
        E = "Zombie";
        Aa = "targets[";
        T = "water_flow";
        D = Float.intBitsToFloat(0x5D215881 ^ 0x60772FD7);
        t = ", I: ";
        c = "Hi. I'm Minecraft, and I'm a crashaholic.";
        j = "rearlegtip.main";
        e = "shadersmod.transform.SMCClassTransformer";
        x = "shadowtex0";
        v = "potion.prefix.charming";
        i = 0x74629227E9DBBA3BL ^ 0x8B9D6DD8162445BBL;
        f = "MC_GL_VENDOR_NVIDIA";
        a = "WATER_BUBBLE";
        A = "GL13.GL_TEXTURE_COMPRESSED_IMAGE_SIZE";
        q = 0x884C4BBA ^ 0x884CD7EE;
        m = 0xAE702BC9 ^ 0xAE70A32C;
        C = "(open error)";
        w = "Ping: (1.6) from {}:{}";
        F = "Body.Shape14";
        M = "banner";
        z = "shadow camera";
        R = "connecting";
        u = "textColorValCase_";
        ja = ".";
        G = 0x440B1EF8 ^ 0x440B1C53;
        n = Float.intBitsToFloat(0x16756787 ^ 0x547D6787);
    }
}

