/*
 * Decompiled with CFR 0.152.
 */
public final class vQa_2 {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final int Da;
    public static final String ca;
    public static final long Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final double fa;
    public static final String Ka;
    public static final String Aa;
    public static final float S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final double c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final double e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final float m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public vQa_2() {
        vQa_2 a2;
    }

    static {
        C = "Shape1";
        r = "SPELL_MOB";
        b = "EXPOSED_COPPER";
        Ia = "endianness";
        A = "Stopping due to interrupt";
        B = "\\.";
        E = "Head.25";
        L = "\u4ec9";
        y = "Generator";
        q = 3.0F /* ZKM Deobf */;
        G = "TOWN_AURA";
        W = "FLIP_SOUTH";
        ja = "\u0417\u0430\u043f\u0440\u0435\u0449\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0430\u0442\u044c\u0441\u044f \u043d\u0430 \u0441\u0435\u0440\u0432\u0435\u0440 \u0441 \u043b\u044e\u0431\u044b\u043c\u0438 \u0448\u0435\u0439\u0434\u0435\u0440\u0430\u043c\u0438.";
        c = 20.0D /* ZKM Deobf */;
        Ka = "fence_nse";
        K = "rows_";
        s = "daysLoop";
        ca = "Right55";
        e = 0.03125D /* ZKM Deobf */;
        ga = "Debug compile ";
        T = "multiply";
        D = "EASE_IN_OUT_QUAD";
        Da = 2375478 /* ZKM Deobf Int */;
        h = 36226 /* ZKM Deobf Int */;
        i = ", options=";
        v = "Front.7b";
        j = "DARK_GRAY";
        t = "hoverBackground_";
        u = "BLOCK";
        Ha = "doorBirch";
        x = "overflow_";
        H = "lure";
        fa = 0.98D /* ZKM Deobf */;
        F = 409 /* ZKM Deobf Int */;
        f = "Piece1.Shape9";
        p = "Right.Right40";
        n = "%d total; %s";
        w = -3.700000047683716F /* ZKM Deobf */;
        M = "GL14.GL_FUNC_REVERSE_SUBTRACT";
        J = "HTTP/1.1";
        X = "platinum_ore";
        z = "||";
        g = "testforblocks";
        P = "rabbitStew";
        R = "GL11.GL_RETURN";
        d = 15198183 /* ZKM Deobf Int */;
        la = "GL11.GL_COPY_INVERTED";
        I = "[AD]";
        N = 2.3499999046325684F /* ZKM Deobf */;
        Aa = "[Texteria] ";
        Y = "Working...";
        k = -4.800000190734863F /* ZKM Deobf */;
        S = 0.6320363879203796F /* ZKM Deobf */;
        O = "birch";
        o = "wooden_door";
        U = "REMOVE_POINT";
        V = ".dat";
        m = 0.7850000262260437F /* ZKM Deobf */;
        Ga = "dead_bubble_coral_block";
        l = "lava";
        Z = "classic";
        Q = "scaleXvalCase_";
        Ja = 0xFAA6B756681EF797L ^ 0xFAA6B756681EFF6BL;
        a = "Piece2.Shape18";
    }
}

