/*
 * Decompiled with CFR 0.152.
 */
public final class Vra {
    public static final String Ca;
    public static final int ia;
    public static final double Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final long fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final long B;
    public static final float d;
    public static final int a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Vra() {
        Vra a2;
    }

    static {
        I = "MIPMAP_LEVELS";
        C = 34007 /* ZKM Deobf Int */;
        X = "next_";
        g = 32777 /* ZKM Deobf Int */;
        c = 511 /* ZKM Deobf Int */;
        Fa = "TREES";
        v = "ofAnimatedSmoke";
        B = 0x52452AEE2A6B0050L ^ 0x52452AEE2A6B0000L;
        Ka = "waxedWeatheredCutCopper";
        V = "  #";
        P = "textures/entity/explosion.png";
        O = "NEW";
        ha = "Eyes.Shape19";
        J = "TITANIUM";
        k = "System Details";
        Y = "SkeletonType";
        ca = "Format error: ";
        Q = "sandstone_wall";
        q = "ENTITY_PARTICLE_TEXTURE";
        Ha = "zombie/zombie_villager";
        la = "Ozelot";
        h = " is already known to ID ";
        fa = 0x36CF69E9F864E9C6L ^ 0x36CF69E9F864EE17L;
        r = "prepareterrain";
        N = "optionsshaders.txt";
        y = "Could not play camera path";
        A = "setblock";
        F = 428 /* ZKM Deobf Int */;
        Da = 709 /* ZKM Deobf Int */;
        M = "oreDiamond";
        p = 33874 /* ZKM Deobf Int */;
        K = "AND";
        Ma = 4000.0D /* ZKM Deobf */;
        w = "unpowered_comparator";
        ia = 375 /* ZKM Deobf Int */;
        S = "Left.Shape19123";
        ja = "Spider";
        G = "CUTOUT_MIPPED";
        m = "mcpatcher/sky/world";
        a = 34026 /* ZKM Deobf Int */;
        j = ", aberration=";
        W = "' expression!";
        t = "textures/entity/slime/slime.png";
        Ga = "_nether";
        s = 32937 /* ZKM Deobf Int */;
        H = "ENDERMITE";
        U = 32852 /* ZKM Deobf Int */;
        o = "textures/entity/guardian_elder.png";
        n = "textures/body/white_bigwings.png";
        i = "GL13.GL_COMPRESSED_LUMINANCE";
        u = 4294967199 /* ZKM Deobf Int */;
        Ia = "GL11.GL_FRONT";
        ga = -0.45378559827804565F /* ZKM Deobf */;
        Ca = "TRIANGLES_BOTTOM";
        f = "CLIENTBOUND";
        d = 0.46875F /* ZKM Deobf */;
        L = 2833 /* ZKM Deobf Int */;
        Aa = "ISOMETRICENABLE";
        Z = "Item data";
        Ja = "GL11.GL_EDGE_FLAG";
        D = 34014 /* ZKM Deobf Int */;
        x = "GL11.GL_SMOOTH";
        T = "ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.\n";
        R = 0.1221729964017868F /* ZKM Deobf */;
        b = 67 /* ZKM Deobf Int */;
        ba = "a boolean (";
        l = "Modifier is already applied on this attribute!";
        e = ", name=";
        z = "' \u0443 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u0430 \u0441 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435\u043c '";
        E = "FireworksItem";
    }
}

