/*
 * Decompiled with CFR 0.152.
 */
public final class Vra {
    public static final String Ca;
    public static final int ia;
    public static final double Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final int Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final long fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final long B;
    public static final float d;
    public static final int a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Vra() {
        Vra a2;
    }

    static {
        I = "MIPMAP_LEVELS";
        C = 0xCB56C6F1 ^ 0xCB564226;
        X = "next_";
        g = 0xEBF1E4B9 ^ 0xEBF164B0;
        c = 0xCA5143D ^ 0xCA515C2;
        Fa = "TREES";
        v = "ofAnimatedSmoke";
        B = 0x52452AEE2A6B0050L ^ 0x52452AEE2A6B0000L;
        Ka = "waxedWeatheredCutCopper";
        V = "  #";
        P = "textures/entity/explosion.png";
        O = "NEW";
        ha = "Eyes.Shape19";
        J = "TITANIUM";
        k = "System Details";
        Y = "SkeletonType";
        ca = "Format error: ";
        Q = "sandstone_wall";
        q = "ENTITY_PARTICLE_TEXTURE";
        Ha = "zombie/zombie_villager";
        la = "Ozelot";
        h = " is already known to ID ";
        fa = 0x36CF69E9F864E9C6L ^ 0x36CF69E9F864EE17L;
        r = "prepareterrain";
        N = "optionsshaders.txt";
        y = "Could not play camera path";
        A = "setblock";
        F = 0x20F06F5C ^ 0x20F06EF0;
        Da = 0x3FF50CB0 ^ 0x3FF50E75;
        M = "oreDiamond";
        p = 0x1FB75A47 ^ 0x1FB7DE15;
        K = "AND";
        Ma = Double.longBitsToDouble(0xDF57A64B705543A1L ^ 0x9FF8E64B705543A1L);
        w = "unpowered_comparator";
        ia = 0x537BA035 ^ 0x537BA142;
        S = "Left.Shape19123";
        ja = "Spider";
        G = "CUTOUT_MIPPED";
        m = "mcpatcher/sky/world";
        a = 0xF40D5C76 ^ 0xF40DD89C;
        j = ", aberration=";
        W = "' expression!";
        t = "textures/entity/slime/slime.png";
        Ga = "_nether";
        s = 0xB7E17F04 ^ 0xB7E1FFAD;
        H = "ENDERMITE";
        U = 0xFB335D6F ^ 0xFB33DD3B;
        o = "textures/entity/guardian_elder.png";
        n = "textures/body/white_bigwings.png";
        i = "GL13.GL_COMPRESSED_LUMINANCE";
        u = 0x33F72B2A ^ 0xCC08D4B5;
        Ia = "GL11.GL_FRONT";
        ga = Float.intBitsToFloat(0xA116D962 ^ 0x1FFE8FF4);
        Ca = "TRIANGLES_BOTTOM";
        f = "CLIENTBOUND";
        d = Float.intBitsToFloat(0x19907543 ^ 0x27607543);
        L = 0x4401AD91 ^ 0x4401A680;
        Aa = "ISOMETRICENABLE";
        Z = "Item data";
        Ja = "GL11.GL_EDGE_FLAG";
        D = 0xD70E1D19 ^ 0xD70E99C7;
        x = "GL11.GL_SMOOTH";
        T = "ARB_shader_objects, ARB_vertex_shader, and ARB_fragment_shader are supported.\n";
        R = Float.intBitsToFloat(0xD979E3F4 ^ 0xE483D622);
        b = 0x51157BC ^ 0x51157FF;
        ba = "a boolean (";
        l = "Modifier is already applied on this attribute!";
        e = ", name=";
        z = "' \u0443 \u044d\u043b\u0435\u043c\u0435\u043d\u0442\u0430 \u0441 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435\u043c '";
        E = "FireworksItem";
    }
}

