/*
 * Decompiled with CFR 0.152.
 */
public final class vRa_1 {
    public static final String aa;
    public static final int ea;
    public static final int Ea;
    public static final int Ca;
    public static final int ia;
    public static final String Ma;
    public static final int ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final double Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final float Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final float o;
    public static final int h;
    public static final double K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final float f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final float m;
    public static final long C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public vRa_1() {
        vRa_1 a2;
    }

    static {
        O = "steve_noob";
        Ja = "LOOKAT_Y";
        n = 0x80AA122F ^ 0x80AA9306;
        W = "dark_oak_log";
        S = "placedMainChest";
        ga = " y";
        h = 0x749657E ^ 0x7C3EFF4;
        M = "GL15.GL_STATIC_READ";
        la = "save-off";
        o = Float.intBitsToFloat(0x699D1092 ^ 0x5697810F);
        Ea = 0xE591AE74 ^ 0xE591AEF7;
        q = Float.intBitsToFloat(0xA328DEB1 ^ 0xE04EDEB1);
        v = "skull_wither";
        K = Double.longBitsToDouble(0xDA315462E720C47FL ^ 0x9A79D462E720C47FL);
        ja = "Head.Shape6";
        ca = 0x221FCD54 ^ 0x221FCFB3;
        Ia = "options.anaglyph";
        G = "\u0428\u0443\u043c\u043e\u043f\u043e\u0434\u0430\u0432\u043b\u0435\u043d\u0438\u0435";
        Q = Float.intBitsToFloat(0xFEAEC345 ^ 0xBC2CC345);
        Da = "facing=east,half=top,shape=inner_right";
        Ca = 0x54F50A4B ^ 0x54F50BC3;
        m = Float.intBitsToFloat(0xAE525428 ^ 0xEC9C5428);
        b = "text.code.";
        p = "\u0413\u0440\u0430\u0444\u0444\u0438\u0442\u0438";
        X = "outOfWorld";
        a = "Pet.Ribbon6";
        k = "opengl_vendor";
        aa = "mr";
        d = 0x38C26FCE ^ 0x38C26FCF;
        l = "0.65, 0, 0.35, 1";
        t = "mob.silverfish.kill";
        U = "fullscreen";
        N = "Extreme Hills";
        D = "axis=x";
        y = "buy";
        Aa = Float.intBitsToFloat(0x6DE88CF1 ^ 0x52C8558D);
        A = "?";
        w = "wingtip.skin";
        i = "Body.Shape32";
        Ga = "easeInCubic";
        H = "stairsWoodAcacia";
        u = Float.intBitsToFloat(0xF36F045E ^ 0xB2F41AE6);
        Ka = "skeleton";
        Ma = "Invalid block id ";
        fa = "Score";
        Ha = Double.longBitsToDouble(0xDC5ABFB71B37D502L ^ 0x1D262380EB37D502L);
        x = "key.hotbar.2";
        r = "Body.Shape15";
        T = Float.intBitsToFloat(0x7DEABAD ^ 0x4606ABAD);
        B = "key.left";
        j = "dioriteSlab";
        C = 0x8B80492201D6CFDFL ^ 0x8B804922FE293020L;
        P = "Handle action: {}";
        Y = "custom/";
        Z = "VC: Player disconnected '{}'";
        L = "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0002\u0000\u0001\u001b\u0002\u1007\u0000\u0003\u1007\u0001\u0004\u1007\u0002\u0005'\u0006\u1004\u0003\u0007\u1007\u0004";
        g = "facing=west,half=top,shape=outer_right";
        ha = "q.screen_height";
        ba = 0x7599FE2D ^ 0x75990E21;
        Fa = "CHAT_VISIBILITY";
        ea = 0x48D5047B ^ 0x48D51177;
        c = "GL11.GL_SCISSOR_BOX";
        V = "MINECART_HOPPER";
        J = "NOT_SET";
        F = "fermentedSpiderEye";
        I = 0x4F92E580 ^ 0x4F926012;
        s = "GL11.GL_R";
        E = 0x557F4B49 ^ 0x557F4028;
        z = "reconnect off";
        R = "Head.10";
        ia = 0x68EA4F62 ^ 0x68EA4279;
        f = Float.intBitsToFloat(0x83AC67A5 ^ 0xBE1EADFD);
        e = 0x67DD2E88 ^ 0x67DD2394;
    }
}

