/*
 * Decompiled with CFR 0.152.
 */
public final class vTa {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final double ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final double x;
    public static final int v;
    public static final int o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final float e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public vTa() {
        vTa a2;
    }

    static {
        ha = "achievement.get";
        W = "world-light-updates";
        i = "GL11.GL_TEXTURE_COORD_ARRAY_STRIDE";
        K = -0.2617993950843811F /* ZKM Deobf */;
        ca = "bilinear";
        fa = 35632 /* ZKM Deobf Int */;
        C = "blocks/destroy_stage_5";
        F = "textures/body/mercy_wings_gold.png";
        d = 676 /* ZKM Deobf Int */;
        e = -0.0872664600610733F /* ZKM Deobf */;
        U = 34165 /* ZKM Deobf Int */;
        L = " X";
        Aa = ", rainbow=";
        Fa = "REMOVE_ROW";
        f = 4215066 /* ZKM Deobf Int */;
        k = "QQQ";
        o = 30010 /* ZKM Deobf Int */;
        ba = "textures/entity/experience_orb.png";
        Ga = "GL11.GL_LOAD";
        R = "inventory.png";
        Z = "Right.Right10";
        n = 33386 /* ZKM Deobf Int */;
        P = "GL13.GL_TEXTURE24";
        p = "minecartFurnace";
        q = "\u0421\u043d\u0430\u0447\u0430\u043b\u0430 \u0441\u0442\u0430\u0440\u0430\u044f";
        a = "CustomSky: Texture not found: ";
        I = 372 /* ZKM Deobf Int */;
        c = "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0006\u0002\u0001";
        y = 210 /* ZKM Deobf Int */;
        m = "12a";
        S = "=";
        la = "Invalid lightmap width: ";
        l = 1.3962634015954636D /* ZKM Deobf */;
        M = "##TEffectHud";
        H = "tile.oreIron.name";
        Ja = "ofCustomItems";
        ga = 0.3873D /* ZKM Deobf */;
        h = "OCELOT";
        O = "glass_pane_top_orange";
        J = "animations/pet/player_animation.json";
        E = "VC: Connected";
        t = "experience_bottle";
        w = "defaultFinishAnimationDuration_";
        s = "blast";
        x = -99999.0D /* ZKM Deobf */;
        N = 0.550000011920929F /* ZKM Deobf */;
        ja = "createWorld.customize.custom.next";
        D = "\\\\\"";
        Ka = "Render pass not supported: ";
        X = "Shaders can not be loaded, Anisotropic Filtering is enabled: ";
        r = "MENU";
        z = "> ";
        Ha = "\u5041";
        B = "WitherBoss";
        Q = 7555121 /* ZKM Deobf Int */;
        Y = "Mipmap levels";
        T = "chunkCheck";
        b = "uniform [ _a-zA-Z0-9]+ shadowtex0;.*";
        A = "0 & 1 & !2 & 3 & 3+6";
        V = "XpP";
        G = "potatoes";
        v = 32732 /* ZKM Deobf Int */;
        u = 40006 /* ZKM Deobf Int */;
        Ia = "0.12, 0, 0.39, 0";
        Da = "Too big internal image";
        g = "south_west";
        j = "disconnect.lost";
    }
}

