/*
 * Decompiled with CFR 0.152.
 */
public final class vTa {
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final double ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final int U;
    public static final String P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final float N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final double x;
    public static final int v;
    public static final int o;
    public static final String h;
    public static final float K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final double l;
    public static final float e;
    public static final String G;
    public static final String D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public vTa() {
        vTa a2;
    }

    static {
        ha = "achievement.get";
        W = "world-light-updates";
        i = "GL11.GL_TEXTURE_COORD_ARRAY_STRIDE";
        K = Float.intBitsToFloat(0x712A7925 ^ 0xCFAC73B7);
        ca = "bilinear";
        fa = 0xDA01C14C ^ 0xDA014A7C;
        C = "blocks/destroy_stage_5";
        F = "textures/body/mercy_wings_gold.png";
        d = 0x1E70537D ^ 0x1E7051D9;
        e = Float.intBitsToFloat(0xE1604936 ^ 0x5CD2F1F4);
        U = 0x6C86A810 ^ 0x6C862D65;
        L = " X";
        Aa = ", rainbow=";
        Fa = "REMOVE_ROW";
        f = 0xE3C1C7FB ^ 0xE38196E1;
        k = "QQQ";
        o = 0x16A02D35 ^ 0x16A0580F;
        ba = "textures/entity/experience_orb.png";
        Ga = "GL11.GL_LOAD";
        R = "inventory.png";
        Z = "Right.Right10";
        n = 0xC7C2A73D ^ 0xC7C22557;
        P = "GL13.GL_TEXTURE24";
        p = "minecartFurnace";
        q = "\u0421\u043d\u0430\u0447\u0430\u043b\u0430 \u0441\u0442\u0430\u0440\u0430\u044f";
        a = "CustomSky: Texture not found: ";
        I = 0x886086B9 ^ 0x886087CD;
        c = "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0006\u0002\u0001";
        y = 0xE2FFAA15 ^ 0xE2FFAAC7;
        m = "12a";
        S = "=";
        la = "Invalid lightmap width: ";
        l = Double.longBitsToDouble(0xDD48E82D701B4D5EL ^ 0xE2BEBF353AFC09D9L);
        M = "##TEffectHud";
        H = "tile.oreIron.name";
        Ja = "ofCustomItems";
        ga = Double.longBitsToDouble(0x9BA6C9EA28135DC1L ^ 0xA47E006FD87C3485L);
        h = "OCELOT";
        O = "glass_pane_top_orange";
        J = "animations/pet/player_animation.json";
        E = "VC: Connected";
        t = "experience_bottle";
        w = "defaultFinishAnimationDuration_";
        s = "blast";
        x = Double.longBitsToDouble(0x76EBE61B5C4D00D2L ^ 0xB6138FEB5C4D00D2L);
        N = Float.intBitsToFloat(0x10B2A3F ^ 0x3E07E6F2);
        ja = "createWorld.customize.custom.next";
        D = "\\\\\"";
        Ka = "Render pass not supported: ";
        X = "Shaders can not be loaded, Anisotropic Filtering is enabled: ";
        r = "MENU";
        z = "> ";
        Ha = "\u5041";
        B = "WitherBoss";
        Q = 0xF0794EC0 ^ 0xF00A06F1;
        Y = "Mipmap levels";
        T = "chunkCheck";
        b = "uniform [ _a-zA-Z0-9]+ shadowtex0;.*";
        A = "0 & 1 & !2 & 3 & 3+6";
        V = "XpP";
        G = "potatoes";
        v = 0xB0001C15 ^ 0xB00063C9;
        u = 0xE037E7C2 ^ 0xE0377B84;
        Ia = "0.12, 0, 0.39, 0";
        Da = "Too big internal image";
        g = "south_west";
        j = "disconnect.lost";
    }
}

