/*
 * Decompiled with CFR 0.152.
 */
public final class vua {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final float ha;
    public static final long Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final double Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final long U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final double K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final int l;
    public static final String e;
    public static final float G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final double C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public vua() {
        vua a2;
    }

    static {
        ia = "hoveredBlockFace_";
        F = 814 /* ZKM Deobf Int */;
        H = "Rot";
        S = ", y=";
        Ca = "Death in Hardcore";
        Aa = "EASE_OUT_BOUNCE";
        V = "ANIMATED_SMOKE";
        i = "BLOCK_CRACK";
        b = 2980 /* ZKM Deobf Int */;
        Ka = "^^";
        T = "rightHorn";
        c = "minecraft:items/empty_armor_slot_leggings";
        ha = 500.0F /* ZKM Deobf */;
        B = 30001 /* ZKM Deobf Int */;
        L = "Shape9";
        Ha = 0.15000000074505807D /* ZKM Deobf */;
        M = "SCALEX";
        Q = "DropItem";
        ja = "LeftLeg.Lp";
        v = 732 /* ZKM Deobf Int */;
        W = "glass_red";
        o = "GL11.GL_LINE_WIDTH_GRANULARITY";
        N = "skyColor";
        Ma = 2437522 /* ZKM Deobf Int */;
        n = "Left.Shape43123";
        m = 40081 /* ZKM Deobf Int */;
        Ga = "game.hostile.hurt";
        J = "reconnectTo_";
        g = "baseSize";
        x = 16724016 /* ZKM Deobf Int */;
        C = 0.0009D /* ZKM Deobf */;
        Ea = "M6";
        f = "()";
        A = "asin";
        l = 651 /* ZKM Deobf Int */;
        U = 0x2036514B9929B0D0L ^ 0x2036514B9929B050L;
        k = "INVISIBLE";
        z = "buyB";
        Ja = 0.8470588326454163F /* ZKM Deobf */;
        t = 0.09999999403953552F /* ZKM Deobf */;
        E = "textures/entity/creeper/creeper_armor.png";
        G = -0.15000000596046448F /* ZKM Deobf */;
        X = "composite4";
        d = "Data ID";
        Ia = "fill";
        y = 162 /* ZKM Deobf Int */;
        r = "container.repair";
        u = "Item not found: ";
        ca = "particles_opaque";
        Z = "aesCipherRelease";
        fa = "ANGLEYANIM";
        I = 613 /* ZKM Deobf Int */;
        P = "heightScale";
        e = "COULD_NOT_CONNECT";
        Da = " particles";
        j = "stone_brick";
        K = 21.0D /* ZKM Deobf */;
        R = "\u4f5a";
        la = 32770 /* ZKM Deobf Int */;
        s = "ONION";
        w = "DRIP_WATER";
        Y = 34004 /* ZKM Deobf Int */;
        p = "SnowMan";
        D = "Left.Shape73123";
        ba = "Silent";
        q = "--assetsDir";
        ga = "Recipes";
        h = "disconnect.endOfStream";
        a = "Invalid data length";
        O = "solaris";
        Fa = 0xC1274F175F553D28L ^ 0xC1274F175F552EA0L;
    }
}

