/*
 * Decompiled with CFR 0.152.
 */
public final class vua {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final float ha;
    public static final long Fa;
    public static final String Ia;
    public static final int la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final double Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final long U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final double K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final int l;
    public static final String e;
    public static final float G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final double C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    public vua() {
        vua a2;
    }

    static {
        ia = "hoveredBlockFace_";
        F = 0x47BD5B6D ^ 0x47BD5843;
        H = "Rot";
        S = ", y=";
        Ca = "Death in Hardcore";
        Aa = "EASE_OUT_BOUNCE";
        V = "ANIMATED_SMOKE";
        i = "BLOCK_CRACK";
        b = 0xD7D30B17 ^ 0xD7D300B3;
        Ka = "^^";
        T = "rightHorn";
        c = "minecraft:items/empty_armor_slot_leggings";
        ha = Float.intBitsToFloat(0xCA4D41AD ^ 0x89B741AD);
        B = 0xA97234A8 ^ 0xA9724199;
        L = "Shape9";
        Ha = Double.longBitsToDouble(0xC5B8E057EB694D7FL ^ 0xFA7BD364DFA581B2L);
        M = "SCALEX";
        Q = "DropItem";
        ja = "LeftLeg.Lp";
        v = 0xA6F5B591 ^ 0xA6F5B74D;
        W = "glass_red";
        o = "GL11.GL_LINE_WIDTH_GRANULARITY";
        N = "skyColor";
        Ma = 0x38E80784 ^ 0x38CD3616;
        n = "Left.Shape43123";
        m = 0x6817794A ^ 0x6817E5DB;
        Ga = "game.hostile.hurt";
        J = "reconnectTo_";
        g = "baseSize";
        x = 0x5453344E ^ 0x54AC047E;
        C = Double.longBitsToDouble(0xAB119D58D78F9CDEL ^ 0x945CE0E79FF0574CL);
        Ea = "M6";
        f = "()";
        A = "asin";
        l = 0x49BDB98F ^ 0x49BDBB04;
        U = 0x2036514B9929B0D0L ^ 0x2036514B9929B050L;
        k = "INVISIBLE";
        z = "buyB";
        Ja = Float.intBitsToFloat(0xEF5EB0D9 ^ 0xD0066800);
        t = Float.intBitsToFloat(0xEB04EF3E ^ 0xD6C823F2);
        E = "textures/entity/creeper/creeper_armor.png";
        G = Float.intBitsToFloat(0x63CCE5F4 ^ 0xDDD57C6E);
        X = "composite4";
        d = "Data ID";
        Ia = "fill";
        y = 0xD98C2D36 ^ 0xD98C2D94;
        r = "container.repair";
        u = "Item not found: ";
        ca = "particles_opaque";
        Z = "aesCipherRelease";
        fa = "ANGLEYANIM";
        I = 0xAE735FB7 ^ 0xAE735DD2;
        P = "heightScale";
        e = "COULD_NOT_CONNECT";
        Da = " particles";
        j = "stone_brick";
        K = Double.longBitsToDouble(0xAA099493CBC5069FL ^ 0xEA3C9493CBC5069FL);
        R = "\u4f5a";
        la = 0xCBE532C9 ^ 0xCBE5B2CB;
        s = "ONION";
        w = "DRIP_WATER";
        Y = 0xFAB56F65 ^ 0xFAB5EBB1;
        p = "SnowMan";
        D = "Left.Shape73123";
        ba = "Silent";
        q = "--assetsDir";
        ga = "Recipes";
        h = "disconnect.endOfStream";
        a = "Invalid data length";
        O = "solaris";
        Fa = 0xC1274F175F553D28L ^ 0xC1274F175F552EA0L;
    }
}

