/*
 * Decompiled with CFR 0.152.
 */
public final class WOa {
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final float Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final long D;
    public static final int f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final int k;
    public static final double j;
    public static final String J;
    public static final String A;
    public static final String I;

    public WOa() {
        WOa a2;
    }

    static {
        ja = "GL13.GL_TEXTURE5";
        L = "SPRINT";
        Ka = "\u00a77";
        t = "Tunnelers' Dream";
        I = "v+h";
        i = 5387 /* ZKM Deobf Int */;
        Ja = "sponge_wet";
        p = "playing_lan";
        Aa = "MC_OS_LINUX";
        O = "On the bright side, I bought you a teddy bear!";
        M = "Needed to grow BufferBuilder buffer: Old size ";
        l = "FrozenRiver";
        R = "wood_old";
        ca = " to be a string, was ";
        w = "GL11.GL_UNPACK_ALIGNMENT";
        k = 668265261 /* ZKM Deobf Int */;
        y = "Invalid tag encountered, expected '{' as first char.";
        b = 3347 /* ZKM Deobf Int */;
        o = 3346 /* ZKM Deobf Int */;
        ga = "text.sign";
        C = "toggledownfall";
        K = "Low";
        Y = "GL13.GL_TEXTURE_COMPRESSED";
        m = "easeInSine";
        d = "concretePowder";
        a = "item.fireworksCharge.trail";
        j = 1.15D /* ZKM Deobf */;
        g = "LPT7";
        P = "BIT_OR";
        S = 3123 /* ZKM Deobf Int */;
        D = 0x44ECB4959B54F74BL ^ 0x44ECB4959B54F667L;
        n = "GL11.GL_COLOR_INDEXES";
        B = " // Shader option ";
        A = "jungleFenceGate";
        x = "delay_";
        e = " is in the wrong location; relocating. (Expected ";
        s = "GL11.GL_MAP2_TEXTURE_COORD_4";
        G = "commands.clone.failed";
        u = "stairsWoodDarkOak";
        H = "COM6";
        Q = "commands.scoreboard.players.enable.success";
        Ha = "Invalid default spacing";
        W = "flower_paeonia";
        fa = 9 /* ZKM Deobf Int */;
        U = "_froglight";
        v = "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u1001\u0000\u0002\u0006\u0003\u1006\u0001";
        J = "aesCipherEncrypt";
        f = 34966 /* ZKM Deobf Int */;
        q = 3887386 /* ZKM Deobf Int */;
        Da = "ANIMATED_EXPLOSION";
        Ga = "SOUNDSTOP";
        F = "LEGS_DEFAULT";
        h = 8365974 /* ZKM Deobf Int */;
        c = "ViST";
        X = "mob.guardian.hit";
        Z = 21.25F /* ZKM Deobf */;
        r = "grass_side";
        z = "animation_player";
        T = "options.stream.chat.userFilter";
        V = " \u00a7f(\u00a77\u0418\u0434\u0435\u0442 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0430...\u00a7f)";
        E = "resources_";
        N = "Biome A ID";
    }
}

