/*
 * Decompiled with CFR 0.152.
 */
public final class wOa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final float z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final double G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    static {
        Da = "birch_sapling";
        I = 6146 /* ZKM Deobf Int */;
        C = 744 /* ZKM Deobf Int */;
        L = "SlotOutlineColor";
        la = "\u041f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435...";
        x = 1.0299999713897705F /* ZKM Deobf */;
        P = "mobSpawner";
        d = "Piece2.Shape11";
        u = "ender_chest";
        B = "textures/pet/sheeppig.png";
        l = "[Shaders] Error: Invalid program ";
        Ka = "red_glazed_terracotta";
        n = "east=true,north=true,south=true,west=true";
        N = "angleX_";
        Q = "Very likely; Jar signature invalidated";
        s = "LeftHand.LH1";
        z = 1700.0F /* ZKM Deobf */;
        m = "fast";
        fa = "ARMS_ON_TOP";
        g = "ADD";
        ja = "chat.link.open";
        Z = "body3";
        Ha = ".line2";
        A = "raw_gold_block";
        k = 2293580 /* ZKM Deobf Int */;
        G = -0.05000000074505806D /* ZKM Deobf */;
        U = "TNTFuse";
        r = 32863 /* ZKM Deobf Int */;
        i = "Unexpected error";
        V = "collision_drag";
        T = "allowBlockAlternatives";
        W = "ofFogStart";
        X = "X#";
        Ia = "PURPLE";
        v = "facing=north,half=bottom,shape=inner_right";
        R = "centered_";
        t = 19 /* ZKM Deobf Int */;
        S = "dark_oak";
        q = "portal.trigger";
        e = "\u0420\u0435\u0436\u0438\u043c \u0440\u0430\u0446\u0438\u0438";
        H = 16445005 /* ZKM Deobf Int */;
        Y = "chest_name";
        Ja = "://mc.vimeworld.";
        c = 3312 /* ZKM Deobf Int */;
        F = "minecraft:particle_initial_spin";
        E = "clearWeatherTime";
        h = 21 /* ZKM Deobf Int */;
        Ga = 739 /* ZKM Deobf Int */;
        w = 0.75F /* ZKM Deobf */;
        f = "heal";
        p = "of.options.shaderOptionsTitle";
        b = "rawIronBlock";
        Aa = 3089 /* ZKM Deobf Int */;
        ga = "No weighted models for: ";
        K = "black_iron_ore";
        Fa = ", shaking=";
        D = "ClickEvent{action=";
        o = "paleOakSlab";
        ha = "mob.wolf.death";
        a = 519 /* ZKM Deobf Int */;
        M = "GL11.GL_MAP1_GRID_SEGMENTS";
        O = "stat.sprintOneCm";
        j = "UNLOCKED";
        J = ", material=";
        y = "z1";
        ca = 20226 /* ZKM Deobf Int */;
    }

    public wOa_1() {
        wOa_1 a2;
    }
}

