/*
 * Decompiled with CFR 0.152.
 */
public final class wOa_1 {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final int r;
    public static final String V;
    public static final float z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final int c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final double G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final int I;

    static {
        Da = "birch_sapling";
        I = 0xA3A4DF2 ^ 0xA3A55F0;
        C = 0x68BEB92 ^ 0x68BE97A;
        L = "SlotOutlineColor";
        la = "\u041f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435...";
        x = Float.intBitsToFloat(0xD483384B ^ 0xEB00EF41);
        P = "mobSpawner";
        d = "Piece2.Shape11";
        u = "ender_chest";
        B = "textures/pet/sheeppig.png";
        l = "[Shaders] Error: Invalid program ";
        Ka = "red_glazed_terracotta";
        n = "east=true,north=true,south=true,west=true";
        N = "angleX_";
        Q = "Very likely; Jar signature invalidated";
        s = "LeftHand.LH1";
        z = Float.intBitsToFloat(0x2F785663 ^ 0x6BACD663);
        m = "fast";
        fa = "ARMS_ON_TOP";
        g = "ADD";
        ja = "chat.link.open";
        Z = "body3";
        Ha = ".line2";
        A = "raw_gold_block";
        k = 0x48DB5B23 ^ 0x48F9A46F;
        G = Double.longBitsToDouble(0x15D29B8EC6D80C0CL ^ 0xAA7B021766D80C0CL);
        U = "TNTFuse";
        r = 0x31E3135B ^ 0x31E39304;
        i = "Unexpected error";
        V = "collision_drag";
        T = "allowBlockAlternatives";
        W = "ofFogStart";
        X = "X#";
        Ia = "PURPLE";
        v = "facing=north,half=bottom,shape=inner_right";
        R = "centered_";
        t = 0x774E11D5 ^ 0x774E11C6;
        S = "dark_oak";
        q = "portal.trigger";
        e = "\u0420\u0435\u0436\u0438\u043c \u0440\u0430\u0446\u0438\u0438";
        H = 0x5BECAAA9 ^ 0x5B1644E4;
        Y = "chest_name";
        Ja = "://mc.vimeworld.";
        c = 0x5E171AC9 ^ 0x5E171639;
        F = "minecraft:particle_initial_spin";
        E = "clearWeatherTime";
        h = 0x749E7E17 ^ 0x749E7E02;
        Ga = 0xBD02498B ^ 0xBD024B68;
        w = Float.intBitsToFloat(0xC34DDB12 ^ 0xFC0DDB12);
        f = "heal";
        p = "of.options.shaderOptionsTitle";
        b = "rawIronBlock";
        Aa = 0x156B3528 ^ 0x156B3939;
        ga = "No weighted models for: ";
        K = "black_iron_ore";
        Fa = ", shaking=";
        D = "ClickEvent{action=";
        o = "paleOakSlab";
        ha = "mob.wolf.death";
        a = 0x38D1DEDB ^ 0x38D1DCDC;
        M = "GL11.GL_MAP1_GRID_SEGMENTS";
        O = "stat.sprintOneCm";
        j = "UNLOCKED";
        J = ", material=";
        y = "z1";
        ca = 0xEFD148A7 ^ 0xEFD107A5;
    }

    public wOa_1() {
        wOa_1 a2;
    }
}

