/*
 * Decompiled with CFR 0.152.
 */
public final class WPa {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final float z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final double P;
    public static final long u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final int n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final float F;
    public static final String g;
    public static final int L;
    public static final float E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        d = "sizeExpr_";
        H = "LAVA";
        I = "gbuffers_item";
        w = "SKELETON";
        r = "sandstoneWall";
        T = -0.03490658476948738F /* ZKM Deobf */;
        L = 68 /* ZKM Deobf Int */;
        s = 5889 /* ZKM Deobf Int */;
        u = 0x982BF667F0DC36B0L ^ 0x982BF667F0DC360BL;
        A = "options.vbo";
        ga = "GL14.GL_CURRENT_SECONDARY_COLOR";
        G = "skins.";
        V = "WANDERER";
        J = "angleZvalCase_";
        W = "[Shaders] Error: Failed creating framebuffer! (Status ";
        la = "Forced entities";
        k = "Left.Shape36123";
        x = "options.chat.height.focused";
        t = "minZ_";
        l = "chatScale:";
        f = "gbuffers";
        U = "Probably not. Jar signature remains and both client + server brands are untouched.";
        v = "mob.endermen.scream";
        z = -0.4363322854042053F /* ZKM Deobf */;
        Ja = "commands.scoreboard.teams.list.entry";
        B = "&e/cam interpolation <";
        a = 34002 /* ZKM Deobf Int */;
        N = "commands.fill.usage";
        g = "Failed to save pvp options";
        C = "CachingFontRenderer.disabled";
        X = "leftStick.LeftStick";
        m = "resinBrickStairs";
        F = -4.611299991607666F /* ZKM Deobf */;
        ja = "OpenGlError: ";
        b = "Would you like a cupcake?";
        y = 1.7999999523162842D /* ZKM Deobf */;
        q = 36059 /* ZKM Deobf Int */;
        M = 4291795520 /* ZKM Deobf Int */;
        i = 10047 /* ZKM Deobf Int */;
        ca = "rd";
        e = "checkedPosition < toCheckCount";
        Ka = "selectWorld.enterName";
        Ga = "textures/entity/rabbit/brown.png";
        Da = "keybind_";
        D = " MB) up to ";
        Ha = "bootsCloth";
        Aa = "geforce";
        R = 8448 /* ZKM Deobf Int */;
        P = 44.0D /* ZKM Deobf */;
        p = "hide_with_boots";
        O = "Event data";
        n = 32970 /* ZKM Deobf Int */;
        S = "%.0f";
        Fa = "GL11.GL_FILL";
        E = 144.0F /* ZKM Deobf */;
        fa = "SNOW_SHOVEL";
        Ia = "textures/pet/creeper.png";
        j = "red_stained_glass_pane";
        Z = "unix";
        c = "body.body2";
        h = "\u0411\u043e\u043b\u044c\u0448\u043e\u0439";
        Q = "waxedWeatheredCopperGrate";
        K = ", numericId=";
        o = "unsupported color format: ";
        Y = "EntityId";
    }

    public WPa() {
        WPa a2;
    }
}

