/*
 * Decompiled with CFR 0.152.
 */
public final class WPa {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final float z;
    public static final String X;
    public static final double y;
    public static final String U;
    public static final double P;
    public static final long u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final int n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final float F;
    public static final String g;
    public static final int L;
    public static final float E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        d = "sizeExpr_";
        H = "LAVA";
        I = "gbuffers_item";
        w = "SKELETON";
        r = "sandstoneWall";
        T = Float.intBitsToFloat(0xFA170E8B ^ 0x4719F4BE);
        L = 0x26AF2280 ^ 0x26AF22C4;
        s = 0x160F91C7 ^ 0x160F86C6;
        u = 0x982BF667F0DC36B0L ^ 0x982BF667F0DC360BL;
        A = "options.vbo";
        ga = "GL14.GL_CURRENT_SECONDARY_COLOR";
        G = "skins.";
        V = "WANDERER";
        J = "angleZvalCase_";
        W = "[Shaders] Error: Failed creating framebuffer! (Status ";
        la = "Forced entities";
        k = "Left.Shape36123";
        x = "options.chat.height.focused";
        t = "minZ_";
        l = "chatScale:";
        f = "gbuffers";
        U = "Probably not. Jar signature remains and both client + server brands are untouched.";
        v = "mob.endermen.scream";
        z = Float.intBitsToFloat(0x2F73E1E1 ^ 0x91AC8713);
        Ja = "commands.scoreboard.teams.list.entry";
        B = "&e/cam interpolation <";
        a = 0x9793BEEA ^ 0x97933A38;
        N = "commands.fill.usage";
        g = "Failed to save pvp options";
        C = "CachingFontRenderer.disabled";
        X = "leftStick.LeftStick";
        m = "resinBrickStairs";
        F = Float.intBitsToFloat(0x6BD52FAF ^ 0xAB46A06A);
        ja = "OpenGlError: ";
        b = "Would you like a cupcake?";
        y = Double.longBitsToDouble(0x1FAFCDCDEE486CBFL ^ 0x205301012E486CBFL);
        q = 0xB1C982F5 ^ 0xB1C90E2E;
        M = 0xC1A2A852 ^ 0x3E6D3212;
        i = 0x89650DC5 ^ 0x89652AFA;
        ca = "rd";
        e = "checkedPosition < toCheckCount";
        Ka = "selectWorld.enterName";
        Ga = "textures/entity/rabbit/brown.png";
        Da = "keybind_";
        D = " MB) up to ";
        Ha = "bootsCloth";
        Aa = "geforce";
        R = 0x120CECF3 ^ 0x120CCDF3;
        P = Double.longBitsToDouble(0x7AAB9AF3B4786F53L ^ 0x3AED9AF3B4786F53L);
        p = "hide_with_boots";
        O = "Event data";
        n = 0x7751C01 ^ 0x7759CCB;
        S = "%.0f";
        Fa = "GL11.GL_FILL";
        E = Float.intBitsToFloat(0x5520F88B ^ 0x1630F88B);
        fa = "SNOW_SHOVEL";
        Ia = "textures/pet/creeper.png";
        j = "red_stained_glass_pane";
        Z = "unix";
        c = "body.body2";
        h = "\u0411\u043e\u043b\u044c\u0448\u043e\u0439";
        Q = "waxedWeatheredCopperGrate";
        K = ", numericId=";
        o = "unsupported color format: ";
        Y = "EntityId";
    }

    public WPa() {
        WPa a2;
    }
}

