/*
 * Decompiled with CFR 0.152.
 */
public final class Wqa {
    public static final double Ea;
    public static final float Ca;
    public static final int ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final double Z;
    public static final String Y;
    public static final double r;
    public static final float V;
    public static final double z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final int o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final double d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final double m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Wqa() {
        Wqa a2;
    }

    static {
        K = "Entity's Vehicle";
        N = "Right37";
        Ia = "blaze";
        H = "MATRIX";
        A = "flower_rose";
        G = 827 /* ZKM Deobf Int */;
        Z = 8.0D /* ZKM Deobf */;
        c = 33169 /* ZKM Deobf Int */;
        ha = "bubble";
        m = 10.0D /* ZKM Deobf */;
        T = "preCelestialRotate";
        ba = "item.fireworksCharge.type.";
        y = "RECTANGLE";
        d = 0.275D /* ZKM Deobf */;
        Ga = "GL13.GL_CONSTANT";
        Ha = "GL13.GL_DOT3_RGBA";
        M = "wall_ne";
        i = "Head.20";
        Q = "layers";
        V = -2.5999999046325684F /* ZKM Deobf */;
        la = "replaceitem";
        t = "RightHand.RH1";
        D = "The server is full!";
        fa = "%";
        O = 4864 /* ZKM Deobf Int */;
        F = "body.body5";
        x = "Input target '";
        Ka = "XXL";
        j = "/~";
        g = "GL14.GL_FOG_COORDINATE_ARRAY_STRIDE";
        R = "GL11.GL_LUMINANCE16";
        l = "gl_caps[ARB_fragment_layer_viewport]";
        ca = "gzip";
        J = "EASE_IN_CIRC";
        ga = "startFadeOut";
        I = "easeOutElastic";
        P = "left-hand-visible";
        u = "CRAFTING";
        p = "IMPL_LOOKUP";
        z = 0.15707963267948966D /* ZKM Deobf */;
        E = 34030 /* ZKM Deobf Int */;
        Ma = "GL11.GL_LIGHT_MODEL_TWO_SIDE";
        a = "strad";
        S = ", resistance=";
        r = 0.0020000000949949026D /* ZKM Deobf */;
        ia = 501 /* ZKM Deobf Int */;
        s = "facing=west,half=top,shape=outer_left";
        h = 32855 /* ZKM Deobf Int */;
        W = "fancyGraphics";
        e = "party/checkbox/inactive_hover.png";
        v = 40009 /* ZKM Deobf Int */;
        Aa = 818 /* ZKM Deobf Int */;
        w = 769 /* ZKM Deobf Int */;
        X = 33878 /* ZKM Deobf Int */;
        Y = "list";
        Fa = "mob.villager.hit";
        b = "Entity That Is Already Tracked";
        B = "GL13.GL_OPERAND1_ALPHA";
        q = "createWorld.customize.custom.depthNoiseScaleX";
        n = "rock";
        Ja = 536870912 /* ZKM Deobf Int */;
        Ca = 0.06499999761581421F /* ZKM Deobf */;
        o = 386 /* ZKM Deobf Int */;
        Da = "buffer";
        C = "variable.particle_pos.y";
        U = "blockId";
        f = "assets/minecraft/models/block/stairs.json";
        L = "Stat{id=";
        ja = "VC: Join {}:{} '{}'";
        k = 0.31690141558647156F /* ZKM Deobf */;
        Ea = 3000.0D /* ZKM Deobf */;
    }
}

