/*
 * Decompiled with CFR 0.152.
 */
public final class Wqa {
    public static final double Ea;
    public static final float Ca;
    public static final int ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final int Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final String S;
    public static final double Z;
    public static final String Y;
    public static final double r;
    public static final float V;
    public static final double z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final int o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final double d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final int G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final int E;
    public static final double m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Wqa() {
        Wqa a2;
    }

    static {
        K = "Entity's Vehicle";
        N = "Right37";
        Ia = "blaze";
        H = "MATRIX";
        A = "flower_rose";
        G = 0xABCB9577 ^ 0xABCB964C;
        Z = Double.longBitsToDouble(0xCF6CCDCFB242510AL ^ 0x8F4CCDCFB242510AL);
        c = 0x6AA790B7 ^ 0x6AA71126;
        ha = "bubble";
        m = Double.longBitsToDouble(0x3F8A5A8A12B78F1CL ^ 0x7FAE5A8A12B78F1CL);
        T = "preCelestialRotate";
        ba = "item.fireworksCharge.type.";
        y = "RECTANGLE";
        d = Double.longBitsToDouble(0xAA240BE8902DBF9AL ^ 0x95F5927109B42600L);
        Ga = "GL13.GL_CONSTANT";
        Ha = "GL13.GL_DOT3_RGBA";
        M = "wall_ne";
        i = "Head.20";
        Q = "layers";
        V = Float.intBitsToFloat(0x9723F202 ^ 0x57059464);
        la = "replaceitem";
        t = "RightHand.RH1";
        D = "The server is full!";
        fa = "%";
        O = 0x7CFBA5E1 ^ 0x7CFBB6E1;
        F = "body.body5";
        x = "Input target '";
        Ka = "XXL";
        j = "/~";
        g = "GL14.GL_FOG_COORDINATE_ARRAY_STRIDE";
        R = "GL11.GL_LUMINANCE16";
        l = "gl_caps[ARB_fragment_layer_viewport]";
        ca = "gzip";
        J = "EASE_IN_CIRC";
        ga = "startFadeOut";
        I = "easeOutElastic";
        P = "left-hand-visible";
        u = "CRAFTING";
        p = "IMPL_LOOKUP";
        z = Double.longBitsToDouble(0x5FD992F1D4C69B8BL ^ 0x601D89DEA25A6B6BL);
        E = 0x47C343CD ^ 0x47C3C723;
        Ma = "GL11.GL_LIGHT_MODEL_TWO_SIDE";
        a = "strad";
        S = ", resistance=";
        r = Double.longBitsToDouble(0x5DF0D5B844805C1CL ^ 0x6290B7F5A4805C1CL);
        ia = 0xCA73F555 ^ 0xCA73F4A0;
        s = "facing=west,half=top,shape=outer_left";
        h = 0x2F47F033 ^ 0x2F477064;
        W = "fancyGraphics";
        e = "party/checkbox/inactive_hover.png";
        v = 0x16D48526 ^ 0x16D4196F;
        Aa = 0x7F4D3AE6 ^ 0x7F4D39D4;
        w = 0x377B5FD1 ^ 0x377B5CD0;
        X = 0x19932B16 ^ 0x1993AF40;
        Y = "list";
        Fa = "mob.villager.hit";
        b = "Entity That Is Already Tracked";
        B = "GL13.GL_OPERAND1_ALPHA";
        q = "createWorld.customize.custom.depthNoiseScaleX";
        n = "rock";
        Ja = 0xF282F8EA ^ 0xD282F8EA;
        Ca = Float.intBitsToFloat(0x22E54BED ^ 0x1F605555);
        o = 0x34F9821F ^ 0x34F9839D;
        Da = "buffer";
        C = "variable.particle_pos.y";
        U = "blockId";
        f = "assets/minecraft/models/block/stairs.json";
        L = "Stat{id=";
        ja = "VC: Join {}:{} '{}'";
        k = Float.intBitsToFloat(0xA6EBF94A ^ 0x9849B9AD);
        Ea = Double.longBitsToDouble(0x8B3FAE2786A9F096L ^ 0xCB98DE2786A9F096L);
    }
}

