/*
 * Decompiled with CFR 0.152.
 */
public final class wra_1 {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final double Ja;
    public static final String ja;
    public static final int Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final double Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final int u;
    public static final int O;
    public static final long t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final float L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public wra_1() {
        wra_1 a2;
    }

    static {
        Ga = "Shape33";
        Z = 0x91FC4D4A ^ 0x91FC4C07;
        G = "FALL";
        a = "world";
        D = "maxX_";
        O = 0x22F89359 ^ 0x22F892B9;
        J = "gray_concrete";
        s = "GL15.GL_DYNAMIC_DRAW";
        Ka = "\u501c";
        t = 0xC45BEACD07EEBCF1L ^ 0xC45BEACD07EEBD61L;
        Ja = Double.longBitsToDouble(0x4546520A361910A5L ^ 0x851F520A361910A5L);
        y = "Wither";
        Y = "Outdated client! Please use 1.8.8";
        B = 0xA1CA04CE ^ 0xA1CA1B6E;
        d = "GL13.GL_TEXTURE_CUBE_MAP";
        n = "_pressed";
        x = ", pos=";
        q = "oak_fence_gate";
        u = 0xBE68D15A ^ 0xBE68D213;
        g = "GL11.GL_CURRENT_RASTER_POSITION_VALID";
        I = "/party invite ";
        z = "cloud";
        ja = "GL13.GL_TEXTURE28";
        e = 0x677E5016 ^ 0x677E503B;
        la = "indirectMagic";
        N = "Style.ROOT";
        K = ", cannot add it to event ";
        F = "textures/entity/guardian.png";
        Ha = 0xC5A7F46 ^ 0xC5A7347;
        H = "MC_GL_VENDOR_OTHER";
        v = ", glAct: ";
        c = "lang/%s.lang";
        ca = "GL11.GL_COEFF";
        R = "ofSunMoon";
        V = 0x8C45DD05 ^ 0x738119C1;
        W = 0x4DDA244 ^ 0x4DDA1B3;
        M = "Wanderer";
        A = "of.options.AUTOSAVE_TICKS";
        p = "createWorld.customize.custom.seaLevel";
        P = 0x86379FE5 ^ 0x86379FCD;
        b = "villager/villager";
        ga = "easeOutBack";
        i = "Rcon";
        o = "createWorld.customize.custom.preset.goodLuck";
        Da = "me";
        T = " is below server threshold of ";
        w = "netherite_chestplate";
        Aa = Double.longBitsToDouble(0xD191A04A111AF935L ^ 0xEE5D6C86D11AF935L);
        m = "vignette";
        k = "zPos";
        L = Float.intBitsToFloat(0xA69C7525 ^ 0x982EC819);
        h = "GL11.GL_ALPHA_TEST";
        E = "underlined";
        Q = "commands.scoreboard.teams.option.success";
        U = "cracked_polished_blackstone_bricks";
        fa = "0.61, 1, 0.88, 1";
        f = "Item entity ";
        X = "farmsunflower.secret";
        l = "palette.format";
        C = "BOTH";
        j = "boat";
        S = "COMPOUND";
        r = "(=[ \t]*|;)";
    }
}

