/*
 * Decompiled with CFR 0.152.
 */
public final class wsa {
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final int V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final long R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final float W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final float e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final float j;
    public static final String J;
    public static final int A;
    public static final String I;

    public wsa() {
        wsa a2;
    }

    static {
        N = "GL11.GL_POINT_SIZE";
        la = "Authentication servers are down but will let them in anyway!";
        a = "RightHands";
        G = "EMERALD";
        H = "UTF-8";
        l = "lime_stained_hardened_clay";
        Ha = "KICK";
        D = "iron_ingot";
        Aa = "speckled_melon";
        X = "glass_white";
        Z = "multiplayer.downloadingTerrain";
        C = "tuff_stairs";
        ca = "BurnTime";
        fa = 0x6F7F7B7F ^ 0x6F7F7ADA;
        x = "math.sin";
        z = "textures/misc/vignette.png";
        c = "gbuffers_terrain_solid";
        O = "LERP_SIZE";
        v = 0xCD0BFD8A ^ 0xC50BFD8A;
        h = "andesite_smooth";
        M = "cookFish";
        K = "deathMessageVisibility";
        J = "potent";
        o = "Hopper";
        W = Float.intBitsToFloat(0xFA2DBB47 ^ 0xC7CCFCE9);
        r = Float.intBitsToFloat(0xF026A165 ^ 0xB1626DA8);
        ja = "Couldn't load actions";
        Da = "HIDE_FOR_OTHER_TEAMS";
        u = "commands.scoreboard.teams.join.usage";
        B = "hardened_clay";
        e = Float.intBitsToFloat(0xBCC5A246 ^ 0x7C86754C);
        w = "gravel";
        T = "minus";
        n = "GL11.GL_LINE_STIPPLE_REPEAT";
        Ja = "easeOutBounce";
        k = "+0+1-2+3&4-4+13";
        d = 0x9C0842E1 ^ 0x9CD35690;
        S = "commands.effect.success.removed";
        V = 0x62D1253F ^ 0x62FD673A;
        Ga = "detect";
        j = Float.intBitsToFloat(0x3A51AA69 ^ 0x790AE92);
        y = "overkill";
        g = "protection";
        t = "PROMOACTIVATERESULT";
        I = "Witty comment unavailable :(";
        Q = "s";
        f = "commands.particle.notFound";
        b = Float.intBitsToFloat(0xC5E9EC21 ^ 0x5E2CB9A);
        U = "Cannot register null clazz for id: ";
        F = "carrot_on_a_stick";
        i = "end";
        L = 0x5ECABD7D ^ 0x5ECAC849;
        q = "Tile";
        m = "variable.particle_speed.y";
        E = "dye_magenta";
        Y = "os.arch";
        Ka = "shimmer";
        ga = 0x37D10453 ^ 0x37D12E76;
        P = "MinSpawnDelay";
        s = " (OS)";
        A = 0x34C6EB4 ^ 0x34C3E95;
        R = 0xEAF547A427518CF4L ^ 0xEAF547A427518DDCL;
        p = "mob.cat.purr";
    }
}

