/*
 * Decompiled with CFR 0.152.
 */
public final class WSa_1 {
    public static final int Ma;
    public static final String ba;
    public static final int ha;
    public static final String Fa;
    public static final long Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final String Ha;
    public static final float Ga;
    public static final String fa;
    public static final float Ka;
    public static final String Aa;
    public static final float S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final int U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final double e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final float C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final String A;
    public static final String I;

    public WSa_1() {
        WSa_1 a2;
    }

    static {
        N = "GL14.GL_FOG_COORDINATE_SOURCE";
        f = "/";
        Da = "commands.scoreboard.players.test.notFound";
        D = "BLLeg.BLL3";
        g = 0x9B196CD4 ^ 0x9B1969D1;
        fa = "Baby speed boost";
        la = "commands.publish.started";
        y = "Invalid rotation axis: ";
        ha = 0xC7708DD6 ^ 0xC7708C55;
        B = Float.intBitsToFloat(0xE6DB2E44 ^ 0xDE0A9953);
        p = "XEXPRANIM";
        M = "easeInBounce";
        G = "EnderCrystal";
        ba = ": '";
        O = "Invalid CRC";
        Q = "tickChunk";
        Z = ", offsetY: ";
        v = "key.hotbar.7";
        L = "scaleZval_";
        J = 0x2E25E6A4 ^ 0x2E256D20;
        U = 0xF1EB082B ^ 0xF1EB0BD3;
        k = "brown_mushroom_block";
        Ma = 0x56E1EC5 ^ 0x56E9EB1;
        h = "VILLAGER_ANGRY";
        d = ", microDisabled=";
        ga = "YVAL_NOT_SET";
        I = "\u0421\u043d\u044f\u0442\u044c";
        c = "commands.compare.success";
        C = Float.intBitsToFloat(0x924F7FD5 ^ 0xD3837FD5);
        Y = "shadow_solid";
        l = "smooth";
        i = "achievement.enchantments";
        Fa = "textures/pet/xmas_gift_red.png";
        w = 0x7E90D75 ^ 0xF816F280;
        P = Double.longBitsToDouble(0x16B1761076256750L ^ 0x295F761076256750L);
        a = "facing=north,half=bottom,shape=outer_right";
        X = 0xD0159A2A ^ 0xD015910F;
        K = "record_strad";
        A = "Right.Right54";
        ca = "noisetex";
        Ka = Float.intBitsToFloat(0xBDB99992 ^ 0xF7E22392);
        T = "LOCKED_DISABLED";
        j = "offsetLeft_";
        Ha = "tile.oreDiamond.name";
        Aa = "iron_golem";
        o = 0x5E9F19FA ^ 0x5E9F1988;
        ja = 0x4724AFF5 ^ 0x4724AEC8;
        x = "armorTextAnimation:";
        Ga = Float.intBitsToFloat(0xB6315283 ^ 0x834A2EC);
        e = Double.longBitsToDouble(0x130C8AF107E74B02L ^ 0xD383B2F107E74B02L);
        R = "pick";
        E = "FadeColors";
        S = Float.intBitsToFloat(0x1DFC32D4 ^ 0x5DB53D08);
        H = "textures/entity/enderman/enderman_eyes.png";
        s = "textures/entity/rabbit/gold.png";
        u = "of.options.shaders.TEX_MIN_FIL_N";
        n = "potion.nightVision";
        W = "This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]";
        V = "options.particles";
        Ia = 0x8E83C08D2B2A6C73L ^ 0x8E83C08D2B2A6C17L;
        b = "$1_$2";
        F = "stat.playOneMinute";
        r = "mossy_stone_brick_wall";
        t = "\u5043";
        m = "SCALEYANIM";
        q = 0xCB5E5A62 ^ 0xCB5E7041;
        Ja = "random.bowhit";
        z = "Block: %d %d %d";
    }
}

