/*
 * Decompiled with CFR 0.152.
 */
public final class XOa {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final float ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final float t;
    public static final double R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final float v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final float b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final float f;
    public static final String F;
    public static final long g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public XOa() {
        XOa a2;
    }

    static {
        j = "colorPositions_";
        M = 0x1DF7768B ^ 0x1DF77ADB;
        la = "Couldn't open link";
        V = "Reset world renderers";
        R = Double.longBitsToDouble(0xACBA2B094AA52D4FL ^ 0x93A01DEBAAA52D4FL);
        z = "GL11.GL_CURRENT_RASTER_COLOR";
        o = "float";
        Ka = "RL1";
        p = "animations/pet/sheeppig_animation.json";
        Ga = "show";
        E = "cyan_wool";
        ca = 0x67DEAB56 ^ 0x676217EA;
        Y = "LeftStick";
        N = "26";
        I = "swordNetherite";
        m = "scale_billboard";
        Q = "min_scale";
        U = "5";
        X = "Can't keep up! Did the system time change, or is the server overloaded? Running {}ms behind, skipping {} tick(s)";
        k = "of.options.otherTitle";
        t = Float.intBitsToFloat(0x4711EAF5 ^ 0x7323DFF);
        s = "mob.wither.idle";
        F = "game.player.hurt.fall.small";
        Ha = "ofCustomItems:";
        q = "achievement.buildPickaxe";
        Z = "minecraft:";
        L = 0x78828D40 ^ 0x78828E6B;
        S = "otherNetworkInfo";
        u = "MONSTER";
        f = Float.intBitsToFloat(0x4C53A71A ^ 0xA77A71A);
        ga = "GL11.GL_QUADRATIC_ATTENUATION";
        G = "ZVAL_NOT_SET";
        r = Float.intBitsToFloat(0x2CC1B83B ^ 0x93A5D4DC);
        g = 0x498BDAEB28096C4L ^ 0x498BDAEB28096ECL;
        n = "commands.me.usage";
        h = 0x20B67C94 ^ 0x20B67C14;
        w = "maskImageCase_";
        B = "CPU: %s";
        H = "horizontal+vertical";
        A = "Right21";
        O = "BRICKS";
        D = "]";
        J = "pow";
        d = "border";
        C = "Health";
        ja = Float.intBitsToFloat(0x3A5DE4BE ^ 0x4C1B9DA);
        T = "openCollections";
        x = "GL11.GL_ALPHA_TEST_FUNC";
        Ja = "GL11.GL_INDEX_OFFSET";
        Da = "xx";
        K = "chunkSource";
        P = "snooperEnabled";
        b = Float.intBitsToFloat(0xBEAFE71D ^ 0x17CD42E);
        fa = "All players";
        l = "Unable to parse resource index file: ";
        W = "prismarine_bricks";
        e = 0x43EECDCE ^ 0x43B8F1FD;
        i = "Map";
        a = "double_stone_slab";
        c = "showInventoryAchievementHint";
        Aa = "Source block type";
        v = Float.intBitsToFloat(0xEFA4AF88 ^ 0xD0CC5A4B);
        y = "commands.blockdata.failed";
    }
}

