/*
 * Decompiled with CFR 0.152.
 */
public final class xSa {
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final double ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final int Y;
    public static final int r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final int K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final float D;
    public static final int f;
    public static final float F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        J = "slot.horse.armor";
        e = "connect.failed";
        n = 40034 /* ZKM Deobf Int */;
        ga = "mob.irongolem.death";
        o = "ViW";
        G = "orientation_";
        T = "head2";
        V = -0.4089655876159668F /* ZKM Deobf */;
        N = "leftLeg1";
        Ja = "MC|Brand";
        ja = "vsync_enabled";
        fa = "itemGroup.";
        s = "Exported png to: {}";
        Z = "potion.prefix.odorless";
        K = 2883 /* ZKM Deobf Int */;
        Da = "Unexpected empty array of components";
        Ia = "openInventory";
        x = "Resource location";
        q = "LeftLeg.LeftLeg2";
        Q = "/\\* SHADOWRES:[0-9]+ \\*/.*";
        l = "inTile";
        la = 0.800000011920929F /* ZKM Deobf */;
        Aa = "rightHand.bow1";
        C = "Unable to fit: %s, size: %dx%d, atlas: %dx%d, atlasMax: %dx%d - Maybe try a lower resolution resourcepack?";
        m = "commands.debug.notStarted";
        S = 40015 /* ZKM Deobf Int */;
        D = 1.0499999523162842F /* ZKM Deobf */;
        y = "GL11.GL_RED_SCALE";
        I = "textureheight";
        Y = 3440 /* ZKM Deobf Int */;
        f = 3041 /* ZKM Deobf Int */;
        ca = 0.16D /* ZKM Deobf */;
        W = "Hat.Shape4";
        z = "key.categories.movement";
        j = "PLAYER_PREVIEW";
        b = "R32I";
        v = "Right.Right42";
        p = "EASE_IN_OUT_CUBIC";
        Ka = "Left.Shape34123";
        U = "keyBindings_";
        H = "([0-9]+)\\.([0-9]+)(\\.([0-9]+))?(.+)?";
        g = "outline";
        t = "lit_redstone_lamp";
        P = "commands.spreadplayers.info.";
        a = "score";
        i = "options.difficulty.easy";
        c = -0.05779999867081642F /* ZKM Deobf */;
        h = 3253 /* ZKM Deobf Int */;
        E = "NETHERBRICK";
        d = "GL12.GL_MAX_ELEMENTS_VERTICES";
        A = "Can't get the number of an unknown enum value.";
        F = 9.899999618530273F /* ZKM Deobf */;
        Ga = " :";
        L = "texture_leggings";
        k = "ironTrapdoor";
        M = "config_";
        Fa = "DRINK";
        R = 3255 /* ZKM Deobf Int */;
        u = "textures/entity/cow/cow.png";
        r = 4294967198 /* ZKM Deobf Int */;
        O = 3472 /* ZKM Deobf Int */;
        ha = 2885 /* ZKM Deobf Int */;
        B = "GL13.GL_TEXTURE17";
        X = "Unsupported format: '";
        w = "variable.emitter_random_4";
        Ha = "acacia_planks";
    }

    public xSa() {
        xSa a2;
    }
}

