/*
 * Decompiled with CFR 0.152.
 */
public final class xSa {
    public static final int ha;
    public static final String Fa;
    public static final String Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final double ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final int Y;
    public static final int r;
    public static final float V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final int K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final float D;
    public static final int f;
    public static final float F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        J = "slot.horse.armor";
        e = "connect.failed";
        n = 0xA5468FD0 ^ 0xA54613B2;
        ga = "mob.irongolem.death";
        o = "ViW";
        G = "orientation_";
        T = "head2";
        V = Float.intBitsToFloat(0xA7FC89DF ^ 0x192DEA2F);
        N = "leftLeg1";
        Ja = "MC|Brand";
        ja = "vsync_enabled";
        fa = "itemGroup.";
        s = "Exported png to: {}";
        Z = "potion.prefix.odorless";
        K = 0x1F6F04B7 ^ 0x1F6F0FF4;
        Da = "Unexpected empty array of components";
        Ia = "openInventory";
        x = "Resource location";
        q = "LeftLeg.LeftLeg2";
        Q = "/\\* SHADOWRES:[0-9]+ \\*/.*";
        l = "inTile";
        la = Float.intBitsToFloat(0xA839DCF2 ^ 0x9775103F);
        Aa = "rightHand.bow1";
        C = "Unable to fit: %s, size: %dx%d, atlas: %dx%d, atlasMax: %dx%d - Maybe try a lower resolution resourcepack?";
        m = "commands.debug.notStarted";
        S = 0x58BB894F ^ 0x58BB1500;
        D = Float.intBitsToFloat(0xA595BB82 ^ 0x9A13DDE4);
        y = "GL11.GL_RED_SCALE";
        I = "textureheight";
        Y = 0xB3763996 ^ 0xB37634E6;
        f = 0x578E04BF ^ 0x578E0F5E;
        ca = Double.longBitsToDouble(0x3DA51923FAEA9AA3L ^ 0x26163C2BD448ED8L);
        W = "Hat.Shape4";
        z = "key.categories.movement";
        j = "PLAYER_PREVIEW";
        b = "R32I";
        v = "Right.Right42";
        p = "EASE_IN_OUT_CUBIC";
        Ka = "Left.Shape34123";
        U = "keyBindings_";
        H = "([0-9]+)\\.([0-9]+)(\\.([0-9]+))?(.+)?";
        g = "outline";
        t = "lit_redstone_lamp";
        P = "commands.spreadplayers.info.";
        a = "score";
        i = "options.difficulty.easy";
        c = Float.intBitsToFloat(0x67E8F64D ^ 0xDA8449FC);
        h = 0x2A3EDADF ^ 0x2A3ED66A;
        E = "NETHERBRICK";
        d = "GL12.GL_MAX_ELEMENTS_VERTICES";
        A = "Can't get the number of an unknown enum value.";
        F = Float.intBitsToFloat(0xC11081AE ^ 0x800EE7C8);
        Ga = " :";
        L = "texture_leggings";
        k = "ironTrapdoor";
        M = "config_";
        Fa = "DRINK";
        R = 0xA3040893 ^ 0xA3040424;
        u = "textures/entity/cow/cow.png";
        r = 0x25BB1636 ^ 0xDA44E9A8;
        O = 0xD5B8C752 ^ 0xD5B8CAC2;
        ha = 0x79ABF2F7 ^ 0x79ABF9B2;
        B = "GL13.GL_TEXTURE17";
        X = "Unsupported format: '";
        w = "variable.emitter_random_4";
        Ha = "acacia_planks";
    }

    public xSa() {
        xSa a2;
    }
}

