/*
 * Decompiled with CFR 0.152.
 */
public final class Xsa_1 {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final long S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final int z;
    public static final String X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final float c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final long f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final double i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        Ha = "28";
        U = "Flight";
        Ja = "SHAKING";
        J = "grass";
        a = "GL11.GL_SPECULAR";
        p = "enchant";
        S = 0x7C3F8018F847FB96L ^ 0x7C3F8019FD8CDD47L;
        w = "netherite_helmet";
        l = "easeInQuint";
        Ka = "oxidized_cut_copper_slab";
        N = "GL11.GL_TEXTURE_WIDTH";
        y = 0x266CEF48 ^ 0x266CEE57;
        C = 0x649F3A14 ^ 0x649F39E6;
        ca = 0xD0C0C16E ^ 0xD0C049F4;
        H = "bricks";
        la = "options.stream.compression.high";
        L = "east=true,north=false,south=false,up=true,west=false";
        u = "weathered_cut_copper_stairs";
        G = "glass_pane_top_magenta";
        D = 0x551761FA ^ 0x551791E4;
        Y = "GL11.GL_BLEND_DST";
        E = "potion.saturation";
        b = 0x4983A7F3 ^ 0x4983232F;
        fa = "body.body";
        r = "GL11.GL_STENCIL_INDEX";
        g = "[Shaders] Invalid value, option: ";
        j = "VSpigot2";
        T = "POINTS";
        Z = "GL11.GL_ALPHA12";
        W = "stairsQuartz";
        c = Float.intBitsToFloat(0x4BB245E1 ^ 0xB042387);
        M = "SOUND_NOT_SET";
        B = "Shape15";
        ga = "Video Settings";
        x = 0xD5A10F45 ^ 0xD5A18B1E;
        F = "Head.23";
        t = 0xAD3EBC1 ^ 0xAD3EFCA;
        h = "options.controls";
        P = "DOUBLE";
        O = "seeds_pumpkin";
        X = "Cauldron";
        K = "_concrete_powder";
        i = Double.longBitsToDouble(0x29DF7371249B642BL ^ 0x960C404217A85718L);
        v = "black_carpet";
        ja = "emitter_transform_xy";
        o = "ofAutoSaveTicks:";
        Aa = "(Unknown file) ";
        q = "{\"coordinateScale\":684.412, \"heightScale\":684.412, \"upperLimitScale\":512.0, \"lowerLimitScale\":512.0, \"depthNoiseScaleX\":200.0, \"depthNoiseScaleZ\":200.0, \"depthNoiseScaleExponent\":0.5, \"mainNoiseScaleX\":80.0, \"mainNoiseScaleY\":160.0, \"mainNoiseScaleZ\":80.0, \"baseSize\":8.5, \"stretchY\":12.0, \"biomeDepthWeight\":1.0, \"biomeDepthOffset\":0.0, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":0.0, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":true, \"seaLevel\":40 }";
        Q = ", underlined=";
        e = "Missing particle!";
        A = "Internal exception";
        k = "pass";
        d = Float.intBitsToFloat(0x3C57199A ^ 0xFC76EF67);
        Ga = "Invalid minHeight: ";
        m = "q.player_pos_x";
        f = 0x77F9BBB372054826L ^ 0x77F9BBB372054D1FL;
        V = "textures/entity/villager/villager.png";
        s = "Invalid animation sequence";
        R = "' at pos ";
        Da = "half=top,variant=default";
        n = "slices_";
        z = 0x5D623AE3 ^ 0x5D623A16;
        I = "DesertHills";
    }

    public Xsa_1() {
        Xsa_1 a2;
    }
}

