/*
 * Decompiled with CFR 0.152.
 */
public final class XTa_1 {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final double ja;
    public static final int Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final int p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final float F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    public XTa_1() {
        XTa_1 a2;
    }

    static {
        L = "stat.mineBlock.";
        N = "Invalid duration";
        g = 3417 /* ZKM Deobf Int */;
        V = "del shadow depth";
        Da = " \u0441\u0435\u043a. \u0434\u043e \u043f\u0435\u0440\u0435\u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f";
        ca = "RightLeg.RL2";
        C = "tile.stone.diorite.name";
        Ia = "commands.scoreboard.players.operation.invalidOperation";
        x = "SPECIAL";
        B = 323 /* ZKM Deobf Int */;
        G = "Mesa";
        e = "mudBrickStairs";
        O = "Right8";
        m = 34186 /* ZKM Deobf Int */;
        P = "shadow terrain cutout";
        F = -1.4763000011444092F /* ZKM Deobf */;
        f = "TextComponent{text='";
        W = 7 /* ZKM Deobf Int */;
        d = " = ";
        A = "eModel_";
        l = "Couldn't save entities";
        la = "https://shaderserver.vimeworld.com/verify/check";
        K = "polishedBasalt";
        Z = "'";
        U = 5.25F /* ZKM Deobf */;
        Aa = "lighting";
        Ja = "zvalCase_";
        X = "SHFC";
        D = "RenderHeldItems";
        R = "coarse_dirt";
        k = " bytes";
        v = "textures/pet/bear.png";
        b = "Exception while ticking a block";
        E = "moss_block";
        n = "\u041f\u043e\u0432\u043e\u0440\u043e\u0442 \u043a\u0430\u043c\u0435\u0440\u044b \u043f\u0440\u043e\u0442\u0438\u0432 \u0447\u0430\u0441\u043e\u0432\u043e\u0439 \u0441\u0442\u0440\u0435\u043b\u043a\u0438";
        s = -2.4600000381469727F /* ZKM Deobf */;
        u = "cr";
        t = "Invalid resource";
        ga = "DonkeyKong";
        Ga = "Unable to find bone '";
        a = "START_SPRINTING";
        j = 33876 /* ZKM Deobf Int */;
        q = "gl_caps[EXT_texture_buffer_object]";
        Q = "warped_planks";
        H = "options.chat.visibility";
        T = 4294959103 /* ZKM Deobf Int */;
        S = "mob.zombie.unfect";
        M = 701 /* ZKM Deobf Int */;
        Ka = "ERROR";
        Ha = 2835 /* ZKM Deobf Int */;
        I = "Seed";
        p = 4294967206 /* ZKM Deobf Int */;
        r = "Could not serialize ";
        y = "Creeper";
        c = "Mega Taiga Hills";
        Y = "FERN";
        h = "GL14.GL_BLEND_DST_ALPHA";
        i = "scaleZ_";
        w = "thinStainedGlass";
        J = "textures/entity/spider_eyes.png";
        o = "Okssi";
        fa = 1.9722219705581665F /* ZKM Deobf */;
        ja = 0.328D /* ZKM Deobf */;
        z = "facing=north";
    }
}

