/*
 * Decompiled with CFR 0.152.
 */
public final class XTa_1 {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final double ja;
    public static final int Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final int p;
    public static final String n;
    public static final float s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final int B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final float F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final int M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final String I;

    public XTa_1() {
        XTa_1 a2;
    }

    static {
        L = "stat.mineBlock.";
        N = "Invalid duration";
        g = 0xF2258640 ^ 0xF2258B19;
        V = "del shadow depth";
        Da = " \u0441\u0435\u043a. \u0434\u043e \u043f\u0435\u0440\u0435\u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f";
        ca = "RightLeg.RL2";
        C = "tile.stone.diorite.name";
        Ia = "commands.scoreboard.players.operation.invalidOperation";
        x = "SPECIAL";
        B = 0xF754FCC9 ^ 0xF754FD8A;
        G = "Mesa";
        e = "mudBrickStairs";
        O = "Right8";
        m = 0x5323988C ^ 0x53231D06;
        P = "shadow terrain cutout";
        F = Float.intBitsToFloat(0x9A484CB4 ^ 0x25F4BBD2);
        f = "TextComponent{text='";
        W = 0x1FD99839 ^ 0x1FD9983E;
        d = " = ";
        A = "eModel_";
        l = "Couldn't save entities";
        la = "https://shaderserver.vimeworld.com/verify/check";
        K = "polishedBasalt";
        Z = "'";
        U = Float.intBitsToFloat(0xF0704A20 ^ 0xB0D84A20);
        Aa = "lighting";
        Ja = "zvalCase_";
        X = "SHFC";
        D = "RenderHeldItems";
        R = "coarse_dirt";
        k = " bytes";
        v = "textures/pet/bear.png";
        b = "Exception while ticking a block";
        E = "moss_block";
        n = "\u041f\u043e\u0432\u043e\u0440\u043e\u0442 \u043a\u0430\u043c\u0435\u0440\u044b \u043f\u0440\u043e\u0442\u0438\u0432 \u0447\u0430\u0441\u043e\u0432\u043e\u0439 \u0441\u0442\u0440\u0435\u043b\u043a\u0438";
        s = Float.intBitsToFloat(0xBD5EF1D0 ^ 0x7D438174);
        u = "cr";
        t = "Invalid resource";
        ga = "DonkeyKong";
        Ga = "Unable to find bone '";
        a = "START_SPRINTING";
        j = 0x67FE90E6 ^ 0x67FE14B2;
        q = "gl_caps[EXT_texture_buffer_object]";
        Q = "warped_planks";
        H = "options.chat.visibility";
        T = 0x5F203240 ^ 0xA0DFEDBF;
        S = "mob.zombie.unfect";
        M = 0xCD48ED21 ^ 0xCD48EF9C;
        Ka = "ERROR";
        Ha = 0xF370AD56 ^ 0xF370A645;
        I = "Seed";
        p = 0xBF9DFAE7 ^ 0x40620541;
        r = "Could not serialize ";
        y = "Creeper";
        c = "Mega Taiga Hills";
        Y = "FERN";
        h = "GL14.GL_BLEND_DST_ALPHA";
        i = "scaleZ_";
        w = "thinStainedGlass";
        J = "textures/entity/spider_eyes.png";
        o = "Okssi";
        fa = Float.intBitsToFloat(0xD4DB3552 ^ 0xEB274497);
        ja = Double.longBitsToDouble(0x134486B714A81769L ^ 0x2C907B44A2EDB6A2L);
        z = "facing=north";
    }
}

