/*
 * Decompiled with CFR 0.152.
 */
public final class Ypa_1 {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final int ja;
    public static final float Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final int S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final int X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final float B;
    public static final double d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    static {
        G = "anvil";
        R = "armor";
        z = "Exception preparing structure feature";
        e = "CUSTOM_SKY";
        w = "ID is already registered: ";
        T = "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0002\u0003\u0002";
        S = 69696 /* ZKM Deobf Int */;
        s = "Head.14";
        E = "Shadow Translucent";
        Aa = 34467 /* ZKM Deobf Int */;
        p = 8194 /* ZKM Deobf Int */;
        L = "CRIT_MAGIC";
        ga = 3387 /* ZKM Deobf Int */;
        O = "Response";
        y = 740 /* ZKM Deobf Int */;
        ca = "LavaSlime";
        f = "gui.achievements";
        U = "sku";
        u = "waxedWeatheredCutCopperStairs";
        b = "commands.save.start";
        o = "pink_stained_glass_pane";
        C = "GRATES";
        Ka = "GL13.GL_TEXTURE18";
        Fa = "q.player_pos_y";
        la = "Attach";
        r = "killedByTeam.";
        k = "R X";
        B = -0.08869999647140503F /* ZKM Deobf */;
        M = "11";
        I = "crackedPolishedBlackstoneBricks";
        q = "math.die_roll";
        Z = 138 /* ZKM Deobf Int */;
        N = "displayFormat";
        g = "F10";
        A = 15 /* ZKM Deobf Int */;
        c = "light_blue_concrete_powder";
        v = "ofCustomColors:";
        m = "sun.security.provider.SeedGenerator$ThreadedSeedGenerator";
        ja = 32775 /* ZKM Deobf Int */;
        Ha = 6.2831854820251465F /* ZKM Deobf */;
        P = "MOJANG";
        h = "#W#";
        J = "(format error)";
        Ia = " h";
        Q = "commands.scoreboard.teams.add.alreadyExists";
        fa = "variable.emitter_age";
        V = "axis";
        Ga = "[UNNAMED TAG]";
        W = 8195 /* ZKM Deobf Int */;
        x = "ofChunkUpdates:";
        Da = "delay";
        d = 0.65D /* ZKM Deobf */;
        D = "uniform [ _a-zA-Z0-9]+ depthtex1;.*";
        t = ", nameId=";
        Y = "commands.scoreboard.objectives.list.entry";
        H = "assets/minecraft/blockstates/cobblestone.json";
        K = "Body.Shape22";
        n = 33875 /* ZKM Deobf Int */;
        j = "mob.horse.armor";
        l = "light-guard";
        F = 784 /* ZKM Deobf Int */;
        i = "Front.10a";
        Ja = "renderDistance";
        a = "pine.png";
        X = 61449 /* ZKM Deobf Int */;
    }

    public Ypa_1() {
        Ypa_1 a2;
    }
}

