/*
 * Decompiled with CFR 0.152.
 */
public final class yRa {
    public static final String Ea;
    public static final int Ca;
    public static final String ia;
    public static final String Ma;
    public static final int ba;
    public static final float ha;
    public static final String Fa;
    public static final long Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final float Aa;
    public static final int S;
    public static final String Z;
    public static final int Y;
    public static final int r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final int O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final long W;
    public static final String q;
    public static final float x;
    public static final long v;
    public static final String o;
    public static final String h;
    public static final int K;
    public static final long H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final int i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final float A;
    public static final String I;

    static {
        e = "Tool modifier";
        ja = "polishedBlackstoneSlab";
        g = "warpedFence";
        ca = "[{}]@.({}:{}): {}";
        Ma = "animation.model.new";
        T = 219 /* ZKM Deobf Int */;
        k = "1.10.0";
        la = "ban";
        ia = "(:| )";
        X = "useRavines";
        s = "assets/minidot/home_screen.json";
        p = "commands.stop.start";
        P = "Head.31";
        q = "identifier";
        t = "menu.resetdemo";
        w = 2401 /* ZKM Deobf Int */;
        fa = "ao";
        S = 3233098 /* ZKM Deobf Int */;
        Ca = 261 /* ZKM Deobf Int */;
        b = "renderHeldItems";
        B = "Can't find the resource index file: ";
        x = -0.2094395011663437F /* ZKM Deobf */;
        Aa = -10.25F /* ZKM Deobf */;
        O = 30048 /* ZKM Deobf Int */;
        ba = 3136 /* ZKM Deobf Int */;
        Z = "maxFps";
        A = 9.600000381469727F /* ZKM Deobf */;
        Ja = "wood";
        y = "\u0000\u0000";
        U = "allocateTextureMap ";
        G = "Function ";
        d = 3 /* ZKM Deobf Int */;
        Ga = "\u0445\u043e\u0442\u0438\u0442\u0435 \u043f\u0440\u0438\u043e\u0431\u0440\u0435\u0441\u0442\u0438";
        L = "droplet";
        u = 11.710000038146973F /* ZKM Deobf */;
        M = "XSX";
        V = "&a\u041f\u0443\u0442\u044c &f";
        ga = "silver_stained_hardened_clay";
        I = "linear_acceleration";
        R = 2.5350000858306885F /* ZKM Deobf */;
        m = "MC|BOpen";
        C = "chiseledResinBricks";
        Q = "exp";
        N = "tRNS chunk without PLTE chunk";
        Ia = 0x2C2104CD0B45D74EL ^ 0x2C2104CD0B45D77EL;
        Y = 4294967276 /* ZKM Deobf Int */;
        a = "crimsonFenceGate";
        Ka = "team";
        K = 15000 /* ZKM Deobf Int */;
        Fa = "frames";
        E = "COM1";
        H = 0xDF1C5639DD333F2DL ^ 0xDF1C5639DD333B2DL;
        F = "chickenRaw";
        D = "Levels";
        z = "foliage-coloro";
        i = 4294967282 /* ZKM Deobf Int */;
        Ea = "VCR: disconnected";
        j = "{\"coordinateScale\":738.41864, \"heightScale\":157.69133, \"upperLimitScale\":801.4267, \"lowerLimitScale\":1254.1643, \"depthNoiseScaleX\":374.93652, \"depthNoiseScaleZ\":288.65228, \"depthNoiseScaleExponent\":1.2092624, \"mainNoiseScaleX\":1355.9908, \"mainNoiseScaleY\":745.5343, \"mainNoiseScaleZ\":1183.464, \"baseSize\":1.8758626, \"stretchY\":1.7137525, \"biomeDepthWeight\":1.7553768, \"biomeDepthOffset\":3.4701107, \"biomeScaleWeight\":1.0, \"biomeScaleOffset\":2.535211, \"useCaves\":true, \"useDungeons\":true, \"dungeonChance\":8, \"useStrongholds\":true, \"useVillages\":true, \"useMineShafts\":true, \"useTemples\":true, \"useRavines\":true, \"useWaterLakes\":true, \"waterLakeChance\":4, \"useLavaLakes\":true, \"lavaLakeChance\":80, \"useLavaOceans\":false, \"seaLevel\":63 }";
        v = 0xD281CB003BFC2D78L ^ 0xD281CB003BFC2C58L;
        ha = -4.75F /* ZKM Deobf */;
        l = "CookTimeTotal";
        J = "purple";
        n = "waxedOxidizedCopperGrate";
        o = "JungleHills";
        c = "LeftLeg.LL1";
        f = "False";
        h = "textures/entity/slime/magmacube.png";
        r = 156 /* ZKM Deobf Int */;
        Ha = "statistic";
        Da = "text";
        W = 0xE563332B5DB80EC4L ^ 0xE563332B5DB80ECBL;
    }

    public yRa() {
        yRa a2;
    }
}

