/*
 * Decompiled with CFR 0.152.
 */
public final class ySa {
    public static final float Da;
    public static final String ca;
    public static final double Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final float fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final double P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final int n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final int o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final double E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public ySa() {
        ySa a2;
    }

    static {
        J = "of.options.mipmap.nearest";
        i = "Front.12a";
        W = "BorderCenterZ";
        N = "PortalCooldown";
        v = 8421631 /* ZKM Deobf Int */;
        C = "Invalid item ID: ";
        e = ".info";
        d = 3413 /* ZKM Deobf Int */;
        r = "MaxSpawnDelay";
        n = 792 /* ZKM Deobf Int */;
        h = "Stack trace";
        R = "half_dimensions";
        Q = "MINECART_COMMAND";
        p = "gl_caps[gl_max_fragment_uniforms]";
        s = "mob.wolf.hurt";
        Ka = "dls";
        Aa = "Shape29";
        x = "USE_VBO";
        H = "Blocks";
        E = 0.36363636363636365D /* ZKM Deobf */;
        V = "Enderman";
        c = "XYZ";
        Ha = "minidot.dev";
        fa = -8.699999809265137F /* ZKM Deobf */;
        ja = "Body.Shape13";
        y = "Right.Right41";
        I = "Dir";
        t = "commands.scoreboard.teamNotFound";
        o = 3009 /* ZKM Deobf Int */;
        ca = "WITCH";
        Ja = 0.05000000074505806D /* ZKM Deobf */;
        P = 2.0943951023931953D /* ZKM Deobf */;
        m = "ARTHROPOD";
        F = "camera";
        K = "gameMode.spectator";
        w = "dye_purple";
        A = "ROTATEEXPRANIM";
        j = "COLOR_4UB";
        O = "\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c";
        G = "CIRCLE_MIDDLE";
        D = "leggingsChain";
        M = "commands.testforblock.outOfWorld";
        Da = 1.600000023841858F /* ZKM Deobf */;
        L = "food";
        Y = "o O o";
        u = "diagonal_up_right";
        Ga = "mob.ghast.charge";
        l = "browse";
        k = "PACKET_SENT";
        X = "variable.particle_random_2";
        f = "GL11.GL_LUMINANCE12";
        S = "Level weather";
        z = "Looking at: %d %d %d";
        q = "minecraft:particle_lifetime_expression";
        b = "That name is already taken.";
        B = "Content-Type";
        T = 100 /* ZKM Deobf Int */;
        U = "(?!^)";
        Z = 125 /* ZKM Deobf Int */;
        a = "backFace.cutoutMipped";
        g = "Level is null!";
    }
}

