/*
 * Decompiled with CFR 0.152.
 */
public final class YSa_3 {
    public static final float Ca;
    public static final String ia;
    public static final int Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final float Ia;
    public static final float la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final float Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final int Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final float V;
    public static final String z;
    public static final int X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final int O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final long n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final int c;
    public static final String B;
    public static final float d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final float G;
    public static final double D;
    public static final String f;
    public static final int F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final int I;

    static {
        Ga = "flower_oxeye_daisy";
        M = "Could not render item ";
        ba = "_armor";
        J = "\u042d\u0444\u0444\u0435\u043a\u0442 \u0443\u0431\u0438\u0439\u0441\u0442\u0432\u0430";
        K = ", v1=";
        N = "townaura";
        F = 3222278160 /* ZKM Deobf Int */;
        A = 326 /* ZKM Deobf Int */;
        I = 315 /* ZKM Deobf Int */;
        G = 4.0F /* ZKM Deobf */;
        O = 344 /* ZKM Deobf Int */;
        w = "gl_caps[ARB_half_float_pixel]";
        d = 0.5555555820465088F /* ZKM Deobf */;
        l = "%02d:%02d:%02d";
        z = "Invalid default value: ";
        v = "EMITTER_XY";
        R = "theEnd2";
        Aa = "dynblock:items.txt";
        L = 15728880 /* ZKM Deobf Int */;
        x = "chat.type.emote";
        f = ", ao: ";
        la = -1.7000000476837158F /* ZKM Deobf */;
        Fa = "noHurtCam";
        Ja = -0.019999999552965164F /* ZKM Deobf */;
        X = 30027 /* ZKM Deobf Int */;
        Ka = 33984 /* ZKM Deobf Int */;
        q = "NeBS";
        p = "EXPERIENCE_ORB";
        fa = "redstone_dust_line";
        B = "BRL2";
        S = "GL11.GL_LUMINANCE";
        c = 240 /* ZKM Deobf Int */;
        E = "The received encoded string buffer length is longer than maximum allowed (";
        r = "WATER_DROP";
        ja = "tulipWhite";
        T = 3.950000047683716F /* ZKM Deobf */;
        Ha = "/=";
        b = "mob.guardian.idle";
        Ma = 29999984 /* ZKM Deobf Int */;
        t = "tuff_wall";
        Ca = 15.84000015258789F /* ZKM Deobf */;
        P = "MINECART_FURNACE";
        D = 25.0D /* ZKM Deobf */;
        ga = "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1009\u0000";
        Q = "textures/entity/horse/horse_markings_white.png";
        U = "LINE";
        Z = "MinecartChest";
        g = "of.options.mipmap.bilinear";
        i = "GL11.GL_ACCUM_BLUE_BITS";
        ca = "textures/pet/console.png";
        Ia = -9.733099937438965F /* ZKM Deobf */;
        s = "CONTAINER";
        h = "end_stone_brick_stairs";
        y = "assets/minecraft/";
        ha = "commands.replaceitem.block.usage";
        k = "chatWidth:";
        u = "refined";
        H = "mod(counter(checkbox),2) * (xw(cprev(checkbox))+5)";
        Da = "CHAIN";
        ia = "'!";
        V = -7.099999904632568F /* ZKM Deobf */;
        C = "skeleton/skeleton";
        n = 0x376EB895959CB84CL ^ 0x376EB895959CF84CL;
        a = "Cancelled";
        Y = "gl_caps[ARB_seamless_cube_map]";
        e = "GL11.GL_COLOR_INDEX";
        W = 32829 /* ZKM Deobf Int */;
        o = " bytes (";
        m = "OpenGL: ";
        j = "/glass_pane_";
    }

    public YSa_3() {
        YSa_3 a2;
    }
}

