/*
 * Decompiled with CFR 0.152.
 */
public final class ysa_1 {
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final double Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final float x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final long f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final float k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public ysa_1() {
        ysa_1 a2;
    }

    static {
        b = "textures/entity/endercrystal/endercrystal.png";
        q = "TEX_MAG_FIL_B";
        t = "achievement.killEnemy";
        Ka = "Shaderpack ";
        h = 61443 /* ZKM Deobf Int */;
        v = "attribute.modifier.take.";
        V = "of.options.qualityTitle";
        w = "timeout";
        X = "\u043a\u043e\u0438\u043d";
        U = "FONT_NOT_SET";
        H = 34479 /* ZKM Deobf Int */;
        F = "Thrower";
        Ga = ", path: ";
        S = "Body.Shape29";
        z = "resin_brick_slab";
        A = 1644825 /* ZKM Deobf Int */;
        T = 0.45378559827804565F /* ZKM Deobf */;
        D = "EASE_IN_OUT_BACK";
        J = "GL11.GL_EXP2";
        g = "graniteSlab";
        Z = 7.5625D /* ZKM Deobf */;
        P = "underwater.png";
        Da = "angleXval_";
        E = "bamboo_mosaic_stairs";
        Q = 12293 /* ZKM Deobf Int */;
        ca = "mobBaseTick";
        u = "Keep Open";
        k = 12398.0F /* ZKM Deobf */;
        Aa = "WIDTHEXPR";
        fa = "RGB16";
        C = "Invalid entityFacing ";
        B = "facing=south";
        n = "cmdcam-tp";
        s = 64 /* ZKM Deobf Int */;
        x = -13.399999618530273F /* ZKM Deobf */;
        e = "keyJumpButton:";
        f = 0xCF116B3F1DA891FFL ^ 0xCF116B70849164F7L;
        Y = "Life";
        ja = "stat.entityKills.none";
        a = "selectServer.select";
        Ha = "of.options.shaders.OLD_HAND_LIGHT";
        l = "acacia_door";
        d = "M7";
        r = "oak_stairs";
        I = "swampfoliagecolor.png";
        Ja = "Left.Shape54123";
        c = "Piece2.Shape5";
        m = "ANIMATION_NOT_SET";
        N = "profile";
        y = "painting";
        M = "a";
        L = 40054 /* ZKM Deobf Int */;
        j = "easeOutQuart";
        R = "Nearest-Linear";
        O = "commands.worldborder.setSlowly.grow.success";
        K = "MUTE";
        i = "Players cannot be null/empty";
        W = "ofFastMath:";
        o = "glass_pane";
        p = "aesCipherSignKey";
        G = "Angry";
    }
}

