/*
 * Decompiled with CFR 0.152.
 */
public final class Yua {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final float S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final int u;
    public static final int O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final int A;
    public static final String I;

    public Yua() {
        Yua a2;
    }

    static {
        P = ", localizedNames=";
        Ja = "birch_leaves";
        l = "Already building!";
        D = "commands.achievement.dontHave";
        i = "020E0DFB-87AE-4653-9556-831010E291A0";
        j = "colors_";
        Q = "WOOD";
        B = "commandBlock";
        M = "Savanna";
        la = "yellow_glazed_terracotta";
        I = "HORIZONTAL";
        f = "FAST_MATH";
        A = 32887 /* ZKM Deobf Int */;
        ca = "rolli";
        m = 679 /* ZKM Deobf Int */;
        Ka = "Level game mode";
        F = "exposed_chiseled_copper";
        w = "SCREENSHAKEANIMATION";
        N = "createWorld.customize.custom.biomeDepthOffset";
        n = "tulipOrange";
        c = "FURNACE";
        Y = "^[\\w\\d\\s_+-/*%^&|<>=!?:.,()\"'@~\\[\\]]+$";
        u = 7170 /* ZKM Deobf Int */;
        o = "OMDYZR";
        Da = "commands.achievement.alreadyHave";
        x = "textures/pet/slime.png";
        U = -0.7330383062362671F /* ZKM Deobf */;
        Ia = "bed";
        Aa = "/glass_";
        W = 5122 /* ZKM Deobf Int */;
        G = "font/glyph_sizes.bin";
        C = 34071 /* ZKM Deobf Int */;
        Ga = "ofVignette:";
        h = "Tracking range";
        p = "builtin/";
        ga = "bamboo_planks";
        K = "Invalid width: ";
        v = "EggLayTime";
        Ha = "collar.";
        q = "EASE_OUT_CUBIC";
        X = "LOOKAT_DIRECTION";
        t = 0.029999999329447746D /* ZKM Deobf */;
        y = "BLAZE";
        z = "EDIT";
        b = 34008 /* ZKM Deobf Int */;
        d = "entries_";
        L = "pale_oak_log";
        a = "eating";
        R = "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0000\u0000\u0001\u0004\u0002\u0004\u0003\u0004\u0004\u0004\u0005\u0001\u0006\u0001\u0007\u0001\b\u0004\t\u0004";
        Z = "rw";
        V = "https://mc.vimeworld.com/";
        g = "selectServer.defaultName";
        E = "blue_stained_glass_pane";
        s = "Previous Page";
        O = 1028 /* ZKM Deobf Int */;
        H = "stemcolor.png";
        J = 10792 /* ZKM Deobf Int */;
        ja = "armor_feet";
        fa = 3840 /* ZKM Deobf Int */;
        S = -5.599999904632568F /* ZKM Deobf */;
        r = "players_seen";
        k = "CREATURE";
        T = -20.75F /* ZKM Deobf */;
        e = 35005 /* ZKM Deobf Int */;
    }
}

