/*
 * Decompiled with CFR 0.152.
 */
public final class Yua {
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final float S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final float U;
    public static final String P;
    public static final int u;
    public static final int O;
    public static final double t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final float T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final int b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final int J;
    public static final int A;
    public static final String I;

    public Yua() {
        Yua a2;
    }

    static {
        P = ", localizedNames=";
        Ja = "birch_leaves";
        l = "Already building!";
        D = "commands.achievement.dontHave";
        i = "020E0DFB-87AE-4653-9556-831010E291A0";
        j = "colors_";
        Q = "WOOD";
        B = "commandBlock";
        M = "Savanna";
        la = "yellow_glazed_terracotta";
        I = "HORIZONTAL";
        f = "FAST_MATH";
        A = 0xC220343E ^ 0xC220B449;
        ca = "rolli";
        m = 0x80EB844A ^ 0x80EB86ED;
        Ka = "Level game mode";
        F = "exposed_chiseled_copper";
        w = "SCREENSHAKEANIMATION";
        N = "createWorld.customize.custom.biomeDepthOffset";
        n = "tulipOrange";
        c = "FURNACE";
        Y = "^[\\w\\d\\s_+-/*%^&|<>=!?:.,()\"'@~\\[\\]]+$";
        u = 0xBE25A3BC ^ 0xBE25BFBE;
        o = "OMDYZR";
        Da = "commands.achievement.alreadyHave";
        x = "textures/pet/slime.png";
        U = Float.intBitsToFloat(0xE42B02A7 ^ 0x5B10AAC1);
        Ia = "bed";
        Aa = "/glass_";
        W = 0x2887DD75 ^ 0x2887C977;
        G = "font/glyph_sizes.bin";
        C = 0x2AE36B91 ^ 0x2AE3EE86;
        Ga = "ofVignette:";
        h = "Tracking range";
        p = "builtin/";
        ga = "bamboo_planks";
        K = "Invalid width: ";
        v = "EggLayTime";
        Ha = "collar.";
        q = "EASE_OUT_CUBIC";
        X = "LOOKAT_DIRECTION";
        t = Double.longBitsToDouble(0x535A8CA10D1F85B2L ^ 0x6CC434F0ED1F85B2L);
        y = "BLAZE";
        z = "EDIT";
        b = 0x9A7CDB6B ^ 0x9A7C5FB3;
        d = "entries_";
        L = "pale_oak_log";
        a = "eating";
        R = "\u0000\t\u0000\u0000\u0001\t\t\u0000\u0000\u0000\u0001\u0004\u0002\u0004\u0003\u0004\u0004\u0004\u0005\u0001\u0006\u0001\u0007\u0001\b\u0004\t\u0004";
        Z = "rw";
        V = "https://mc.vimeworld.com/";
        g = "selectServer.defaultName";
        E = "blue_stained_glass_pane";
        s = "Previous Page";
        O = 0x87A020CE ^ 0x87A024CA;
        H = "stemcolor.png";
        J = 0x7B7F3EDF ^ 0x7B7F14F7;
        ja = "armor_feet";
        fa = 0x2FC56965 ^ 0x2FC56665;
        S = Float.intBitsToFloat(0xA38A8BB9 ^ 0x6339B88A);
        r = "players_seen";
        k = "CREATURE";
        T = Float.intBitsToFloat(0x15AF9C65 ^ 0xD4099C65);
        e = 0x6BBBDDAF ^ 0x6BBB5512;
    }
}

