/*
 * Decompiled with CFR 0.152.
 */
public final class zOa {
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final int fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final int Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final double X;
    public static final double y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final int t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final int H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final int e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final float C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final int A;
    public static final String I;

    public zOa() {
        zOa a2;
    }

    static {
        J = "aqua_affinity";
        n = "%\n";
        R = 0xAEAF1790 ^ 0xAEAF95D8;
        i = "crying_obsidian";
        Aa = "custom-emote";
        A = 0xFF82D893 ^ 0xFF82DB8A;
        k = "potatoPoisonous";
        ja = "body.body3";
        b = "options.modelPart.";
        B = "Shape48";
        K = "Block type";
        H = 0x3CB5C459 ^ 0x3CB5CFC1;
        c = "deepslate_gold_ore";
        Da = "bezier_left_value";
        q = "VCR: updated {}, {}, {}";
        y = Double.longBitsToDouble(0x573C93191842B904L ^ 0x170493191842B904L);
        p = "O";
        h = "projectile";
        w = "leftHigh";
        D = 0xE4848CF5 ^ 0xE41DBFC6;
        L = "mcpatcher/cit/Potion/";
        Ia = "Head.Shape12";
        M = "KEYBOARDUNBIND";
        Y = "\\s*([\\w:]+)\\s*=\\s*([-]?\\d+)\\s*";
        Ja = "2x2";
        W = "LEFT_PANTS_LEG";
        E = ", it is not an allowed value";
        t = 0xD01F893F ^ 0xD01F090D;
        a = 0x1F8D885F ^ 0x1F8D8893;
        P = "BOOK";
        T = "gui_supported";
        Q = "\\s";
        F = "Q";
        la = "j";
        e = 0x99CC54B4 ^ 0x99CCD4B2;
        j = "cyan_stained_glass_pane";
        z = "Could not set level chunk sections, array length is ";
        G = "chat.type.announcement";
        Z = 0x355F44DB ^ 0x355FD8B2;
        o = "Customize World Presets";
        I = "QC";
        Fa = "GL11.GL_EYE_PLANE";
        O = "placedTrap1";
        d = "Piece2.Shape10";
        ca = "Chunk: %d %d %d in %d %d %d";
        fa = 0x7B43401C ^ 0x2B43401C;
        C = Float.intBitsToFloat(0x32E62A39 ^ 0xDB8926B);
        Ha = "Item";
        ga = "generic.maxHealth";
        s = "Chunk render task was ";
        v = 0x79E95EF7 ^ 0x79E95E94;
        Ga = "EXT_framebuffer_object is ";
        V = "Unknown attachment type";
        u = "https://shaderserver.vimeworld.com/client/check";
        g = "could not find sampler named ";
        x = 0x1144B8E2 ^ 0x11443DE2;
        S = "/\\* WETNESSHL:[0-9\\.]+ \\*/.*";
        r = "of.options.save.20s";
        l = "ARMS";
        X = Double.longBitsToDouble(0x95082A8C66BFA47BL ^ 0xD5262A8C66BFA47BL);
        Ka = "FLOWER";
        f = "RepairCost";
        N = "stem";
        U = "controls.reset";
        m = 0xBB079861 ^ 0xBBE97D61;
    }
}

