/*
 * Decompiled with CFR 0.152.
 */
public final class ZOa_1 {
    public static final int ba;
    public static final double ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final double Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final int p;
    public static final double n;
    public static final String s;
    public static final String w;
    public static final double W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final float I;

    static {
        M = "shadow terrain";
        ha = Double.longBitsToDouble(0xD5C81301FC8D45CCL ^ 0x94E69781FC8D45CCL);
        z = "exists";
        U = 0xA41C47B2 ^ 0xA41C77B0;
        v = "brick_stairs";
        a = "ban-ip";
        Aa = "weightedPlate_heavy";
        Y = 0xB5AD14C4 ^ 0xB5E10DC2;
        q = "Cow";
        Ia = "warpedDoor";
        ja = "head.scale";
        F = "inventory";
        y = "oak_log";
        Da = "of.options.AO_LEVEL";
        d = 0xC0D8DA95 ^ 0xC0D8DA44;
        t = "Key pair generation failed!";
        x = 0xC7F22CD2 ^ 0xC7F22C1A;
        o = "optifine_entity";
        P = 0xFF07FA05 ^ 0xFF07FBAF;
        c = "right_side";
        Z = "generatorVersion";
        i = "textures/entity/horse/armor/horse_armor_iron.png";
        T = "GL11.GL_LUMINANCE8";
        W = Double.longBitsToDouble(0x56AEF3BD10882BCEL ^ 0x16DCF3BD10882BCEL);
        E = "Invalid enum";
        Ga = "tnt_minecart";
        w = "white_wool";
        p = 0xF889F473 ^ 0xF889F6B0;
        k = 0xBFFF17B1 ^ 0xBFFF982B;
        Q = "of.options.STARS";
        ga = Float.intBitsToFloat(0x535A323D ^ 0x6DF42646);
        S = "math.ceil";
        I = Float.intBitsToFloat(0x7D098A17 ^ 0x439E63CE);
        ca = "SHA-1";
        H = "CHECK";
        X = "vertex";
        l = Float.intBitsToFloat(0x7C53D93A ^ 0x43EA40A0);
        m = "slightlyDamaged";
        C = "mangrove";
        la = "tuff";
        f = "fullBeacon";
        n = Double.longBitsToDouble(0x43404E7EB6BD9686L ^ 0x7CB509D0A2C777CEL);
        L = "theEnd";
        j = ">";
        Ha = "enchanting_table";
        G = "hideForOwnTeam";
        O = "options.sensitivity";
        Fa = "achievement.snipeSkeleton";
        fa = "addServer.resourcePack.";
        Ja = Double.longBitsToDouble(0xA5EA2D43D335941L ^ 0x4A2822D43D335941L);
        g = "operation";
        e = "COLUMN";
        J = "commands.scoreboard.players.add.usage";
        Ka = "Shadow map field of view: ";
        V = "textures/entity/guardian_beam.png";
        h = "commands.save.usage";
        ba = 0x9D6FD061 ^ 0x9D6F5302;
        K = "True";
        b = "key.categories.multiplayer";
        s = " back into data...";
        B = "DIAGONAL_RIGHT_MIRROR";
        A = "fireResistance";
        u = 0x13BEC04E ^ 0x13BE4076;
        N = 0xDD1CBE7A ^ 0xDD1CB548;
        r = ", expected to find a Float";
        R = "item/";
        D = "SET_POINT";
    }

    public ZOa_1() {
        ZOa_1 a2;
    }
}

