/*
 * Decompiled with CFR 0.152.
 */
public final class ZOa_1 {
    public static final int ba;
    public static final double ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final float ga;
    public static final String Da;
    public static final String ca;
    public static final double Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final int U;
    public static final int P;
    public static final int u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final int N;
    public static final String T;
    public static final int p;
    public static final double n;
    public static final String s;
    public static final String w;
    public static final double W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final String a;
    public static final String b;
    public static final float l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final float I;

    static {
        M = "shadow terrain";
        ha = 1000000.0D /* ZKM Deobf */;
        z = "exists";
        U = 12290 /* ZKM Deobf Int */;
        v = "brick_stairs";
        a = "ban-ip";
        Aa = "weightedPlate_heavy";
        Y = 4987142 /* ZKM Deobf Int */;
        q = "Cow";
        Ia = "warpedDoor";
        ja = "head.scale";
        F = "inventory";
        y = "oak_log";
        Da = "of.options.AO_LEVEL";
        d = 209 /* ZKM Deobf Int */;
        t = "Key pair generation failed!";
        x = 200 /* ZKM Deobf Int */;
        o = "optifine_entity";
        P = 426 /* ZKM Deobf Int */;
        c = "right_side";
        Z = "generatorVersion";
        i = "textures/entity/horse/armor/horse_armor_iron.png";
        T = "GL11.GL_LUMINANCE8";
        W = 288.0D /* ZKM Deobf */;
        E = "Invalid enum";
        Ga = "tnt_minecart";
        w = "white_wool";
        p = 707 /* ZKM Deobf Int */;
        k = 36762 /* ZKM Deobf Int */;
        Q = "of.options.STARS";
        ga = 0.3400000035762787F /* ZKM Deobf */;
        S = "math.ceil";
        I = 0.2967059910297394F /* ZKM Deobf */;
        ca = "SHA-1";
        H = "CHECK";
        X = "vertex";
        l = 1.4500000476837158F /* ZKM Deobf */;
        m = "slightlyDamaged";
        C = "mangrove";
        la = "tuff";
        f = "fullBeacon";
        n = 1.33D /* ZKM Deobf */;
        L = "theEnd";
        j = ">";
        Ha = "enchanting_table";
        G = "hideForOwnTeam";
        O = "options.sensitivity";
        Fa = "achievement.snipeSkeleton";
        fa = "addServer.resourcePack.";
        Ja = 360.0D /* ZKM Deobf */;
        g = "operation";
        e = "COLUMN";
        J = "commands.scoreboard.players.add.usage";
        Ka = "Shadow map field of view: ";
        V = "textures/entity/guardian_beam.png";
        h = "commands.save.usage";
        ba = 33635 /* ZKM Deobf Int */;
        K = "True";
        b = "key.categories.multiplayer";
        s = " back into data...";
        B = "DIAGONAL_RIGHT_MIRROR";
        A = "fireResistance";
        u = 32824 /* ZKM Deobf Int */;
        N = 2866 /* ZKM Deobf Int */;
        r = ", expected to find a Float";
        R = "item/";
        D = "SET_POINT";
    }

    public ZOa_1() {
        ZOa_1 a2;
    }
}

