/*
 * Decompiled with CFR 0.152.
 */
public final class Zra {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final double Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final float y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final double N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final int s;
    public static final String w;
    public static final int W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final int f;
    public static final double F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final int J;
    public static final int A;
    public static final String I;

    public Zra() {
        Zra a2;
    }

    static {
        E = "\u0413\u043e\u0440\u0438\u0437\u043e\u043d\u0442\u0430\u043b\u044c\u043d\u043e";
        w = "Playing sound {} for event {} as channel {}";
        f = 7424 /* ZKM Deobf Int */;
        g = "GL11.GL_LINE_STRIP";
        s = 783 /* ZKM Deobf Int */;
        Ka = "east=false,north=false,south=true,up=true,west=true";
        C = 33882 /* ZKM Deobf Int */;
        F = -0.2D /* ZKM Deobf */;
        ja = "commands.replaceitem.noContainer";
        y = -1.0471975803375244F /* ZKM Deobf */;
        Aa = "commands.xp.usage";
        z = "composite1";
        h = "waterWorker";
        Y = "shaders.debug.save";
        j = "textures/missing.png";
        ha = "options.invertMouse";
        a = "Unable to load block model: '";
        q = "CA";
        O = "darkPrismarineStairs";
        e = "Right.Right37";
        V = "You have been IP banned.";
        u = 0.6661999821662903F /* ZKM Deobf */;
        R = "angleRotationY_";
        k = 14188952 /* ZKM Deobf Int */;
        I = "STREAM_BYTES_PER_PIXEL";
        D = 32898 /* ZKM Deobf Int */;
        p = 4210943 /* ZKM Deobf Int */;
        Ga = 32837 /* ZKM Deobf Int */;
        o = "block/cube";
        W = 1029 /* ZKM Deobf Int */;
        l = "elements";
        Z = "wall";
        X = "[VimeStorage] Could not save index to ";
        H = "char";
        b = "ofTrees";
        Q = " to bedrock format";
        Fa = "snowman";
        Ia = " is a wall and should have 1 texture, got ";
        t = "ADD_POINT";
        L = "color";
        T = "key.pickItem";
        Ja = "textures/entity/wolf/wolf_angry.png";
        B = "bypassesPlayerLimit";
        la = "ACY";
        d = "minecraft:emitter_shape_sphere";
        P = "redstonecolor.png";
        n = "enchantmentTable";
        Ha = 7.189819D /* ZKM Deobf */;
        ca = "SkullAndRoses";
        M = "commands.clone.usage";
        J = 756 /* ZKM Deobf Int */;
        A = 40008 /* ZKM Deobf Int */;
        N = 2.65625D /* ZKM Deobf */;
        Da = ", hexColor=";
        i = "! (Max is ";
        m = "\u0432\u0438\u043c\u0435\u0440\u043e\u0432";
        ga = "luckyBlock";
        G = "RG32UI";
        c = "Couldn't compile ";
        S = "GL11.GL_TEXTURE_WRAP_S";
        U = "Shape35123";
        K = "HH";
        fa = "channel";
        v = "packetListener";
        r = "screenWidth_";
        x = 385 /* ZKM Deobf Int */;
    }
}

