/*
 * Decompiled with CFR 0.152.
 */
public final class ZSa {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final double Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final int O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final double o;
    public static final int h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        A = " # ";
        x = "commands.testforblock.failed.data";
        l = 1004 /* ZKM Deobf Int */;
        z = "ENTITYTYPE";
        B = "rottenFlesh";
        Z = "LeftLeg.LL";
        E = "%4s";
        k = "Bust";
        ca = "HurtByTimestamp";
        G = "GL11.GL_INDEX_CLEAR_VALUE";
        D = "ofAnimatedFire:";
        Ia = "visible_";
        w = 0.03125F /* ZKM Deobf */;
        J = "minecraft:music.menu";
        Q = "Netty Client IO #%d";
        C = "Gif streaming enabled for ";
        O = 4290772991 /* ZKM Deobf Int */;
        t = "options.stream.bytesPerPixel";
        X = "ld";
        c = " fast";
        H = "Stop capturing";
        Ja = "all_stem";
        f = "SUNFLOWER";
        b = "GL11.GL_MODELVIEW";
        la = "NATURAL_TEXTURES";
        i = "minecraft:music.game.nether";
        Fa = "GL11.GL_BYTE";
        h = 722 /* ZKM Deobf Int */;
        j = "/party public request";
        o = 256.0D /* ZKM Deobf */;
        fa = "GL11.GL_DST_ALPHA";
        ga = "bold";
        n = "red_nether_brick_wall";
        q = 0.699999988079071F /* ZKM Deobf */;
        s = "GL11.GL_FOG_COLOR";
        U = "gui.stats";
        r = 0.0010000000474974513F /* ZKM Deobf */;
        Aa = "diamond_ore";
        Y = "GL13.GL_INTERPOLATE";
        R = 0.741100013256073F /* ZKM Deobf */;
        N = " MB)";
        I = "textures/blocks/destroy_stage_6.png";
        g = 20224 /* ZKM Deobf Int */;
        W = "commands.weather.rain";
        y = 2851 /* ZKM Deobf Int */;
        ha = "hideGUI";
        M = "Shape36123";
        Ka = "gl_caps[ARB_vertex_shader]";
        L = 669 /* ZKM Deobf Int */;
        Ga = "ARCHIVE_NOT_SET";
        F = 746 /* ZKM Deobf Int */;
        m = "AUDIO";
        P = "Couldn't connect to auth servers but will continue to join LAN";
        v = "gl_caps[ARB_gpu_shader5]";
        d = "Piece1.Shape10";
        e = "\u041d\u043e\u0433\u0438";
        Da = "Right.Right52";
        S = "SpawnForced";
        a = "+14&13-13";
        T = "%s:textures/models/armor/%s_layer_%d%s.png";
        u = -0.34375F /* ZKM Deobf */;
        p = "wooden_sword";
        Ha = 999.0D /* ZKM Deobf */;
        ja = 0.21819999814033508F /* ZKM Deobf */;
        V = "paleOakTrapdoor";
        K = 8960 /* ZKM Deobf Int */;
    }

    public ZSa() {
        ZSa a2;
    }
}

