/*
 * Decompiled with CFR 0.152.
 */
public final class ZSa {
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final float ja;
    public static final double Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final String Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final int y;
    public static final String U;
    public static final String P;
    public static final float u;
    public static final int O;
    public static final String t;
    public static final float R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final float q;
    public static final String x;
    public static final String v;
    public static final double o;
    public static final int h;
    public static final int K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final int F;
    public static final int g;
    public static final int L;
    public static final String E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    static {
        A = " # ";
        x = "commands.testforblock.failed.data";
        l = 0x59FA032C ^ 0x59FA00C0;
        z = "ENTITYTYPE";
        B = "rottenFlesh";
        Z = "LeftLeg.LL";
        E = "%4s";
        k = "Bust";
        ca = "HurtByTimestamp";
        G = "GL11.GL_INDEX_CLEAR_VALUE";
        D = "ofAnimatedFire:";
        Ia = "visible_";
        w = Float.intBitsToFloat(0x23F43FEB ^ 0x1EF43FEB);
        J = "minecraft:music.menu";
        Q = "Netty Client IO #%d";
        C = "Gif streaming enabled for ";
        O = 0xC69BE728 ^ 0x392418D7;
        t = "options.stream.bytesPerPixel";
        X = "ld";
        c = " fast";
        H = "Stop capturing";
        Ja = "all_stem";
        f = "SUNFLOWER";
        b = "GL11.GL_MODELVIEW";
        la = "NATURAL_TEXTURES";
        i = "minecraft:music.game.nether";
        Fa = "GL11.GL_BYTE";
        h = 0xA8743129 ^ 0xA87433FB;
        j = "/party public request";
        o = Double.longBitsToDouble(0xD9349A372E9EECFAL ^ 0x99449A372E9EECFAL);
        fa = "GL11.GL_DST_ALPHA";
        ga = "bold";
        n = "red_nether_brick_wall";
        q = Float.intBitsToFloat(0x5491B8CF ^ 0x6BA28BFC);
        s = "GL11.GL_FOG_COLOR";
        U = "gui.stats";
        r = Float.intBitsToFloat(0x5207C257 ^ 0x6884D038);
        Aa = "diamond_ore";
        Y = "GL13.GL_INTERPOLATE";
        R = Float.intBitsToFloat(0xABACBE25 ^ 0x9491069E);
        N = " MB)";
        I = "textures/blocks/destroy_stage_6.png";
        g = 0xB5AAA11E ^ 0xB5AAEE1E;
        W = "commands.weather.rain";
        y = 0x7E0784A3 ^ 0x7E078F80;
        ha = "hideGUI";
        M = "Shape36123";
        Ka = "gl_caps[ARB_vertex_shader]";
        L = 0xDB9D163D ^ 0xDB9D14A0;
        Ga = "ARCHIVE_NOT_SET";
        F = 0x181ED728 ^ 0x181ED5C2;
        m = "AUDIO";
        P = "Couldn't connect to auth servers but will continue to join LAN";
        v = "gl_caps[ARB_gpu_shader5]";
        d = "Piece1.Shape10";
        e = "\u041d\u043e\u0433\u0438";
        Da = "Right.Right52";
        S = "SpawnForced";
        a = "+14&13-13";
        T = "%s:textures/models/armor/%s_layer_%d%s.png";
        u = Float.intBitsToFloat(0x933BB0DB ^ 0x2D8BB0DB);
        p = "wooden_sword";
        Ha = Double.longBitsToDouble(0x5B6994FCCF3995CEL ^ 0x1BE6ACFCCF3995CEL);
        ja = Float.intBitsToFloat(0xA67E6672 ^ 0x982109A0);
        V = "paleOakTrapdoor";
        K = 0xC8019754 ^ 0xC801B454;
    }

    public ZSa() {
        ZSa a2;
    }
}

