/*
 * Decompiled with CFR 0.152.
 */
public final class zsa_1 {
    public static final String Ea;
    public static final String Ca;
    public static final String ia;
    public static final String Ma;
    public static final String ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final int ga;
    public static final String Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final int Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final int S;
    public static final String Z;
    public static final int Y;
    public static final float r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final int P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final long R;
    public static final String Q;
    public static final float N;
    public static final float T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final String w;
    public static final String W;
    public static final String q;
    public static final int x;
    public static final String v;
    public static final String o;
    public static final int h;
    public static final String K;
    public static final float H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final int a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final int D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final float E;
    public static final String m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final int k;
    public static final String j;
    public static final float J;
    public static final String A;
    public static final String I;

    public zsa_1() {
        zsa_1 a2;
    }

    static {
        B = "SpawnData";
        j = "dirtMinHeight";
        ha = "melon_stem_(?:connected|disconnected)?";
        C = "GL11.GL_2D";
        Ha = " to be a JsonArray, was ";
        m = "SNOWMAN";
        M = "Unknown?";
        Ea = "ClearWater (";
        F = "Couldn't open link (";
        h = 36160 /* ZKM Deobf Int */;
        x = 4802889 /* ZKM Deobf Int */;
        z = "DATA_NOT_SET";
        Ma = "white_concrete_powder";
        Fa = "Shape52";
        a = 4294967290 /* ZKM Deobf Int */;
        l = "mcpatcher/ctm/default/";
        y = "createWorld.customize.custom.page";
        Y = 7969893 /* ZKM Deobf Int */;
        P = 12000 /* ZKM Deobf Int */;
        Ja = "ofChunkUpdates";
        Ga = 4393481 /* ZKM Deobf Int */;
        t = "textColorVal_";
        T = 0.8203046917915344F /* ZKM Deobf */;
        la = "assets/";
        u = "pickaxeStone";
        R = 0xDC3DDFEE67E78CFAL ^ 0xDC3DDFEE67E78D0EL;
        r = 1.2216999530792236F /* ZKM Deobf */;
        O = "stripe_bottom";
        d = 747097 /* ZKM Deobf Int */;
        W = "MaxNearbyEntities";
        L = 2196 /* ZKM Deobf Int */;
        p = 2854 /* ZKM Deobf Int */;
        n = "minecraft:beacon";
        E = 0.8726645708084106F /* ZKM Deobf */;
        ja = "options.chat.scale";
        g = "silver_stained_glass_pane";
        K = "RightLeg";
        q = "pale_oak_stairs";
        J = -1.5010000467300415F /* ZKM Deobf */;
        D = 821 /* ZKM Deobf Int */;
        c = "end_stone_brick_slab";
        ia = "textures/entity/horse/horse_brown.png";
        U = "Missing ')' after argument to ";
        Ca = "Could not read file ";
        i = "mossy";
        Q = "myceliumparticlecolor.png";
        Aa = "Unsigned Short";
        N = 14.399999618530273F /* ZKM Deobf */;
        X = "Position hash";
        fa = "%.2f";
        Ia = "GGG";
        s = ", siblings=";
        f = "quadro";
        e = "waxedExposedCopper";
        ga = 10788 /* ZKM Deobf Int */;
        o = "Tried send packet with manually closed connection";
        ba = "gray";
        k = 35046 /* ZKM Deobf Int */;
        V = "Invalid speed: ";
        I = "textures/entity/beacon_beam.png";
        G = "options.ao.off";
        A = "brown_stained_glass";
        w = "gl_caps[ARB_sync]";
        b = "' tried to join with an invalid session";
        ca = 7938 /* ZKM Deobf Int */;
        Z = "time_stamp";
        v = "\u0421\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c";
        S = 499 /* ZKM Deobf Int */;
        Ka = "Shape40123";
        H = 2.670353889465332F /* ZKM Deobf */;
        Da = "GL13.GL_TEXTURE2";
    }
}

