/*
 * Decompiled with CFR 0.152.
 */
public final class Zta_2 {
    public static final String ia;
    public static final int Ma;
    public static final double ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final float S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final int a;
    public static final int b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final double C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final int I;

    public Zta_2() {
        Zta_2 a2;
    }

    static {
        f = "EXT_blend_func_separate is ";
        J = "CACTUS";
        ba = 16.0D /* ZKM Deobf */;
        ca = 2693828752 /* ZKM Deobf Int */;
        ga = "filtering";
        e = "LAZY_CHUNK_LOADING";
        Aa = 35001 /* ZKM Deobf Int */;
        h = "reset";
        M = "Piece2.Shape8";
        x = "potion.regeneration";
        la = "GL11.GL_FRONT_LEFT";
        Ga = "potion.jump";
        ja = "mob.guardian.elder.death";
        z = "shadow_cutout";
        k = "GL11.GL_INVALID_VALUE";
        X = "Invalid statistic progress in ";
        Fa = "server";
        u = "pre";
        V = "Coordinates of biome request";
        q = "colortex6";
        W = "SPIDER";
        T = 2432696319 /* ZKM Deobf Int */;
        H = "rightStick.rightStick";
        L = "dyePowder";
        w = 250 /* ZKM Deobf Int */;
        a = 2897 /* ZKM Deobf Int */;
        B = "gl_caps[gl_max_vertex_uniforms]";
        y = "textures/gui/container/enchanting_table.png";
        E = ", e=";
        l = 60.0D /* ZKM Deobf */;
        m = 4027580432 /* ZKM Deobf Int */;
        F = "q.gui_scale";
        Ia = "GD";
        b = 33062 /* ZKM Deobf Int */;
        Ha = "tall_grass";
        U = "tile.stone.granite.name";
        O = "RGR";
        D = "birch_door";
        N = "feather_falling";
        R = "Invalid protocol ID ";
        I = 1014 /* ZKM Deobf Int */;
        Q = 118 /* ZKM Deobf Int */;
        P = "Left.Shape67123";
        Ka = "NOT_SAFE";
        d = 1973019 /* ZKM Deobf Int */;
        Z = "mob.horse.skeleton.death";
        ha = "tripWire";
        v = 2250012 /* ZKM Deobf Int */;
        r = "disableRender_";
        o = "GL11.GL_PIXEL_MAP_A_TO_A_SIZE";
        n = "GL11.GL_BLEND";
        g = "NeStart";
        fa = "green_carpet";
        ia = "Mob";
        Y = 10790 /* ZKM Deobf Int */;
        Ja = "\" line: ";
        K = "SleepTimer";
        S = 0.017500000074505806F /* ZKM Deobf */;
        C = 8000.0D /* ZKM Deobf */;
        s = "chunked";
        t = "carrots";
        p = "AO_LEVEL";
        i = "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\.|$)){4}$";
        c = "helmetDiamond";
        Da = 0.23000000417232513F /* ZKM Deobf */;
        G = "\u506c";
        Ma = 122 /* ZKM Deobf Int */;
        A = "RGBA32F";
        j = 16274 /* ZKM Deobf Int */;
    }
}

