/*
 * Decompiled with CFR 0.152.
 */
public final class Zta_2 {
    public static final String ia;
    public static final int Ma;
    public static final double ba;
    public static final String ha;
    public static final String Fa;
    public static final String Ia;
    public static final String la;
    public static final String ga;
    public static final float Da;
    public static final int ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final int Aa;
    public static final float S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final int Q;
    public static final String N;
    public static final int T;
    public static final String p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final int v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final int d;
    public static final int a;
    public static final int b;
    public static final double l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final String L;
    public static final String E;
    public static final int m;
    public static final double C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final String J;
    public static final String A;
    public static final int I;

    public Zta_2() {
        Zta_2 a2;
    }

    static {
        f = "EXT_blend_func_separate is ";
        J = "CACTUS";
        ba = Double.longBitsToDouble(0xD99AFEE8DFD5C145L ^ 0x99AAFEE8DFD5C145L);
        ca = 0xB802DDC ^ 0xAB10BD4C;
        ga = "filtering";
        e = "LAZY_CHUNK_LOADING";
        Aa = 0x17526C19 ^ 0x1752E4A0;
        h = "reset";
        M = "Piece2.Shape8";
        x = "potion.regeneration";
        la = "GL11.GL_FRONT_LEFT";
        Ga = "potion.jump";
        ja = "mob.guardian.elder.death";
        z = "shadow_cutout";
        k = "GL11.GL_INVALID_VALUE";
        X = "Invalid statistic progress in ";
        Fa = "server";
        u = "pre";
        V = "Coordinates of biome request";
        q = "colortex6";
        W = "SPIDER";
        T = 0x7F545548 ^ 0xEFABAAB7;
        H = "rightStick.rightStick";
        L = "dyePowder";
        w = 0x5F315621 ^ 0x5F3156DB;
        a = 0x5E21B660 ^ 0x5E21BD31;
        B = "gl_caps[gl_max_vertex_uniforms]";
        y = "textures/gui/container/enchanting_table.png";
        E = ", e=";
        l = Double.longBitsToDouble(0x134C65058706DD8BL ^ 0x530265058706DD8BL);
        m = 0xFE5D26E2 ^ 0xE4D26F2;
        F = "q.gui_scale";
        Ia = "GD";
        b = 0xCF325D2E ^ 0xCF32DC08;
        Ha = "tall_grass";
        U = "tile.stone.granite.name";
        O = "RGR";
        D = "birch_door";
        N = "feather_falling";
        R = "Invalid protocol ID ";
        I = 0xF18E0793 ^ 0xF18E0465;
        Q = 0x16DD6F12 ^ 0x16DD6F64;
        P = "Left.Shape67123";
        Ka = "NOT_SAFE";
        d = 0xD88A2AC4 ^ 0xD89431DF;
        Z = "mob.horse.skeleton.death";
        ha = "tripWire";
        v = 0x11E431D ^ 0x13C1601;
        r = "disableRender_";
        o = "GL11.GL_PIXEL_MAP_A_TO_A_SIZE";
        n = "GL11.GL_BLEND";
        g = "NeStart";
        fa = "green_carpet";
        ia = "Mob";
        Y = 0xE9759F01 ^ 0xE975B527;
        Ja = "\" line: ";
        K = "SleepTimer";
        S = Float.intBitsToFloat(0xCA947669 ^ 0xF61B2A40);
        C = Double.longBitsToDouble(0x3651E1FE105EB64EL ^ 0x76EEA1FE105EB64EL);
        s = "chunked";
        t = "carrots";
        p = "AO_LEVEL";
        i = "^((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\\.|$)){4}$";
        c = "helmetDiamond";
        Da = Float.intBitsToFloat(0xD3207C82 ^ 0xED4BF99D);
        G = "\u506c";
        Ma = 0x54EB6088 ^ 0x54EB60F2;
        A = "RGBA32F";
        j = 0x8958446A ^ 0x89587BF8;
    }
}

