/*
 * Decompiled with CFR 0.152.
 */
public final class zua {
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final float Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final String y;
    public static final double U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final int R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final float w;
    public static final String W;
    public static final String q;
    public static final String x;
    public static final String v;
    public static final String o;
    public static final String h;
    public static final String K;
    public static final String H;
    public static final String c;
    public static final String B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final int l;
    public static final String e;
    public static final String G;
    public static final String D;
    public static final String f;
    public static final String F;
    public static final String g;
    public static final int L;
    public static final String E;
    public static final int m;
    public static final String C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final int j;
    public static final int J;
    public static final String A;
    public static final String I;

    public zua() {
        zua a2;
    }

    static {
        ja = "/party promote ";
        u = "dye_white";
        p = 776 /* ZKM Deobf Int */;
        c = "old! ";
        Z = "commands.unban.success";
        S = "SKY_BLUE";
        t = "friendlyfire";
        H = "FILL";
        X = "CONNECTED_TEXTURES";
        T = "GL11.GL_DEPTH_BIAS";
        P = "EASE_OUT_QUINT";
        r = "screenBrightness";
        V = "minecraft:emitter_local_space";
        R = 782 /* ZKM Deobf Int */;
        d = "spruce_log";
        m = 96 /* ZKM Deobf Int */;
        l = 3221225471 /* ZKM Deobf Int */;
        y = "visibleStart_";
        O = "Couldn't download http texture ";
        z = "GL11.GL_GEQUAL";
        U = 29999999.0D /* ZKM Deobf */;
        A = " col: ";
        ca = "tile.bed.noSleep";
        Ha = "hoveredPositionZ_";
        a = "Body.Shape18";
        b = "Uniform '";
        Y = -1.4660769701004028F /* ZKM Deobf */;
        e = "GL11.GL_MAX_ATTRIB_STACK_DEPTH";
        C = "options.chat.visibility.system";
        s = "\u041a\u043d\u043e\u043f\u043a\u0438 \u043c\u044b\u0448\u0438";
        Ka = "soundCategory.";
        f = "\u0000\u0018\n\u0000\u0001\u0018\u0018\u0000\u0001\u0000\u00014\u0000\u00024\u0000\u00034\u0001\u00044\u0001\u00054\u0002\u00064\u0002\u0007\u001b\b4\u0003\t4\u0003\n4\u0003\u000b4\u0004\f4\u0004\r4\u0004\u000e4\u0005\u000f4\u0005\u00104\u0005\u00114\u0006\u00124\u0006\u00134\u0007\u00144\u0007\u00154\b\u00164\b\u00174\t\u00184\t";
        W = "LINES_X";
        F = "facing=east,half=top,shape=outer_right";
        n = "LESS";
        G = "players_max";
        w = -1.100000023841858F /* ZKM Deobf */;
        g = "coins";
        Aa = "GL11.GL_MAX_EVAL_ORDER";
        M = "minecraft:villager";
        x = "Do you feel the need for... optimization?";
        Ga = "compass generation marker";
        L = 32882 /* ZKM Deobf Int */;
        K = "glass_pane_top_red";
        Ja = "Shape24";
        J = 36096 /* ZKM Deobf Int */;
        D = "[Shaders] ";
        q = "\u5145";
        i = "shadowClipFrustrum";
        h = "textures/body/mercy_wings_red.png";
        N = "Predicates for character(s) ";
        j = 3317 /* ZKM Deobf Int */;
        o = "IDZ";
        fa = "texteria";
        Q = "lilypad";
        v = "ELEMENT_VISIBLE";
        B = "customArmor:";
        k = "MSRoom";
        I = " not found";
        E = "shovelDiamond";
    }
}

