/*
 * Decompiled with CFR 0.152.
 */
public final class Zua_1 {
    public static final String la;
    public static final String ga;
    public static final String Da;
    public static final String ca;
    public static final String Ja;
    public static final String ja;
    public static final String Ha;
    public static final String Ga;
    public static final String fa;
    public static final String Ka;
    public static final String Aa;
    public static final String S;
    public static final String Z;
    public static final int Y;
    public static final String r;
    public static final String V;
    public static final String z;
    public static final String X;
    public static final float y;
    public static final String U;
    public static final String P;
    public static final String u;
    public static final String O;
    public static final String t;
    public static final String R;
    public static final String Q;
    public static final String N;
    public static final String T;
    public static final int p;
    public static final String n;
    public static final String s;
    public static final int w;
    public static final String W;
    public static final int q;
    public static final String x;
    public static final String v;
    public static final int o;
    public static final float h;
    public static final int K;
    public static final String H;
    public static final float c;
    public static final long B;
    public static final String d;
    public static final String a;
    public static final String b;
    public static final String l;
    public static final String e;
    public static final String G;
    public static final float D;
    public static final String f;
    public static final String F;
    public static final int g;
    public static final String L;
    public static final String E;
    public static final String m;
    public static final int C;
    public static final String i;
    public static final String M;
    public static final String k;
    public static final String j;
    public static final String J;
    public static final String A;
    public static final String I;

    public Zua_1() {
        Zua_1 a2;
    }

    static {
        v = "Bomb";
        Z = "shaders/post/fxaa.json";
        u = "looped_";
        Y = 0x8253D712 ^ 0xE2532892;
        Q = "CHAT_HEIGHT_FOCUSED";
        F = "GL11.GL_PACK_ROW_LENGTH";
        h = Float.intBitsToFloat(0xC428E222 ^ 0x84234273);
        L = "commands.execute.failed";
        d = "spider/spider";
        s = "mm";
        k = "ENDERMAN";
        l = "VC: Fallback to default input device ";
        q = 0xF5AA9E41 ^ 0xF5D55258;
        E = "BEFORE_HUD";
        ga = "shaders/post/flip.json";
        ca = "commands.op.usage";
        V = "Entry{path=";
        S = "commands.playsound.success";
        ja = "mainNoiseScaleZ";
        e = "DARK_GREEN";
        N = "pickaxeWood";
        R = "armorTextColor";
        Ha = "hoverStart_";
        W = "birchFenceGate";
        Ka = "q.mouse_local_y";
        Aa = "gameMode.survival";
        D = Float.intBitsToFloat(0xB3D43F7A ^ 0x8C270C49);
        b = "CustomDisplayTile";
        z = "ANIMATED_PORTAL";
        c = Float.intBitsToFloat(0x98B0C2FE ^ 0xA6D18550);
        m = "GL11.GL_S";
        x = "\u041f\u043e\u0434\u043e\u0436\u0434\u0438\u0442\u0435 \u043d\u0435\u043c\u043d\u043e\u0433\u043e...";
        H = "achievement.acquireIron";
        f = "tile.oreLapis.name";
        K = 0xE1245614 ^ 0xE1245A37;
        p = 0xB8F6FBDA ^ 0xB8F6F763;
        I = "ResourcePack: ignored non-lowercase namespace: %s in %s";
        la = "#X#";
        Ga = "Piece1.Shape27";
        O = "RL";
        Ja = "T X";
        A = "nodrop";
        U = "frameTime";
        j = "keyTextShadow:";
        X = "sizevalCase_";
        i = "Negative index in crash report handler (";
        T = "cyan_concrete";
        o = 0x9491FC7C ^ 0x9491D57C;
        G = "YEXPR";
        C = 0x5848D68E ^ 0x58484AD6;
        fa = "eProgressBar_";
        P = "options.blockAlternatives";
        B = 0x54C90FC511D8C1EEL ^ 0x54C90FC511D8C1F7L;
        M = "GL14.GL_BLEND_SRC_ALPHA";
        J = "achievement.bakeCake";
        n = "EXT_framebuffer_object is supported.\n";
        y = Float.intBitsToFloat(0xB038B4DE ^ 0x8E58B4DE);
        t = "container.chest";
        r = "flowing_water";
        g = 0xC466E2AB ^ 0xC466F0AC;
        Da = "lapis_block";
        w = 0xD2F71DFF ^ 0x2DF7E200;
        a = "TheNakuName";
    }
}

